Point Cloud Library (PCL): pcl::console::TicToc Class Reference
pcl::console::TicToc Class Reference
#include <pcl/console/time.h>
Public Member Functions
TicToc ()=default
void tic ()
double toc () const
void toc_print () const
Detailed Description
Definition at line 49 of file time.h.
Constructor & Destructor Documentation
TicToc()
pcl::console::TicToc::TicToc () default
Member Function Documentation
tic()
void pcl::console::TicToc::tic () inline
Definition at line 56 of file time.h.
toc()
double pcl::console::TicToc::toc () const inline
Definition at line 62 of file time.h.
Referenced by toc_print().
toc_print()
void pcl::console::TicToc::toc_print () const inline
Definition at line 69 of file time.h.
References pcl::console::print_info(), pcl::console::print_value(), and toc().
The documentation for this class was generated from the following file:
pcl/console/time.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:26