Point Cloud Library (PCL): pcl::octree::BufferedBranchNode< ContainerT > Class Template Reference
pcl::octree::BufferedBranchNode< ContainerT > Class Template Reference
#include <pcl/octree/octree2buf_base.h>
Public Member Functions
BufferedBranchNode ()
Empty constructor.
BufferedBranchNode (const BufferedBranchNode &source)
Copy constructor.
BufferedBranchNode & operator= (const BufferedBranchNode &source_arg)
Copy operator.
~BufferedBranchNode () override=default
Empty constructor.
BufferedBranchNode * deepCopy () const override
Method to perform a deep copy of the octree.
OctreeNode * getChildPtr (unsigned char buffer_arg, unsigned char index_arg) const
Get child pointer in current branch node.
void setChildPtr (unsigned char buffer_arg, unsigned char index_arg, OctreeNode *newNode_arg)
Set child pointer in current branch node.
bool hasChild (unsigned char buffer_arg, unsigned char index_arg) const
Check if branch is pointing to a particular child node.
node_type_t getNodeType () const override
Get the type of octree node.
void reset ()
Reset branch node container for every branch buffer.
const ContainerT * operator-> () const
Get const pointer to container.
ContainerT * operator-> ()
Get pointer to container.
const ContainerT & operator* () const
Get const reference to container.
ContainerT & operator* ()
Get reference to container.
const ContainerT & getContainer () const
Get const reference to container.
ContainerT & getContainer ()
Get reference to container.
const ContainerT * getContainerPtr () const
Get const pointer to container.
ContainerT * getContainerPtr ()
Get pointer to container.
Public Member Functions inherited from pcl::octree::OctreeNode
OctreeNode ()=default
virtual ~OctreeNode ()=default
Protected Types
template<typename T , std::size_t ROW, std::size_t COL>
using OctreeMatrix = std::array< std::array< T, COL >, ROW >
Protected Attributes
ContainerT container_
OctreeMatrix< OctreeNode *, 2, 8 > child_node_array_ {}
Detailed Description
template<typename ContainerT>
class pcl::octree::BufferedBranchNode< ContainerT >
Definition at line 54 of file octree2buf_base.h.
Member Typedef Documentation
OctreeMatrix
template<typename ContainerT > template<typename T , std::size_t ROW, std::size_t COL> using pcl::octree::BufferedBranchNode< ContainerT >::OctreeMatrix = std::array<std::array<T, COL>, ROW> protected
Definition at line 203 of file octree2buf_base.h.
Constructor & Destructor Documentation
BufferedBranchNode() [1/2]
template<typename ContainerT > pcl::octree::BufferedBranchNode< ContainerT >::BufferedBranchNode () inline
Empty constructor.
Definition at line 58 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::reset().
Referenced by pcl::octree::BufferedBranchNode< ContainerT >::deepCopy().
BufferedBranchNode() [2/2]
template<typename ContainerT > pcl::octree::BufferedBranchNode< ContainerT >::BufferedBranchNode (const BufferedBranchNode< ContainerT > & source) inline
Copy constructor.
Definition at line 61 of file octree2buf_base.h.
~BufferedBranchNode()
template<typename ContainerT > pcl::octree::BufferedBranchNode< ContainerT >::~BufferedBranchNode () override default
Empty constructor.
Member Function Documentation
deepCopy()
template<typename ContainerT > BufferedBranchNode* pcl::octree::BufferedBranchNode< ContainerT >::deepCopy () const inline override virtual
Method to perform a deep copy of the octree.
Implements pcl::octree::OctreeNode.
Definition at line 86 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::BufferedBranchNode().
getChildPtr()
template<typename ContainerT > OctreeNode* pcl::octree::BufferedBranchNode< ContainerT >::getChildPtr (unsigned char buffer_arg, unsigned char index_arg) const inline
Get child pointer in current branch node.
Parameters
buffer_arg buffer selector, must be less than 2
index_arg index of child in node, must be less than 8
Returns
pointer to child node
Definition at line 97 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::child_node_array_.
Referenced by pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::branchHasChild(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::createLeafRecursive(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::deleteBranch(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::deleteBranchChild(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::deleteLeafRecursive(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::deserializeTreeRecursive(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::findLeafRecursive(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::getBranchBitPattern(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::getBranchChildPtr(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::getBranchXORBitPattern(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::serializeTreeRecursive(), and pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::treeCleanUpRecursive().
getContainer() [1/2]
template<typename ContainerT > ContainerT& pcl::octree::BufferedBranchNode< ContainerT >::getContainer () inline
Get reference to container.
Definition at line 180 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::container_.
getContainer() [2/2]
template<typename ContainerT > const ContainerT& pcl::octree::BufferedBranchNode< ContainerT >::getContainer () const inline
Get const reference to container.
Definition at line 173 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::container_.
getContainerPtr() [1/2]
template<typename ContainerT > ContainerT* pcl::octree::BufferedBranchNode< ContainerT >::getContainerPtr () inline
Get pointer to container.
Definition at line 194 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::container_.
getContainerPtr() [2/2]
template<typename ContainerT > const ContainerT* pcl::octree::BufferedBranchNode< ContainerT >::getContainerPtr () const inline
Get const pointer to container.
Definition at line 187 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::container_.
getNodeType()
template<typename ContainerT > node_type_t pcl::octree::BufferedBranchNode< ContainerT >::getNodeType () const inline override virtual
Get the type of octree node.
Returns LEAVE_NODE type
Implements pcl::octree::OctreeNode.
Definition at line 131 of file octree2buf_base.h.
References pcl::octree::BRANCH_NODE.
hasChild()
template<typename ContainerT > bool pcl::octree::BufferedBranchNode< ContainerT >::hasChild (unsigned char buffer_arg, unsigned char index_arg) const inline
Check if branch is pointing to a particular child node.
Parameters
buffer_arg buffer selector, must be less than 2
index_arg index of child in node, must be less than 8
Returns
"true" if pointer to child node exists; "false" otherwise
Definition at line 123 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::child_node_array_.
Referenced by pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::createLeafRecursive(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::deleteBranchChild(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::deleteLeafRecursive(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::deserializeTreeRecursive(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::findLeafRecursive(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::serializeTreeRecursive(), and pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::treeCleanUpRecursive().
operator*() [1/2]
template<typename ContainerT > ContainerT& pcl::octree::BufferedBranchNode< ContainerT >::operator* () inline
Get reference to container.
Definition at line 166 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::container_.
operator*() [2/2]
template<typename ContainerT > const ContainerT& pcl::octree::BufferedBranchNode< ContainerT >::operator* () const inline
Get const reference to container.
Definition at line 159 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::container_.
operator->() [1/2]
template<typename ContainerT > ContainerT* pcl::octree::BufferedBranchNode< ContainerT >::operator-> () inline
Get pointer to container.
Definition at line 152 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::container_.
operator->() [2/2]
template<typename ContainerT > const ContainerT* pcl::octree::BufferedBranchNode< ContainerT >::operator-> () const inline
Get const pointer to container.
Definition at line 145 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::container_.
operator=()
template<typename ContainerT > BufferedBranchNode& pcl::octree::BufferedBranchNode< ContainerT >::operator= (const BufferedBranchNode< ContainerT > & source_arg) inline
Copy operator.
Definition at line 68 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::child_node_array_.
reset()
template<typename ContainerT > void pcl::octree::BufferedBranchNode< ContainerT >::reset () inline
Reset branch node container for every branch buffer.
Definition at line 138 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::child_node_array_.
Referenced by pcl::octree::BufferedBranchNode< ContainerT >::BufferedBranchNode().
setChildPtr()
template<typename ContainerT > void pcl::octree::BufferedBranchNode< ContainerT >::setChildPtr (unsigned char buffer_arg, unsigned char index_arg, OctreeNode * newNode_arg) inline
Set child pointer in current branch node.
Parameters
buffer_arg buffer selector, must be less than 2
index_arg index of child in node, must be less than 8
newNode_arg pointer to new child node
Definition at line 109 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::child_node_array_.
Referenced by pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::createBranchChild(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::createLeafChild(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::createLeafRecursive(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::deleteBranch(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::deleteBranchChild(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::deserializeTreeRecursive(), and pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::setBranchChildPtr().
Member Data Documentation
child_node_array_
template<typename ContainerT > OctreeMatrix<OctreeNode*, 2, 8> pcl::octree::BufferedBranchNode< ContainerT >::child_node_array_ {} protected
Definition at line 205 of file octree2buf_base.h.
Referenced by pcl::octree::BufferedBranchNode< ContainerT >::getChildPtr(), pcl::octree::BufferedBranchNode< ContainerT >::hasChild(), pcl::octree::BufferedBranchNode< ContainerT >::operator=(), pcl::octree::BufferedBranchNode< ContainerT >::reset(), and pcl::octree::BufferedBranchNode< ContainerT >::setChildPtr().
container_
template<typename ContainerT > ContainerT pcl::octree::BufferedBranchNode< ContainerT >::container_ protected
Definition at line 200 of file octree2buf_base.h.
Referenced by pcl::octree::BufferedBranchNode< ContainerT >::getContainer(), pcl::octree::BufferedBranchNode< ContainerT >::getContainerPtr(), pcl::octree::BufferedBranchNode< ContainerT >::operator*(), and pcl::octree::BufferedBranchNode< ContainerT >::operator->().
The documentation for this class was generated from the following file:
pcl/octree/octree2buf_base.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:32