Point Cloud Library (PCL): pcl::ESFEstimation< PointInT, PointOutT > Class Template Reference
pcl::ESFEstimation< PointInT, PointOutT > Class Template Reference
Module features
ESFEstimation estimates the ensemble of shape functions descriptors for a given point cloud dataset containing points.
#include <pcl/features/esf.h>
Public Types
using Ptr = shared_ptr< ESFEstimation< PointInT, PointOutT > >
using ConstPtr = shared_ptr< const ESFEstimation< PointInT, PointOutT > >
using PointCloudIn = pcl::PointCloud< PointInT >
using PointCloudOut = typename Feature< PointInT, PointOutT >::PointCloudOut
Public Types inherited from pcl::Feature< PointInT, pcl::ESFSignature640 >
using BaseClass = PCLBase< PointInT >
using Ptr = shared_ptr< Feature< PointInT, pcl::ESFSignature640 > >
using ConstPtr = shared_ptr< const Feature< PointInT, pcl::ESFSignature640 > >
using KdTree = pcl::search::Search< PointInT >
using KdTreePtr = typename KdTree::Ptr
using PointCloudIn = pcl::PointCloud< PointInT >
using PointCloudInPtr = typename PointCloudIn::Ptr
using PointCloudInConstPtr = typename PointCloudIn::ConstPtr
using PointCloudOut = pcl::PointCloud< pcl::ESFSignature640 >
using SearchMethod = std::function< int(std::size_t, double, pcl::Indices &, std::vector< float > &)>
using SearchMethodSurface = std::function< int(const PointCloudIn &cloud, std::size_t index, double, pcl::Indices &, std::vector< float > &)>
Public Types inherited from pcl::PCLBase< PointInT >
using PointCloud = pcl::PointCloud< PointInT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
ESFEstimation ()
Empty constructor.
void compute (PointCloudOut &output)
Overloaded computed method from pcl::Feature.
Public Member Functions inherited from pcl::Feature< PointInT, pcl::ESFSignature640 >
Feature ()
Empty constructor.
void setSearchSurface (const PointCloudInConstPtr &cloud)
Provide a pointer to a dataset to add additional information to estimate the features for every point in the input dataset.
PointCloudInConstPtr getSearchSurface () const
Get a pointer to the surface point cloud dataset.
void setSearchMethod (const KdTreePtr &tree)
Provide a pointer to the search object.
KdTreePtr getSearchMethod () const
Get a pointer to the search method used.
double getSearchParameter () const
Get the internal search parameter.
void setKSearch (int k)
Set the number of k nearest neighbors to use for the feature estimation.
int getKSearch () const
get the number of k nearest neighbors used for the feature estimation.
void setRadiusSearch (double radius)
Set the sphere radius that is to be used for determining the nearest neighbors used for the feature estimation.
double getRadiusSearch () const
Get the sphere radius used for determining the neighbors.
void compute (PointCloudOut &output)
Base method for feature estimation for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Public Member Functions inherited from pcl::PCLBase< PointInT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointInT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
void computeFeature (PointCloudOut &output) override
Estimate the Ensebmel of Shape Function (ESF) descriptors at a set of points given by <setInputCloud (),.
int lci (const int x1, const int y1, const int z1, const int x2, const int y2, const int z2, float &ratio, int &incnt, int &pointcount)
...
void computeESF (PointCloudIn &pc, std::vector< float > &hist)
...
void voxelize9 (PointCloudIn &cluster)
...
void cleanup9 (PointCloudIn &cluster)
...
void scale_points_unit_sphere (const pcl::PointCloud< PointInT > &pc, float scalefactor, Eigen::Vector4f &centroid)
...
Protected Member Functions inherited from pcl::Feature< PointInT, pcl::ESFSignature640 >
const std::string & getClassName () const
Get a string representation of the name of this class.
virtual bool initCompute ()
This method should get called before starting the actual computation.
virtual bool deinitCompute ()
This method should get called after ending the actual computation.
int searchForNeighbors (std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
int searchForNeighbors (const PointCloudIn &cloud, std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
Protected Member Functions inherited from pcl::PCLBase< PointInT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Additional Inherited Members
Protected Attributes inherited from pcl::Feature< PointInT, pcl::ESFSignature640 >
std::string feature_name_
The feature name.
SearchMethodSurface search_method_surface_
The search method template for points.
PointCloudInConstPtr surface_
An input point cloud describing the surface that is to be used for nearest neighbors estimation.
KdTreePtr tree_
A pointer to the spatial search object.
double search_parameter_
The actual search parameter (from either search_radius_ or k_).
double search_radius_
The nearest neighbors search radius for each point.
int k_
The number of K nearest neighbors to use for each point.
bool fake_surface_
If no surface is given, we use the input PointCloud as the surface.
Protected Attributes inherited from pcl::PCLBase< PointInT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointInT, typename PointOutT = pcl::ESFSignature640>
class pcl::ESFEstimation< PointInT, PointOutT >
ESFEstimation estimates the ensemble of shape functions descriptors for a given point cloud dataset containing points.
Shape functions are D2, D3, A3. For more information about the ESF descriptor, see: Walter Wohlkinger and Markus Vincze, "Ensemble of Shape Functions for 3D Object Classification", IEEE International Conference on Robotics and Biomimetics (IEEE-ROBIO), 2011
Author
Walter Wohlkinger
Definition at line 59 of file esf.h.
Member Typedef Documentation
ConstPtr
template<typename PointInT , typename PointOutT = pcl::ESFSignature640> using pcl::ESFEstimation< PointInT, PointOutT >::ConstPtr = shared_ptr<const ESFEstimation<PointInT, PointOutT> >
Definition at line 63 of file esf.h.
PointCloudIn
template<typename PointInT , typename PointOutT = pcl::ESFSignature640> using pcl::ESFEstimation< PointInT, PointOutT >::PointCloudIn = pcl::PointCloud<PointInT>
Definition at line 73 of file esf.h.
PointCloudOut
template<typename PointInT , typename PointOutT = pcl::ESFSignature640> using pcl::ESFEstimation< PointInT, PointOutT >::PointCloudOut = typename Feature<PointInT, PointOutT>::PointCloudOut
Definition at line 74 of file esf.h.
Ptr
template<typename PointInT , typename PointOutT = pcl::ESFSignature640> using pcl::ESFEstimation< PointInT, PointOutT >::Ptr = shared_ptr<ESFEstimation<PointInT, PointOutT> >
Definition at line 62 of file esf.h.
Constructor & Destructor Documentation
ESFEstimation()
template<typename PointInT , typename PointOutT = pcl::ESFSignature640> pcl::ESFEstimation< PointInT, PointOutT >::ESFEstimation () inline
Empty constructor.
Definition at line 77 of file esf.h.
References pcl::Feature< PointInT, pcl::ESFSignature640 >::feature_name_, pcl::Feature< PointInT, pcl::ESFSignature640 >::k_, and pcl::Feature< PointInT, pcl::ESFSignature640 >::search_radius_.
Member Function Documentation
cleanup9()
template<typename PointInT , typename PointOutT > void pcl::ESFEstimation< PointInT, PointOutT >::cleanup9 (PointCloudIn & cluster) protected
...
Definition at line 453 of file esf.hpp.
compute()
template<typename PointInT , typename PointOutT > void pcl::ESFEstimation< PointInT, PointOutT >::compute (PointCloudOut & output)
Overloaded computed method from pcl::Feature.
Parameters
[out] output the resultant point cloud model dataset containing the estimated features
Definition at line 506 of file esf.hpp.
computeESF()
template<typename PointInT , typename PointOutT > void pcl::ESFEstimation< PointInT, PointOutT >::computeESF (PointCloudIn & pc, std::vector< float > & hist) protected
...
Definition at line 52 of file esf.hpp.
References pcl::euclideanDistance(), M_PI, pcl_round(), and pcl::PointCloud< PointT >::size().
computeFeature()
template<typename PointInT , typename PointOutT > void pcl::ESFEstimation< PointInT, PointOutT >::computeFeature (PointCloudOut & output) override protected
Estimate the Ensebmel of Shape Function (ESF) descriptors at a set of points given by <setInputCloud (),.
Parameters
output the resultant point cloud model histogram that contains the ESF feature estimates
Definition at line 534 of file esf.hpp.
lci()
template<typename PointInT , typename PointOutT > int pcl::ESFEstimation< PointInT, PointOutT >::lci (const int x1, const int y1, const int z1, const int x2, const int y2, const int z2, float & ratio, int & incnt, int & pointcount) protected
...
Definition at line 306 of file esf.hpp.
scale_points_unit_sphere()
template<typename PointInT , typename PointOutT > void pcl::ESFEstimation< PointInT, PointOutT >::scale_points_unit_sphere (const pcl::PointCloud< PointInT > & pc, float scalefactor, Eigen::Vector4f & centroid) protected
...
Definition at line 481 of file esf.hpp.
References pcl::compute3DCentroid(), pcl::demeanPointCloud(), pcl::euclideanDistance(), and pcl::transformPointCloud().
voxelize9()
template<typename PointInT , typename PointOutT > void pcl::ESFEstimation< PointInT, PointOutT >::voxelize9 (PointCloudIn & cluster) protected
...
Definition at line 425 of file esf.hpp.
The documentation for this class was generated from the following files:
pcl/features/esf.h
pcl/features/impl/esf.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:10