Point Cloud Library (PCL): pcl::ConvexHull< PointInT > Class Template Reference
pcl::ConvexHull< PointInT > Class Template Reference
Module surface
ConvexHull using libqhull library.
#include <pcl/surface/convex_hull.h>
Public Types
using Ptr = shared_ptr< ConvexHull< PointInT > >
using ConstPtr = shared_ptr< const ConvexHull< PointInT > >
using PointCloud = pcl::PointCloud< PointInT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
Public Types inherited from pcl::MeshConstruction< PointInT >
using Ptr = shared_ptr< MeshConstruction< PointInT > >
using ConstPtr = shared_ptr< const MeshConstruction< PointInT > >
Public Types inherited from pcl::PCLSurfaceBase< PointInT >
using Ptr = shared_ptr< PCLSurfaceBase< PointInT > >
using ConstPtr = shared_ptr< const PCLSurfaceBase< PointInT > >
using KdTree = pcl::search::Search< PointInT >
using KdTreePtr = typename KdTree::Ptr
Public Types inherited from pcl::PCLBase< PointInT >
using PointCloud = pcl::PointCloud< PointInT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
ConvexHull ()=default
Empty constructor.
~ConvexHull () override=default
Empty destructor.
void reconstruct (PointCloud &points, std::vector< pcl::Vertices > &polygons)
Compute a convex hull for all points given.
void reconstruct (PointCloud &points)
Compute a convex hull for all points given.
void setComputeAreaVolume (bool value)
If set to true, the qhull library is called to compute the total area and volume of the convex hull.
double getTotalArea () const
Returns the total area of the convex hull.
double getTotalVolume () const
Returns the total volume of the convex hull.
void setDimension (int dimension)
Sets the dimension on the input data, 2D or 3D.
int getDimension () const
Returns the dimensionality (2 or 3) of the calculated hull.
void getHullPointIndices (pcl::PointIndices &hull_point_indices) const
Retrieve the indices of the input point cloud that for the convex hull.
Public Member Functions inherited from pcl::MeshConstruction< PointInT >
MeshConstruction ()=default
Constructor.
~MeshConstruction () override=default
Destructor.
void reconstruct (pcl::PolygonMesh &output) override
Base method for surface reconstruction for all points given in <setInputCloud (), setIndices ()>
virtual void reconstruct (std::vector< pcl::Vertices > &polygons)
Base method for mesh construction for all points given in <setInputCloud (), setIndices ()>
Public Member Functions inherited from pcl::PCLSurfaceBase< PointInT >
PCLSurfaceBase ()
Empty constructor.
~PCLSurfaceBase () override=default
Empty destructor.
void setSearchMethod (const KdTreePtr &tree)
Provide an optional pointer to a search object.
KdTreePtr getSearchMethod ()
Get a pointer to the search method used.
Public Member Functions inherited from pcl::PCLBase< PointInT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointInT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
void performReconstruction (PointCloud &points, std::vector< pcl::Vertices > &polygons, bool fill_polygon_data=false)
The actual reconstruction method.
void performReconstruction2D (PointCloud &points, std::vector< pcl::Vertices > &polygons, bool fill_polygon_data=false)
The reconstruction method for 2D data.
void performReconstruction3D (PointCloud &points, std::vector< pcl::Vertices > &polygons, bool fill_polygon_data=false)
The reconstruction method for 3D data.
void performReconstruction (PolygonMesh &output) override
A reconstruction method that returns a polygonmesh.
void performReconstruction (std::vector< pcl::Vertices > &polygons) override
A reconstruction method that returns the polygon of the convex hull.
void calculateInputDimension ()
Automatically determines the dimension of input data - 2D or 3D.
std::string getClassName () const override
Class get name method.
Protected Member Functions inherited from pcl::PCLBase< PointInT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Protected Attributes
bool compute_area_ {false}
double total_area_ {0.0}
double total_volume_ {0.0}
int dimension_ {0}
The dimensionality of the concave hull (2D or 3D).
double projection_angle_thresh_ {std::cos (0.174532925)}
How close can a 2D plane's normal be to an axis to make projection problematic.
std::string qhull_flags {"qhull "}
Option flag string to be used calling qhull.
const Eigen::Vector3d x_axis_ {1.0, 0.0, 0.0}
const Eigen::Vector3d y_axis_ {0.0, 1.0, 0.0}
const Eigen::Vector3d z_axis_ {0.0, 0.0, 1.0}
pcl::PointIndices hull_indices_
Protected Attributes inherited from pcl::MeshConstruction< PointInT >
bool check_tree_ {true}
A flag specifying whether or not the derived reconstruction algorithm needs the search object tree.
Protected Attributes inherited from pcl::PCLSurfaceBase< PointInT >
KdTreePtr tree_
A pointer to the spatial search object.
Protected Attributes inherited from pcl::PCLBase< PointInT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointInT>
class pcl::ConvexHull< PointInT >
ConvexHull using libqhull library.
Author
Aitor Aldoma, Alex Trevor
Definition at line 72 of file convex_hull.h.
Member Typedef Documentation
ConstPtr
template<typename PointInT > using pcl::ConvexHull< PointInT >::ConstPtr = shared_ptr<const ConvexHull<PointInT> >
Definition at line 82 of file convex_hull.h.
PointCloud
template<typename PointInT > using pcl::ConvexHull< PointInT >::PointCloud = pcl::PointCloud<PointInT>
Definition at line 86 of file convex_hull.h.
PointCloudConstPtr
template<typename PointInT > using pcl::ConvexHull< PointInT >::PointCloudConstPtr = typename PointCloud::ConstPtr
Definition at line 88 of file convex_hull.h.
PointCloudPtr
template<typename PointInT > using pcl::ConvexHull< PointInT >::PointCloudPtr = typename PointCloud::Ptr
Definition at line 87 of file convex_hull.h.
Ptr
template<typename PointInT > using pcl::ConvexHull< PointInT >::Ptr = shared_ptr<ConvexHull<PointInT> >
Definition at line 81 of file convex_hull.h.
Constructor & Destructor Documentation
ConvexHull()
template<typename PointInT > pcl::ConvexHull< PointInT >::ConvexHull () default
Empty constructor.
~ConvexHull()
template<typename PointInT > pcl::ConvexHull< PointInT >::~ConvexHull () override default
Empty destructor.
Member Function Documentation
calculateInputDimension()
template<typename PointInT > void pcl::ConvexHull< PointInT >::calculateInputDimension protected
Automatically determines the dimension of input data - 2D or 3D.
Definition at line 57 of file convex_hull.hpp.
References pcl::compute3DCentroid(), pcl::computeCovarianceMatrixNormalized(), and pcl::eigen33().
getClassName()
template<typename PointInT > std::string pcl::ConvexHull< PointInT >::getClassName () const inline override protected virtual
Class get name method.
Reimplemented from pcl::PCLSurfaceBase< PointInT >.
Definition at line 230 of file convex_hull.h.
Referenced by pcl::ConvexHull< PointInT >::setDimension().
getDimension()
template<typename PointInT > int pcl::ConvexHull< PointInT >::getDimension () const inline
Returns the dimensionality (2 or 3) of the calculated hull.
Definition at line 160 of file convex_hull.h.
References pcl::ConvexHull< PointInT >::dimension_.
getHullPointIndices()
template<typename PointInT > void pcl::ConvexHull< PointInT >::getHullPointIndices (pcl::PointIndices & hull_point_indices) const
Retrieve the indices of the input point cloud that for the convex hull.
Note
Should only be called after reconstruction was performed.
Parameters
[out] hull_point_indices The indices of the points forming the point cloud
Definition at line 502 of file convex_hull.hpp.
getTotalArea()
template<typename PointInT > double pcl::ConvexHull< PointInT >::getTotalArea () const inline
Returns the total area of the convex hull.
Definition at line 132 of file convex_hull.h.
References pcl::ConvexHull< PointInT >::total_area_.
getTotalVolume()
template<typename PointInT > double pcl::ConvexHull< PointInT >::getTotalVolume () const inline
Returns the total volume of the convex hull.
Only valid for 3-dimensional sets. For 2D-sets volume is zero.
Definition at line 141 of file convex_hull.h.
References pcl::ConvexHull< PointInT >::total_volume_.
performReconstruction() [1/3]
template<typename PointInT > void pcl::ConvexHull< PointInT >::performReconstruction (PointCloud & points, std::vector< pcl::Vertices > & polygons, bool fill_polygon_data = false) protected
The actual reconstruction method.
Parameters
[out] points the resultant points lying on the convex hull
[out] polygons the resultant convex hull polygons, as a set of vertices. The Vertices structure contains an array of point indices.
[in] fill_polygon_data true if polygons should be filled, false otherwise
Definition at line 424 of file convex_hull.hpp.
performReconstruction() [2/3]
template<typename PointInT > void pcl::ConvexHull< PointInT >::performReconstruction (PolygonMesh & output) override protected virtual
A reconstruction method that returns a polygonmesh.
Parameters
[out] output a PolygonMesh representing the convex hull of the input data.
Implements pcl::MeshConstruction< PointInT >.
Definition at line 462 of file convex_hull.hpp.
References pcl::PolygonMesh::cloud, pcl::PolygonMesh::polygons, and pcl::toPCLPointCloud2().
performReconstruction() [3/3]
template<typename PointInT > void pcl::ConvexHull< PointInT >::performReconstruction (std::vector< pcl::Vertices > & polygons) override protected virtual
A reconstruction method that returns the polygon of the convex hull.
Parameters
[out] polygons the polygon(s) representing the convex hull of the input data.
Implements pcl::MeshConstruction< PointInT >.
Definition at line 474 of file convex_hull.hpp.
performReconstruction2D()
template<typename PointInT > void pcl::ConvexHull< PointInT >::performReconstruction2D (PointCloud & points, std::vector< pcl::Vertices > & polygons, bool fill_polygon_data = false) protected
The reconstruction method for 2D data.
Does not require dimension to be set.
Parameters
[out] points the resultant points lying on the convex hull
[out] polygons the resultant convex hull polygons, as a set of vertices. The Vertices structure contains an array of point indices.
[in] fill_polygon_data true if polygons should be filled, false otherwise
Definition at line 76 of file convex_hull.hpp.
References pcl::PointCloud< PointT >::clear(), pcl::comparePoints2D(), pcl::compute3DCentroid(), pcl::computeCovarianceMatrixNormalized(), pcl::eigen33(), pcl::PointCloud< PointT >::height, pcl::PointCloud< PointT >::is_dense, pcl::console::isVerbosityLevelEnabled(), pcl::isXYZFinite(), pcl::console::L_DEBUG, pcl::PointCloud< PointT >::resize(), pcl::PointCloud< PointT >::size(), and pcl::PointCloud< PointT >::width.
performReconstruction3D()
template<typename PointInT > void pcl::ConvexHull< PointInT >::performReconstruction3D (PointCloud & points, std::vector< pcl::Vertices > & polygons, bool fill_polygon_data = false) protected
The reconstruction method for 3D data.
Does not require dimension to be set.
Parameters
[out] points the resultant points lying on the convex hull
[out] polygons the resultant convex hull polygons, as a set of vertices. The Vertices structure contains an array of point indices.
[in] fill_polygon_data true if polygons should be filled, false otherwise
Definition at line 291 of file convex_hull.hpp.
References pcl::PointCloud< PointT >::height, pcl::PointCloud< PointT >::is_dense, pcl::console::isVerbosityLevelEnabled(), pcl::console::L_DEBUG, pcl::PointCloud< PointT >::resize(), pcl::PointCloud< PointT >::size(), and pcl::PointCloud< PointT >::width.
reconstruct() [1/2]
template<typename PointInT > void pcl::ConvexHull< PointInT >::reconstruct (PointCloud & points)
Compute a convex hull for all points given.
Parameters
[out] points the resultant points lying on the convex hull.
Definition at line 439 of file convex_hull.hpp.
References pcl::PointCloud< PointT >::clear(), pcl::PointCloud< PointT >::header, pcl::PointCloud< PointT >::height, pcl::PointCloud< PointT >::is_dense, pcl::PointCloud< PointT >::size(), and pcl::PointCloud< PointT >::width.
reconstruct() [2/2]
template<typename PointInT > void pcl::ConvexHull< PointInT >::reconstruct (PointCloud & points, std::vector< pcl::Vertices > & polygons)
Compute a convex hull for all points given.
Note
In 2D case (i.e. if the input points belong to one plane) the polygons vector will have a single item, whereas in 3D case it will contain one item for each hull facet.
Parameters
[out] points the resultant points lying on the convex hull.
[out] polygons the resultant convex hull polygons, as a set of vertices. The Vertices structure contains an array of point indices.
Definition at line 482 of file convex_hull.hpp.
References pcl::PointCloud< PointT >::clear(), pcl::PointCloud< PointT >::header, pcl::PointCloud< PointT >::height, pcl::PointCloud< PointT >::is_dense, pcl::PointCloud< PointT >::size(), and pcl::PointCloud< PointT >::width.
setComputeAreaVolume()
template<typename PointInT > void pcl::ConvexHull< PointInT >::setComputeAreaVolume (bool value) inline
If set to true, the qhull library is called to compute the total area and volume of the convex hull.
NOTE: When this option is activated, the qhull library produces output to the console.
Parameters
[in] value whether to compute the area and the volume, default is false
Definition at line 121 of file convex_hull.h.
References pcl::ConvexHull< PointInT >::compute_area_, and pcl::ConvexHull< PointInT >::qhull_flags.
setDimension()
template<typename PointInT > void pcl::ConvexHull< PointInT >::setDimension (int dimension) inline
Sets the dimension on the input data, 2D or 3D.
Parameters
[in] dimension The dimension of the input data. If not set, this will be determined automatically.
Definition at line 150 of file convex_hull.h.
References pcl::ConvexHull< PointInT >::dimension_, and pcl::ConvexHull< PointInT >::getClassName().
Member Data Documentation
compute_area_
template<typename PointInT > bool pcl::ConvexHull< PointInT >::compute_area_ {false} protected
Definition at line 236 of file convex_hull.h.
Referenced by pcl::ConvexHull< PointInT >::setComputeAreaVolume().
dimension_
template<typename PointInT > int pcl::ConvexHull< PointInT >::dimension_ {0} protected
The dimensionality of the concave hull (2D or 3D).
Definition at line 245 of file convex_hull.h.
Referenced by pcl::ConvexHull< PointInT >::getDimension(), and pcl::ConvexHull< PointInT >::setDimension().
hull_indices_
template<typename PointInT > pcl::PointIndices pcl::ConvexHull< PointInT >::hull_indices_ protected
Definition at line 263 of file convex_hull.h.
projection_angle_thresh_
template<typename PointInT > double pcl::ConvexHull< PointInT >::projection_angle_thresh_ {std::cos (0.174532925)} protected
How close can a 2D plane's normal be to an axis to make projection problematic.
Definition at line 248 of file convex_hull.h.
qhull_flags
template<typename PointInT > std::string pcl::ConvexHull< PointInT >::qhull_flags {"qhull "} protected
Option flag string to be used calling qhull.
Definition at line 251 of file convex_hull.h.
Referenced by pcl::ConvexHull< PointInT >::setComputeAreaVolume().
total_area_
template<typename PointInT > double pcl::ConvexHull< PointInT >::total_area_ {0.0} protected
Definition at line 239 of file convex_hull.h.
Referenced by pcl::ConvexHull< PointInT >::getTotalArea().
total_volume_
template<typename PointInT > double pcl::ConvexHull< PointInT >::total_volume_ {0.0} protected
Definition at line 242 of file convex_hull.h.
Referenced by pcl::ConvexHull< PointInT >::getTotalVolume().
x_axis_
template<typename PointInT > const Eigen::Vector3d pcl::ConvexHull< PointInT >::x_axis_ {1.0, 0.0, 0.0} protected
Definition at line 254 of file convex_hull.h.
y_axis_
template<typename PointInT > const Eigen::Vector3d pcl::ConvexHull< PointInT >::y_axis_ {0.0, 1.0, 0.0} protected
Definition at line 257 of file convex_hull.h.
z_axis_
template<typename PointInT > const Eigen::Vector3d pcl::ConvexHull< PointInT >::z_axis_ {0.0, 0.0, 1.0} protected
Definition at line 260 of file convex_hull.h.
The documentation for this class was generated from the following files:
pcl/surface/convex_hull.h
pcl/surface/impl/convex_hull.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:25