Point Cloud Library (PCL): pcl::geometry::EdgeIndex Class Reference
pcl::geometry::EdgeIndex Class Reference
Module geometry
Index used to access elements in the half-edge mesh.
#include <pcl/geometry/mesh_indices.h>
Public Types
using Base = boost::totally_ordered< pcl::geometry::EdgeIndex, boost::unit_steppable< pcl::geometry::EdgeIndex, boost::additive< pcl::geometry::EdgeIndex > >>
using Self = pcl::geometry::EdgeIndex
Public Member Functions
EdgeIndex ()
Constructor.
EdgeIndex (const int index)
Constructor.
bool isValid () const
Returns true if the index is valid.
void invalidate ()
Invalidate the index.
int get () const
Get the index.
void set (const int index)
Set the index.
bool operator< (const Self &other) const
Comparison operators (with boost::operators): < > <= >=.
bool operator== (const Self &other) const
Comparison operators (with boost::operators): == !=.
Self & operator++ ()
Increment operators (with boost::operators): ++ (pre and post)
Self & operator-- ()
Decrement operators (with boost::operators): -- (pre and post)
Self & operator+= (const Self &other)
Addition operators (with boost::operators): + +=.
Self & operator-= (const Self &other)
Subtraction operators (with boost::operators): - -=.
Friends
std::istream & operator>> (std::istream &is, pcl::geometry::EdgeIndex &index)
istream operator.
Detailed Description
Index used to access elements in the half-edge mesh.
It is basically just a wrapper around an integer with a few added methods.
Author
Martin Saelzle
Definition at line 327 of file mesh_indices.h.
Member Typedef Documentation
Base
using pcl::geometry::EdgeIndex::Base = boost::totally_ordered< pcl::geometry::EdgeIndex, boost::unit_steppable<pcl::geometry::EdgeIndex, boost::additive<pcl::geometry::EdgeIndex> >>
Definition at line 339 of file mesh_indices.h.
Self
using pcl::geometry::EdgeIndex::Self = pcl::geometry::EdgeIndex
Definition at line 340 of file mesh_indices.h.
Constructor & Destructor Documentation
EdgeIndex() [1/2]
pcl::geometry::EdgeIndex::EdgeIndex () inline
Constructor.
Initializes with an invalid index.
Definition at line 343 of file mesh_indices.h.
EdgeIndex() [2/2]
pcl::geometry::EdgeIndex::EdgeIndex (const int index) inline explicit
Constructor.
Parameters
[in] index The integer index.
Definition at line 348 of file mesh_indices.h.
Member Function Documentation
get()
int pcl::geometry::EdgeIndex::get () const inline
Get the index.
Definition at line 366 of file mesh_indices.h.
Referenced by pcl::geometry::getBoundBoundaryHalfEdges(), operator+=(), operator-=(), operator<(), pcl::geometry::operator<<(), operator==(), and pcl::geometry::toHalfEdgeIndex().
invalidate()
void pcl::geometry::EdgeIndex::invalidate () inline
Invalidate the index.
Definition at line 359 of file mesh_indices.h.
isValid()
bool pcl::geometry::EdgeIndex::isValid () const inline
Returns true if the index is valid.
Definition at line 352 of file mesh_indices.h.
Referenced by pcl::geometry::toHalfEdgeIndex().
operator++()
Self& pcl::geometry::EdgeIndex::operator++ () inline
Increment operators (with boost::operators): ++ (pre and post)
Definition at line 394 of file mesh_indices.h.
operator+=()
Self& pcl::geometry::EdgeIndex::operator+= (const Self & other) inline
Addition operators (with boost::operators): + +=.
Definition at line 410 of file mesh_indices.h.
References get().
operator--()
Self& pcl::geometry::EdgeIndex::operator-- () inline
Decrement operators (with boost::operators): -- (pre and post)
Definition at line 402 of file mesh_indices.h.
operator-=()
Self& pcl::geometry::EdgeIndex::operator-= (const Self & other) inline
Subtraction operators (with boost::operators): - -=.
Definition at line 418 of file mesh_indices.h.
References get().
operator<()
bool pcl::geometry::EdgeIndex::operator< (const Self & other) const inline
Comparison operators (with boost::operators): < > <= >=.
Definition at line 380 of file mesh_indices.h.
References get().
operator==()
bool pcl::geometry::EdgeIndex::operator== (const Self & other) const inline
Comparison operators (with boost::operators): == !=.
Definition at line 387 of file mesh_indices.h.
References get().
set()
void pcl::geometry::EdgeIndex::set (const int index) inline
Set the index.
Definition at line 373 of file mesh_indices.h.
Friends And Related Function Documentation
operator>>
std::istream& operator>> (std::istream & is, pcl::geometry::EdgeIndex & index) friend
istream operator.
Definition at line 441 of file mesh_indices.h.
The documentation for this class was generated from the following file:
pcl/geometry/mesh_indices.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Apr 6 2021 19:04:55