Point Cloud Library (PCL): pcl::TfQuadraticXYZComparison< PointT > Class Template Reference
pcl::TfQuadraticXYZComparison< PointT > Class Template Reference
A comparison whether the (x,y,z) components of a given point satisfy (p'Ap + 2v'p + c [OP] 0).
#include <pcl/filters/conditional_removal.h>
Public Types
using Ptr = shared_ptr< TfQuadraticXYZComparison< PointT > >
using ConstPtr = shared_ptr< const TfQuadraticXYZComparison< PointT > >
Public Types inherited from pcl::ComparisonBase< PointT >
using Ptr = shared_ptr< ComparisonBase< PointT > >
using ConstPtr = shared_ptr< const ComparisonBase< PointT > >
Public Member Functions
TfQuadraticXYZComparison ()
Constructor.
~TfQuadraticXYZComparison ()
Empty destructor.
TfQuadraticXYZComparison (const pcl::ComparisonOps::CompareOp op, const Eigen::Matrix3f &comparison_matrix, const Eigen::Vector3f &comparison_vector, const float &comparison_scalar, const Eigen::Affine3f &comparison_transform=Eigen::Affine3f::Identity())
Constructor.
void setComparisonOperator (const pcl::ComparisonOps::CompareOp op)
set the operator "[OP]" of the comparison "p'Ap + 2v'p + c [OP] 0".
void setComparisonMatrix (const Eigen::Matrix3f &matrix)
set the matrix "A" of the comparison "p'Ap + 2v'p + c [OP] 0".
void setComparisonMatrix (const Eigen::Matrix4f &homogeneousMatrix)
set the matrix "A" of the comparison "p'Ap + 2v'p + c [OP] 0".
void setComparisonVector (const Eigen::Vector3f &vector)
set the vector "v" of the comparison "p'Ap + 2v'p + c [OP] 0".
void setComparisonVector (const Eigen::Vector4f &homogeneousVector)
set the vector "v" of the comparison "p'Ap + 2v'p + c [OP] 0".
void setComparisonScalar (const float &scalar)
set the scalar "c" of the comparison "p'Ap + 2v'p + c [OP] 0".
void transformComparison (const Eigen::Matrix4f &transform)
transform the coordinate system of the comparison.
void transformComparison (const Eigen::Affine3f &transform)
transform the coordinate system of the comparison.
bool evaluate (const PointT &point) const override
Determine the result of this comparison.
Public Member Functions inherited from pcl::ComparisonBase< PointT >
ComparisonBase ()
Constructor.
virtual ~ComparisonBase ()
Destructor.
bool isCapable () const
Return if the comparison is capable.
Protected Attributes
Eigen::Matrix4f comp_matr_
Eigen::Vector4f comp_vect_
float comp_scalar_
Protected Attributes inherited from pcl::ComparisonBase< PointT >
bool capable_
True if capable.
std::string field_name_
Field name to compare data on.
std::uint32_t offset_
The data offset.
ComparisonOps::CompareOp op_
The comparison operator type.
Detailed Description
template<typename PointT>
class pcl::TfQuadraticXYZComparison< PointT >
A comparison whether the (x,y,z) components of a given point satisfy (p'Ap + 2v'p + c [OP] 0).
Here [OP] stands for the defined pcl::ComparisonOps, i.e. for GT, GE, LT, LE or EQ; p = (x,y,z) is a point of the point cloud; A is 3x3 matrix; v is the 3x1 vector; c is a scalar.
One can also use TfQuadraticXYZComparison for simpler geometric shapes by defining the quadratic parts (i.e. the matrix A) to be zero. By combining different instances of TfQuadraticXYZComparison one can get more complex shapes. For example, to have a simple cylinder (along the x-axis) of specific length one needs three comparisons combined as AND condition:
The cylinder: A = [0 0 0, 0 1 0, 0 0 1]; v = [0, 0, 0]; c = radius²; OP = LT (meaning "<")
X-min limit: A = 0; v = [1, 0, 0]; c = x_min; OP = GT
X-max ...
Author
Julian Löchner
Definition at line 311 of file conditional_removal.h.
Member Typedef Documentation
ConstPtr
template<typename PointT > using pcl::TfQuadraticXYZComparison< PointT >::ConstPtr = shared_ptr<const TfQuadraticXYZComparison<PointT> >
Definition at line 317 of file conditional_removal.h.
Ptr
template<typename PointT > using pcl::TfQuadraticXYZComparison< PointT >::Ptr = shared_ptr<TfQuadraticXYZComparison<PointT> >
Definition at line 316 of file conditional_removal.h.
Constructor & Destructor Documentation
TfQuadraticXYZComparison() [1/2]
template<typename PointT > pcl::TfQuadraticXYZComparison< PointT >::TfQuadraticXYZComparison
Constructor.
Definition at line 369 of file conditional_removal.hpp.
References pcl::ComparisonBase< PointT >::capable_, pcl::TfQuadraticXYZComparison< PointT >::comp_matr_, pcl::TfQuadraticXYZComparison< PointT >::comp_vect_, pcl::ComparisonOps::EQ, and pcl::ComparisonBase< PointT >::op_.
~TfQuadraticXYZComparison()
template<typename PointT > pcl::TfQuadraticXYZComparison< PointT >::~TfQuadraticXYZComparison () inline
Empty destructor.
Definition at line 324 of file conditional_removal.h.
TfQuadraticXYZComparison() [2/2]
template<typename PointT > pcl::TfQuadraticXYZComparison< PointT >::TfQuadraticXYZComparison (const pcl::ComparisonOps::CompareOp op, const Eigen::Matrix3f & comparison_matrix, const Eigen::Vector3f & comparison_vector, const float & comparison_scalar, const Eigen::Affine3f & comparison_transform = Eigen::Affine3f::Identity ())
Constructor.
Parameters
op the operator "[OP]" of the comparison "p'Ap + 2v'p + c [OP] 0".
comparison_matrix the matrix "A" of the comparison "p'Ap + 2v'p + c [OP] 0".
comparison_vector the vector "v" of the comparison "p'Ap + 2v'p + c [OP] 0".
comparison_scalar the scalar "c" of the comparison "p'Ap + 2v'p + c [OP] 0".
comparison_transform the transformation of the comparison.
Definition at line 427 of file conditional_removal.hpp.
References pcl::ComparisonBase< PointT >::capable_, pcl::ComparisonBase< PointT >::op_, pcl::TfQuadraticXYZComparison< PointT >::setComparisonMatrix(), pcl::TfQuadraticXYZComparison< PointT >::setComparisonVector(), and pcl::TfQuadraticXYZComparison< PointT >::transformComparison().
Member Function Documentation
evaluate()
template<typename PointT > bool pcl::TfQuadraticXYZComparison< PointT >::evaluate (const PointT & point) const override virtual
Determine the result of this comparison.
Parameters
point the point to evaluate
Returns
the result of this comparison.
Implements pcl::ComparisonBase< PointT >.
Definition at line 490 of file conditional_removal.hpp.
References pcl::ComparisonOps::EQ, pcl::ComparisonOps::GE, pcl::ComparisonOps::GT, pcl::ComparisonOps::LE, and pcl::ComparisonOps::LT.
setComparisonMatrix() [1/2]
template<typename PointT > void pcl::TfQuadraticXYZComparison< PointT >::setComparisonMatrix (const Eigen::Matrix3f & matrix) inline
set the matrix "A" of the comparison "p'Ap + 2v'p + c [OP] 0".
Definition at line 348 of file conditional_removal.h.
References pcl::TfQuadraticXYZComparison< PointT >::comp_matr_.
Referenced by pcl::TfQuadraticXYZComparison< PointT >::TfQuadraticXYZComparison().
setComparisonMatrix() [2/2]
template<typename PointT > void pcl::TfQuadraticXYZComparison< PointT >::setComparisonMatrix (const Eigen::Matrix4f & homogeneousMatrix) inline
set the matrix "A" of the comparison "p'Ap + 2v'p + c [OP] 0".
Definition at line 360 of file conditional_removal.h.
References pcl::TfQuadraticXYZComparison< PointT >::comp_matr_.
setComparisonOperator()
template<typename PointT > void pcl::TfQuadraticXYZComparison< PointT >::setComparisonOperator (const pcl::ComparisonOps::CompareOp op) inline
set the operator "[OP]" of the comparison "p'Ap + 2v'p + c [OP] 0".
Definition at line 340 of file conditional_removal.h.
References pcl::ComparisonBase< PointT >::op_.
setComparisonScalar()
template<typename PointT > void pcl::TfQuadraticXYZComparison< PointT >::setComparisonScalar (const float & scalar) inline
set the scalar "c" of the comparison "p'Ap + 2v'p + c [OP] 0".
Definition at line 387 of file conditional_removal.h.
References pcl::TfQuadraticXYZComparison< PointT >::comp_scalar_.
setComparisonVector() [1/2]
template<typename PointT > void pcl::TfQuadraticXYZComparison< PointT >::setComparisonVector (const Eigen::Vector3f & vector) inline
set the vector "v" of the comparison "p'Ap + 2v'p + c [OP] 0".
Definition at line 369 of file conditional_removal.h.
References pcl::TfQuadraticXYZComparison< PointT >::comp_vect_.
Referenced by pcl::TfQuadraticXYZComparison< PointT >::TfQuadraticXYZComparison().
setComparisonVector() [2/2]
template<typename PointT > void pcl::TfQuadraticXYZComparison< PointT >::setComparisonVector (const Eigen::Vector4f & homogeneousVector) inline
set the vector "v" of the comparison "p'Ap + 2v'p + c [OP] 0".
Definition at line 378 of file conditional_removal.h.
References pcl::TfQuadraticXYZComparison< PointT >::comp_vect_.
transformComparison() [1/2]
template<typename PointT > void pcl::TfQuadraticXYZComparison< PointT >::transformComparison (const Eigen::Affine3f & transform) inline
transform the coordinate system of the comparison.
If you think of the transformation to be a translation and rotation of the comparison in the same coordinate system, you have to provide the inverse transformation. This function does not change the original definition of the comparison. Thus, each call of this function will assume the original definition of the comparison as starting point for the transformation.
Parameters
transform the transformation (rotation and translation) as an affine matrix.
Definition at line 418 of file conditional_removal.h.
References pcl::TfQuadraticXYZComparison< PointT >::transformComparison().
transformComparison() [2/2]
template<typename PointT > void pcl::TfQuadraticXYZComparison< PointT >::transformComparison (const Eigen::Matrix4f & transform) inline
transform the coordinate system of the comparison.
If you think of the transformation to be a translation and rotation of the comparison in the same coordinate system, you have to provide the inverse transformation. This function does not change the original definition of the comparison. Thus, each call of this function will assume the original definition of the comparison as starting point for the transformation.
Parameters
transform the transformation (rotation and translation) as an affine matrix.
Definition at line 402 of file conditional_removal.h.
References pcl::TfQuadraticXYZComparison< PointT >::comp_matr_, and pcl::TfQuadraticXYZComparison< PointT >::comp_vect_.
Referenced by pcl::TfQuadraticXYZComparison< PointT >::TfQuadraticXYZComparison(), and pcl::TfQuadraticXYZComparison< PointT >::transformComparison().
Member Data Documentation
comp_matr_
template<typename PointT > Eigen::Matrix4f pcl::TfQuadraticXYZComparison< PointT >::comp_matr_ protected
Definition at line 434 of file conditional_removal.h.
Referenced by pcl::TfQuadraticXYZComparison< PointT >::setComparisonMatrix(), pcl::TfQuadraticXYZComparison< PointT >::TfQuadraticXYZComparison(), and pcl::TfQuadraticXYZComparison< PointT >::transformComparison().
comp_scalar_
template<typename PointT > float pcl::TfQuadraticXYZComparison< PointT >::comp_scalar_ protected
Definition at line 437 of file conditional_removal.h.
Referenced by pcl::TfQuadraticXYZComparison< PointT >::setComparisonScalar().
comp_vect_
template<typename PointT > Eigen::Vector4f pcl::TfQuadraticXYZComparison< PointT >::comp_vect_ protected
Definition at line 435 of file conditional_removal.h.
Referenced by pcl::TfQuadraticXYZComparison< PointT >::setComparisonVector(), pcl::TfQuadraticXYZComparison< PointT >::TfQuadraticXYZComparison(), and pcl::TfQuadraticXYZComparison< PointT >::transformComparison().
The documentation for this class was generated from the following files:
pcl/filters/conditional_removal.h
pcl/filters/impl/conditional_removal.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Jun 2 2020 14:13:06