Point Cloud Library (PCL): pcl::octree::OctreeLeafNodeIterator< OctreeT > Class Template Reference
pcl::octree::OctreeLeafNodeIterator< OctreeT > Class Template Reference
Module octree
Octree leaf node iterator class.
#include <pcl/octree/octree_iterator.h>
Public Member Functions
OctreeLeafNodeIterator (unsigned int max_depth_arg=0)
Empty constructor.
OctreeLeafNodeIterator (OctreeT *octree_arg, unsigned int max_depth_arg=0)
Constructor.
OctreeLeafNodeIterator (OctreeT *octree_arg, unsigned int max_depth_arg, IteratorState *current_state, const std::vector< IteratorState > &stack=std::vector< IteratorState >())
Constructor.
void reset ()
Reset the iterator to the root node of the octree.
OctreeLeafNodeIterator & operator++ ()
Preincrement operator.
OctreeLeafNodeIterator operator++ (int)
postincrement operator.
OctreeNode * operator* () const
*operator.
Public Member Functions inherited from pcl::octree::OctreeDepthFirstIterator< OctreeT >
OctreeDepthFirstIterator (unsigned int max_depth_arg=0)
Empty constructor.
OctreeDepthFirstIterator (OctreeT *octree_arg, unsigned int max_depth_arg=0)
Constructor.
OctreeDepthFirstIterator (OctreeT *octree_arg, unsigned int max_depth_arg, IteratorState *current_state, const std::vector< IteratorState > &stack=std::vector< IteratorState >())
Constructor.
OctreeDepthFirstIterator (const OctreeDepthFirstIterator &other)
Copy Constructor.
OctreeDepthFirstIterator & operator= (const OctreeDepthFirstIterator &src)
Copy assignment.
OctreeDepthFirstIterator & operator++ ()
Preincrement operator.
OctreeDepthFirstIterator operator++ (int)
postincrement operator.
void skipChildVoxels ()
Skip all child voxels of current node and return to parent node.
Public Member Functions inherited from pcl::octree::OctreeIteratorBase< OctreeT >
OctreeIteratorBase (unsigned int max_depth_arg=0)
Empty constructor.
OctreeIteratorBase (OctreeT *octree_arg, unsigned int max_depth_arg=0)
Constructor.
OctreeIteratorBase (OctreeT *octree_arg, unsigned int max_depth_arg, IteratorState *current_state)
Constructor.
virtual ~OctreeIteratorBase ()
Empty deconstructor.
bool operator== (const OctreeIteratorBase &other) const
Equal comparison operator.
bool operator!= (const OctreeIteratorBase &other) const
Inequal comparison operator.
void reset ()
Reset iterator.
const OctreeKey & getCurrentOctreeKey () const
Get octree key for the current iterator octree node.
unsigned int getCurrentOctreeDepth () const
Get the current depth level of octree.
OctreeNode * getCurrentOctreeNode () const
Get the current octree node.
bool isBranchNode () const
check if current node is a branch node
bool isLeafNode () const
check if current node is a branch node
OctreeNode * operator* () const
*operator.
char getNodeConfiguration () const
Get bit pattern of children configuration of current node.
const LeafContainer & getLeafContainer () const
Method for retrieving a single leaf container from the octree leaf node.
LeafContainer & getLeafContainer ()
Method for retrieving a single leaf container from the octree leaf node.
const BranchContainer & getBranchContainer () const
Method for retrieving the container from an octree branch node.
BranchContainer & getBranchContainer ()
Method for retrieving the container from an octree branch node.
virtual unsigned long getNodeID () const
get a integer identifier for current node (note: identifier depends on tree depth).
Additional Inherited Members
Public Types inherited from pcl::octree::OctreeDepthFirstIterator< OctreeT >
typedef OctreeIteratorBase
< OctreeT >::LeafNode LeafNode
typedef OctreeIteratorBase
< OctreeT >::BranchNode BranchNode
Public Types inherited from pcl::octree::OctreeIteratorBase< OctreeT >
typedef OctreeT::LeafNode LeafNode
typedef OctreeT::BranchNode BranchNode
typedef OctreeT::LeafContainer LeafContainer
typedef OctreeT::BranchContainer BranchContainer
Protected Attributes inherited from pcl::octree::OctreeDepthFirstIterator< OctreeT >
std::vector< IteratorState > stack_
Stack structure.
Protected Attributes inherited from pcl::octree::OctreeIteratorBase< OctreeT >
OctreeT * octree_
Reference to octree class.
IteratorState * current_state_
Pointer to current iterator state.
unsigned int max_octree_depth_
Maximum octree depth.
Detailed Description
template<typename OctreeT>
class pcl::octree::OctreeLeafNodeIterator< OctreeT >
Octree leaf node iterator class.
Note
This class implements a forward iterator for traversing the leaf nodes of an octree data structure.
Author
Julius Kammerl (juliu.nosp@m.s@ka.nosp@m.mmerl.nosp@m..de)
Definition at line 665 of file octree_iterator.h.
Constructor & Destructor Documentation
template<typename OctreeT > pcl::octree::OctreeLeafNodeIterator< OctreeT >::OctreeLeafNodeIterator (unsigned int max_depth_arg = 0) inline explicit
Empty constructor.
Parameters
[in] max_depth_arg Depth limitation during traversal
Definition at line 675 of file octree_iterator.h.
References pcl::octree::OctreeLeafNodeIterator< OctreeT >::reset().
template<typename OctreeT > pcl::octree::OctreeLeafNodeIterator< OctreeT >::OctreeLeafNodeIterator (OctreeT * octree_arg, unsigned int max_depth_arg = 0) inline explicit
Constructor.
Parameters
[in] octree_arg Octree to be iterated. Initially the iterator is set to its root node.
[in] max_depth_arg Depth limitation during traversal
Definition at line 686 of file octree_iterator.h.
References pcl::octree::OctreeLeafNodeIterator< OctreeT >::reset().
template<typename OctreeT > pcl::octree::OctreeLeafNodeIterator< OctreeT >::OctreeLeafNodeIterator (OctreeT * octree_arg, unsigned int max_depth_arg, IteratorState * current_state, const std::vector< IteratorState > & stack = std::vector<IteratorState> ()) inline explicit
Constructor.
Parameters
[in] octree_arg Octree to be iterated. Initially the iterator is set to its root node.
[in] max_depth_arg Depth limitation during traversal
[in] current_state A pointer to the current iterator state
Warning
For advanced users only.
Definition at line 700 of file octree_iterator.h.
Member Function Documentation
template<typename OctreeT > OctreeNode* pcl::octree::OctreeLeafNodeIterator< OctreeT >::operator* () const inline
*operator.
Returns
pointer to the current octree leaf node
Definition at line 748 of file octree_iterator.h.
References pcl::octree::OctreeIteratorBase< OctreeT >::current_state_, pcl::octree::OctreeNode::getNodeType(), pcl::octree::LEAF_NODE, and pcl::octree::IteratorState::node_.
template<typename OctreeT > OctreeLeafNodeIterator& pcl::octree::OctreeLeafNodeIterator< OctreeT >::operator++ () inline
Preincrement operator.
Note
recursively step to next octree leaf node
Definition at line 723 of file octree_iterator.h.
References pcl::octree::OctreeIteratorBase< OctreeT >::current_state_, pcl::octree::OctreeNode::getNodeType(), pcl::octree::LEAF_NODE, pcl::octree::IteratorState::node_, and pcl::octree::OctreeDepthFirstIterator< OctreeT >::operator++().
Referenced by pcl::octree::OctreeLeafNodeIterator< OctreeT >::reset().
template<typename OctreeT > OctreeLeafNodeIterator pcl::octree::OctreeLeafNodeIterator< OctreeT >::operator++ (int) inline
postincrement operator.
Note
step to next octree node
Definition at line 737 of file octree_iterator.h.
template<typename OctreeT > void pcl::octree::OctreeLeafNodeIterator< OctreeT >::reset () inline virtual
Reset the iterator to the root node of the octree.
Reimplemented from pcl::octree::OctreeDepthFirstIterator< OctreeT >.
Definition at line 713 of file octree_iterator.h.
References pcl::octree::OctreeLeafNodeIterator< OctreeT >::operator++(), and pcl::octree::OctreeDepthFirstIterator< OctreeT >::reset().
Referenced by pcl::octree::OctreeLeafNodeIterator< OctreeT >::OctreeLeafNodeIterator().
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/octree/include/pcl/octree/octree_iterator.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Mon Jul 9 2018 16:46:17