Point Cloud Library (PCL): pcl::geometry::VertexIndex Class Reference
pcl::geometry::VertexIndex Class Reference
Module geometry
Index used to access elements in the half-edge mesh.
#include <pcl/geometry/mesh_indices.h>
Public Types
using Base = boost::totally_ordered< pcl::geometry::VertexIndex, boost::unit_steppable< pcl::geometry::VertexIndex, boost::additive< pcl::geometry::VertexIndex > >>
using Self = pcl::geometry::VertexIndex
Public Member Functions
VertexIndex ()
Constructor.
VertexIndex (const int index)
Constructor.
bool isValid () const
Returns true if the index is valid.
void invalidate ()
Invalidate the index.
int get () const
Get the index.
void set (const int index)
Set the index.
bool operator< (const Self &other) const
Comparison operators (with boost::operators): < > <= >=.
bool operator== (const Self &other) const
Comparison operators (with boost::operators): == !=.
Self & operator++ ()
Increment operators (with boost::operators): ++ (pre and post)
Self & operator-- ()
Decrement operators (with boost::operators): -- (pre and post)
Self & operator+= (const Self &other)
Addition operators (with boost::operators): + +=.
Self & operator-= (const Self &other)
Subtraction operators (with boost::operators): - -=.
Friends
std::istream & operator>> (std::istream &is, pcl::geometry::VertexIndex &index)
istream operator.
Detailed Description
Index used to access elements in the half-edge mesh.
It is basically just a wrapper around an integer with a few added methods.
Author
Martin Saelzle
Definition at line 61 of file mesh_indices.h.
Member Typedef Documentation
Base
using pcl::geometry::VertexIndex::Base = boost::totally_ordered< pcl::geometry::VertexIndex, boost::unit_steppable<pcl::geometry::VertexIndex, boost::additive<pcl::geometry::VertexIndex> >>
Definition at line 73 of file mesh_indices.h.
Self
using pcl::geometry::VertexIndex::Self = pcl::geometry::VertexIndex
Definition at line 74 of file mesh_indices.h.
Constructor & Destructor Documentation
VertexIndex() [1/2]
pcl::geometry::VertexIndex::VertexIndex () inline
Constructor.
Initializes with an invalid index.
Definition at line 77 of file mesh_indices.h.
VertexIndex() [2/2]
pcl::geometry::VertexIndex::VertexIndex (const int index) inline explicit
Constructor.
Parameters
[in] index The integer index.
Definition at line 82 of file mesh_indices.h.
Member Function Documentation
get()
int pcl::geometry::VertexIndex::get () const inline
Get the index.
Definition at line 100 of file mesh_indices.h.
Referenced by pcl::geometry::MeshBase< QuadMesh< MeshTraitsT >, MeshTraitsT, QuadMeshTag >::getVertex(), operator+=(), operator-=(), operator<(), pcl::geometry::operator<<(), operator==(), and pcl::geometry::MeshBase< QuadMesh< MeshTraitsT >, MeshTraitsT, QuadMeshTag >::setVertex().
invalidate()
void pcl::geometry::VertexIndex::invalidate () inline
Invalidate the index.
Definition at line 93 of file mesh_indices.h.
Referenced by pcl::geometry::MeshBase< QuadMesh< MeshTraitsT >, MeshTraitsT, QuadMeshTag >::markDeleted().
isValid()
bool pcl::geometry::VertexIndex::isValid () const inline
Returns true if the index is valid.
Definition at line 86 of file mesh_indices.h.
operator++()
Self& pcl::geometry::VertexIndex::operator++ () inline
Increment operators (with boost::operators): ++ (pre and post)
Definition at line 128 of file mesh_indices.h.
operator+=()
Self& pcl::geometry::VertexIndex::operator+= (const Self & other) inline
Addition operators (with boost::operators): + +=.
Definition at line 144 of file mesh_indices.h.
References get().
operator--()
Self& pcl::geometry::VertexIndex::operator-- () inline
Decrement operators (with boost::operators): -- (pre and post)
Definition at line 136 of file mesh_indices.h.
operator-=()
Self& pcl::geometry::VertexIndex::operator-= (const Self & other) inline
Subtraction operators (with boost::operators): - -=.
Definition at line 152 of file mesh_indices.h.
References get().
operator<()
bool pcl::geometry::VertexIndex::operator< (const Self & other) const inline
Comparison operators (with boost::operators): < > <= >=.
Definition at line 114 of file mesh_indices.h.
References get().
operator==()
bool pcl::geometry::VertexIndex::operator== (const Self & other) const inline
Comparison operators (with boost::operators): == !=.
Definition at line 121 of file mesh_indices.h.
References get().
set()
void pcl::geometry::VertexIndex::set (const int index) inline
Set the index.
Definition at line 107 of file mesh_indices.h.
Friends And Related Function Documentation
operator>>
std::istream& operator>> (std::istream & is, pcl::geometry::VertexIndex & index) friend
istream operator.
Definition at line 175 of file mesh_indices.h.
The documentation for this class was generated from the following file:
pcl/geometry/mesh_indices.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Apr 6 2021 19:04:57