Point Cloud Library (PCL): pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid Class Reference
pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid Class Reference
A minimalistic implementation of a voxel grid, necessary for the point cloud upsampling.
#include <pcl/surface/mls.h>
Classes
struct Leaf
Public Types
typedef std::map< std::uint64_t, Leaf > HashMap
Public Member Functions
MLSVoxelGrid (PointCloudInConstPtr &cloud, IndicesPtr &indices, float voxel_size)
void dilate ()
void getIndexIn1D (const Eigen::Vector3i &index, std::uint64_t &index_1d) const
void getIndexIn3D (std::uint64_t index_1d, Eigen::Vector3i &index_3d) const
void getCellIndex (const Eigen::Vector3f &p, Eigen::Vector3i &index) const
void getPosition (const std::uint64_t &index_1d, Eigen::Vector3f &point) const
Public Attributes
HashMap voxel_grid_
Eigen::Vector4f bounding_min_
Eigen::Vector4f bounding_max_
std::uint64_t data_size_
float voxel_size_
Detailed Description
template<typename PointInT, typename PointOutT>
class pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid
A minimalistic implementation of a voxel grid, necessary for the point cloud upsampling.
Note
Used only in the case of VOXEL_GRID_DILATION upsampling
Definition at line 603 of file mls.h.
Member Typedef Documentation
HashMap
template<typename PointInT , typename PointOutT > typedef std::map<std::uint64_t, Leaf> pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::HashMap
Definition at line 648 of file mls.h.
Constructor & Destructor Documentation
MLSVoxelGrid()
template<typename PointInT , typename PointOutT > pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::MLSVoxelGrid (PointCloudInConstPtr & cloud, IndicesPtr & indices, float voxel_size)
Definition at line 834 of file mls.hpp.
References pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::bounding_max_, pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::bounding_min_, pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::data_size_, pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::getCellIndex(), pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::getIndexIn1D(), pcl::getMinMax3D(), pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::voxel_grid_, and pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::voxel_size_.
Member Function Documentation
dilate()
template<typename PointInT , typename PointOutT > void pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::dilate
Definition at line 860 of file mls.hpp.
Referenced by pcl::MovingLeastSquares< PointInT, PointOutT >::performUpsampling().
getCellIndex()
template<typename PointInT , typename PointOutT > void pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::getCellIndex (const Eigen::Vector3f & p, Eigen::Vector3i & index) const inline
Definition at line 633 of file mls.h.
References pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::bounding_min_, and pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::voxel_size_.
Referenced by pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::MLSVoxelGrid().
getIndexIn1D()
template<typename PointInT , typename PointOutT > void pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::getIndexIn1D (const Eigen::Vector3i & index, std::uint64_t & index_1d) const inline
Definition at line 616 of file mls.h.
References pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::data_size_.
Referenced by pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::MLSVoxelGrid().
getIndexIn3D()
template<typename PointInT , typename PointOutT > void pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::getIndexIn3D (std::uint64_t index_1d, Eigen::Vector3i & index_3d) const inline
Definition at line 623 of file mls.h.
References pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::data_size_.
Referenced by pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::getPosition().
getPosition()
template<typename PointInT , typename PointOutT > void pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::getPosition (const std::uint64_t & index_1d, Eigen::Vector3f & point) const inline
Definition at line 640 of file mls.h.
References pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::bounding_min_, pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::getIndexIn3D(), and pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::voxel_size_.
Referenced by pcl::MovingLeastSquares< PointInT, PointOutT >::performUpsampling().
Member Data Documentation
bounding_max_
template<typename PointInT , typename PointOutT > Eigen::Vector4f pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::bounding_max_
Definition at line 650 of file mls.h.
Referenced by pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::MLSVoxelGrid().
bounding_min_
template<typename PointInT , typename PointOutT > Eigen::Vector4f pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::bounding_min_
Definition at line 650 of file mls.h.
Referenced by pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::getCellIndex(), pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::getPosition(), and pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::MLSVoxelGrid().
data_size_
template<typename PointInT , typename PointOutT > std::uint64_t pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::data_size_
Definition at line 651 of file mls.h.
Referenced by pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::getIndexIn1D(), pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::getIndexIn3D(), and pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::MLSVoxelGrid().
voxel_grid_
template<typename PointInT , typename PointOutT > HashMap pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::voxel_grid_
Definition at line 649 of file mls.h.
Referenced by pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::MLSVoxelGrid(), and pcl::MovingLeastSquares< PointInT, PointOutT >::performUpsampling().
voxel_size_
template<typename PointInT , typename PointOutT > float pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::voxel_size_
Definition at line 652 of file mls.h.
Referenced by pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::getCellIndex(), pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::getPosition(), and pcl::MovingLeastSquares< PointInT, PointOutT >::MLSVoxelGrid::MLSVoxelGrid().
The documentation for this class was generated from the following files:
pcl/surface/mls.h
pcl/surface/impl/mls.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Jun 2 2020 14:12:17