Point Cloud Library (PCL): pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT > Class Template Reference
pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT > Class Template Reference
Module recognition
Class implementing a 3D correspondence grouping algorithm that can deal with multiple instances of a model template found into a given scene.
#include <pcl/recognition/cg/hough_3d.h>
Public Types
using ModelRfCloud = pcl::PointCloud< PointModelRfT >
using ModelRfCloudPtr = typename ModelRfCloud::Ptr
using ModelRfCloudConstPtr = typename ModelRfCloud::ConstPtr
using SceneRfCloud = pcl::PointCloud< PointSceneRfT >
using SceneRfCloudPtr = typename SceneRfCloud::Ptr
using SceneRfCloudConstPtr = typename SceneRfCloud::ConstPtr
using PointCloud = pcl::PointCloud< PointModelT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using SceneCloudConstPtr = typename pcl::CorrespondenceGrouping< PointModelT, PointSceneT >::SceneCloudConstPtr
Public Types inherited from pcl::CorrespondenceGrouping< PointModelT, PointSceneT >
using SceneCloud = pcl::PointCloud< PointSceneT >
using SceneCloudPtr = typename SceneCloud::Ptr
using SceneCloudConstPtr = typename SceneCloud::ConstPtr
Public Types inherited from pcl::PCLBase< PointModelT >
using PointCloud = pcl::PointCloud< PointModelT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
Hough3DGrouping ()
Constructor.
void setInputCloud (const PointCloudConstPtr &cloud) override
Provide a pointer to the input dataset.
void setInputRf (const ModelRfCloudConstPtr &input_rf)
Provide a pointer to the input dataset's reference frames.
ModelRfCloudConstPtr getInputRf () const
Getter for the input dataset's reference frames.
void setSceneCloud (const SceneCloudConstPtr &scene) override
Provide a pointer to the scene dataset (i.e.
void setSceneRf (const SceneRfCloudConstPtr &scene_rf)
Provide a pointer to the scene dataset's reference frames.
SceneRfCloudConstPtr getSceneRf () const
Getter for the scene dataset's reference frames.
void setModelSceneCorrespondences (const CorrespondencesConstPtr &corrs) override
Provide a pointer to the precomputed correspondences between points in the input dataset and points in the scene dataset.
void setHoughThreshold (double threshold)
Sets the minimum number of votes in the Hough space needed to infer the presence of a model instance into the scene cloud.
double getHoughThreshold () const
Gets the minimum number of votes in the Hough space needed to infer the presence of a model instance into the scene cloud.
void setHoughBinSize (double bin_size)
Sets the size of each bin into the Hough space.
double getHoughBinSize () const
Gets the size of each bin into the Hough space.
void setUseInterpolation (bool use_interpolation)
Sets whether the vote casting procedure interpolates the score between neighboring bins of the Hough space or not.
bool getUseInterpolation () const
Gets whether the vote casting procedure interpolates the score between neighboring bins of the Hough space or not.
void setUseDistanceWeight (bool use_distance_weight)
Sets whether the vote casting procedure uses the correspondence's distance as a score.
bool getUseDistanceWeight () const
Gets whether the vote casting procedure uses the correspondence's distance as a score.
void setLocalRfNormalsSearchRadius (float local_rf_normals_search_radius)
If the Local reference frame has not been set for either the model cloud or the scene cloud, this algorithm makes the computation itself but needs a suitable search radius to compute the normals in order to subsequently compute the RF (if not set a default 15 nearest neighbors search is performed).
float getLocalRfNormalsSearchRadius () const
If the Local reference frame has not been set for either the model cloud or the scene cloud, this algorithm makes the computation itself but needs a suitable search radius to compute the normals in order to subsequently compute the RF (if not set a default 15 nearest neighbors search is performed).
void setLocalRfSearchRadius (float local_rf_search_radius)
If the Local reference frame has not been set for either the model cloud or the scene cloud, this algorithm makes the computation itself but needs a suitable search radius to do so.
float getLocalRfSearchRadius () const
If the Local reference frame has not been set for either the model cloud or the scene cloud, this algorithm makes the computation itself but needs a suitable search radius to do so.
bool train ()
Call this function after setting the input, the input_rf and the hough_bin_size parameters to perform an off line training of the algorithm.
bool recognize (std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f > > &transformations)
The main function, recognizes instances of the model into the scene set by the user.
bool recognize (std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f > > &transformations, std::vector< pcl::Correspondences > &clustered_corrs)
The main function, recognizes instances of the model into the scene set by the user.
Public Member Functions inherited from pcl::CorrespondenceGrouping< PointModelT, PointSceneT >
CorrespondenceGrouping ()
Empty constructor.
~CorrespondenceGrouping ()
destructor.
SceneCloudConstPtr getSceneCloud () const
Getter for the scene dataset.
CorrespondencesConstPtr getModelSceneCorrespondences () const
Getter for the precomputed correspondences between points in the input dataset and points in the scene dataset.
std::vector< double > getCharacteristicScales () const
Getter for the vector of characteristic scales associated to each cluster.
void cluster (std::vector< Correspondences > &clustered_corrs)
Clusters the input correspondences belonging to different model instances.
Public Member Functions inherited from pcl::PCLBase< PointModelT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
const PointCloudConstPtr getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
const IndicesConstPtr getIndices () const
Get a pointer to the vector of indices used.
const PointModelT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
void clusterCorrespondences (std::vector< Correspondences > &model_instances) override
Cluster the input correspondences in order to distinguish between different instances of the model into the scene.
bool houghVoting ()
The Hough space voting procedure.
template<typename PointType , typename PointRfType >
void computeRf (const typename pcl::PointCloud< PointType >::ConstPtr &input, pcl::PointCloud< PointRfType > &rf)
Computes the reference frame for an input cloud.
Protected Member Functions inherited from pcl::CorrespondenceGrouping< PointModelT, PointSceneT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Protected Member Functions inherited from pcl::PCLBase< PointModelT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Protected Attributes
ModelRfCloudConstPtr input_rf_
The input Rf cloud.
SceneRfCloudConstPtr scene_rf_
The scene Rf cloud.
bool needs_training_
If the training of the Hough space is needed; set on change of either the input cloud or the input_rf.
std::vector< Eigen::Vector3f, Eigen::aligned_allocator< Eigen::Vector3f > > model_votes_
The result of the training.
double hough_threshold_
The minimum number of votes in the Hough space needed to infer the presence of a model instance into the scene cloud.
double hough_bin_size_
The size of each bin of the hough space.
bool use_interpolation_
Use the interpolation between neighboring Hough bins when casting votes.
bool use_distance_weight_
Use the weighted correspondence distance when casting votes.
float local_rf_normals_search_radius_
Normals search radius for the potential Rf calculation.
float local_rf_search_radius_
Search radius for the potential Rf calculation.
pcl::recognition::HoughSpace3D::Ptr hough_space_
The Hough space.
std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f > > found_transformations_
Transformations found by clusterCorrespondences method.
bool hough_space_initialized_
Whether the Hough space already contains the correct votes for the current input parameters and so the cluster and recognize calls don't need to recompute each value.
Protected Attributes inherited from pcl::CorrespondenceGrouping< PointModelT, PointSceneT >
SceneCloudConstPtr scene_
The scene cloud.
CorrespondencesConstPtr model_scene_corrs_
The correspondences between points in the input and the scene datasets.
std::vector< double > corr_group_scale_
characteristic scale associated to each correspondence subset; if the cg algorithm can not handle scale invariance, the size of the vector will be 0.
Protected Attributes inherited from pcl::PCLBase< PointModelT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointModelT, typename PointSceneT, typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame>
class pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >
Class implementing a 3D correspondence grouping algorithm that can deal with multiple instances of a model template found into a given scene.
Each correspondence casts a vote for a reference point in a 3D Hough Space. The remaining 3 DOF are taken into account by associating each correspondence with a local Reference Frame. The suggested PointModelRfT is pcl::ReferenceFrame
Note
If you use this code in any academic work, please cite the original paper:
F. Tombari, L. Di Stefano: Object recognition in 3D scenes with occlusions and clutter by Hough voting. 2010, Fourth Pacific-Rim Symposium on Image and Video Technology
Author
Federico Tombari (original), Tommaso Cavallari (PCL port)
Definition at line 149 of file hough_3d.h.
Member Typedef Documentation
ModelRfCloud
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> using pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::ModelRfCloud = pcl::PointCloud<PointModelRfT>
Definition at line 152 of file hough_3d.h.
ModelRfCloudConstPtr
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> using pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::ModelRfCloudConstPtr = typename ModelRfCloud::ConstPtr
Definition at line 154 of file hough_3d.h.
ModelRfCloudPtr
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> using pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::ModelRfCloudPtr = typename ModelRfCloud::Ptr
Definition at line 153 of file hough_3d.h.
PointCloud
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> using pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::PointCloud = pcl::PointCloud<PointModelT>
Definition at line 160 of file hough_3d.h.
PointCloudConstPtr
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> using pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::PointCloudConstPtr = typename PointCloud::ConstPtr
Definition at line 162 of file hough_3d.h.
PointCloudPtr
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> using pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::PointCloudPtr = typename PointCloud::Ptr
Definition at line 161 of file hough_3d.h.
SceneCloudConstPtr
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> using pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::SceneCloudConstPtr = typename pcl::CorrespondenceGrouping<PointModelT, PointSceneT>::SceneCloudConstPtr
Definition at line 164 of file hough_3d.h.
SceneRfCloud
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> using pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::SceneRfCloud = pcl::PointCloud<PointSceneRfT>
Definition at line 156 of file hough_3d.h.
SceneRfCloudConstPtr
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> using pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::SceneRfCloudConstPtr = typename SceneRfCloud::ConstPtr
Definition at line 158 of file hough_3d.h.
SceneRfCloudPtr
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> using pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::SceneRfCloudPtr = typename SceneRfCloud::Ptr
Definition at line 157 of file hough_3d.h.
Constructor & Destructor Documentation
Hough3DGrouping()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::Hough3DGrouping () inline
Constructor.
Definition at line 167 of file hough_3d.h.
Member Function Documentation
clusterCorrespondences()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT , typename PointSceneRfT > void pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::clusterCorrespondences (std::vector< Correspondences > & model_instances) override protected virtual
Cluster the input correspondences in order to distinguish between different instances of the model into the scene.
Parameters
[out] model_instances a vector containing the clustered correspondences for each model found on the scene.
Returns
true if the clustering had been successful or false if errors have occurred.
Implements pcl::CorrespondenceGrouping< PointModelT, PointSceneT >.
Definition at line 258 of file hough_3d.hpp.
References pcl::copyPointCloud(), pcl::registration::CorrespondenceRejectorSampleConsensus< PointT >::getBestTransformation(), pcl::registration::CorrespondenceRejectorSampleConsensus< PointT >::getRemainingCorrespondences(), pcl::registration::CorrespondenceRejectorSampleConsensus< PointT >::setInlierThreshold(), pcl::registration::CorrespondenceRejectorSampleConsensus< PointT >::setInputSource(), pcl::registration::CorrespondenceRejectorSampleConsensus< PointT >::setInputTarget(), and pcl::registration::CorrespondenceRejectorSampleConsensus< PointT >::setMaximumIterations().
computeRf()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT , typename PointSceneRfT > template<typename PointType , typename PointRfType > void pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::computeRf (const typename pcl::PointCloud< PointType >::ConstPtr & input, pcl::PointCloud< PointRfType > & rf) protected
Computes the reference frame for an input cloud.
Parameters
[in] input the input cloud.
[out] rf the resulting reference frame.
Definition at line 54 of file hough_3d.hpp.
References pcl::Feature< PointInT, PointOutT >::compute(), pcl::Feature< PointInT, ReferenceFrame >::compute(), pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::setFindHoles(), pcl::PCLBase< PointInT >::setInputCloud(), pcl::NormalEstimation< PointInT, PointOutT >::setInputCloud(), pcl::FeatureFromNormals< PointInT, PointNT, ReferenceFrame >::setInputNormals(), pcl::Feature< PointInT, PointOutT >::setKSearch(), pcl::Feature< PointInT, ReferenceFrame >::setRadiusSearch(), and pcl::Feature< PointInT, PointOutT >::setRadiusSearch().
getHoughBinSize()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> double pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::getHoughBinSize () const inline
Gets the size of each bin into the Hough space.
Returns
the size of each Hough space's bin.
Definition at line 307 of file hough_3d.h.
References pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::hough_bin_size_.
getHoughThreshold()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> double pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::getHoughThreshold () const inline
Gets the minimum number of votes in the Hough space needed to infer the presence of a model instance into the scene cloud.
Returns
the threshold for the Hough space voting.
Definition at line 286 of file hough_3d.h.
References pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::hough_threshold_.
getInputRf()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> ModelRfCloudConstPtr pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::getInputRf () const inline
Getter for the input dataset's reference frames.
Each point in the reference frame cloud should be the reference frame of the correspondent point in the input dataset.
Returns
the pointer to the input cloud's reference frames.
Definition at line 213 of file hough_3d.h.
References pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::input_rf_.
getLocalRfNormalsSearchRadius()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> float pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::getLocalRfNormalsSearchRadius () const inline
If the Local reference frame has not been set for either the model cloud or the scene cloud, this algorithm makes the computation itself but needs a suitable search radius to compute the normals in order to subsequently compute the RF (if not set a default 15 nearest neighbors search is performed).
Returns
the normals search radius for the local reference frame calculation.
Definition at line 377 of file hough_3d.h.
References pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::local_rf_normals_search_radius_.
getLocalRfSearchRadius()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> float pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::getLocalRfSearchRadius () const inline
If the Local reference frame has not been set for either the model cloud or the scene cloud, this algorithm makes the computation itself but needs a suitable search radius to do so.
Attention
This parameter NEEDS to be set if the reference frames are not precomputed externally, otherwise the recognition results won't be correct.
Returns
the search radius for the local reference frame calculation.
Definition at line 405 of file hough_3d.h.
References pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::local_rf_search_radius_.
getSceneRf()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> SceneRfCloudConstPtr pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::getSceneRf () const inline
Getter for the scene dataset's reference frames.
Each point in the reference frame cloud should be the reference frame of the correspondent point in the scene dataset.
Returns
the pointer to the scene cloud's reference frames.
Definition at line 250 of file hough_3d.h.
References pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::scene_rf_.
getUseDistanceWeight()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> bool pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::getUseDistanceWeight () const inline
Gets whether the vote casting procedure uses the correspondence's distance as a score.
Returns
if the algorithm should use the weighted distance when calculating the Hough voting score.
Definition at line 351 of file hough_3d.h.
References pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::use_distance_weight_.
getUseInterpolation()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> bool pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::getUseInterpolation () const inline
Gets whether the vote casting procedure interpolates the score between neighboring bins of the Hough space or not.
Returns
if the algorithm should interpolate the vote score between neighboring bins.
Definition at line 330 of file hough_3d.h.
References pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::use_interpolation_.
houghVoting()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT , typename PointSceneRfT > bool pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::houghVoting protected
The Hough space voting procedure.
Returns
true if the voting had been successful or false if errors have occurred.
Definition at line 137 of file hough_3d.hpp.
References pcl::geometry::distance().
recognize() [1/2]
template<typename PointModelT , typename PointSceneT , typename PointModelRfT , typename PointSceneRfT > bool pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::recognize (std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f > > & transformations)
The main function, recognizes instances of the model into the scene set by the user.
Parameters
[out] transformations a vector containing one transformation matrix for each instance of the model recognized into the scene.
Returns
true if the recognition had been successful or false if errors have occurred.
Definition at line 333 of file hough_3d.hpp.
recognize() [2/2]
template<typename PointModelT , typename PointSceneT , typename PointModelRfT , typename PointSceneRfT > bool pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::recognize (std::vector< Eigen::Matrix4f, Eigen::aligned_allocator< Eigen::Matrix4f > > & transformations, std::vector< pcl::Correspondences > & clustered_corrs)
The main function, recognizes instances of the model into the scene set by the user.
Parameters
[out] transformations a vector containing one transformation matrix for each instance of the model recognized into the scene.
[out] clustered_corrs a vector containing the correspondences for each instance of the model found within the input data (the same output of clusterCorrespondences).
Returns
true if the recognition had been successful or false if errors have occurred.
Definition at line 342 of file hough_3d.hpp.
setHoughBinSize()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> void pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setHoughBinSize (double bin_size) inline
Sets the size of each bin into the Hough space.
Parameters
[in] bin_size the size of each Hough space's bin.
Definition at line 296 of file hough_3d.h.
References pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::hough_bin_size_, and pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::hough_space_initialized_.
setHoughThreshold()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> void pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setHoughThreshold (double threshold) inline
Sets the minimum number of votes in the Hough space needed to infer the presence of a model instance into the scene cloud.
Parameters
[in] threshold the threshold for the Hough space voting, if set between -1 and 0 the maximum vote in the entire space is automatically calculated and -threshold the maximum value is used as a threshold. This means that a value between -1 and 0 should be used only if at least one instance of the model is always present in the scene, or if this false positive can be filtered later.
Definition at line 276 of file hough_3d.h.
References pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::hough_threshold_.
setInputCloud()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> void pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setInputCloud (const PointCloudConstPtr & cloud) inline override virtual
Provide a pointer to the input dataset.
Parameters
[in] cloud the const boost shared pointer to a PointCloud message.
Reimplemented from pcl::PCLBase< PointModelT >.
Definition at line 184 of file hough_3d.h.
References pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::hough_space_initialized_, pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::input_rf_, pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::needs_training_, and pcl::PCLBase< PointT >::setInputCloud().
setInputRf()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> void pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setInputRf (const ModelRfCloudConstPtr & input_rf) inline
Provide a pointer to the input dataset's reference frames.
Each point in the reference frame cloud should be the reference frame of the correspondent point in the input dataset.
Parameters
[in] input_rf the pointer to the input cloud's reference frames.
Definition at line 199 of file hough_3d.h.
References pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::hough_space_initialized_, pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::input_rf_, and pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::needs_training_.
setLocalRfNormalsSearchRadius()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> void pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setLocalRfNormalsSearchRadius (float local_rf_normals_search_radius) inline
If the Local reference frame has not been set for either the model cloud or the scene cloud, this algorithm makes the computation itself but needs a suitable search radius to compute the normals in order to subsequently compute the RF (if not set a default 15 nearest neighbors search is performed).
Parameters
[in] local_rf_normals_search_radius the normals search radius for the local reference frame calculation.
Definition at line 363 of file hough_3d.h.
References pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::hough_space_initialized_, pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::local_rf_normals_search_radius_, and pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::needs_training_.
setLocalRfSearchRadius()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> void pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setLocalRfSearchRadius (float local_rf_search_radius) inline
If the Local reference frame has not been set for either the model cloud or the scene cloud, this algorithm makes the computation itself but needs a suitable search radius to do so.
Attention
This parameter NEEDS to be set if the reference frames are not precomputed externally, otherwise the recognition results won't be correct.
Parameters
[in] local_rf_search_radius the search radius for the local reference frame calculation.
Definition at line 390 of file hough_3d.h.
References pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::hough_space_initialized_, pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::local_rf_search_radius_, and pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::needs_training_.
setModelSceneCorrespondences()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> void pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setModelSceneCorrespondences (const CorrespondencesConstPtr & corrs) inline override virtual
Provide a pointer to the precomputed correspondences between points in the input dataset and points in the scene dataset.
The correspondences are going to be clustered into different model instances by the algorithm.
Parameters
[in] corrs the correspondences between the model and the scene.
Reimplemented from pcl::CorrespondenceGrouping< PointModelT, PointSceneT >.
Definition at line 262 of file hough_3d.h.
References pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::hough_space_initialized_, and pcl::CorrespondenceGrouping< PointModelT, PointSceneT >::model_scene_corrs_.
setSceneCloud()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> void pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setSceneCloud (const SceneCloudConstPtr & scene) inline override virtual
Provide a pointer to the scene dataset (i.e.
the cloud in which the algorithm has to search for instances of the input model)
Parameters
[in] scene the const boost shared pointer to a PointCloud message.
Reimplemented from pcl::CorrespondenceGrouping< PointModelT, PointSceneT >.
Definition at line 223 of file hough_3d.h.
References pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::hough_space_initialized_, pcl::CorrespondenceGrouping< PointModelT, PointSceneT >::scene_, and pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::scene_rf_.
setSceneRf()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> void pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setSceneRf (const SceneRfCloudConstPtr & scene_rf) inline
Provide a pointer to the scene dataset's reference frames.
Each point in the reference frame cloud should be the reference frame of the correspondent point in the scene dataset.
Parameters
[in] scene_rf the pointer to the scene cloud's reference frames.
Definition at line 237 of file hough_3d.h.
References pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::hough_space_initialized_, and pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::scene_rf_.
setUseDistanceWeight()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> void pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setUseDistanceWeight (bool use_distance_weight) inline
Sets whether the vote casting procedure uses the correspondence's distance as a score.
Parameters
[in] use_distance_weight the algorithm should use the weighted distance when calculating the Hough voting score.
Definition at line 340 of file hough_3d.h.
References pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::hough_space_initialized_, and pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::use_distance_weight_.
setUseInterpolation()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> void pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setUseInterpolation (bool use_interpolation) inline
Sets whether the vote casting procedure interpolates the score between neighboring bins of the Hough space or not.
Parameters
[in] use_interpolation the algorithm should interpolate the vote score between neighboring bins.
Definition at line 318 of file hough_3d.h.
References pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::hough_space_initialized_, and pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::use_interpolation_.
train()
template<typename PointModelT , typename PointSceneT , typename PointModelRfT , typename PointSceneRfT > bool pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::train
Call this function after setting the input, the input_rf and the hough_bin_size parameters to perform an off line training of the algorithm.
This might be useful if one wants to perform once and for all a pre-computation of votes that only concern the models, increasing the on-line efficiency of the grouping algorithm. The algorithm is automatically trained on the first invocation of the recognize method or the cluster method if this training function has not been manually invoked.
Returns
true if the training had been successful or false if errors have occurred.
Definition at line 84 of file hough_3d.hpp.
Member Data Documentation
found_transformations_
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> std::vector<Eigen::Matrix4f, Eigen::aligned_allocator<Eigen::Matrix4f> > pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::found_transformations_ protected
Transformations found by clusterCorrespondences method.
Definition at line 476 of file hough_3d.h.
hough_bin_size_
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> double pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::hough_bin_size_ protected
The size of each bin of the hough space.
Definition at line 458 of file hough_3d.h.
Referenced by pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::getHoughBinSize(), and pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setHoughBinSize().
hough_space_
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> pcl::recognition::HoughSpace3D::Ptr pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::hough_space_ protected
The Hough space.
Definition at line 473 of file hough_3d.h.
hough_space_initialized_
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> bool pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::hough_space_initialized_ protected
Whether the Hough space already contains the correct votes for the current input parameters and so the cluster and recognize calls don't need to recompute each value.
Reset on the change of any parameter except the hough_threshold.
Definition at line 481 of file hough_3d.h.
Referenced by pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setHoughBinSize(), pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setInputCloud(), pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setInputRf(), pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setLocalRfNormalsSearchRadius(), pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setLocalRfSearchRadius(), pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setModelSceneCorrespondences(), pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setSceneCloud(), pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setSceneRf(), pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setUseDistanceWeight(), and pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setUseInterpolation().
hough_threshold_
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> double pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::hough_threshold_ protected
The minimum number of votes in the Hough space needed to infer the presence of a model instance into the scene cloud.
Definition at line 455 of file hough_3d.h.
Referenced by pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::getHoughThreshold(), and pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setHoughThreshold().
input_rf_
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> ModelRfCloudConstPtr pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::input_rf_ protected
The input Rf cloud.
Definition at line 443 of file hough_3d.h.
Referenced by pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::getInputRf(), pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setInputCloud(), and pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setInputRf().
local_rf_normals_search_radius_
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> float pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::local_rf_normals_search_radius_ protected
Normals search radius for the potential Rf calculation.
Definition at line 467 of file hough_3d.h.
Referenced by pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::getLocalRfNormalsSearchRadius(), and pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setLocalRfNormalsSearchRadius().
local_rf_search_radius_
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> float pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::local_rf_search_radius_ protected
Search radius for the potential Rf calculation.
Definition at line 470 of file hough_3d.h.
Referenced by pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::getLocalRfSearchRadius(), and pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setLocalRfSearchRadius().
model_votes_
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> std::vector<Eigen::Vector3f, Eigen::aligned_allocator<Eigen::Vector3f> > pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::model_votes_ protected
The result of the training.
The vector between each model point and the centroid of the model adjusted by its local reference frame.
Definition at line 452 of file hough_3d.h.
needs_training_
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> bool pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::needs_training_ protected
If the training of the Hough space is needed; set on change of either the input cloud or the input_rf.
Definition at line 449 of file hough_3d.h.
Referenced by pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setInputCloud(), pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setInputRf(), pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setLocalRfNormalsSearchRadius(), and pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setLocalRfSearchRadius().
scene_rf_
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> SceneRfCloudConstPtr pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::scene_rf_ protected
The scene Rf cloud.
Definition at line 446 of file hough_3d.h.
Referenced by pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::getSceneRf(), pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setSceneCloud(), and pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setSceneRf().
use_distance_weight_
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> bool pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::use_distance_weight_ protected
Use the weighted correspondence distance when casting votes.
Definition at line 464 of file hough_3d.h.
Referenced by pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::getUseDistanceWeight(), and pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setUseDistanceWeight().
use_interpolation_
template<typename PointModelT , typename PointSceneT , typename PointModelRfT = pcl::ReferenceFrame, typename PointSceneRfT = pcl::ReferenceFrame> bool pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::use_interpolation_ protected
Use the interpolation between neighboring Hough bins when casting votes.
Definition at line 461 of file hough_3d.h.
Referenced by pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::getUseInterpolation(), and pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::setUseInterpolation().
The documentation for this class was generated from the following files:
pcl/recognition/cg/hough_3d.h
pcl/recognition/impl/cg/hough_3d.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Jun 2 2020 14:12:05