Point Cloud Library (PCL): NCVVectorAlloc< T > Class Template Reference
NCVVectorAlloc< T > Class Template Reference
NCVVectorAlloc.
#include </__w/1/s/gpu/people/src/cuda/nvidia/NCV.hpp>
Public Member Functions
NCVVectorAlloc (INCVMemAllocator &allocator, Ncv32u length)
~NCVVectorAlloc ()
NcvBool isMemAllocated () const
Ncv32u getAllocatorsAlignment () const
NCVMemSegment getSegment () const
Public Member Functions inherited from NCVVector< T >
NCVVector ()
void clear ()
NCVStatus copySolid (NCVVector< T > &dst, cudaStream_t cuStream, std::size_t howMuch=0) const
T * ptr () const
std::size_t length () const
NCVMemoryType memType () const
Additional Inherited Members
Protected Attributes inherited from NCVVector< T >
T * _ptr
std::size_t _length
NCVMemoryType _memtype
Detailed Description
template<class T>
class NCVVectorAlloc< T >
NCVVectorAlloc.
Definition at line 565 of file NCV.hpp.
Constructor & Destructor Documentation
NCVVectorAlloc()
template<class T > NCVVectorAlloc< T >::NCVVectorAlloc (INCVMemAllocator & allocator, Ncv32u length) inline
Definition at line 573 of file NCV.hpp.
References NCVVector< T >::_ptr, INCVMemAllocator::alloc(), NCVMemSegment::begin, NCVMemSegment::clear(), NCVVector< T >::clear(), NCVVector< T >::length(), and NCVMemPtr::ptr.
~NCVVectorAlloc()
template<class T > NCVVectorAlloc< T >::~NCVVectorAlloc () inline
Definition at line 590 of file NCV.hpp.
References NCVVector< T >::clear(), and INCVMemAllocator::dealloc().
Member Function Documentation
getAllocatorsAlignment()
template<class T > Ncv32u NCVVectorAlloc< T >::getAllocatorsAlignment () const inline
Definition at line 605 of file NCV.hpp.
References INCVMemAllocator::alignment().
getSegment()
template<class T > NCVMemSegment NCVVectorAlloc< T >::getSegment () const inline
Definition at line 610 of file NCV.hpp.
isMemAllocated()
template<class T > NcvBool NCVVectorAlloc< T >::isMemAllocated () const inline
Definition at line 600 of file NCV.hpp.
References NCVMemSegment::begin, INCVMemAllocator::isCounting(), and NCVMemPtr::ptr.
The documentation for this class was generated from the following file:
/__w/1/s/gpu/people/src/cuda/nvidia/NCV.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:06