Point Cloud Library (PCL): pcl::IntegralImage2D< DataType, Dimension > Class Template Reference
pcl::IntegralImage2D< DataType, Dimension > Class Template Reference
Determines an integral image representation for a given organized data array.
#include <pcl/features/integral_image2D.h>
Public Types
using Ptr = shared_ptr< IntegralImage2D< DataType, Dimension > >
using ConstPtr = shared_ptr< const IntegralImage2D< DataType, Dimension > >
using ElementType = Eigen::Matrix< typename IntegralImageTypeTraits< DataType >::IntegralType, Dimension, 1 >
using SecondOrderType = Eigen::Matrix< typename IntegralImageTypeTraits< DataType >::IntegralType, second_order_size, 1 >
Public Member Functions
IntegralImage2D (bool compute_second_order_integral_images)
Constructor for an Integral Image.
virtual ~IntegralImage2D ()
Destructor.
void setSecondOrderComputation (bool compute_second_order_integral_images)
sets the computation for second order integral images on or off.
void setInput (const DataType *data, unsigned width, unsigned height, unsigned element_stride, unsigned row_stride)
Set the input data to compute the integral image for.
ElementType getFirstOrderSum (unsigned start_x, unsigned start_y, unsigned width, unsigned height) const
Compute the first order sum within a given rectangle.
ElementType getFirstOrderSumSE (unsigned start_x, unsigned start_y, unsigned end_x, unsigned end_y) const
Compute the first order sum within a given rectangle.
SecondOrderType getSecondOrderSum (unsigned start_x, unsigned start_y, unsigned width, unsigned height) const
Compute the second order sum within a given rectangle.
SecondOrderType getSecondOrderSumSE (unsigned start_x, unsigned start_y, unsigned end_x, unsigned end_y) const
Compute the second order sum within a given rectangle.
unsigned getFiniteElementsCount (unsigned start_x, unsigned start_y, unsigned width, unsigned height) const
Compute the number of finite elements within a given rectangle.
unsigned getFiniteElementsCountSE (unsigned start_x, unsigned start_y, unsigned end_x, unsigned end_y) const
Compute the number of finite elements within a given rectangle.
Static Public Attributes
static const unsigned second_order_size = (Dimension * (Dimension + 1)) >> 1
Detailed Description
template<class DataType, unsigned Dimension>
class pcl::IntegralImage2D< DataType, Dimension >
Determines an integral image representation for a given organized data array.
Author
Suat Gedikli
Definition at line 109 of file integral_image2D.h.
Member Typedef Documentation
ConstPtr
template<class DataType , unsigned Dimension> using pcl::IntegralImage2D< DataType, Dimension >::ConstPtr = shared_ptr<const IntegralImage2D<DataType, Dimension> >
Definition at line 113 of file integral_image2D.h.
ElementType
template<class DataType , unsigned Dimension> using pcl::IntegralImage2D< DataType, Dimension >::ElementType = Eigen::Matrix<typename IntegralImageTypeTraits<DataType>::IntegralType, Dimension, 1>
Definition at line 115 of file integral_image2D.h.
Ptr
template<class DataType , unsigned Dimension> using pcl::IntegralImage2D< DataType, Dimension >::Ptr = shared_ptr<IntegralImage2D<DataType, Dimension> >
Definition at line 112 of file integral_image2D.h.
SecondOrderType
template<class DataType , unsigned Dimension> using pcl::IntegralImage2D< DataType, Dimension >::SecondOrderType = Eigen::Matrix<typename IntegralImageTypeTraits<DataType>::IntegralType, second_order_size, 1>
Definition at line 116 of file integral_image2D.h.
Constructor & Destructor Documentation
IntegralImage2D()
template<class DataType , unsigned Dimension> pcl::IntegralImage2D< DataType, Dimension >::IntegralImage2D (bool compute_second_order_integral_images) inline
Constructor for an Integral Image.
Parameters
[in] compute_second_order_integral_images set to true if we want to compute a second order image
Definition at line 121 of file integral_image2D.h.
~IntegralImage2D()
template<class DataType , unsigned Dimension> virtual pcl::IntegralImage2D< DataType, Dimension >::~IntegralImage2D () inline virtual
Destructor.
Definition at line 132 of file integral_image2D.h.
Member Function Documentation
getFiniteElementsCount()
template<typename DataType , unsigned Dimension> unsigned pcl::IntegralImage2D< DataType, Dimension >::getFiniteElementsCount (unsigned start_x, unsigned start_y, unsigned width, unsigned height) const inline
Compute the number of finite elements within a given rectangle.
Parameters
[in] start_x x position of rectangle
[in] start_y y position of rectangle
[in] width width of rectangle
[in] height height of rectangle
Definition at line 102 of file integral_image2D.hpp.
getFiniteElementsCountSE()
template<typename DataType , unsigned Dimension> unsigned pcl::IntegralImage2D< DataType, Dimension >::getFiniteElementsCountSE (unsigned start_x, unsigned start_y, unsigned end_x, unsigned end_y) const inline
Compute the number of finite elements within a given rectangle.
Parameters
[in] start_x x position of the start of the rectangle
[in] start_y x position of the start of the rectangle
[in] end_x x position of the end of the rectangle
[in] end_y x position of the end of the rectangle
Definition at line 144 of file integral_image2D.hpp.
getFirstOrderSum()
template<typename DataType , unsigned Dimension> pcl::IntegralImage2D< DataType, Dimension >::ElementType pcl::IntegralImage2D< DataType, Dimension >::getFirstOrderSum (unsigned start_x, unsigned start_y, unsigned width, unsigned height) const inline
Compute the first order sum within a given rectangle.
Parameters
[in] start_x x position of rectangle
[in] start_y y position of rectangle
[in] width width of rectangle
[in] height height of rectangle
Definition at line 74 of file integral_image2D.hpp.
Referenced by pcl::IntegralImageNormalEstimation< pcl::PointXYZRGBA, pcl::Normal >::computePointNormal().
getFirstOrderSumSE()
template<typename DataType , unsigned Dimension> pcl::IntegralImage2D< DataType, Dimension >::ElementType pcl::IntegralImage2D< DataType, Dimension >::getFirstOrderSumSE (unsigned start_x, unsigned start_y, unsigned end_x, unsigned end_y) const inline
Compute the first order sum within a given rectangle.
Parameters
[in] start_x x position of the start of the rectangle
[in] start_y x position of the start of the rectangle
[in] end_x x position of the end of the rectangle
[in] end_y x position of the end of the rectangle
Definition at line 116 of file integral_image2D.hpp.
Referenced by pcl::IntegralImageNormalEstimation< pcl::PointXYZRGBA, pcl::Normal >::computePointNormalMirror().
getSecondOrderSum()
template<typename DataType , unsigned Dimension> pcl::IntegralImage2D< DataType, Dimension >::SecondOrderType pcl::IntegralImage2D< DataType, Dimension >::getSecondOrderSum (unsigned start_x, unsigned start_y, unsigned width, unsigned height) const inline
Compute the second order sum within a given rectangle.
Parameters
[in] start_x x position of rectangle
[in] start_y y position of rectangle
[in] width width of rectangle
[in] height height of rectangle
Definition at line 88 of file integral_image2D.hpp.
Referenced by pcl::IntegralImageNormalEstimation< pcl::PointXYZRGBA, pcl::Normal >::computePointNormal().
getSecondOrderSumSE()
template<typename DataType , unsigned Dimension> pcl::IntegralImage2D< DataType, Dimension >::SecondOrderType pcl::IntegralImage2D< DataType, Dimension >::getSecondOrderSumSE (unsigned start_x, unsigned start_y, unsigned end_x, unsigned end_y) const inline
Compute the second order sum within a given rectangle.
Parameters
[in] start_x x position of the start of the rectangle
[in] start_y x position of the start of the rectangle
[in] end_x x position of the end of the rectangle
[in] end_y x position of the end of the rectangle
Definition at line 130 of file integral_image2D.hpp.
setInput()
template<typename DataType , unsigned Dimension> void pcl::IntegralImage2D< DataType, Dimension >::setInput (const DataType * data, unsigned width, unsigned height, unsigned element_stride, unsigned row_stride)
Set the input data to compute the integral image for.
Parameters
[in] data the input data
[in] width the width of the data
[in] height the height of the data
[in] element_stride the element stride of the data
[in] row_stride the row stride of the data
Definition at line 58 of file integral_image2D.hpp.
setSecondOrderComputation()
template<typename DataType , unsigned Dimension> void pcl::IntegralImage2D< DataType, Dimension >::setSecondOrderComputation (bool compute_second_order_integral_images)
sets the computation for second order integral images on or off.
Parameters
compute_second_order_integral_images
Definition at line 51 of file integral_image2D.hpp.
Member Data Documentation
second_order_size
template<class DataType , unsigned Dimension> const unsigned pcl::IntegralImage2D< DataType, Dimension >::second_order_size = (Dimension * (Dimension + 1)) >> 1 static
Definition at line 114 of file integral_image2D.h.
The documentation for this class was generated from the following files:
pcl/features/integral_image2D.h
pcl/features/impl/integral_image2D.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Jun 2 2020 14:12:06