Point Cloud Library (PCL): pcl::SampleConsensusModelCylinder< PointT, PointNT > Class Template Reference
pcl::SampleConsensusModelCylinder< PointT, PointNT > Class Template Reference
Module sample_consensus
SampleConsensusModelCylinder defines a model for 3D cylinder segmentation.
#include <pcl/sample_consensus/sac_model_cylinder.h>
Public Types
using PointCloud = typename SampleConsensusModel< PointT >::PointCloud
using PointCloudPtr = typename SampleConsensusModel< PointT >::PointCloudPtr
using PointCloudConstPtr = typename SampleConsensusModel< PointT >::PointCloudConstPtr
using Ptr = shared_ptr< SampleConsensusModelCylinder< PointT, PointNT > >
using ConstPtr = shared_ptr< const SampleConsensusModelCylinder< PointT, PointNT > >
Public Types inherited from pcl::SampleConsensusModel< PointT >
using PointCloud = pcl::PointCloud< PointT >
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointCloudPtr = typename PointCloud::Ptr
using SearchPtr = typename pcl::search::Search< PointT >::Ptr
using Ptr = shared_ptr< SampleConsensusModel< PointT > >
using ConstPtr = shared_ptr< const SampleConsensusModel< PointT > >
Public Types inherited from pcl::SampleConsensusModelFromNormals< PointT, PointNT >
using PointCloudNConstPtr = typename pcl::PointCloud< PointNT >::ConstPtr
using PointCloudNPtr = typename pcl::PointCloud< PointNT >::Ptr
using Ptr = shared_ptr< SampleConsensusModelFromNormals< PointT, PointNT > >
using ConstPtr = shared_ptr< const SampleConsensusModelFromNormals< PointT, PointNT > >
Public Member Functions
SampleConsensusModelCylinder (const PointCloudConstPtr &cloud, bool random=false)
Constructor for base SampleConsensusModelCylinder.
SampleConsensusModelCylinder (const PointCloudConstPtr &cloud, const Indices &indices, bool random=false)
Constructor for base SampleConsensusModelCylinder.
SampleConsensusModelCylinder (const SampleConsensusModelCylinder &source)
Copy constructor.
~SampleConsensusModelCylinder () override=default
Empty destructor.
SampleConsensusModelCylinder & operator= (const SampleConsensusModelCylinder &source)
Copy constructor.
void setEpsAngle (const double ea)
Set the angle epsilon (delta) threshold.
double getEpsAngle () const
Get the angle epsilon (delta) threshold.
void setAxis (const Eigen::Vector3f &ax)
Set the axis along which we need to search for a cylinder direction.
Eigen::Vector3f getAxis () const
Get the axis along which we need to search for a cylinder direction.
bool computeModelCoefficients (const Indices &samples, Eigen::VectorXf &model_coefficients) const override
Check whether the given index samples can form a valid cylinder model, compute the model coefficients from these samples and store them in model_coefficients.
void getDistancesToModel (const Eigen::VectorXf &model_coefficients, std::vector< double > &distances) const override
Compute all distances from the cloud data to a given cylinder model.
void selectWithinDistance (const Eigen::VectorXf &model_coefficients, const double threshold, Indices &inliers) override
Select all the points which respect the given model coefficients as inliers.
std::size_t countWithinDistance (const Eigen::VectorXf &model_coefficients, const double threshold) const override
Count all the points which respect the given model coefficients as inliers.
void optimizeModelCoefficients (const Indices &inliers, const Eigen::VectorXf &model_coefficients, Eigen::VectorXf &optimized_coefficients) const override
Recompute the cylinder coefficients using the given inlier set and return them to the user.
void projectPoints (const Indices &inliers, const Eigen::VectorXf &model_coefficients, PointCloud &projected_points, bool copy_data_fields=true) const override
Create a new point cloud with inliers projected onto the cylinder model.
bool doSamplesVerifyModel (const std::set< index_t > &indices, const Eigen::VectorXf &model_coefficients, const double threshold) const override
Verify whether a subset of indices verifies the given cylinder model coefficients.
pcl::SacModel getModelType () const override
Return a unique id for this model (SACMODEL_CYLINDER).
Public Member Functions inherited from pcl::SampleConsensusModel< PointT >
SampleConsensusModel (const PointCloudConstPtr &cloud, bool random=false)
Constructor for base SampleConsensusModel.
SampleConsensusModel (const PointCloudConstPtr &cloud, const Indices &indices, bool random=false)
Constructor for base SampleConsensusModel.
virtual ~SampleConsensusModel ()=default
Destructor for base SampleConsensusModel.
virtual void getSamples (int &iterations, Indices &samples)
Get a set of random data samples and return them as point indices.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr getInputCloud () const
Get a pointer to the input point cloud dataset.
void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
void setIndices (const Indices &indices)
Provide the vector of indices that represents the input data.
IndicesPtr getIndices () const
Get a pointer to the vector of indices used.
const std::string & getClassName () const
Get a string representation of the name of this class.
unsigned int getSampleSize () const
Return the size of a sample from which the model is computed.
unsigned int getModelSize () const
Return the number of coefficients in the model.
void setRadiusLimits (const double &min_radius, const double &max_radius)
Set the minimum and maximum allowable radius limits for the model (applicable to models that estimate a radius)
void getRadiusLimits (double &min_radius, double &max_radius) const
Get the minimum and maximum allowable radius limits for the model as set by the user.
void setModelConstraints (std::function< bool(const Eigen::VectorXf &)> function)
This can be used to impose any kind of constraint on the model, e.g.
void setSamplesMaxDist (const double &radius, SearchPtr search)
Set the maximum distance allowed when drawing random samples.
void getSamplesMaxDist (double &radius) const
Get maximum distance allowed when drawing random samples.
double computeVariance (const std::vector< double > &error_sqr_dists) const
Compute the variance of the errors to the model.
double computeVariance () const
Compute the variance of the errors to the model from the internally estimated vector of distances.
Public Member Functions inherited from pcl::SampleConsensusModelFromNormals< PointT, PointNT >
SampleConsensusModelFromNormals ()
Empty constructor for base SampleConsensusModelFromNormals.
virtual ~SampleConsensusModelFromNormals ()=default
Destructor.
void setNormalDistanceWeight (const double w)
Set the normal angular distance weight.
double getNormalDistanceWeight () const
Get the normal angular distance weight.
void setInputNormals (const PointCloudNConstPtr &normals)
Provide a pointer to the input dataset that contains the point normals of the XYZ dataset.
PointCloudNConstPtr getInputNormals () const
Get a pointer to the normals of the input XYZ point cloud dataset.
Protected Member Functions
double pointToLineDistance (const Eigen::Vector4f &pt, const Eigen::VectorXf &model_coefficients) const
Get the distance from a point to a line (represented by a point and a direction)
void projectPointToLine (const Eigen::Vector4f &pt, const Eigen::Vector4f &line_pt, const Eigen::Vector4f &line_dir, Eigen::Vector4f &pt_proj) const
Project a point onto a line given by a point and a direction vector.
void projectPointToCylinder (const Eigen::Vector4f &pt, const Eigen::VectorXf &model_coefficients, Eigen::Vector4f &pt_proj) const
Project a point onto a cylinder given by its model coefficients (point_on_axis, axis_direction, cylinder_radius_R)
bool isModelValid (const Eigen::VectorXf &model_coefficients) const override
Check whether a model is valid given the user constraints.
bool isSampleGood (const Indices &samples) const override
Check if a sample of indices results in a good sample of points indices.
Protected Member Functions inherited from pcl::SampleConsensusModel< PointT >
SampleConsensusModel (bool random=false)
Empty constructor for base SampleConsensusModel.
void drawIndexSample (Indices &sample)
Fills a sample array with random samples from the indices_ vector.
void drawIndexSampleRadius (Indices &sample)
Fills a sample array with one random sample from the indices_ vector and other random samples that are closer than samples_radius_.
int rnd ()
Boost-based random number generator.
Additional Inherited Members
Protected Attributes inherited from pcl::SampleConsensusModel< PointT >
std::string model_name_
The model name.
PointCloudConstPtr input_
A boost shared pointer to the point cloud data array.
IndicesPtr indices_
A pointer to the vector of point indices to use.
double radius_min_
The minimum and maximum radius limits for the model.
double radius_max_
double samples_radius_
The maximum distance of subsequent samples from the first (radius search)
SearchPtr samples_radius_search_
The search object for picking subsequent samples using radius search.
Indices shuffled_indices_
Data containing a shuffled version of the indices.
boost::mt19937 rng_alg_
Boost-based random number generator algorithm.
std::shared_ptr< boost::uniform_int<> > rng_dist_
Boost-based random number generator distribution.
std::shared_ptr< boost::variate_generator< boost::mt19937 &, boost::uniform_int<> > > rng_gen_
Boost-based random number generator.
std::vector< double > error_sqr_dists_
A vector holding the distances to the computed model.
unsigned int sample_size_
The size of a sample from which the model is computed.
unsigned int model_size_
The number of coefficients in the model.
std::function< bool(const Eigen::VectorXf &)> custom_model_constraints_
A user defined function that takes model coefficients and returns whether the model is acceptable or not.
Protected Attributes inherited from pcl::SampleConsensusModelFromNormals< PointT, PointNT >
double normal_distance_weight_ {0.0}
The relative weight (between 0 and 1) to give to the angular distance (0 to pi/2) between point normals and the plane normal.
PointCloudNConstPtr normals_
A pointer to the input dataset that contains the point normals of the XYZ dataset.
Static Protected Attributes inherited from pcl::SampleConsensusModel< PointT >
static const unsigned int max_sample_checks_ = 1000
The maximum number of samples to try until we get a good one.
Detailed Description
template<typename PointT, typename PointNT>
class pcl::SampleConsensusModelCylinder< PointT, PointNT >
SampleConsensusModelCylinder defines a model for 3D cylinder segmentation.
The model coefficients are defined as:
point_on_axis.x : the X coordinate of a point located on the cylinder axis
point_on_axis.y : the Y coordinate of a point located on the cylinder axis
point_on_axis.z : the Z coordinate of a point located on the cylinder axis
axis_direction.x : the X coordinate of the cylinder's axis direction
axis_direction.y : the Y coordinate of the cylinder's axis direction
axis_direction.z : the Z coordinate of the cylinder's axis direction
radius : the cylinder's radius
Author
Radu Bogdan Rusu
Definition at line 68 of file sac_model_cylinder.h.
Member Typedef Documentation
ConstPtr
template<typename PointT , typename PointNT > using pcl::SampleConsensusModelCylinder< PointT, PointNT >::ConstPtr = shared_ptr<const SampleConsensusModelCylinder<PointT, PointNT> >
Definition at line 85 of file sac_model_cylinder.h.
PointCloud
template<typename PointT , typename PointNT > using pcl::SampleConsensusModelCylinder< PointT, PointNT >::PointCloud = typename SampleConsensusModel<PointT>::PointCloud
Definition at line 80 of file sac_model_cylinder.h.
PointCloudConstPtr
template<typename PointT , typename PointNT > using pcl::SampleConsensusModelCylinder< PointT, PointNT >::PointCloudConstPtr = typename SampleConsensusModel<PointT>::PointCloudConstPtr
Definition at line 82 of file sac_model_cylinder.h.
PointCloudPtr
template<typename PointT , typename PointNT > using pcl::SampleConsensusModelCylinder< PointT, PointNT >::PointCloudPtr = typename SampleConsensusModel<PointT>::PointCloudPtr
Definition at line 81 of file sac_model_cylinder.h.
Ptr
template<typename PointT , typename PointNT > using pcl::SampleConsensusModelCylinder< PointT, PointNT >::Ptr = shared_ptr<SampleConsensusModelCylinder<PointT, PointNT> >
Definition at line 84 of file sac_model_cylinder.h.
Constructor & Destructor Documentation
SampleConsensusModelCylinder() [1/3]
template<typename PointT , typename PointNT > pcl::SampleConsensusModelCylinder< PointT, PointNT >::SampleConsensusModelCylinder (const PointCloudConstPtr & cloud, bool random = false) inline
Constructor for base SampleConsensusModelCylinder.
Parameters
[in] cloud the input point cloud dataset
[in] random if true set the random seed to the current time, else set to 12345 (default: false)
Definition at line 91 of file sac_model_cylinder.h.
References pcl::SampleConsensusModel< PointT >::model_name_, pcl::SampleConsensusModel< PointT >::model_size_, and pcl::SampleConsensusModel< PointT >::sample_size_.
SampleConsensusModelCylinder() [2/3]
template<typename PointT , typename PointNT > pcl::SampleConsensusModelCylinder< PointT, PointNT >::SampleConsensusModelCylinder (const PointCloudConstPtr & cloud, const Indices & indices, bool random = false) inline
Constructor for base SampleConsensusModelCylinder.
Parameters
[in] cloud the input point cloud dataset
[in] indices a vector of point indices to be used from cloud
[in] random if true set the random seed to the current time, else set to 12345 (default: false)
Definition at line 107 of file sac_model_cylinder.h.
References pcl::SampleConsensusModel< PointT >::model_name_, pcl::SampleConsensusModel< PointT >::model_size_, and pcl::SampleConsensusModel< PointT >::sample_size_.
SampleConsensusModelCylinder() [3/3]
template<typename PointT , typename PointNT > pcl::SampleConsensusModelCylinder< PointT, PointNT >::SampleConsensusModelCylinder (const SampleConsensusModelCylinder< PointT, PointNT > & source) inline
Copy constructor.
Parameters
[in] source the model to copy into this
Definition at line 123 of file sac_model_cylinder.h.
References pcl::SampleConsensusModel< PointT >::model_name_.
~SampleConsensusModelCylinder()
template<typename PointT , typename PointNT > pcl::SampleConsensusModelCylinder< PointT, PointNT >::~SampleConsensusModelCylinder () override default
Empty destructor.
Member Function Documentation
computeModelCoefficients()
template<typename PointT , typename PointNT > bool pcl::SampleConsensusModelCylinder< PointT, PointNT >::computeModelCoefficients (const Indices & samples, Eigen::VectorXf & model_coefficients) const override virtual
Check whether the given index samples can form a valid cylinder model, compute the model coefficients from these samples and store them in model_coefficients.
The cylinder coefficients are: point_on_axis, axis_direction, cylinder_radius_R
Parameters
[in] samples the point indices found as possible good candidates for creating a valid model
[out] model_coefficients the resultant model coefficients
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 75 of file sac_model_cylinder.hpp.
References pcl::sqrPointToLineDistance().
countWithinDistance()
template<typename PointT , typename PointNT > std::size_t pcl::SampleConsensusModelCylinder< PointT, PointNT >::countWithinDistance (const Eigen::VectorXf & model_coefficients, const double threshold) const override virtual
Count all the points which respect the given model coefficients as inliers.
Parameters
[in] model_coefficients the coefficients of a model that we need to compute distances to
[in] threshold maximum admissible distance threshold for determining the inliers from the outliers
Returns
the resultant number of inliers
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 240 of file sac_model_cylinder.hpp.
References pcl::getAngle3D(), and M_PI.
doSamplesVerifyModel()
template<typename PointT , typename PointNT > bool pcl::SampleConsensusModelCylinder< PointT, PointNT >::doSamplesVerifyModel (const std::set< index_t > & indices, const Eigen::VectorXf & model_coefficients, const double threshold) const override virtual
Verify whether a subset of indices verifies the given cylinder model coefficients.
Parameters
[in] indices the data indices that need to be tested against the cylinder model
[in] model_coefficients the cylinder model coefficients
[in] threshold a maximum admissible distance threshold for determining the inliers from the outliers
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 414 of file sac_model_cylinder.hpp.
getAxis()
template<typename PointT , typename PointNT > Eigen::Vector3f pcl::SampleConsensusModelCylinder< PointT, PointNT >::getAxis () const inline
Get the axis along which we need to search for a cylinder direction.
Definition at line 167 of file sac_model_cylinder.h.
Referenced by pcl::SACSegmentationFromNormals< PointT, PointNT >::initSACModel().
getDistancesToModel()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelCylinder< PointT, PointNT >::getDistancesToModel (const Eigen::VectorXf & model_coefficients, std::vector< double > & distances) const override virtual
Compute all distances from the cloud data to a given cylinder model.
Parameters
[in] model_coefficients the coefficients of a cylinder model that we need to compute distances to
[out] distances the resultant estimated distances
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 145 of file sac_model_cylinder.hpp.
References pcl::getAngle3D(), and M_PI.
getEpsAngle()
template<typename PointT , typename PointNT > double pcl::SampleConsensusModelCylinder< PointT, PointNT >::getEpsAngle () const inline
Get the angle epsilon (delta) threshold.
Definition at line 157 of file sac_model_cylinder.h.
Referenced by pcl::SACSegmentationFromNormals< PointT, PointNT >::initSACModel().
getModelType()
template<typename PointT , typename PointNT > pcl::SacModel pcl::SampleConsensusModelCylinder< PointT, PointNT >::getModelType () const inline override virtual
Return a unique id for this model (SACMODEL_CYLINDER).
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 243 of file sac_model_cylinder.h.
References pcl::SACMODEL_CYLINDER.
isModelValid()
template<typename PointT , typename PointNT > bool pcl::SampleConsensusModelCylinder< PointT, PointNT >::isModelValid (const Eigen::VectorXf & model_coefficients) const override protected virtual
Check whether a model is valid given the user constraints.
Parameters
[in] model_coefficients the set of model coefficients
Reimplemented from pcl::SampleConsensusModel< PointT >.
Definition at line 467 of file sac_model_cylinder.hpp.
References pcl::getAngle3D(), and M_PI.
isSampleGood()
template<typename PointT , typename PointNT > bool pcl::SampleConsensusModelCylinder< PointT, PointNT >::isSampleGood (const Indices & samples) const override protected virtual
Check if a sample of indices results in a good sample of points indices.
Pure virtual.
Parameters
[in] samples the resultant index samples
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 50 of file sac_model_cylinder.hpp.
operator=()
template<typename PointT , typename PointNT > SampleConsensusModelCylinder& pcl::SampleConsensusModelCylinder< PointT, PointNT >::operator= (const SampleConsensusModelCylinder< PointT, PointNT > & source) inline
Copy constructor.
Parameters
[in] source the model to copy into this
Definition at line 140 of file sac_model_cylinder.h.
optimizeModelCoefficients()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelCylinder< PointT, PointNT >::optimizeModelCoefficients (const Indices & inliers, const Eigen::VectorXf & model_coefficients, Eigen::VectorXf & optimized_coefficients) const override virtual
Recompute the cylinder coefficients using the given inlier set and return them to the user.
Note
: these are the coefficients of the cylinder model after refinement (e.g. after SVD)
Parameters
[in] inliers the data inliers found as supporting the model
[in] model_coefficients the initial guess for the optimization
[out] optimized_coefficients the resultant recomputed coefficients after non-linear optimization
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 282 of file sac_model_cylinder.hpp.
References pcl::internal::optimizeModelCoefficientsCylinder().
pointToLineDistance()
template<typename PointT , typename PointNT > double pcl::SampleConsensusModelCylinder< PointT, PointNT >::pointToLineDistance (const Eigen::Vector4f & pt, const Eigen::VectorXf & model_coefficients) const protected
Get the distance from a point to a line (represented by a point and a direction)
Parameters
[in] pt a point
[in] model_coefficients the line coefficients (a point on the line, line direction)
Definition at line 439 of file sac_model_cylinder.hpp.
References pcl::sqrPointToLineDistance().
projectPoints()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelCylinder< PointT, PointNT >::projectPoints (const Indices & inliers, const Eigen::VectorXf & model_coefficients, PointCloud & projected_points, bool copy_data_fields = true) const override virtual
Create a new point cloud with inliers projected onto the cylinder model.
Parameters
[in] inliers the data inliers that we want to project on the cylinder model
[in] model_coefficients the coefficients of a cylinder model
[out] projected_points the resultant projected points
[in] copy_data_fields set to true if we need to copy the other data fields
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 326 of file sac_model_cylinder.hpp.
References pcl::PointCloud< PointT >::header, pcl::PointCloud< PointT >::height, pcl::PointCloud< PointT >::is_dense, pcl::PointCloud< PointT >::resize(), pcl::PointCloud< PointT >::size(), and pcl::PointCloud< PointT >::width.
projectPointToCylinder()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelCylinder< PointT, PointNT >::projectPointToCylinder (const Eigen::Vector4f & pt, const Eigen::VectorXf & model_coefficients, Eigen::Vector4f & pt_proj) const protected
Project a point onto a cylinder given by its model coefficients (point_on_axis, axis_direction, cylinder_radius_R)
Parameters
[in] pt the input point to project
[in] model_coefficients the coefficients of the cylinder (point_on_axis, axis_direction, cylinder_radius_R)
[out] pt_proj the resultant projected point
Definition at line 449 of file sac_model_cylinder.hpp.
projectPointToLine()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelCylinder< PointT, PointNT >::projectPointToLine (const Eigen::Vector4f & pt, const Eigen::Vector4f & line_pt, const Eigen::Vector4f & line_dir, Eigen::Vector4f & pt_proj) const inline protected
Project a point onto a line given by a point and a direction vector.
Parameters
[in] pt the input point to project
[in] line_pt the point on the line (make sure that line_pt[3] = 0 as there are no internal checks!)
[in] line_dir the direction of the line (make sure that line_dir[3] = 0 as there are no internal checks!)
[out] pt_proj the resultant projected point
Definition at line 263 of file sac_model_cylinder.h.
selectWithinDistance()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelCylinder< PointT, PointNT >::selectWithinDistance (const Eigen::VectorXf & model_coefficients, const double threshold, Indices & inliers) override virtual
Select all the points which respect the given model coefficients as inliers.
Parameters
[in] model_coefficients the coefficients of a cylinder model that we need to compute distances to
[in] threshold a maximum admissible distance threshold for determining the inliers from the outliers
[out] inliers the resultant model inliers
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 188 of file sac_model_cylinder.hpp.
References pcl::geometry::distance(), pcl::getAngle3D(), and M_PI.
setAxis()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelCylinder< PointT, PointNT >::setAxis (const Eigen::Vector3f & ax) inline
Set the axis along which we need to search for a cylinder direction.
Parameters
[in] ax the axis along which we need to search for a cylinder direction
Definition at line 163 of file sac_model_cylinder.h.
Referenced by pcl::SACSegmentationFromNormals< PointT, PointNT >::initSACModel().
setEpsAngle()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelCylinder< PointT, PointNT >::setEpsAngle (const double ea) inline
Set the angle epsilon (delta) threshold.
Parameters
[in] ea the maximum allowed difference between the cylinder axis and the given axis.
Definition at line 153 of file sac_model_cylinder.h.
Referenced by pcl::SACSegmentationFromNormals< PointT, PointNT >::initSACModel().
The documentation for this class was generated from the following files:
pcl/sample_consensus/sac_model_cylinder.h
pcl/sample_consensus/impl/sac_model_cylinder.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:20