Point Cloud Library (PCL): pcl::PFHEstimation< PointInT, PointNT, PointOutT > Class Template Reference
pcl::PFHEstimation< PointInT, PointNT, PointOutT > Class Template Reference
Module features
PFHEstimation estimates the Point Feature Histogram (PFH) descriptor for a given point cloud dataset containing points and normals.
#include <pcl/features/pfh.h>
Public Types
using Ptr = shared_ptr< PFHEstimation< PointInT, PointNT, PointOutT > >
using ConstPtr = shared_ptr< const PFHEstimation< PointInT, PointNT, PointOutT > >
using PointCloudOut = typename Feature< PointInT, PointOutT >::PointCloudOut
using PointCloudIn = typename Feature< PointInT, PointOutT >::PointCloudIn
Public Types inherited from pcl::FeatureFromNormals< PointInT, PointNT, pcl::PFHSignature125 >
using PointCloudN = pcl::PointCloud< PointNT >
using PointCloudNPtr = typename PointCloudN::Ptr
using PointCloudNConstPtr = typename PointCloudN::ConstPtr
using Ptr = shared_ptr< FeatureFromNormals< PointInT, PointNT, pcl::PFHSignature125 > >
using ConstPtr = shared_ptr< const FeatureFromNormals< PointInT, PointNT, pcl::PFHSignature125 > >
Public Types inherited from pcl::Feature< PointInT, pcl::PFHSignature125 >
using BaseClass = PCLBase< PointInT >
using Ptr = shared_ptr< Feature< PointInT, pcl::PFHSignature125 > >
using ConstPtr = shared_ptr< const Feature< PointInT, pcl::PFHSignature125 > >
using KdTree = pcl::search::Search< PointInT >
using KdTreePtr = typename KdTree::Ptr
using PointCloudIn = pcl::PointCloud< PointInT >
using PointCloudInPtr = typename PointCloudIn::Ptr
using PointCloudInConstPtr = typename PointCloudIn::ConstPtr
using PointCloudOut = pcl::PointCloud< pcl::PFHSignature125 >
using SearchMethod = std::function< int(std::size_t, double, std::vector< int > &, std::vector< float > &)>
using SearchMethodSurface = std::function< int(const PointCloudIn &cloud, std::size_t index, double, std::vector< int > &, std::vector< float > &)>
Public Types inherited from pcl::PCLBase< PointInT >
using PointCloud = pcl::PointCloud< PointInT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
PFHEstimation ()
Empty constructor.
void setMaximumCacheSize (unsigned int cache_size)
Set the maximum internal cache size.
unsigned int getMaximumCacheSize ()
Get the maximum internal cache size.
void setUseInternalCache (bool use_cache)
Set whether to use an internal cache mechanism for removing redundant calculations or not.
bool getUseInternalCache ()
Get whether the internal cache is used or not for computing the PFH features.
bool computePairFeatures (const pcl::PointCloud< PointInT > &cloud, const pcl::PointCloud< PointNT > &normals, int p_idx, int q_idx, float &f1, float &f2, float &f3, float &f4)
Compute the 4-tuple representation containing the three angles and one distance between two points represented by Cartesian coordinates and normals.
void computePointPFHSignature (const pcl::PointCloud< PointInT > &cloud, const pcl::PointCloud< PointNT > &normals, const std::vector< int > &indices, int nr_split, Eigen::VectorXf &pfh_histogram)
Estimate the PFH (Point Feature Histograms) individual signatures of the three angular (f1, f2, f3) features for a given point based on its spatial neighborhood of 3D points with normals.
Public Member Functions inherited from pcl::FeatureFromNormals< PointInT, PointNT, pcl::PFHSignature125 >
FeatureFromNormals ()
Empty constructor.
virtual ~FeatureFromNormals ()
Empty destructor.
void setInputNormals (const PointCloudNConstPtr &normals)
Provide a pointer to the input dataset that contains the point normals of the XYZ dataset.
PointCloudNConstPtr getInputNormals () const
Get a pointer to the normals of the input XYZ point cloud dataset.
Public Member Functions inherited from pcl::Feature< PointInT, pcl::PFHSignature125 >
Feature ()
Empty constructor.
virtual ~Feature ()
Empty destructor.
void setSearchSurface (const PointCloudInConstPtr &cloud)
Provide a pointer to a dataset to add additional information to estimate the features for every point in the input dataset.
PointCloudInConstPtr getSearchSurface () const
Get a pointer to the surface point cloud dataset.
void setSearchMethod (const KdTreePtr &tree)
Provide a pointer to the search object.
KdTreePtr getSearchMethod () const
Get a pointer to the search method used.
double getSearchParameter () const
Get the internal search parameter.
void setKSearch (int k)
Set the number of k nearest neighbors to use for the feature estimation.
int getKSearch () const
get the number of k nearest neighbors used for the feature estimation.
void setRadiusSearch (double radius)
Set the sphere radius that is to be used for determining the nearest neighbors used for the feature estimation.
double getRadiusSearch () const
Get the sphere radius used for determining the neighbors.
void compute (PointCloudOut &output)
Base method for feature estimation for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Public Member Functions inherited from pcl::PCLBase< PointInT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
const PointCloudConstPtr getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
const IndicesConstPtr getIndices () const
Get a pointer to the vector of indices used.
const PointInT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
void computeFeature (PointCloudOut &output) override
Estimate the Point Feature Histograms (PFH) descriptors at a set of points given by <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Protected Member Functions inherited from pcl::FeatureFromNormals< PointInT, PointNT, pcl::PFHSignature125 >
virtual bool initCompute ()
This method should get called before starting the actual computation.
Protected Member Functions inherited from pcl::Feature< PointInT, pcl::PFHSignature125 >
const std::string & getClassName () const
Get a string representation of the name of this class.
virtual bool deinitCompute ()
This method should get called after ending the actual computation.
int searchForNeighbors (std::size_t index, double parameter, std::vector< int > &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
int searchForNeighbors (const PointCloudIn &cloud, std::size_t index, double parameter, std::vector< int > &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
Protected Member Functions inherited from pcl::PCLBase< PointInT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Protected Attributes
int nr_subdiv_
The number of subdivisions for each angular feature interval.
Eigen::VectorXf pfh_histogram_
Placeholder for a point's PFH signature.
Eigen::Vector4f pfh_tuple_
Placeholder for a PFH 4-tuple.
int f_index_ [3]
Placeholder for a histogram index.
float d_pi_
Float constant = 1.0 / (2.0 * M_PI)
std::map< std::pair< int, int >, Eigen::Vector4f, std::less<>, Eigen::aligned_allocator< std::pair< const std::pair< int, int >, Eigen::Vector4f > > > feature_map_
Internal hashmap, used to optimize efficiency of redundant computations.
std::queue< std::pair< int, int > > key_list_
Queue of pairs saved, used to constrain memory usage.
unsigned int max_cache_size_
Maximum size of internal cache memory.
bool use_cache_
Set to true to use the internal cache for removing redundant computations.
Protected Attributes inherited from pcl::FeatureFromNormals< PointInT, PointNT, pcl::PFHSignature125 >
PointCloudNConstPtr normals_
A pointer to the input dataset that contains the point normals of the XYZ dataset.
Protected Attributes inherited from pcl::Feature< PointInT, pcl::PFHSignature125 >
std::string feature_name_
The feature name.
SearchMethodSurface search_method_surface_
The search method template for points.
PointCloudInConstPtr surface_
An input point cloud describing the surface that is to be used for nearest neighbors estimation.
KdTreePtr tree_
A pointer to the spatial search object.
double search_parameter_
The actual search parameter (from either search_radius_ or k_).
double search_radius_
The nearest neighbors search radius for each point.
int k_
The number of K nearest neighbors to use for each point.
bool fake_surface_
If no surface is given, we use the input PointCloud as the surface.
Protected Attributes inherited from pcl::PCLBase< PointInT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointInT, typename PointNT, typename PointOutT = pcl::PFHSignature125>
class pcl::PFHEstimation< PointInT, PointNT, PointOutT >
PFHEstimation estimates the Point Feature Histogram (PFH) descriptor for a given point cloud dataset containing points and normals.
A commonly used type for PointOutT is pcl::PFHSignature125.
Note
If you use this code in any academic work, please cite:
R.B. Rusu, N. Blodow, Z.C. Marton, M. Beetz. Aligning Point Cloud Views using Persistent Feature Histograms. In Proceedings of the 21st IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS), Nice, France, September 22-26 2008.
R.B. Rusu, Z.C. Marton, N. Blodow, M. Beetz. Learning Informative Point Classes for the Acquisition of Object Model Maps. In Proceedings of the 10th International Conference on Control, Automation, Robotics and Vision (ICARCV), Hanoi, Vietnam, December 17-20 2008.
Attention
The convention for PFH features is:
if a query point's nearest neighbors cannot be estimated, the PFH feature will be set to NaN (not a number)
it is impossible to estimate a PFH descriptor for a point that doesn't have finite 3D coordinates. Therefore, any point that contains NaN data on x, y, or z, will have its PFH feature property set to NaN.
Note
The code is stateful as we do not expect this class to be multicore parallelized. Please look at FPFHEstimationOMP for examples on parallel implementations of the FPFH (Fast Point Feature Histogram).
Author
Radu B. Rusu
Definition at line 81 of file pfh.h.
Member Typedef Documentation
ConstPtr
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PFHSignature125> using pcl::PFHEstimation< PointInT, PointNT, PointOutT >::ConstPtr = shared_ptr<const PFHEstimation<PointInT, PointNT, PointOutT> >
Definition at line 85 of file pfh.h.
PointCloudIn
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PFHSignature125> using pcl::PFHEstimation< PointInT, PointNT, PointOutT >::PointCloudIn = typename Feature<PointInT, PointOutT>::PointCloudIn
Definition at line 96 of file pfh.h.
PointCloudOut
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PFHSignature125> using pcl::PFHEstimation< PointInT, PointNT, PointOutT >::PointCloudOut = typename Feature<PointInT, PointOutT>::PointCloudOut
Definition at line 95 of file pfh.h.
Ptr
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PFHSignature125> using pcl::PFHEstimation< PointInT, PointNT, PointOutT >::Ptr = shared_ptr<PFHEstimation<PointInT, PointNT, PointOutT> >
Definition at line 84 of file pfh.h.
Constructor & Destructor Documentation
PFHEstimation()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PFHSignature125> pcl::PFHEstimation< PointInT, PointNT, PointOutT >::PFHEstimation () inline
Empty constructor.
Sets use_cache_ to false, nr_subdiv_ to 5, and the internal maximum cache size to 1GB.
Definition at line 101 of file pfh.h.
References pcl::Feature< PointInT, pcl::PFHSignature125 >::feature_name_.
Member Function Documentation
computeFeature()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::PFHEstimation< PointInT, PointNT, PointOutT >::computeFeature (PointCloudOut & output) override protected
Estimate the Point Feature Histograms (PFH) descriptors at a set of points given by <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Parameters
[out] output the resultant point cloud model dataset that contains the PFH feature estimates
Definition at line 166 of file pfh.hpp.
References pcl::isFinite().
computePairFeatures()
template<typename PointInT , typename PointNT , typename PointOutT > bool pcl::PFHEstimation< PointInT, PointNT, PointOutT >::computePairFeatures (const pcl::PointCloud< PointInT > & cloud, const pcl::PointCloud< PointNT > & normals, int p_idx, int q_idx, float & f1, float & f2, float & f3, float & f4)
Compute the 4-tuple representation containing the three angles and one distance between two points represented by Cartesian coordinates and normals.
Note
For explanations about the features, please see the literature mentioned above (the order of the features might be different).
Parameters
[in] cloud the dataset containing the XYZ Cartesian coordinates of the two points
[in] normals the dataset containing the surface normals (assuming normalized vectors) at each point in cloud
[in] p_idx the index of the first point (source)
[in] q_idx the index of the second point (target)
[out] f1 the first angular feature (angle between the projection of nq_idx and u)
[out] f2 the second angular feature (angle between nq_idx and v)
[out] f3 the third angular feature (angle between np_idx and |p_idx - q_idx|)
[out] f4 the distance feature (p_idx - q_idx)
Note
For efficiency reasons, we assume that the point data passed to the method is finite.
Definition at line 48 of file pfh.hpp.
References pcl::computePairFeatures(), and pcl::PointCloud< PointT >::points.
computePointPFHSignature()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::PFHEstimation< PointInT, PointNT, PointOutT >::computePointPFHSignature (const pcl::PointCloud< PointInT > & cloud, const pcl::PointCloud< PointNT > & normals, const std::vector< int > & indices, int nr_split, Eigen::VectorXf & pfh_histogram)
Estimate the PFH (Point Feature Histograms) individual signatures of the three angular (f1, f2, f3) features for a given point based on its spatial neighborhood of 3D points with normals.
Parameters
[in] cloud the dataset containing the XYZ Cartesian coordinates of the two points
[in] normals the dataset containing the surface normals at each point in cloud
[in] indices the k-neighborhood point indices in the dataset
[in] nr_split the number of subdivisions for each angular feature interval
[out] pfh_histogram the resultant (combinatorial) PFH histogram representing the feature at the query point
Definition at line 60 of file pfh.hpp.
References pcl::computePairFeatures(), pcl::isFinite(), M_PI, and pcl::PointCloud< PointT >::points.
getMaximumCacheSize()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PFHSignature125> unsigned int pcl::PFHEstimation< PointInT, PointNT, PointOutT >::getMaximumCacheSize () inline
Get the maximum internal cache size.
Definition at line 123 of file pfh.h.
References pcl::PFHEstimation< PointInT, PointNT, PointOutT >::max_cache_size_.
getUseInternalCache()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PFHSignature125> bool pcl::PFHEstimation< PointInT, PointNT, PointOutT >::getUseInternalCache () inline
Get whether the internal cache is used or not for computing the PFH features.
Definition at line 147 of file pfh.h.
References pcl::PFHEstimation< PointInT, PointNT, PointOutT >::use_cache_.
setMaximumCacheSize()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PFHSignature125> void pcl::PFHEstimation< PointInT, PointNT, PointOutT >::setMaximumCacheSize (unsigned int cache_size) inline
Set the maximum internal cache size.
Defaults to 2GB worth of entries.
Parameters
[in] cache_size maximum cache size
Definition at line 116 of file pfh.h.
References pcl::PFHEstimation< PointInT, PointNT, PointOutT >::max_cache_size_.
setUseInternalCache()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PFHSignature125> void pcl::PFHEstimation< PointInT, PointNT, PointOutT >::setUseInternalCache (bool use_cache) inline
Set whether to use an internal cache mechanism for removing redundant calculations or not.
Note
Depending on how the point cloud is ordered and how the nearest neighbors are estimated, using a cache could have a positive or a negative influence. Please test with and without a cache on your data, and choose whatever works best!
See setMaximumCacheSize for setting the maximum cache size
Parameters
[in] use_cache set to true to use the internal cache, false otherwise
Definition at line 140 of file pfh.h.
References pcl::PFHEstimation< PointInT, PointNT, PointOutT >::use_cache_.
Member Data Documentation
d_pi_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PFHSignature125> float pcl::PFHEstimation< PointInT, PointNT, PointOutT >::d_pi_ protected
Float constant = 1.0 / (2.0 * M_PI)
Definition at line 204 of file pfh.h.
f_index_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PFHSignature125> int pcl::PFHEstimation< PointInT, PointNT, PointOutT >::f_index_[3] protected
Placeholder for a histogram index.
Definition at line 201 of file pfh.h.
feature_map_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PFHSignature125> std::map<std::pair<int, int>, Eigen::Vector4f, std::less<>, Eigen::aligned_allocator<std::pair<const std::pair<int, int>, Eigen::Vector4f> > > pcl::PFHEstimation< PointInT, PointNT, PointOutT >::feature_map_ protected
Internal hashmap, used to optimize efficiency of redundant computations.
Definition at line 207 of file pfh.h.
key_list_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PFHSignature125> std::queue<std::pair<int, int> > pcl::PFHEstimation< PointInT, PointNT, PointOutT >::key_list_ protected
Queue of pairs saved, used to constrain memory usage.
Definition at line 210 of file pfh.h.
max_cache_size_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PFHSignature125> unsigned int pcl::PFHEstimation< PointInT, PointNT, PointOutT >::max_cache_size_ protected
Maximum size of internal cache memory.
Definition at line 213 of file pfh.h.
Referenced by pcl::PFHEstimation< PointInT, PointNT, PointOutT >::getMaximumCacheSize(), and pcl::PFHEstimation< PointInT, PointNT, PointOutT >::setMaximumCacheSize().
nr_subdiv_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PFHSignature125> int pcl::PFHEstimation< PointInT, PointNT, PointOutT >::nr_subdiv_ protected
The number of subdivisions for each angular feature interval.
Definition at line 192 of file pfh.h.
pfh_histogram_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PFHSignature125> Eigen::VectorXf pcl::PFHEstimation< PointInT, PointNT, PointOutT >::pfh_histogram_ protected
Placeholder for a point's PFH signature.
Definition at line 195 of file pfh.h.
pfh_tuple_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PFHSignature125> Eigen::Vector4f pcl::PFHEstimation< PointInT, PointNT, PointOutT >::pfh_tuple_ protected
Placeholder for a PFH 4-tuple.
Definition at line 198 of file pfh.h.
use_cache_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::PFHSignature125> bool pcl::PFHEstimation< PointInT, PointNT, PointOutT >::use_cache_ protected
Set to true to use the internal cache for removing redundant computations.
Definition at line 216 of file pfh.h.
Referenced by pcl::PFHEstimation< PointInT, PointNT, PointOutT >::getUseInternalCache(), and pcl::PFHEstimation< PointInT, PointNT, PointOutT >::setUseInternalCache().
The documentation for this class was generated from the following files:
pcl/features/pfh.h
pcl/features/impl/pfh.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Jun 2 2020 14:12:33