Point Cloud Library (PCL): pcl::poisson::SparseMatrix< T > Class Template Reference
pcl::poisson::SparseMatrix< T > Class Template Reference
#include <pcl/surface/3rdparty/poisson4/sparse_matrix.h>
Public Member Functions
MatrixEntry< T > * operator[] (int idx)
const MatrixEntry< T > * operator[] (int idx) const
SparseMatrix (void)
SparseMatrix (int rows)
SparseMatrix (int rows, int maxEntriesPerRow)
void Resize (int rows)
void Resize (int rows, int maxEntriesPerRow)
void SetRowSize (int row, int count)
int Entries (void) const
SparseMatrix (const SparseMatrix &M)
~SparseMatrix ()
void SetZero ()
void SetIdentity ()
SparseMatrix< T > & operator= (const SparseMatrix< T > &M)
SparseMatrix< T > operator* (const T &V) const
SparseMatrix< T > & operator*= (const T &V)
SparseMatrix< T > operator* (const SparseMatrix< T > &M) const
SparseMatrix< T > Multiply (const SparseMatrix< T > &M) const
SparseMatrix< T > MultiplyTranspose (const SparseMatrix< T > &Mt) const
template<class T2 >
Vector< T2 > operator* (const Vector< T2 > &V) const
template<class T2 >
Vector< T2 > Multiply (const Vector< T2 > &V) const
template<class T2 >
void Multiply (const Vector< T2 > &In, Vector< T2 > &Out, int threads=1) const
SparseMatrix< T > Transpose () const
bool write (FILE *fp) const
bool write (const char *fileName) const
bool read (FILE *fp)
bool read (const char *fileName)
Static Public Member Functions
static int UseAllocator (void)
static void SetAllocator (int blockSize)
static int Solve (const SparseMatrix< T > &M, const Vector< T > &b, int iters, Vector< T > &solution, const T eps=1e-8)
template<class T2 >
static int SolveSymmetric (const SparseMatrix< T > &M, const Vector< T2 > &b, int iters, Vector< T2 > &solution, const T2 eps=1e-8, int reset=1, int threads=1)
Public Attributes
int rows
int * rowSizes
MatrixEntry< T > ** m_ppElements
Static Public Attributes
static Allocator< MatrixEntry< T > > internalAllocator
Detailed Description
template<class T>
class pcl::poisson::SparseMatrix< T >
Definition at line 53 of file sparse_matrix.h.
Constructor & Destructor Documentation
SparseMatrix() [1/4]
template<class T > pcl::poisson::SparseMatrix< T >::SparseMatrix (void)
Definition at line 69 of file sparse_matrix.hpp.
SparseMatrix() [2/4]
template<class T > pcl::poisson::SparseMatrix< T >::SparseMatrix (int rows)
Definition at line 78 of file sparse_matrix.hpp.
References pcl::poisson::SparseMatrix< T >::Resize(), and pcl::poisson::SparseMatrix< T >::rows.
SparseMatrix() [3/4]
template<class T > pcl::poisson::SparseMatrix< T >::SparseMatrix (int rows, int maxEntriesPerRow)
Definition at line 79 of file sparse_matrix.hpp.
References pcl::poisson::SparseMatrix< T >::Resize(), and pcl::poisson::SparseMatrix< T >::rows.
SparseMatrix() [4/4]
template<class T > pcl::poisson::SparseMatrix< T >::SparseMatrix (const SparseMatrix< T > & M)
Definition at line 82 of file sparse_matrix.hpp.
References pcl::poisson::SparseMatrix< T >::Resize(), pcl::poisson::SparseMatrix< T >::rows, pcl::poisson::SparseMatrix< T >::rowSizes, and pcl::poisson::SparseMatrix< T >::SetRowSize().
~SparseMatrix()
template<class T > pcl::poisson::SparseMatrix< T >::~SparseMatrix (void)
Definition at line 113 of file sparse_matrix.hpp.
Member Function Documentation
Entries()
template<class T > int pcl::poisson::SparseMatrix< T >::Entries (void) const
Definition at line 93 of file sparse_matrix.hpp.
Multiply() [1/3]
template<class T > SparseMatrix< T > pcl::poisson::SparseMatrix< T >::Multiply (const SparseMatrix< T > & M) const
Definition at line 265 of file sparse_matrix.hpp.
References pcl::poisson::SparseMatrix< T >::m_ppElements, pcl::poisson::SparseMatrix< T >::rows, and pcl::poisson::SparseMatrix< T >::rowSizes.
Referenced by pcl::poisson::SparseMatrix< T >::SolveSymmetric().
Multiply() [2/3]
template<class T > template<class T2 > void pcl::poisson::SparseMatrix< T >::Multiply (const Vector< T2 > & In, Vector< T2 > & Out, int threads = 1) const
Definition at line 299 of file sparse_matrix.hpp.
References pcl::poisson::Vector< T >::m_pV.
Multiply() [3/3]
template<class T > template<class T2 > Vector< T2 > pcl::poisson::SparseMatrix< T >::Multiply (const Vector< T2 > & V) const
Definition at line 282 of file sparse_matrix.hpp.
References pcl::poisson::Vector< T >::m_pV.
MultiplyTranspose()
template<class T > SparseMatrix<T> pcl::poisson::SparseMatrix< T >::MultiplyTranspose (const SparseMatrix< T > & Mt) const
operator*() [1/3]
template<class T > SparseMatrix< T > pcl::poisson::SparseMatrix< T >::operator* (const SparseMatrix< T > & M) const
Definition at line 312 of file sparse_matrix.hpp.
References pcl::poisson::Multiply().
operator*() [2/3]
template<class T > SparseMatrix< T > pcl::poisson::SparseMatrix< T >::operator* (const T & V) const
Definition at line 247 of file sparse_matrix.hpp.
operator*() [3/3]
template<class T > template<class T2 > Vector< T2 > pcl::poisson::SparseMatrix< T >::operator* (const Vector< T2 > & V) const
Definition at line 318 of file sparse_matrix.hpp.
References pcl::poisson::Multiply().
operator*=()
template<class T > SparseMatrix< T > & pcl::poisson::SparseMatrix< T >::operator*= (const T & V)
Definition at line 255 of file sparse_matrix.hpp.
operator=()
template<class T > SparseMatrix< T > & pcl::poisson::SparseMatrix< T >::operator= (const SparseMatrix< T > & M)
Definition at line 100 of file sparse_matrix.hpp.
References pcl::poisson::SparseMatrix< T >::rows, and pcl::poisson::SparseMatrix< T >::rowSizes.
operator[]() [1/2]
template<class T > MatrixEntry< T >* pcl::poisson::SparseMatrix< T >::operator[] (int idx) inline
Definition at line 67 of file sparse_matrix.h.
References pcl::poisson::SparseMatrix< T >::m_ppElements.
operator[]() [2/2]
template<class T > const MatrixEntry< T >* pcl::poisson::SparseMatrix< T >::operator[] (int idx) const inline
Definition at line 68 of file sparse_matrix.h.
References pcl::poisson::SparseMatrix< T >::m_ppElements.
read() [1/2]
template<class T > bool pcl::poisson::SparseMatrix< T >::read (const char * fileName)
Definition at line 125 of file sparse_matrix.hpp.
References pcl::read().
read() [2/2]
template<class T > bool pcl::poisson::SparseMatrix< T >::read (FILE * fp)
Definition at line 142 of file sparse_matrix.hpp.
Resize() [1/2]
template<class T > void pcl::poisson::SparseMatrix< T >::Resize (int rows)
Definition at line 160 of file sparse_matrix.hpp.
Referenced by pcl::poisson::SparseMatrix< T >::SparseMatrix().
Resize() [2/2]
template<class T > void pcl::poisson::SparseMatrix< T >::Resize (int rows, int maxEntriesPerRow)
Definition at line 182 of file sparse_matrix.hpp.
SetAllocator()
template<class T > void pcl::poisson::SparseMatrix< T >::SetAllocator (int blockSize) static
Definition at line 56 of file sparse_matrix.hpp.
Referenced by pcl::poisson::Octree< Degree >::LaplacianMatrixIteration().
SetIdentity()
template<class T > void pcl::poisson::SparseMatrix< T >::SetIdentity
Definition at line 239 of file sparse_matrix.hpp.
SetRowSize()
template<class T > void pcl::poisson::SparseMatrix< T >::SetRowSize (int row, int count)
Definition at line 206 of file sparse_matrix.hpp.
Referenced by pcl::poisson::SparseMatrix< T >::SparseMatrix().
SetZero()
template<class T > void pcl::poisson::SparseMatrix< T >::SetZero
Definition at line 229 of file sparse_matrix.hpp.
Solve()
template<class T > int pcl::poisson::SparseMatrix< T >::Solve (const SparseMatrix< T > & M, const Vector< T > & b, int iters, Vector< T > & solution, const T eps = 1e-8) static
Definition at line 388 of file sparse_matrix.hpp.
References pcl::poisson::Vector< T >::Dimensions(), pcl::poisson::Vector< T >::Dot(), pcl::poisson::Vector< T >::Resize(), pcl::poisson::Vector< T >::SetZero(), and pcl::poisson::SparseMatrix< T >::Transpose().
SolveSymmetric()
template<class T > template<class T2 > int pcl::poisson::SparseMatrix< T >::SolveSymmetric (const SparseMatrix< T > & M, const Vector< T2 > & b, int iters, Vector< T2 > & solution, const T2 eps = 1e-8, int reset = 1, int threads = 1) static
Definition at line 339 of file sparse_matrix.hpp.
References pcl::poisson::Vector< T >::Dimensions(), pcl::poisson::Vector< T >::m_pV, pcl::poisson::SparseMatrix< T >::Multiply(), pcl::poisson::Vector< T >::Resize(), and pcl::poisson::Vector< T >::SetZero().
Transpose()
template<class T > SparseMatrix< T > pcl::poisson::SparseMatrix< T >::Transpose
Definition at line 324 of file sparse_matrix.hpp.
Referenced by pcl::poisson::SparseMatrix< T >::Solve().
UseAllocator()
template<class T > int pcl::poisson::SparseMatrix< T >::UseAllocator (void) static
Definition at line 54 of file sparse_matrix.hpp.
write() [1/2]
template<class T > bool pcl::poisson::SparseMatrix< T >::write (const char * fileName) const
Definition at line 116 of file sparse_matrix.hpp.
References pcl::write().
write() [2/2]
template<class T > bool pcl::poisson::SparseMatrix< T >::write (FILE * fp) const
Definition at line 134 of file sparse_matrix.hpp.
Member Data Documentation
internalAllocator
template<class T > Allocator< MatrixEntry< T > > pcl::poisson::SparseMatrix< T >::internalAllocator static
Definition at line 60 of file sparse_matrix.h.
m_ppElements
template<class T > MatrixEntry<T>** pcl::poisson::SparseMatrix< T >::m_ppElements
Definition at line 66 of file sparse_matrix.h.
Referenced by pcl::poisson::SparseMatrix< T >::Multiply(), and pcl::poisson::SparseMatrix< T >::operator[]().
rows
template<class T > int pcl::poisson::SparseMatrix< T >::rows
Definition at line 64 of file sparse_matrix.h.
Referenced by pcl::poisson::SparseMatrix< T >::Multiply(), pcl::poisson::MultiplyAtomic(), pcl::poisson::SparseMatrix< T >::operator=(), pcl::poisson::SparseSymmetricMatrix< T >::Solve(), pcl::poisson::SparseSymmetricMatrix< T >::SolveAtomic(), and pcl::poisson::SparseMatrix< T >::SparseMatrix().
rowSizes
template<class T > int* pcl::poisson::SparseMatrix< T >::rowSizes
Definition at line 65 of file sparse_matrix.h.
Referenced by pcl::poisson::SparseMatrix< T >::Multiply(), pcl::poisson::MultiplyAtomic(), pcl::poisson::SparseMatrix< T >::operator=(), pcl::poisson::SparseSymmetricMatrix< T >::SolveAtomic(), and pcl::poisson::SparseMatrix< T >::SparseMatrix().
The documentation for this class was generated from the following files:
pcl/surface/3rdparty/poisson4/sparse_matrix.h
pcl/surface/3rdparty/poisson4/sparse_matrix.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:42