Point Cloud Library (PCL): pcl::poisson::Square Class Reference
pcl::poisson::Square Class Reference
#include <pcl/surface/3rdparty/poisson4/marching_cubes_poisson.h>
Public Types
enum { CORNERS =4 , EDGES =4 , NEIGHBORS =4 }
Static Public Member Functions
static int CornerIndex (int x, int y)
static int AntipodalCornerIndex (int idx)
static void FactorCornerIndex (int idx, int &x, int &y)
static int EdgeIndex (int orientation, int i)
static void FactorEdgeIndex (int idx, int &orientation, int &i)
static int ReflectCornerIndex (int idx, int edgeIndex)
static int ReflectEdgeIndex (int idx, int edgeIndex)
static void EdgeCorners (int idx, int &c1, int &c2)
Detailed Description
Definition at line 40 of file marching_cubes_poisson.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
CORNERS
EDGES
NEIGHBORS
Definition at line 43 of file marching_cubes_poisson.h.
Member Function Documentation
AntipodalCornerIndex()
static int pcl::poisson::Square::AntipodalCornerIndex (int idx) static
Referenced by pcl::poisson::SortedTreeNodes::getMaxEdgeCount(), and pcl::poisson::SortedTreeNodes::setEdgeTable().
CornerIndex()
static int pcl::poisson::Square::CornerIndex (int x, int y) static
Referenced by pcl::poisson::SortedTreeNodes::getMaxEdgeCount(), and pcl::poisson::SortedTreeNodes::setEdgeTable().
EdgeCorners()
static void pcl::poisson::Square::EdgeCorners (int idx, int & c1, int & c2) static
EdgeIndex()
static int pcl::poisson::Square::EdgeIndex (int orientation, int i) static
FactorCornerIndex()
static void pcl::poisson::Square::FactorCornerIndex (int idx, int & x, int & y) static
Referenced by pcl::poisson::SortedTreeNodes::getMaxEdgeCount(), and pcl::poisson::SortedTreeNodes::setEdgeTable().
FactorEdgeIndex()
static void pcl::poisson::Square::FactorEdgeIndex (int idx, int & orientation, int & i) static
ReflectCornerIndex()
static int pcl::poisson::Square::ReflectCornerIndex (int idx, int edgeIndex) static
ReflectEdgeIndex()
static int pcl::poisson::Square::ReflectEdgeIndex (int idx, int edgeIndex) static
The documentation for this class was generated from the following file:
pcl/surface/3rdparty/poisson4/marching_cubes_poisson.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:42