Point Cloud Library (PCL): pcl::poisson::Cube Class Reference
pcl::poisson::Cube Class Reference
#include <pcl/surface/3rdparty/poisson4/marching_cubes_poisson.h>
Public Types
enum { CORNERS =8 , EDGES =12 , NEIGHBORS =6 }
Static Public Member Functions
static int CornerIndex (int x, int y, int z)
static void FactorCornerIndex (int idx, int &x, int &y, int &z)
static int EdgeIndex (int orientation, int i, int j)
static void FactorEdgeIndex (int idx, int &orientation, int &i, int &j)
static int FaceIndex (int dir, int offSet)
static int FaceIndex (int x, int y, int z)
static void FactorFaceIndex (int idx, int &x, int &y, int &z)
static void FactorFaceIndex (int idx, int &dir, int &offSet)
static int AntipodalCornerIndex (int idx)
static int FaceReflectCornerIndex (int idx, int faceIndex)
static int FaceReflectEdgeIndex (int idx, int faceIndex)
static int FaceReflectFaceIndex (int idx, int faceIndex)
static int EdgeReflectCornerIndex (int idx, int edgeIndex)
static int EdgeReflectEdgeIndex (int edgeIndex)
static int FaceAdjacentToEdges (int eIndex1, int eIndex2)
static void FacesAdjacentToEdge (int eIndex, int &f1Index, int &f2Index)
static void EdgeCorners (int idx, int &c1, int &c2)
static void FaceCorners (int idx, int &c1, int &c2, int &c3, int &c4)
Detailed Description
Definition at line 56 of file marching_cubes_poisson.h.
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
CORNERS
EDGES
NEIGHBORS
Definition at line 59 of file marching_cubes_poisson.h.
Member Function Documentation
AntipodalCornerIndex()
static int pcl::poisson::Cube::AntipodalCornerIndex (int idx) static
Referenced by pcl::poisson::SortedTreeNodes::getMaxCornerCount(), and pcl::poisson::SortedTreeNodes::setCornerTable().
CornerIndex()
static int pcl::poisson::Cube::CornerIndex (int x, int y, int z) static
Referenced by pcl::poisson::Octree< Degree >::GetMCIsoTriangles(), pcl::poisson::OctNode< NodeData, Real >::ConstNeighborKey5::getNeighbors(), pcl::poisson::OctNode< NodeData, Real >::NeighborKey5::getNeighbors(), and pcl::poisson::OctNode< NodeData, Real >::NeighborKey5::setNeighbors().
EdgeCorners()
static void pcl::poisson::Cube::EdgeCorners (int idx, int & c1, int & c2) static
Referenced by pcl::poisson::OctNode< NodeData, Real >::processNodeEdges().
EdgeIndex()
static int pcl::poisson::Cube::EdgeIndex (int orientation, int i, int j) static
Referenced by pcl::poisson::SortedTreeNodes::setEdgeTable().
EdgeReflectCornerIndex()
static int pcl::poisson::Cube::EdgeReflectCornerIndex (int idx, int edgeIndex) static
EdgeReflectEdgeIndex()
static int pcl::poisson::Cube::EdgeReflectEdgeIndex (int edgeIndex) static
FaceAdjacentToEdges()
static int pcl::poisson::Cube::FaceAdjacentToEdges (int eIndex1, int eIndex2) static
FaceCorners()
static void pcl::poisson::Cube::FaceCorners (int idx, int & c1, int & c2, int & c3, int & c4) static
Referenced by pcl::poisson::OctNode< NodeData, Real >::processNodeFaces().
FaceIndex() [1/2]
static int pcl::poisson::Cube::FaceIndex (int dir, int offSet) static
FaceIndex() [2/2]
static int pcl::poisson::Cube::FaceIndex (int x, int y, int z) static
FaceReflectCornerIndex()
static int pcl::poisson::Cube::FaceReflectCornerIndex (int idx, int faceIndex) static
FaceReflectEdgeIndex()
static int pcl::poisson::Cube::FaceReflectEdgeIndex (int idx, int faceIndex) static
FaceReflectFaceIndex()
static int pcl::poisson::Cube::FaceReflectFaceIndex (int idx, int faceIndex) static
FacesAdjacentToEdge()
static void pcl::poisson::Cube::FacesAdjacentToEdge (int eIndex, int & f1Index, int & f2Index) static
FactorCornerIndex()
static void pcl::poisson::Cube::FactorCornerIndex (int idx, int & x, int & y, int & z) static
Referenced by pcl::poisson::VertexData::CornerIndex(), pcl::poisson::Octree< Degree >::finalize(), pcl::poisson::SortedTreeNodes::getMaxCornerCount(), pcl::poisson::OctNode< NodeData, Real >::ConstNeighborKey5::getNeighbors(), pcl::poisson::OctNode< NodeData, Real >::NeighborKey5::getNeighbors(), pcl::poisson::SortedTreeNodes::setCornerTable(), pcl::poisson::Octree< Degree >::SetLaplacianConstraints(), and pcl::poisson::OctNode< NodeData, Real >::NeighborKey5::setNeighbors().
FactorEdgeIndex()
static void pcl::poisson::Cube::FactorEdgeIndex (int idx, int & orientation, int & i, int & j) static
Referenced by pcl::poisson::OctNode< NodeData, Real >::CommonEdge(), pcl::poisson::VertexData::EdgeIndex(), pcl::poisson::OctNode< NodeData, Real >::edgeNeighbor(), pcl::poisson::SortedTreeNodes::getMaxEdgeCount(), and pcl::poisson::SortedTreeNodes::setEdgeTable().
FactorFaceIndex() [1/2]
static void pcl::poisson::Cube::FactorFaceIndex (int idx, int & dir, int & offSet) static
FactorFaceIndex() [2/2]
static void pcl::poisson::Cube::FactorFaceIndex (int idx, int & x, int & y, int & z) static
Referenced by pcl::poisson::VertexData::FaceIndex().
The documentation for this class was generated from the following file:
pcl/surface/3rdparty/poisson4/marching_cubes_poisson.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:42