Point Cloud Library (PCL): pcl::LinearLeastSquaresNormalEstimation< PointInT, PointOutT > Class Template Reference
pcl::LinearLeastSquaresNormalEstimation< PointInT, PointOutT > Class Template Reference
Surface normal estimation on dense data using a least-squares estimation based on a first-order Taylor approximation.
#include <pcl/features/linear_least_squares_normal.h>
Public Types
using Ptr = shared_ptr< LinearLeastSquaresNormalEstimation< PointInT, PointOutT > >
using ConstPtr = shared_ptr< const LinearLeastSquaresNormalEstimation< PointInT, PointOutT > >
using PointCloudIn = typename Feature< PointInT, PointOutT >::PointCloudIn
using PointCloudOut = typename Feature< PointInT, PointOutT >::PointCloudOut
Public Types inherited from pcl::Feature< PointInT, PointOutT >
using BaseClass = PCLBase< PointInT >
using Ptr = shared_ptr< Feature< PointInT, PointOutT > >
using ConstPtr = shared_ptr< const Feature< PointInT, PointOutT > >
using KdTree = pcl::search::Search< PointInT >
using KdTreePtr = typename KdTree::Ptr
using PointCloudIn = pcl::PointCloud< PointInT >
using PointCloudInPtr = typename PointCloudIn::Ptr
using PointCloudInConstPtr = typename PointCloudIn::ConstPtr
using PointCloudOut = pcl::PointCloud< PointOutT >
using SearchMethod = std::function< int(std::size_t, double, std::vector< int > &, std::vector< float > &)>
using SearchMethodSurface = std::function< int(const PointCloudIn &cloud, std::size_t index, double, std::vector< int > &, std::vector< float > &)>
Public Types inherited from pcl::PCLBase< PointInT >
using PointCloud = pcl::PointCloud< PointInT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
LinearLeastSquaresNormalEstimation ()
Constructor.
~LinearLeastSquaresNormalEstimation ()
Destructor.
void computePointNormal (const int pos_x, const int pos_y, PointOutT &normal)
Computes the normal at the specified position.
void setNormalSmoothingSize (float normal_smoothing_size)
Set the normal smoothing size.
void setDepthDependentSmoothing (bool use_depth_dependent_smoothing)
Set whether to use depth depending smoothing or not.
void setMaxDepthChangeFactor (float max_depth_change_factor)
The depth change threshold for computing object borders.
void setInputCloud (const typename PointCloudIn::ConstPtr &cloud) override
Provide a pointer to the input dataset (overwrites the PCLBase::setInputCloud method)
Public Member Functions inherited from pcl::Feature< PointInT, PointOutT >
Feature ()
Empty constructor.
virtual ~Feature ()
Empty destructor.
void setSearchSurface (const PointCloudInConstPtr &cloud)
Provide a pointer to a dataset to add additional information to estimate the features for every point in the input dataset.
PointCloudInConstPtr getSearchSurface () const
Get a pointer to the surface point cloud dataset.
void setSearchMethod (const KdTreePtr &tree)
Provide a pointer to the search object.
KdTreePtr getSearchMethod () const
Get a pointer to the search method used.
double getSearchParameter () const
Get the internal search parameter.
void setKSearch (int k)
Set the number of k nearest neighbors to use for the feature estimation.
int getKSearch () const
get the number of k nearest neighbors used for the feature estimation.
void setRadiusSearch (double radius)
Set the sphere radius that is to be used for determining the nearest neighbors used for the feature estimation.
double getRadiusSearch () const
Get the sphere radius used for determining the neighbors.
void compute (PointCloudOut &output)
Base method for feature estimation for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Public Member Functions inherited from pcl::PCLBase< PointInT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
const PointCloudConstPtr getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
const IndicesConstPtr getIndices () const
Get a pointer to the vector of indices used.
const PointInT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
void computeFeature (PointCloudOut &output) override
Computes the normal for the complete cloud.
Protected Member Functions inherited from pcl::Feature< PointInT, PointOutT >
const std::string & getClassName () const
Get a string representation of the name of this class.
virtual bool initCompute ()
This method should get called before starting the actual computation.
virtual bool deinitCompute ()
This method should get called after ending the actual computation.
int searchForNeighbors (std::size_t index, double parameter, std::vector< int > &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
int searchForNeighbors (const PointCloudIn &cloud, std::size_t index, double parameter, std::vector< int > &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
Protected Member Functions inherited from pcl::PCLBase< PointInT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Additional Inherited Members
Protected Attributes inherited from pcl::Feature< PointInT, PointOutT >
std::string feature_name_
The feature name.
SearchMethodSurface search_method_surface_
The search method template for points.
PointCloudInConstPtr surface_
An input point cloud describing the surface that is to be used for nearest neighbors estimation.
KdTreePtr tree_
A pointer to the spatial search object.
double search_parameter_
The actual search parameter (from either search_radius_ or k_).
double search_radius_
The nearest neighbors search radius for each point.
int k_
The number of K nearest neighbors to use for each point.
bool fake_surface_
If no surface is given, we use the input PointCloud as the surface.
Protected Attributes inherited from pcl::PCLBase< PointInT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointInT, typename PointOutT>
class pcl::LinearLeastSquaresNormalEstimation< PointInT, PointOutT >
Surface normal estimation on dense data using a least-squares estimation based on a first-order Taylor approximation.
Author
Stefan Holzer, Cedric Cagniart
Definition at line 51 of file linear_least_squares_normal.h.
Member Typedef Documentation
ConstPtr
template<typename PointInT , typename PointOutT > using pcl::LinearLeastSquaresNormalEstimation< PointInT, PointOutT >::ConstPtr = shared_ptr<const LinearLeastSquaresNormalEstimation<PointInT, PointOutT> >
Definition at line 55 of file linear_least_squares_normal.h.
PointCloudIn
template<typename PointInT , typename PointOutT > using pcl::LinearLeastSquaresNormalEstimation< PointInT, PointOutT >::PointCloudIn = typename Feature<PointInT, PointOutT>::PointCloudIn
Definition at line 56 of file linear_least_squares_normal.h.
PointCloudOut
template<typename PointInT , typename PointOutT > using pcl::LinearLeastSquaresNormalEstimation< PointInT, PointOutT >::PointCloudOut = typename Feature<PointInT, PointOutT>::PointCloudOut
Definition at line 57 of file linear_least_squares_normal.h.
Ptr
template<typename PointInT , typename PointOutT > using pcl::LinearLeastSquaresNormalEstimation< PointInT, PointOutT >::Ptr = shared_ptr<LinearLeastSquaresNormalEstimation<PointInT, PointOutT> >
Definition at line 54 of file linear_least_squares_normal.h.
Constructor & Destructor Documentation
LinearLeastSquaresNormalEstimation()
template<typename PointInT , typename PointOutT > pcl::LinearLeastSquaresNormalEstimation< PointInT, PointOutT >::LinearLeastSquaresNormalEstimation () inline
Constructor.
Definition at line 64 of file linear_least_squares_normal.h.
References pcl::Feature< PointInT, PointOutT >::feature_name_, pcl::Feature< PointInT, PointOutT >::k_, and pcl::Feature< PointInT, PointOutT >::tree_.
~LinearLeastSquaresNormalEstimation()
template<typename PointInT , typename PointOutT > pcl::LinearLeastSquaresNormalEstimation< PointInT, PointOutT >::~LinearLeastSquaresNormalEstimation
Destructor.
Definition at line 47 of file linear_least_squares_normal.hpp.
Member Function Documentation
computeFeature()
template<typename PointInT , typename PointOutT > void pcl::LinearLeastSquaresNormalEstimation< PointInT, PointOutT >::computeFeature (PointCloudOut & output) override protected virtual
Computes the normal for the complete cloud.
Parameters
[out] output the resultant normals
Implements pcl::Feature< PointInT, PointOutT >.
Definition at line 155 of file linear_least_squares_normal.hpp.
References pcl::PointCloud< PointT >::points.
computePointNormal()
template<typename PointInT , typename PointOutT > void pcl::LinearLeastSquaresNormalEstimation< PointInT, PointOutT >::computePointNormal (const int pos_x, const int pos_y, PointOutT & normal)
Computes the normal at the specified position.
Parameters
[in] pos_x x position (pixel)
[in] pos_y y position (pixel)
[out] normal the output estimated normal
Definition at line 53 of file linear_least_squares_normal.hpp.
setDepthDependentSmoothing()
template<typename PointInT , typename PointOutT > void pcl::LinearLeastSquaresNormalEstimation< PointInT, PointOutT >::setDepthDependentSmoothing (bool use_depth_dependent_smoothing) inline
Set whether to use depth depending smoothing or not.
Parameters
[in] use_depth_dependent_smoothing decides whether the smoothing is depth dependent
Definition at line 99 of file linear_least_squares_normal.h.
Referenced by pcl::SurfaceNormalModality< PointXYZT >::computeSurfaceNormals().
setInputCloud()
template<typename PointInT , typename PointOutT > void pcl::LinearLeastSquaresNormalEstimation< PointInT, PointOutT >::setInputCloud (const typename PointCloudIn::ConstPtr & cloud) inline override
Provide a pointer to the input dataset (overwrites the PCLBase::setInputCloud method)
Parameters
[in] cloud the const boost shared pointer to a PointCloud message
Definition at line 118 of file linear_least_squares_normal.h.
References pcl::PCLBase< PointInT >::input_.
Referenced by pcl::SurfaceNormalModality< PointXYZT >::computeSurfaceNormals().
setMaxDepthChangeFactor()
template<typename PointInT , typename PointOutT > void pcl::LinearLeastSquaresNormalEstimation< PointInT, PointOutT >::setMaxDepthChangeFactor (float max_depth_change_factor) inline
The depth change threshold for computing object borders.
Parameters
[in] max_depth_change_factor the depth change threshold for computing object borders based on depth changes
Definition at line 109 of file linear_least_squares_normal.h.
Referenced by pcl::SurfaceNormalModality< PointXYZT >::computeSurfaceNormals().
setNormalSmoothingSize()
template<typename PointInT , typename PointOutT > void pcl::LinearLeastSquaresNormalEstimation< PointInT, PointOutT >::setNormalSmoothingSize (float normal_smoothing_size) inline
Set the normal smoothing size.
Parameters
[in] normal_smoothing_size factor which influences the size of the area used to smooth normals (depth dependent if useDepthDependentSmoothing is true)
Definition at line 90 of file linear_least_squares_normal.h.
Referenced by pcl::SurfaceNormalModality< PointXYZT >::computeSurfaceNormals().
The documentation for this class was generated from the following files:
pcl/features/linear_least_squares_normal.h
pcl/features/impl/linear_least_squares_normal.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Jun 2 2020 14:12:11