Point Cloud Library (PCL): pcl::geometry::FaceIndex Class Reference
pcl::geometry::FaceIndex Class Reference
Module geometry
Index used to access elements in the half-edge mesh.
#include <pcl/geometry/mesh_indices.h>
Public Types
using Base = boost::totally_ordered< pcl::geometry::FaceIndex, boost::unit_steppable< pcl::geometry::FaceIndex, boost::additive< pcl::geometry::FaceIndex > >>
using Self = pcl::geometry::FaceIndex
Public Member Functions
FaceIndex ()
Constructor.
FaceIndex (const int index)
Constructor.
bool isValid () const
Returns true if the index is valid.
void invalidate ()
Invalidate the index.
int get () const
Get the index.
void set (const int index)
Set the index.
bool operator< (const Self &other) const
Comparison operators (with boost::operators): < > <= >=.
bool operator== (const Self &other) const
Comparison operators (with boost::operators): == !=.
Self & operator++ ()
Increment operators (with boost::operators): ++ (pre and post)
Self & operator-- ()
Decrement operators (with boost::operators): -- (pre and post)
Self & operator+= (const Self &other)
Addition operators (with boost::operators): + +=.
Self & operator-= (const Self &other)
Subtraction operators (with boost::operators): - -=.
Friends
std::istream & operator>> (std::istream &is, pcl::geometry::FaceIndex &index)
istream operator.
Detailed Description
Index used to access elements in the half-edge mesh.
It is basically just a wrapper around an integer with a few added methods.
Author
Martin Saelzle
Definition at line 460 of file mesh_indices.h.
Member Typedef Documentation
Base
using pcl::geometry::FaceIndex::Base = boost::totally_ordered< pcl::geometry::FaceIndex, boost::unit_steppable<pcl::geometry::FaceIndex, boost::additive<pcl::geometry::FaceIndex> >>
Definition at line 472 of file mesh_indices.h.
Self
using pcl::geometry::FaceIndex::Self = pcl::geometry::FaceIndex
Definition at line 473 of file mesh_indices.h.
Constructor & Destructor Documentation
FaceIndex() [1/2]
pcl::geometry::FaceIndex::FaceIndex () inline
Constructor.
Initializes with an invalid index.
Definition at line 476 of file mesh_indices.h.
FaceIndex() [2/2]
pcl::geometry::FaceIndex::FaceIndex (const int index) inline explicit
Constructor.
Parameters
[in] index The integer index.
Definition at line 481 of file mesh_indices.h.
Member Function Documentation
get()
int pcl::geometry::FaceIndex::get () const inline
Get the index.
Definition at line 499 of file mesh_indices.h.
Referenced by pcl::geometry::MeshBase< QuadMesh< MeshTraitsT >, MeshTraitsT, QuadMeshTag >::getFace(), operator+=(), operator-=(), operator<(), pcl::geometry::operator<<(), operator==(), and pcl::geometry::MeshBase< QuadMesh< MeshTraitsT >, MeshTraitsT, QuadMeshTag >::setFace().
invalidate()
void pcl::geometry::FaceIndex::invalidate () inline
Invalidate the index.
Definition at line 492 of file mesh_indices.h.
Referenced by pcl::geometry::MeshBase< QuadMesh< MeshTraitsT >, MeshTraitsT, QuadMeshTag >::deleteFace().
isValid()
bool pcl::geometry::FaceIndex::isValid () const inline
Returns true if the index is valid.
Definition at line 485 of file mesh_indices.h.
Referenced by pcl::geometry::MeshBase< QuadMesh< MeshTraitsT >, MeshTraitsT, QuadMeshTag >::deleteVertex().
operator++()
Self& pcl::geometry::FaceIndex::operator++ () inline
Increment operators (with boost::operators): ++ (pre and post)
Definition at line 527 of file mesh_indices.h.
operator+=()
Self& pcl::geometry::FaceIndex::operator+= (const Self & other) inline
Addition operators (with boost::operators): + +=.
Definition at line 543 of file mesh_indices.h.
References get().
operator--()
Self& pcl::geometry::FaceIndex::operator-- () inline
Decrement operators (with boost::operators): -- (pre and post)
Definition at line 535 of file mesh_indices.h.
operator-=()
Self& pcl::geometry::FaceIndex::operator-= (const Self & other) inline
Subtraction operators (with boost::operators): - -=.
Definition at line 551 of file mesh_indices.h.
References get().
operator<()
bool pcl::geometry::FaceIndex::operator< (const Self & other) const inline
Comparison operators (with boost::operators): < > <= >=.
Definition at line 513 of file mesh_indices.h.
References get().
operator==()
bool pcl::geometry::FaceIndex::operator== (const Self & other) const inline
Comparison operators (with boost::operators): == !=.
Definition at line 520 of file mesh_indices.h.
References get().
set()
void pcl::geometry::FaceIndex::set (const int index) inline
Set the index.
Definition at line 506 of file mesh_indices.h.
Friends And Related Function Documentation
operator>>
std::istream& operator>> (std::istream & is, pcl::geometry::FaceIndex & index) friend
istream operator.
Definition at line 574 of file mesh_indices.h.
The documentation for this class was generated from the following file:
pcl/geometry/mesh_indices.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Apr 6 2021 19:04:55