Point Cloud Library (PCL): pcl::LabeledEuclideanClusterExtraction< PointT > Class Template Reference
pcl::LabeledEuclideanClusterExtraction< PointT > Class Template Reference
Module segmentation
LabeledEuclideanClusterExtraction represents a segmentation class for cluster extraction in an Euclidean sense, with label info.
#include <pcl/segmentation/extract_labeled_clusters.h>
Public Types
using PointCloud = pcl::PointCloud< PointT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using KdTree = pcl::search::Search< PointT >
using KdTreePtr = typename KdTree::Ptr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Types inherited from pcl::PCLBase< PointT >
using PointCloud = pcl::PointCloud< PointT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
LabeledEuclideanClusterExtraction ()=default
Empty constructor.
void setSearchMethod (const KdTreePtr &tree)
Provide a pointer to the search object.
KdTreePtr getSearchMethod () const
Get a pointer to the search method used.
void setClusterTolerance (double tolerance)
Set the spatial cluster tolerance as a measure in the L2 Euclidean space.
double getClusterTolerance () const
Get the spatial cluster tolerance as a measure in the L2 Euclidean space.
void setMinClusterSize (int min_cluster_size)
Set the minimum number of points that a cluster needs to contain in order to be considered valid.
int getMinClusterSize () const
Get the minimum number of points that a cluster needs to contain in order to be considered valid.
void setMaxClusterSize (int max_cluster_size)
Set the maximum number of points that a cluster needs to contain in order to be considered valid.
int getMaxClusterSize () const
Get the maximum number of points that a cluster needs to contain in order to be considered valid.
void extract (std::vector< std::vector< PointIndices >> &labeled_clusters)
Cluster extraction in a PointCloud given by <setInputCloud (), setIndices ()>
Public Member Functions inherited from pcl::PCLBase< PointT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
virtual std::string getClassName () const
Class getName method.
bool deinitCompute ()
This method should get called after finishing the actual computation.
bool initCompute ()
This method should get called before starting the actual computation.
Protected Member Functions inherited from pcl::PCLBase< PointT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Protected Attributes
KdTreePtr tree_ {nullptr}
A pointer to the spatial search object.
double cluster_tolerance_ {0.0}
The spatial cluster tolerance as a measure in the L2 Euclidean space.
int min_pts_per_cluster_ {1}
The minimum number of points that a cluster needs to contain in order to be considered valid (default = 1).
int max_pts_per_cluster_ {std::numeric_limits<int>::max()}
The maximum number of points that a cluster needs to contain in order to be considered valid (default = MAXINT).
unsigned int max_label_ {std::numeric_limits<unsigned int>::max()}
The maximum number of labels we can find in this pointcloud (default = MAXINT)
IndicesPtr indices_
A pointer to the vector of point indices to use.
PointCloudConstPtr input_
The input point cloud dataset.
Protected Attributes inherited from pcl::PCLBase< PointT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointT>
class pcl::LabeledEuclideanClusterExtraction< PointT >
LabeledEuclideanClusterExtraction represents a segmentation class for cluster extraction in an Euclidean sense, with label info.
Author
Koen Buys
Definition at line 75 of file extract_labeled_clusters.h.
Member Typedef Documentation
KdTree
template<typename PointT > using pcl::LabeledEuclideanClusterExtraction< PointT >::KdTree = pcl::search::Search<PointT>
Definition at line 83 of file extract_labeled_clusters.h.
KdTreePtr
template<typename PointT > using pcl::LabeledEuclideanClusterExtraction< PointT >::KdTreePtr = typename KdTree::Ptr
Definition at line 84 of file extract_labeled_clusters.h.
PointCloud
template<typename PointT > using pcl::LabeledEuclideanClusterExtraction< PointT >::PointCloud = pcl::PointCloud<PointT>
Definition at line 79 of file extract_labeled_clusters.h.
PointCloudConstPtr
template<typename PointT > using pcl::LabeledEuclideanClusterExtraction< PointT >::PointCloudConstPtr = typename PointCloud::ConstPtr
Definition at line 81 of file extract_labeled_clusters.h.
PointCloudPtr
template<typename PointT > using pcl::LabeledEuclideanClusterExtraction< PointT >::PointCloudPtr = typename PointCloud::Ptr
Definition at line 80 of file extract_labeled_clusters.h.
PointIndicesConstPtr
template<typename PointT > using pcl::LabeledEuclideanClusterExtraction< PointT >::PointIndicesConstPtr = PointIndices::ConstPtr
Definition at line 87 of file extract_labeled_clusters.h.
PointIndicesPtr
template<typename PointT > using pcl::LabeledEuclideanClusterExtraction< PointT >::PointIndicesPtr = PointIndices::Ptr
Definition at line 86 of file extract_labeled_clusters.h.
Constructor & Destructor Documentation
LabeledEuclideanClusterExtraction()
template<typename PointT > pcl::LabeledEuclideanClusterExtraction< PointT >::LabeledEuclideanClusterExtraction () default
Empty constructor.
Member Function Documentation
deinitCompute()
template<typename PointT > bool pcl::PCLBase< PointT >::deinitCompute protected
This method should get called after finishing the actual computation.
Definition at line 173 of file pcl_base.hpp.
extract()
template<typename PointT > void pcl::LabeledEuclideanClusterExtraction< PointT >::extract (std::vector< std::vector< PointIndices >> & labeled_clusters)
Cluster extraction in a PointCloud given by <setInputCloud (), setIndices ()>
Parameters
[out] labeled_clusters the resultant point clusters
Definition at line 129 of file extract_labeled_clusters.hpp.
References pcl::gpu::comparePointClusters(), and pcl::extractLabeledEuclideanClusters().
getClassName()
template<typename PointT > virtual std::string pcl::LabeledEuclideanClusterExtraction< PointT >::getClassName () const inline protected virtual
Class getName method.
Definition at line 195 of file extract_labeled_clusters.h.
getClusterTolerance()
template<typename PointT > double pcl::LabeledEuclideanClusterExtraction< PointT >::getClusterTolerance () const inline
Get the spatial cluster tolerance as a measure in the L2 Euclidean space.
Definition at line 122 of file extract_labeled_clusters.h.
References pcl::LabeledEuclideanClusterExtraction< PointT >::cluster_tolerance_.
getMaxClusterSize()
template<typename PointT > int pcl::LabeledEuclideanClusterExtraction< PointT >::getMaxClusterSize () const inline
Get the maximum number of points that a cluster needs to contain in order to be considered valid.
Definition at line 156 of file extract_labeled_clusters.h.
References pcl::LabeledEuclideanClusterExtraction< PointT >::max_pts_per_cluster_.
getMinClusterSize()
template<typename PointT > int pcl::LabeledEuclideanClusterExtraction< PointT >::getMinClusterSize () const inline
Get the minimum number of points that a cluster needs to contain in order to be considered valid.
Definition at line 139 of file extract_labeled_clusters.h.
References pcl::LabeledEuclideanClusterExtraction< PointT >::min_pts_per_cluster_.
getSearchMethod()
template<typename PointT > KdTreePtr pcl::LabeledEuclideanClusterExtraction< PointT >::getSearchMethod () const inline
Get a pointer to the search method used.
Definition at line 104 of file extract_labeled_clusters.h.
References pcl::LabeledEuclideanClusterExtraction< PointT >::tree_.
initCompute()
template<typename PointT > bool pcl::PCLBase< PointT >::initCompute protected
This method should get called before starting the actual computation.
Internally, initCompute() does the following:
checks if an input dataset is given, and returns false otherwise
checks whether a set of input indices has been given. Returns true if yes.
if no input indices have been given, a fake set is created, which will be used until:
either a new set is given via setIndices(), or
a new cloud is given that has a different set of points. This will trigger an update on the set of fake indices
Definition at line 168 of file pcl_base.hpp.
setClusterTolerance()
template<typename PointT > void pcl::LabeledEuclideanClusterExtraction< PointT >::setClusterTolerance (double tolerance) inline
Set the spatial cluster tolerance as a measure in the L2 Euclidean space.
Parameters
[in] tolerance the spatial cluster tolerance as a measure in the L2 Euclidean space
Definition at line 114 of file extract_labeled_clusters.h.
References pcl::LabeledEuclideanClusterExtraction< PointT >::cluster_tolerance_.
setMaxClusterSize()
template<typename PointT > void pcl::LabeledEuclideanClusterExtraction< PointT >::setMaxClusterSize (int max_cluster_size) inline
Set the maximum number of points that a cluster needs to contain in order to be considered valid.
Parameters
[in] max_cluster_size the maximum cluster size
Definition at line 148 of file extract_labeled_clusters.h.
References pcl::LabeledEuclideanClusterExtraction< PointT >::max_pts_per_cluster_.
setMinClusterSize()
template<typename PointT > void pcl::LabeledEuclideanClusterExtraction< PointT >::setMinClusterSize (int min_cluster_size) inline
Set the minimum number of points that a cluster needs to contain in order to be considered valid.
Parameters
[in] min_cluster_size the minimum cluster size
Definition at line 131 of file extract_labeled_clusters.h.
References pcl::LabeledEuclideanClusterExtraction< PointT >::min_pts_per_cluster_.
setSearchMethod()
template<typename PointT > void pcl::LabeledEuclideanClusterExtraction< PointT >::setSearchMethod (const KdTreePtr & tree) inline
Provide a pointer to the search object.
Parameters
[in] tree a pointer to the spatial search object.
Definition at line 97 of file extract_labeled_clusters.h.
References pcl::LabeledEuclideanClusterExtraction< PointT >::tree_.
Member Data Documentation
cluster_tolerance_
template<typename PointT > double pcl::LabeledEuclideanClusterExtraction< PointT >::cluster_tolerance_ {0.0} protected
The spatial cluster tolerance as a measure in the L2 Euclidean space.
Definition at line 178 of file extract_labeled_clusters.h.
Referenced by pcl::LabeledEuclideanClusterExtraction< PointT >::getClusterTolerance(), and pcl::LabeledEuclideanClusterExtraction< PointT >::setClusterTolerance().
indices_
template<typename PointT > IndicesPtr pcl::PCLBase< PointT >::indices_ protected
A pointer to the vector of point indices to use.
Definition at line 150 of file pcl_base.h.
input_
template<typename PointT > PointCloudConstPtr pcl::PCLBase< PointT >::input_ protected
The input point cloud dataset.
Definition at line 147 of file pcl_base.h.
max_label_
template<typename PointT > unsigned int pcl::LabeledEuclideanClusterExtraction< PointT >::max_label_ {std::numeric_limits<unsigned int>::max()} protected
The maximum number of labels we can find in this pointcloud (default = MAXINT)
Deprecated:
Scheduled for removal in version 1 . 18 : "this member variable is unused"
Definition at line 191 of file extract_labeled_clusters.h.
max_pts_per_cluster_
template<typename PointT > int pcl::LabeledEuclideanClusterExtraction< PointT >::max_pts_per_cluster_ {std::numeric_limits<int>::max()} protected
The maximum number of points that a cluster needs to contain in order to be considered valid (default = MAXINT).
Definition at line 186 of file extract_labeled_clusters.h.
Referenced by pcl::LabeledEuclideanClusterExtraction< PointT >::getMaxClusterSize(), and pcl::LabeledEuclideanClusterExtraction< PointT >::setMaxClusterSize().
min_pts_per_cluster_
template<typename PointT > int pcl::LabeledEuclideanClusterExtraction< PointT >::min_pts_per_cluster_ {1} protected
The minimum number of points that a cluster needs to contain in order to be considered valid (default = 1).
Definition at line 182 of file extract_labeled_clusters.h.
Referenced by pcl::LabeledEuclideanClusterExtraction< PointT >::getMinClusterSize(), and pcl::LabeledEuclideanClusterExtraction< PointT >::setMinClusterSize().
tree_
template<typename PointT > KdTreePtr pcl::LabeledEuclideanClusterExtraction< PointT >::tree_ {nullptr} protected
A pointer to the spatial search object.
Definition at line 175 of file extract_labeled_clusters.h.
Referenced by pcl::LabeledEuclideanClusterExtraction< PointT >::getSearchMethod(), and pcl::LabeledEuclideanClusterExtraction< PointT >::setSearchMethod().
The documentation for this class was generated from the following files:
pcl/segmentation/extract_labeled_clusters.h
pcl/segmentation/impl/extract_labeled_clusters.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:21