Point Cloud Library (PCL): pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT > Class Template Reference
pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT > Class Template Reference
Module features
UniqueShapeContext implements the Unique Shape Context Descriptor described here:
#include <pcl/features/usc.h>
Public Types
using PointCloudOut = typename Feature< PointInT, PointOutT >::PointCloudOut
using PointCloudIn = typename Feature< PointInT, PointOutT >::PointCloudIn
using Ptr = shared_ptr< UniqueShapeContext< PointInT, PointOutT, PointRFT > >
using ConstPtr = shared_ptr< const UniqueShapeContext< PointInT, PointOutT, PointRFT > >
Public Types inherited from pcl::Feature< PointInT, pcl::UniqueShapeContext1960 >
using BaseClass = PCLBase< PointInT >
using Ptr = shared_ptr< Feature< PointInT, pcl::UniqueShapeContext1960 > >
using ConstPtr = shared_ptr< const Feature< PointInT, pcl::UniqueShapeContext1960 > >
using KdTree = pcl::search::Search< PointInT >
using KdTreePtr = typename KdTree::Ptr
using PointCloudIn = pcl::PointCloud< PointInT >
using PointCloudInPtr = typename PointCloudIn::Ptr
using PointCloudInConstPtr = typename PointCloudIn::ConstPtr
using PointCloudOut = pcl::PointCloud< pcl::UniqueShapeContext1960 >
using SearchMethod = std::function< int(std::size_t, double, pcl::Indices &, std::vector< float > &)>
using SearchMethodSurface = std::function< int(const PointCloudIn &cloud, std::size_t index, double, pcl::Indices &, std::vector< float > &)>
Public Types inherited from pcl::PCLBase< PointInT >
using PointCloud = pcl::PointCloud< PointInT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Types inherited from pcl::FeatureWithLocalReferenceFrames< PointInT, pcl::ReferenceFrame >
using PointCloudLRF = pcl::PointCloud< pcl::ReferenceFrame >
using PointCloudLRFPtr = typename PointCloudLRF::Ptr
using PointCloudLRFConstPtr = typename PointCloudLRF::ConstPtr
Public Member Functions
UniqueShapeContext ()
Constructor.
~UniqueShapeContext () override=default
std::size_t getAzimuthBins () const
std::size_t getElevationBins () const
std::size_t getRadiusBins () const
void setMinimalRadius (double radius)
The minimal radius value for the search sphere (rmin) in the original paper.
double getMinimalRadius () const
void setPointDensityRadius (double radius)
This radius is used to compute local point density density = number of points within this radius.
double getPointDensityRadius () const
void setLocalRadius (double radius)
Set the local RF radius value.
double getLocalRadius () const
Public Member Functions inherited from pcl::Feature< PointInT, pcl::UniqueShapeContext1960 >
Feature ()
Empty constructor.
void setSearchSurface (const PointCloudInConstPtr &cloud)
Provide a pointer to a dataset to add additional information to estimate the features for every point in the input dataset.
PointCloudInConstPtr getSearchSurface () const
Get a pointer to the surface point cloud dataset.
void setSearchMethod (const KdTreePtr &tree)
Provide a pointer to the search object.
KdTreePtr getSearchMethod () const
Get a pointer to the search method used.
double getSearchParameter () const
Get the internal search parameter.
void setKSearch (int k)
Set the number of k nearest neighbors to use for the feature estimation.
int getKSearch () const
get the number of k nearest neighbors used for the feature estimation.
void setRadiusSearch (double radius)
Set the sphere radius that is to be used for determining the nearest neighbors used for the feature estimation.
double getRadiusSearch () const
Get the sphere radius used for determining the neighbors.
void compute (PointCloudOut &output)
Base method for feature estimation for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Public Member Functions inherited from pcl::PCLBase< PointInT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointInT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Public Member Functions inherited from pcl::FeatureWithLocalReferenceFrames< PointInT, pcl::ReferenceFrame >
FeatureWithLocalReferenceFrames ()
Empty constructor.
virtual ~FeatureWithLocalReferenceFrames ()=default
Default virtual destructor.
void setInputReferenceFrames (const PointCloudLRFConstPtr &frames)
Provide a pointer to the input dataset that contains the local reference frames of the XYZ dataset.
PointCloudLRFConstPtr getInputReferenceFrames () const
Get a pointer to the local reference frames.
Protected Member Functions
void computePointDescriptor (std::size_t index, std::vector< float > &desc)
Compute 3D shape context feature descriptor.
bool initCompute () override
Initialize computation by allocating all the intervals and the volume lookup table.
void computeFeature (PointCloudOut &output) override
The actual feature computation.
Protected Member Functions inherited from pcl::Feature< PointInT, pcl::UniqueShapeContext1960 >
const std::string & getClassName () const
Get a string representation of the name of this class.
virtual bool deinitCompute ()
This method should get called after ending the actual computation.
int searchForNeighbors (std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
int searchForNeighbors (const PointCloudIn &cloud, std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
Protected Member Functions inherited from pcl::PCLBase< PointInT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Protected Member Functions inherited from pcl::FeatureWithLocalReferenceFrames< PointInT, pcl::ReferenceFrame >
virtual bool initLocalReferenceFrames (const std::size_t &indices_size, const LRFEstimationPtr &lrf_estimation=LRFEstimationPtr())
Protected Attributes
std::vector< float > radii_interval_
values of the radii interval.
std::vector< float > theta_divisions_
Theta divisions interval.
std::vector< float > phi_divisions_
Phi divisions interval.
std::vector< float > volume_lut_
Volumes look up table.
std::size_t azimuth_bins_ {14}
Bins along the azimuth dimension.
std::size_t elevation_bins_ {14}
Bins along the elevation dimension.
std::size_t radius_bins_ {10}
Bins along the radius dimension.
double min_radius_ {0.1}
Minimal radius value.
double point_density_radius_ {0.1}
Point density radius.
std::size_t descriptor_length_ {}
Descriptor length.
double local_radius_ {2.0}
Radius to compute local RF.
Protected Attributes inherited from pcl::Feature< PointInT, pcl::UniqueShapeContext1960 >
std::string feature_name_
The feature name.
SearchMethodSurface search_method_surface_
The search method template for points.
PointCloudInConstPtr surface_
An input point cloud describing the surface that is to be used for nearest neighbors estimation.
KdTreePtr tree_
A pointer to the spatial search object.
double search_parameter_
The actual search parameter (from either search_radius_ or k_).
double search_radius_
The nearest neighbors search radius for each point.
int k_
The number of K nearest neighbors to use for each point.
bool fake_surface_
If no surface is given, we use the input PointCloud as the surface.
Protected Attributes inherited from pcl::PCLBase< PointInT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Protected Attributes inherited from pcl::FeatureWithLocalReferenceFrames< PointInT, pcl::ReferenceFrame >
PointCloudLRFConstPtr frames_
A boost shared pointer to the local reference frames.
bool frames_never_defined_
The user has never set the frames.
Additional Inherited Members
Protected Types inherited from pcl::FeatureWithLocalReferenceFrames< PointInT, pcl::ReferenceFrame >
using LRFEstimationPtr = typename Feature< PointInT, pcl::ReferenceFrame >::Ptr
Check if frames_ has been correctly initialized and compute it if needed.
Detailed Description
template<typename PointInT, typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame>
class pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >
UniqueShapeContext implements the Unique Shape Context Descriptor described here:
F. Tombari, S. Salti, L. Di Stefano, "Unique Shape Context for 3D data description", International Workshop on 3D Object Retrieval (3DOR 10) - in conjunction with ACM Multimedia 2010
The suggested PointOutT is pcl::UniqueShapeContext1960
Author
Alessandro Franchi, Federico Tombari, Samuele Salti (original code)
Nizar Sallem (port to PCL)
Definition at line 63 of file usc.h.
Member Typedef Documentation
ConstPtr
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> using pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::ConstPtr = shared_ptr<const UniqueShapeContext<PointInT, PointOutT, PointRFT> >
Definition at line 81 of file usc.h.
PointCloudIn
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> using pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::PointCloudIn = typename Feature<PointInT, PointOutT>::PointCloudIn
Definition at line 79 of file usc.h.
PointCloudOut
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> using pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::PointCloudOut = typename Feature<PointInT, PointOutT>::PointCloudOut
Definition at line 78 of file usc.h.
Ptr
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> using pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::Ptr = shared_ptr<UniqueShapeContext<PointInT, PointOutT, PointRFT> >
Definition at line 80 of file usc.h.
Constructor & Destructor Documentation
UniqueShapeContext()
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::UniqueShapeContext () inline
Constructor.
Definition at line 85 of file usc.h.
References pcl::Feature< PointInT, pcl::UniqueShapeContext1960 >::feature_name_, and pcl::Feature< PointInT, pcl::UniqueShapeContext1960 >::search_radius_.
~UniqueShapeContext()
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::~UniqueShapeContext () override default
Member Function Documentation
computeFeature()
template<typename PointInT , typename PointOutT , typename PointRFT > void pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::computeFeature (PointCloudOut & output) override protected
The actual feature computation.
Parameters
[out] output the resultant features
Definition at line 226 of file usc.hpp.
References pcl::isFinite().
computePointDescriptor()
template<typename PointInT , typename PointOutT , typename PointRFT > void pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::computePointDescriptor (std::size_t index, std::vector< float > & desc) protected
Compute 3D shape context feature descriptor.
Parameters
[in] index point index in input_
[out] desc descriptor to compute
Compute the angle between the neighbour and the z axis (normal) in the interval [0, 180]
Compute the Bin(j, k, l) coordinates of current neighbour
Bin (j, k, l)
Local point density = number of points in a sphere of radius "point_density_radius_" around the current neighbour
point_density is always bigger than 0 because FindPointsWithinRadius returns at least the point itself
Accumulate w into correspondent Bin(j,k,l)
Definition at line 146 of file usc.hpp.
References pcl::geometry::distance(), pcl::utils::equal(), pcl::geometry::project(), and pcl::rad2deg().
getAzimuthBins()
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> std::size_t pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::getAzimuthBins () const inline
Returns
The number of bins along the azimuth.
Definition at line 96 of file usc.h.
References pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::azimuth_bins_.
getElevationBins()
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> std::size_t pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::getElevationBins () const inline
Returns
The number of bins along the elevation
Definition at line 100 of file usc.h.
References pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::elevation_bins_.
getLocalRadius()
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> double pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::getLocalRadius () const inline
Returns
The local RF radius.
Definition at line 135 of file usc.h.
References pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::local_radius_.
getMinimalRadius()
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> double pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::getMinimalRadius () const inline
Returns
The minimal sphere radius.
Definition at line 114 of file usc.h.
References pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::min_radius_.
getPointDensityRadius()
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> double pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::getPointDensityRadius () const inline
Returns
The point density search radius.
Definition at line 125 of file usc.h.
References pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::point_density_radius_.
getRadiusBins()
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> std::size_t pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::getRadiusBins () const inline
Returns
The number of bins along the radii direction.
Definition at line 104 of file usc.h.
References pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::radius_bins_.
initCompute()
template<typename PointInT , typename PointOutT , typename PointRFT > bool pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::initCompute override protected virtual
Initialize computation by allocating all the intervals and the volume lookup table.
Reimplemented from pcl::Feature< PointInT, pcl::UniqueShapeContext1960 >.
Definition at line 54 of file usc.hpp.
References pcl::deg2rad(), pcl::PCLBase< PointT >::setIndices(), pcl::PCLBase< PointT >::setInputCloud(), pcl::Feature< PointInT, PointOutT >::setRadiusSearch(), and pcl::Feature< PointInT, PointOutT >::setSearchSurface().
setLocalRadius()
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> void pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::setLocalRadius (double radius) inline
Set the local RF radius value.
Parameters
[in] radius the desired local RF radius
Definition at line 131 of file usc.h.
References pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::local_radius_.
setMinimalRadius()
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> void pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::setMinimalRadius (double radius) inline
The minimal radius value for the search sphere (rmin) in the original paper.
Parameters
[in] radius the desired minimal radius
Definition at line 110 of file usc.h.
References pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::min_radius_.
setPointDensityRadius()
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> void pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::setPointDensityRadius (double radius) inline
This radius is used to compute local point density density = number of points within this radius.
Parameters
[in] radius Value of the point density search radius
Definition at line 121 of file usc.h.
References pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::point_density_radius_.
Member Data Documentation
azimuth_bins_
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> std::size_t pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::azimuth_bins_ {14} protected
Bins along the azimuth dimension.
Definition at line 168 of file usc.h.
Referenced by pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::getAzimuthBins().
descriptor_length_
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> std::size_t pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::descriptor_length_ {} protected
Descriptor length.
Definition at line 183 of file usc.h.
elevation_bins_
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> std::size_t pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::elevation_bins_ {14} protected
Bins along the elevation dimension.
Definition at line 171 of file usc.h.
Referenced by pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::getElevationBins().
local_radius_
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> double pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::local_radius_ {2.0} protected
Radius to compute local RF.
Definition at line 186 of file usc.h.
Referenced by pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::getLocalRadius(), and pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::setLocalRadius().
min_radius_
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> double pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::min_radius_ {0.1} protected
Minimal radius value.
Definition at line 177 of file usc.h.
Referenced by pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::getMinimalRadius(), and pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::setMinimalRadius().
phi_divisions_
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> std::vector<float> pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::phi_divisions_ protected
Phi divisions interval.
Definition at line 162 of file usc.h.
point_density_radius_
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> double pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::point_density_radius_ {0.1} protected
Point density radius.
Definition at line 180 of file usc.h.
Referenced by pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::getPointDensityRadius(), and pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::setPointDensityRadius().
radii_interval_
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> std::vector<float> pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::radii_interval_ protected
values of the radii interval.
Definition at line 156 of file usc.h.
radius_bins_
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> std::size_t pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::radius_bins_ {10} protected
Bins along the radius dimension.
Definition at line 174 of file usc.h.
Referenced by pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::getRadiusBins().
theta_divisions_
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> std::vector<float> pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::theta_divisions_ protected
Theta divisions interval.
Definition at line 159 of file usc.h.
volume_lut_
template<typename PointInT , typename PointOutT = pcl::UniqueShapeContext1960, typename PointRFT = pcl::ReferenceFrame> std::vector<float> pcl::UniqueShapeContext< PointInT, PointOutT, PointRFT >::volume_lut_ protected
Volumes look up table.
Definition at line 165 of file usc.h.
The documentation for this class was generated from the following files:
pcl/features/usc.h
pcl/features/impl/usc.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:12