Point Cloud Library (PCL): pcl::SampleConsensusModelCone< PointT, PointNT > Class Template Reference
pcl::SampleConsensusModelCone< PointT, PointNT > Class Template Reference
Module sample_consensus
SampleConsensusModelCone defines a model for 3D cone segmentation.
#include <pcl/sample_consensus/sac_model_cone.h>
Public Types
using PointCloud = typename SampleConsensusModel< PointT >::PointCloud
using PointCloudPtr = typename SampleConsensusModel< PointT >::PointCloudPtr
using PointCloudConstPtr = typename SampleConsensusModel< PointT >::PointCloudConstPtr
using Ptr = shared_ptr< SampleConsensusModelCone< PointT, PointNT > >
using ConstPtr = shared_ptr< const SampleConsensusModelCone< PointT, PointNT > >
Public Types inherited from pcl::SampleConsensusModel< PointT >
using PointCloud = pcl::PointCloud< PointT >
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointCloudPtr = typename PointCloud::Ptr
using SearchPtr = typename pcl::search::Search< PointT >::Ptr
using Ptr = shared_ptr< SampleConsensusModel< PointT > >
using ConstPtr = shared_ptr< const SampleConsensusModel< PointT > >
Public Types inherited from pcl::SampleConsensusModelFromNormals< PointT, PointNT >
using PointCloudNConstPtr = typename pcl::PointCloud< PointNT >::ConstPtr
using PointCloudNPtr = typename pcl::PointCloud< PointNT >::Ptr
using Ptr = shared_ptr< SampleConsensusModelFromNormals< PointT, PointNT > >
using ConstPtr = shared_ptr< const SampleConsensusModelFromNormals< PointT, PointNT > >
Public Member Functions
SampleConsensusModelCone (const PointCloudConstPtr &cloud, bool random=false)
Constructor for base SampleConsensusModelCone.
SampleConsensusModelCone (const PointCloudConstPtr &cloud, const Indices &indices, bool random=false)
Constructor for base SampleConsensusModelCone.
SampleConsensusModelCone (const SampleConsensusModelCone &source)
Copy constructor.
~SampleConsensusModelCone () override=default
Empty destructor.
SampleConsensusModelCone & operator= (const SampleConsensusModelCone &source)
Copy constructor.
void setEpsAngle (double ea)
Set the angle epsilon (delta) threshold.
double getEpsAngle () const
Get the angle epsilon (delta) threshold.
void setAxis (const Eigen::Vector3f &ax)
Set the axis along which we need to search for a cone direction.
Eigen::Vector3f getAxis () const
Get the axis along which we need to search for a cone direction.
void setMinMaxOpeningAngle (const double &min_angle, const double &max_angle)
Set the minimum and maximum allowable opening angle for a cone model given from a user.
void getMinMaxOpeningAngle (double &min_angle, double &max_angle) const
Get the opening angle which we need minimum to validate a cone model.
bool computeModelCoefficients (const Indices &samples, Eigen::VectorXf &model_coefficients) const override
Check whether the given index samples can form a valid cone model, compute the model coefficients from these samples and store them in model_coefficients.
void getDistancesToModel (const Eigen::VectorXf &model_coefficients, std::vector< double > &distances) const override
Compute all distances from the cloud data to a given cone model.
void selectWithinDistance (const Eigen::VectorXf &model_coefficients, const double threshold, Indices &inliers) override
Select all the points which respect the given model coefficients as inliers.
std::size_t countWithinDistance (const Eigen::VectorXf &model_coefficients, const double threshold) const override
Count all the points which respect the given model coefficients as inliers.
void optimizeModelCoefficients (const Indices &inliers, const Eigen::VectorXf &model_coefficients, Eigen::VectorXf &optimized_coefficients) const override
Recompute the cone coefficients using the given inlier set and return them to the user.
void projectPoints (const Indices &inliers, const Eigen::VectorXf &model_coefficients, PointCloud &projected_points, bool copy_data_fields=true) const override
Create a new point cloud with inliers projected onto the cone model.
bool doSamplesVerifyModel (const std::set< index_t > &indices, const Eigen::VectorXf &model_coefficients, const double threshold) const override
Verify whether a subset of indices verifies the given cone model coefficients.
pcl::SacModel getModelType () const override
Return a unique id for this model (SACMODEL_CONE).
Public Member Functions inherited from pcl::SampleConsensusModel< PointT >
SampleConsensusModel (const PointCloudConstPtr &cloud, bool random=false)
Constructor for base SampleConsensusModel.
SampleConsensusModel (const PointCloudConstPtr &cloud, const Indices &indices, bool random=false)
Constructor for base SampleConsensusModel.
virtual ~SampleConsensusModel ()=default
Destructor for base SampleConsensusModel.
virtual void getSamples (int &iterations, Indices &samples)
Get a set of random data samples and return them as point indices.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr getInputCloud () const
Get a pointer to the input point cloud dataset.
void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
void setIndices (const Indices &indices)
Provide the vector of indices that represents the input data.
IndicesPtr getIndices () const
Get a pointer to the vector of indices used.
const std::string & getClassName () const
Get a string representation of the name of this class.
unsigned int getSampleSize () const
Return the size of a sample from which the model is computed.
unsigned int getModelSize () const
Return the number of coefficients in the model.
void setRadiusLimits (const double &min_radius, const double &max_radius)
Set the minimum and maximum allowable radius limits for the model (applicable to models that estimate a radius)
void getRadiusLimits (double &min_radius, double &max_radius) const
Get the minimum and maximum allowable radius limits for the model as set by the user.
void setModelConstraints (std::function< bool(const Eigen::VectorXf &)> function)
This can be used to impose any kind of constraint on the model, e.g.
void setSamplesMaxDist (const double &radius, SearchPtr search)
Set the maximum distance allowed when drawing random samples.
void getSamplesMaxDist (double &radius) const
Get maximum distance allowed when drawing random samples.
double computeVariance (const std::vector< double > &error_sqr_dists) const
Compute the variance of the errors to the model.
double computeVariance () const
Compute the variance of the errors to the model from the internally estimated vector of distances.
Public Member Functions inherited from pcl::SampleConsensusModelFromNormals< PointT, PointNT >
SampleConsensusModelFromNormals ()
Empty constructor for base SampleConsensusModelFromNormals.
virtual ~SampleConsensusModelFromNormals ()=default
Destructor.
void setNormalDistanceWeight (const double w)
Set the normal angular distance weight.
double getNormalDistanceWeight () const
Get the normal angular distance weight.
void setInputNormals (const PointCloudNConstPtr &normals)
Provide a pointer to the input dataset that contains the point normals of the XYZ dataset.
PointCloudNConstPtr getInputNormals () const
Get a pointer to the normals of the input XYZ point cloud dataset.
Protected Member Functions
double pointToAxisDistance (const Eigen::Vector4f &pt, const Eigen::VectorXf &model_coefficients) const
Get the distance from a point to a line (represented by a point and a direction)
bool isModelValid (const Eigen::VectorXf &model_coefficients) const override
Check whether a model is valid given the user constraints.
bool isSampleGood (const Indices &samples) const override
Check if a sample of indices results in a good sample of points indices.
Protected Member Functions inherited from pcl::SampleConsensusModel< PointT >
SampleConsensusModel (bool random=false)
Empty constructor for base SampleConsensusModel.
void drawIndexSample (Indices &sample)
Fills a sample array with random samples from the indices_ vector.
void drawIndexSampleRadius (Indices &sample)
Fills a sample array with one random sample from the indices_ vector and other random samples that are closer than samples_radius_.
int rnd ()
Boost-based random number generator.
Additional Inherited Members
Protected Attributes inherited from pcl::SampleConsensusModel< PointT >
std::string model_name_
The model name.
PointCloudConstPtr input_
A boost shared pointer to the point cloud data array.
IndicesPtr indices_
A pointer to the vector of point indices to use.
double radius_min_
The minimum and maximum radius limits for the model.
double radius_max_
double samples_radius_
The maximum distance of subsequent samples from the first (radius search)
SearchPtr samples_radius_search_
The search object for picking subsequent samples using radius search.
Indices shuffled_indices_
Data containing a shuffled version of the indices.
boost::mt19937 rng_alg_
Boost-based random number generator algorithm.
std::shared_ptr< boost::uniform_int<> > rng_dist_
Boost-based random number generator distribution.
std::shared_ptr< boost::variate_generator< boost::mt19937 &, boost::uniform_int<> > > rng_gen_
Boost-based random number generator.
std::vector< double > error_sqr_dists_
A vector holding the distances to the computed model.
unsigned int sample_size_
The size of a sample from which the model is computed.
unsigned int model_size_
The number of coefficients in the model.
std::function< bool(const Eigen::VectorXf &)> custom_model_constraints_
A user defined function that takes model coefficients and returns whether the model is acceptable or not.
Protected Attributes inherited from pcl::SampleConsensusModelFromNormals< PointT, PointNT >
double normal_distance_weight_ {0.0}
The relative weight (between 0 and 1) to give to the angular distance (0 to pi/2) between point normals and the plane normal.
PointCloudNConstPtr normals_
A pointer to the input dataset that contains the point normals of the XYZ dataset.
Static Protected Attributes inherited from pcl::SampleConsensusModel< PointT >
static const unsigned int max_sample_checks_ = 1000
The maximum number of samples to try until we get a good one.
Detailed Description
template<typename PointT, typename PointNT>
class pcl::SampleConsensusModelCone< PointT, PointNT >
SampleConsensusModelCone defines a model for 3D cone segmentation.
The model coefficients are defined as:
apex.x : the X coordinate of cone's apex
apex.y : the Y coordinate of cone's apex
apex.z : the Z coordinate of cone's apex
axis_direction.x : the X coordinate of the cone's axis direction
axis_direction.y : the Y coordinate of the cone's axis direction
axis_direction.z : the Z coordinate of the cone's axis direction
opening_angle : the cone's opening angle
Author
Stefan Schrandt
Definition at line 67 of file sac_model_cone.h.
Member Typedef Documentation
ConstPtr
template<typename PointT , typename PointNT > using pcl::SampleConsensusModelCone< PointT, PointNT >::ConstPtr = shared_ptr<const SampleConsensusModelCone<PointT, PointNT> >
Definition at line 84 of file sac_model_cone.h.
PointCloud
template<typename PointT , typename PointNT > using pcl::SampleConsensusModelCone< PointT, PointNT >::PointCloud = typename SampleConsensusModel<PointT>::PointCloud
Definition at line 79 of file sac_model_cone.h.
PointCloudConstPtr
template<typename PointT , typename PointNT > using pcl::SampleConsensusModelCone< PointT, PointNT >::PointCloudConstPtr = typename SampleConsensusModel<PointT>::PointCloudConstPtr
Definition at line 81 of file sac_model_cone.h.
PointCloudPtr
template<typename PointT , typename PointNT > using pcl::SampleConsensusModelCone< PointT, PointNT >::PointCloudPtr = typename SampleConsensusModel<PointT>::PointCloudPtr
Definition at line 80 of file sac_model_cone.h.
Ptr
template<typename PointT , typename PointNT > using pcl::SampleConsensusModelCone< PointT, PointNT >::Ptr = shared_ptr<SampleConsensusModelCone<PointT, PointNT> >
Definition at line 83 of file sac_model_cone.h.
Constructor & Destructor Documentation
SampleConsensusModelCone() [1/3]
template<typename PointT , typename PointNT > pcl::SampleConsensusModelCone< PointT, PointNT >::SampleConsensusModelCone (const PointCloudConstPtr & cloud, bool random = false) inline
Constructor for base SampleConsensusModelCone.
Parameters
[in] cloud the input point cloud dataset
[in] random if true set the random seed to the current time, else set to 12345 (default: false)
Definition at line 90 of file sac_model_cone.h.
References pcl::SampleConsensusModel< PointT >::model_name_, pcl::SampleConsensusModel< PointT >::model_size_, and pcl::SampleConsensusModel< PointT >::sample_size_.
SampleConsensusModelCone() [2/3]
template<typename PointT , typename PointNT > pcl::SampleConsensusModelCone< PointT, PointNT >::SampleConsensusModelCone (const PointCloudConstPtr & cloud, const Indices & indices, bool random = false) inline
Constructor for base SampleConsensusModelCone.
Parameters
[in] cloud the input point cloud dataset
[in] indices a vector of point indices to be used from cloud
[in] random if true set the random seed to the current time, else set to 12345 (default: false)
Definition at line 108 of file sac_model_cone.h.
References pcl::SampleConsensusModel< PointT >::model_name_, pcl::SampleConsensusModel< PointT >::model_size_, and pcl::SampleConsensusModel< PointT >::sample_size_.
SampleConsensusModelCone() [3/3]
template<typename PointT , typename PointNT > pcl::SampleConsensusModelCone< PointT, PointNT >::SampleConsensusModelCone (const SampleConsensusModelCone< PointT, PointNT > & source) inline
Copy constructor.
Parameters
[in] source the model to copy into this
Definition at line 126 of file sac_model_cone.h.
References pcl::SampleConsensusModel< PointT >::model_name_.
~SampleConsensusModelCone()
template<typename PointT , typename PointNT > pcl::SampleConsensusModelCone< PointT, PointNT >::~SampleConsensusModelCone () override default
Empty destructor.
Member Function Documentation
computeModelCoefficients()
template<typename PointT , typename PointNT > bool pcl::SampleConsensusModelCone< PointT, PointNT >::computeModelCoefficients (const Indices & samples, Eigen::VectorXf & model_coefficients) const override virtual
Check whether the given index samples can form a valid cone model, compute the model coefficients from these samples and store them in model_coefficients.
The cone coefficients are: apex, axis_direction, opening_angle.
Parameters
[in] samples the point indices found as possible good candidates for creating a valid model
[out] model_coefficients the resultant model coefficients
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 60 of file sac_model_cone.hpp.
countWithinDistance()
template<typename PointT , typename PointNT > std::size_t pcl::SampleConsensusModelCone< PointT, PointNT >::countWithinDistance (const Eigen::VectorXf & model_coefficients, const double threshold) const override virtual
Count all the points which respect the given model coefficients as inliers.
Parameters
[in] model_coefficients the coefficients of a model that we need to compute distances to
[in] threshold maximum admissible distance threshold for determining the inliers from the outliers
Returns
the resultant number of inliers
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 274 of file sac_model_cone.hpp.
References pcl::getAngle3D(), and M_PI.
doSamplesVerifyModel()
template<typename PointT , typename PointNT > bool pcl::SampleConsensusModelCone< PointT, PointNT >::doSamplesVerifyModel (const std::set< index_t > & indices, const Eigen::VectorXf & model_coefficients, const double threshold) const override virtual
Verify whether a subset of indices verifies the given cone model coefficients.
Parameters
[in] indices the data indices that need to be tested against the cone model
[in] model_coefficients the cone model coefficients
[in] threshold a maximum admissible distance threshold for determining the inliers from the outliers
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 472 of file sac_model_cone.hpp.
getAxis()
template<typename PointT , typename PointNT > Eigen::Vector3f pcl::SampleConsensusModelCone< PointT, PointNT >::getAxis () const inline
Get the axis along which we need to search for a cone direction.
Definition at line 171 of file sac_model_cone.h.
Referenced by pcl::SACSegmentationFromNormals< PointT, PointNT >::initSACModel().
getDistancesToModel()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelCone< PointT, PointNT >::getDistancesToModel (const Eigen::VectorXf & model_coefficients, std::vector< double > & distances) const override virtual
Compute all distances from the cloud data to a given cone model.
Parameters
[in] model_coefficients the coefficients of a cone model that we need to compute distances to
[out] distances the resultant estimated distances
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 150 of file sac_model_cone.hpp.
References pcl::getAngle3D(), and M_PI.
getEpsAngle()
template<typename PointT , typename PointNT > double pcl::SampleConsensusModelCone< PointT, PointNT >::getEpsAngle () const inline
Get the angle epsilon (delta) threshold.
Definition at line 161 of file sac_model_cone.h.
Referenced by pcl::SACSegmentationFromNormals< PointT, PointNT >::initSACModel().
getMinMaxOpeningAngle()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelCone< PointT, PointNT >::getMinMaxOpeningAngle (double & min_angle, double & max_angle) const inline
Get the opening angle which we need minimum to validate a cone model.
Parameters
[out] min_angle the minimum allowable opening angle of a cone model
[out] max_angle the maximum allowable opening angle of a cone model
Definition at line 190 of file sac_model_cone.h.
Referenced by pcl::SACSegmentationFromNormals< PointT, PointNT >::initSACModel().
getModelType()
template<typename PointT , typename PointNT > pcl::SacModel pcl::SampleConsensusModelCone< PointT, PointNT >::getModelType () const inline override virtual
Return a unique id for this model (SACMODEL_CONE).
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 271 of file sac_model_cone.h.
References pcl::SACMODEL_CONE.
isModelValid()
template<typename PointT , typename PointNT > bool pcl::SampleConsensusModelCone< PointT, PointNT >::isModelValid (const Eigen::VectorXf & model_coefficients) const override protected virtual
Check whether a model is valid given the user constraints.
Parameters
[in] model_coefficients the set of model coefficients
Reimplemented from pcl::SampleConsensusModel< PointT >.
Definition at line 525 of file sac_model_cone.hpp.
References pcl::getAngle3D(), and M_PI.
isSampleGood()
template<typename PointT , typename PointNT > bool pcl::SampleConsensusModelCone< PointT, PointNT >::isSampleGood (const Indices & samples) const override protected virtual
Check if a sample of indices results in a good sample of points indices.
Pure virtual.
Parameters
[in] samples the resultant index samples
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 48 of file sac_model_cone.hpp.
operator=()
template<typename PointT , typename PointNT > SampleConsensusModelCone& pcl::SampleConsensusModelCone< PointT, PointNT >::operator= (const SampleConsensusModelCone< PointT, PointNT > & source) inline
Copy constructor.
Parameters
[in] source the model to copy into this
Definition at line 142 of file sac_model_cone.h.
optimizeModelCoefficients()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelCone< PointT, PointNT >::optimizeModelCoefficients (const Indices & inliers, const Eigen::VectorXf & model_coefficients, Eigen::VectorXf & optimized_coefficients) const override virtual
Recompute the cone coefficients using the given inlier set and return them to the user.
Note
: these are the coefficients of the cone model after refinement (e.g. after SVD)
Parameters
[in] inliers the data inliers found as supporting the model
[in] model_coefficients the initial guess for the optimization
[out] optimized_coefficients the resultant recomputed coefficients after non-linear optimization
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 332 of file sac_model_cone.hpp.
References pcl::internal::optimizeModelCoefficientsCone().
pointToAxisDistance()
template<typename PointT , typename PointNT > double pcl::SampleConsensusModelCone< PointT, PointNT >::pointToAxisDistance (const Eigen::Vector4f & pt, const Eigen::VectorXf & model_coefficients) const protected
Get the distance from a point to a line (represented by a point and a direction)
Parameters
[in] pt a point
[in] model_coefficients the line coefficients (a point on the line, line direction)
Definition at line 515 of file sac_model_cone.hpp.
References pcl::sqrPointToLineDistance().
projectPoints()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelCone< PointT, PointNT >::projectPoints (const Indices & inliers, const Eigen::VectorXf & model_coefficients, PointCloud & projected_points, bool copy_data_fields = true) const override virtual
Create a new point cloud with inliers projected onto the cone model.
Parameters
[in] inliers the data inliers that we want to project on the cone model
[in] model_coefficients the coefficients of a cone model
[out] projected_points the resultant projected points
[in] copy_data_fields set to true if we need to copy the other data fields
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 376 of file sac_model_cone.hpp.
References pcl::PointCloud< PointT >::header, pcl::PointCloud< PointT >::height, pcl::PointCloud< PointT >::is_dense, pcl::PointCloud< PointT >::resize(), pcl::PointCloud< PointT >::size(), and pcl::PointCloud< PointT >::width.
selectWithinDistance()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelCone< PointT, PointNT >::selectWithinDistance (const Eigen::VectorXf & model_coefficients, const double threshold, Indices & inliers) override virtual
Select all the points which respect the given model coefficients as inliers.
Parameters
[in] model_coefficients the coefficients of a cone model that we need to compute distances to
[in] threshold a maximum admissible distance threshold for determining the inliers from the outliers
[out] inliers the resultant model inliers
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 206 of file sac_model_cone.hpp.
References pcl::geometry::distance(), pcl::getAngle3D(), and M_PI.
setAxis()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelCone< PointT, PointNT >::setAxis (const Eigen::Vector3f & ax) inline
Set the axis along which we need to search for a cone direction.
Parameters
[in] ax the axis along which we need to search for a cone direction
Definition at line 167 of file sac_model_cone.h.
Referenced by pcl::SACSegmentationFromNormals< PointT, PointNT >::initSACModel().
setEpsAngle()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelCone< PointT, PointNT >::setEpsAngle (double ea) inline
Set the angle epsilon (delta) threshold.
Parameters
[in] ea the maximum allowed difference between the cone's axis and the given axis.
Definition at line 157 of file sac_model_cone.h.
Referenced by pcl::SACSegmentationFromNormals< PointT, PointNT >::initSACModel().
setMinMaxOpeningAngle()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelCone< PointT, PointNT >::setMinMaxOpeningAngle (const double & min_angle, const double & max_angle) inline
Set the minimum and maximum allowable opening angle for a cone model given from a user.
Parameters
[in] min_angle the minimum allowable opening angle of a cone model
[in] max_angle the maximum allowable opening angle of a cone model
Definition at line 179 of file sac_model_cone.h.
Referenced by pcl::SACSegmentationFromNormals< PointT, PointNT >::initSACModel().
The documentation for this class was generated from the following files:
pcl/sample_consensus/sac_model_cone.h
pcl/sample_consensus/impl/sac_model_cone.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:20