Point Cloud Library (PCL): pcl::SHOTColorEstimationOMP< PointInT, PointNT, PointOutT, PointRFT > Class Template Reference
pcl::SHOTColorEstimationOMP< PointInT, PointNT, PointOutT, PointRFT > Class Template Reference
Module features
SHOTColorEstimationOMP estimates the Signature of Histograms of OrienTations (SHOT) descriptor for a given point cloud dataset containing points, normals and colors, in parallel, using the OpenMP standard.
#include <pcl/features/shot_omp.h>
Public Types
using Ptr = shared_ptr< SHOTColorEstimationOMP< PointInT, PointNT, PointOutT, PointRFT > >
using ConstPtr = shared_ptr< const SHOTColorEstimationOMP< PointInT, PointNT, PointOutT, PointRFT > >
using PointCloudOut = typename Feature< PointInT, PointOutT >::PointCloudOut
using PointCloudIn = typename Feature< PointInT, PointOutT >::PointCloudIn
Public Types inherited from pcl::SHOTColorEstimation< PointInT, PointNT, pcl::SHOT1344, pcl::ReferenceFrame >
using Ptr = shared_ptr< SHOTColorEstimation< PointInT, PointNT, pcl::SHOT1344, pcl::ReferenceFrame > >
using ConstPtr = shared_ptr< const SHOTColorEstimation< PointInT, PointNT, pcl::SHOT1344, pcl::ReferenceFrame > >
using PointCloudIn = typename Feature< PointInT, pcl::SHOT1344 >::PointCloudIn
Public Types inherited from pcl::SHOTEstimationBase< PointInT, PointNT, pcl::SHOT1344, pcl::ReferenceFrame >
using Ptr = shared_ptr< SHOTEstimationBase< PointInT, PointNT, pcl::SHOT1344, pcl::ReferenceFrame > >
using ConstPtr = shared_ptr< const SHOTEstimationBase< PointInT, PointNT, pcl::SHOT1344, pcl::ReferenceFrame > >
using PointCloudIn = typename Feature< PointInT, pcl::SHOT1344 >::PointCloudIn
Public Types inherited from pcl::FeatureFromNormals< PointInT, PointNT, pcl::SHOT1344 >
using PointCloudN = pcl::PointCloud< PointNT >
using PointCloudNPtr = typename PointCloudN::Ptr
using PointCloudNConstPtr = typename PointCloudN::ConstPtr
using Ptr = shared_ptr< FeatureFromNormals< PointInT, PointNT, pcl::SHOT1344 > >
using ConstPtr = shared_ptr< const FeatureFromNormals< PointInT, PointNT, pcl::SHOT1344 > >
Public Types inherited from pcl::Feature< PointInT, pcl::SHOT1344 >
using BaseClass = PCLBase< PointInT >
using Ptr = shared_ptr< Feature< PointInT, pcl::SHOT1344 > >
using ConstPtr = shared_ptr< const Feature< PointInT, pcl::SHOT1344 > >
using KdTree = pcl::search::Search< PointInT >
using KdTreePtr = typename KdTree::Ptr
using PointCloudIn = pcl::PointCloud< PointInT >
using PointCloudInPtr = typename PointCloudIn::Ptr
using PointCloudInConstPtr = typename PointCloudIn::ConstPtr
using PointCloudOut = pcl::PointCloud< pcl::SHOT1344 >
using SearchMethod = std::function< int(std::size_t, double, std::vector< int > &, std::vector< float > &)>
using SearchMethodSurface = std::function< int(const PointCloudIn &cloud, std::size_t index, double, std::vector< int > &, std::vector< float > &)>
Public Types inherited from pcl::PCLBase< PointInT >
using PointCloud = pcl::PointCloud< PointInT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Types inherited from pcl::FeatureWithLocalReferenceFrames< PointInT, pcl::ReferenceFrame >
using PointCloudLRF = pcl::PointCloud< pcl::ReferenceFrame >
using PointCloudLRFPtr = typename PointCloudLRF::Ptr
using PointCloudLRFConstPtr = typename PointCloudLRF::ConstPtr
Public Member Functions
SHOTColorEstimationOMP (bool describe_shape=true, bool describe_color=true, unsigned int nr_threads=0)
Empty constructor.
void setNumberOfThreads (unsigned int nr_threads=0)
Initialize the scheduler and set the number of threads to use.
Public Member Functions inherited from pcl::SHOTColorEstimation< PointInT, PointNT, pcl::SHOT1344, pcl::ReferenceFrame >
SHOTColorEstimation (bool describe_shape=true, bool describe_color=true)
Empty constructor.
~SHOTColorEstimation ()
Empty destructor.
void computePointSHOT (const int index, const std::vector< int > &indices, const std::vector< float > &sqr_dists, Eigen::VectorXf &shot) override
Estimate the SHOT descriptor for a given point based on its spatial neighborhood of 3D points with normals.
Public Member Functions inherited from pcl::SHOTEstimationBase< PointInT, PointNT, pcl::SHOT1344, pcl::ReferenceFrame >
~SHOTEstimationBase ()
Empty destructor.
virtual void setLRFRadius (float radius)
Set the radius used for local reference frame estimation if the frames are not set by the user.
virtual float getLRFRadius () const
Get the radius used for local reference frame estimation.
Public Member Functions inherited from pcl::FeatureFromNormals< PointInT, PointNT, pcl::SHOT1344 >
FeatureFromNormals ()
Empty constructor.
virtual ~FeatureFromNormals ()
Empty destructor.
void setInputNormals (const PointCloudNConstPtr &normals)
Provide a pointer to the input dataset that contains the point normals of the XYZ dataset.
PointCloudNConstPtr getInputNormals () const
Get a pointer to the normals of the input XYZ point cloud dataset.
Public Member Functions inherited from pcl::Feature< PointInT, pcl::SHOT1344 >
Feature ()
Empty constructor.
virtual ~Feature ()
Empty destructor.
void setSearchSurface (const PointCloudInConstPtr &cloud)
Provide a pointer to a dataset to add additional information to estimate the features for every point in the input dataset.
PointCloudInConstPtr getSearchSurface () const
Get a pointer to the surface point cloud dataset.
void setSearchMethod (const KdTreePtr &tree)
Provide a pointer to the search object.
KdTreePtr getSearchMethod () const
Get a pointer to the search method used.
double getSearchParameter () const
Get the internal search parameter.
void setKSearch (int k)
Set the number of k nearest neighbors to use for the feature estimation.
int getKSearch () const
get the number of k nearest neighbors used for the feature estimation.
void setRadiusSearch (double radius)
Set the sphere radius that is to be used for determining the nearest neighbors used for the feature estimation.
double getRadiusSearch () const
Get the sphere radius used for determining the neighbors.
void compute (PointCloudOut &output)
Base method for feature estimation for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Public Member Functions inherited from pcl::PCLBase< PointInT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
const PointCloudConstPtr getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
const IndicesConstPtr getIndices () const
Get a pointer to the vector of indices used.
const PointInT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Public Member Functions inherited from pcl::FeatureWithLocalReferenceFrames< PointInT, pcl::ReferenceFrame >
FeatureWithLocalReferenceFrames ()
Empty constructor.
virtual ~FeatureWithLocalReferenceFrames ()
Empty destructor.
void setInputReferenceFrames (const PointCloudLRFConstPtr &frames)
Provide a pointer to the input dataset that contains the local reference frames of the XYZ dataset.
PointCloudLRFConstPtr getInputReferenceFrames () const
Get a pointer to the local reference frames.
Protected Member Functions
void computeFeature (PointCloudOut &output) override
Estimate the Signatures of Histograms of OrienTations (SHOT) descriptors at a set of points given by <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
bool initCompute () override
This method should get called before starting the actual computation.
Protected Member Functions inherited from pcl::SHOTColorEstimation< PointInT, PointNT, pcl::SHOT1344, pcl::ReferenceFrame >
void computeFeature (pcl::PointCloud< pcl::SHOT1344 > &output) override
Estimate the Signatures of Histograms of OrienTations (SHOT) descriptors at a set of points given by <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
void interpolateDoubleChannel (const std::vector< int > &indices, const std::vector< float > &sqr_dists, const int index, std::vector< double > &binDistanceShape, std::vector< double > &binDistanceColor, const int nr_bins_shape, const int nr_bins_color, Eigen::VectorXf &shot)
Quadrilinear interpolation; used when color and shape descriptions are both activated.
Protected Member Functions inherited from pcl::SHOTEstimationBase< PointInT, PointNT, pcl::SHOT1344, pcl::ReferenceFrame >
SHOTEstimationBase (int nr_shape_bins=10)
Empty constructor.
bool initCompute () override
This method should get called before starting the actual computation.
void interpolateSingleChannel (const std::vector< int > &indices, const std::vector< float > &sqr_dists, const int index, std::vector< double > &binDistance, const int nr_bins, Eigen::VectorXf &shot)
Quadrilinear interpolation used when color and shape descriptions are NOT activated simultaneously.
void normalizeHistogram (Eigen::VectorXf &shot, int desc_length)
Normalize the SHOT histogram.
void createBinDistanceShape (int index, const std::vector< int > &indices, std::vector< double > &bin_distance_shape)
Create a binned distance shape histogram.
Protected Member Functions inherited from pcl::Feature< PointInT, pcl::SHOT1344 >
const std::string & getClassName () const
Get a string representation of the name of this class.
virtual bool deinitCompute ()
This method should get called after ending the actual computation.
int searchForNeighbors (std::size_t index, double parameter, std::vector< int > &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
int searchForNeighbors (const PointCloudIn &cloud, std::size_t index, double parameter, std::vector< int > &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
Protected Member Functions inherited from pcl::PCLBase< PointInT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Protected Member Functions inherited from pcl::FeatureWithLocalReferenceFrames< PointInT, pcl::ReferenceFrame >
virtual bool initLocalReferenceFrames (const std::size_t &indices_size, const LRFEstimationPtr &lrf_estimation=LRFEstimationPtr())
Protected Attributes
unsigned int threads_
The number of threads the scheduler should use.
Protected Attributes inherited from pcl::SHOTColorEstimation< PointInT, PointNT, pcl::SHOT1344, pcl::ReferenceFrame >
bool b_describe_shape_
Compute shape descriptor.
bool b_describe_color_
Compute color descriptor.
int nr_color_bins_
The number of bins in each color histogram.
Protected Attributes inherited from pcl::SHOTEstimationBase< PointInT, PointNT, pcl::SHOT1344, pcl::ReferenceFrame >
int nr_shape_bins_
The number of bins in each shape histogram.
Eigen::VectorXf shot_
Placeholder for a point's SHOT.
float lrf_radius_
The radius used for the LRF computation.
double sqradius_
The squared search radius.
double radius3_4_
3/4 of the search radius.
double radius1_4_
1/4 of the search radius.
double radius1_2_
1/2 of the search radius.
const int nr_grid_sector_
Number of azimuthal sectors.
const int maxAngularSectors_
...
int descLength_
One SHOT length.
Protected Attributes inherited from pcl::FeatureFromNormals< PointInT, PointNT, pcl::SHOT1344 >
PointCloudNConstPtr normals_
A pointer to the input dataset that contains the point normals of the XYZ dataset.
Protected Attributes inherited from pcl::Feature< PointInT, pcl::SHOT1344 >
std::string feature_name_
The feature name.
SearchMethodSurface search_method_surface_
The search method template for points.
PointCloudInConstPtr surface_
An input point cloud describing the surface that is to be used for nearest neighbors estimation.
KdTreePtr tree_
A pointer to the spatial search object.
double search_parameter_
The actual search parameter (from either search_radius_ or k_).
double search_radius_
The nearest neighbors search radius for each point.
int k_
The number of K nearest neighbors to use for each point.
bool fake_surface_
If no surface is given, we use the input PointCloud as the surface.
Protected Attributes inherited from pcl::PCLBase< PointInT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Protected Attributes inherited from pcl::FeatureWithLocalReferenceFrames< PointInT, pcl::ReferenceFrame >
PointCloudLRFConstPtr frames_
A boost shared pointer to the local reference frames.
bool frames_never_defined_
The user has never set the frames.
Additional Inherited Members
Static Public Member Functions inherited from pcl::SHOTColorEstimation< PointInT, PointNT, pcl::SHOT1344, pcl::ReferenceFrame >
static void RGB2CIELAB (unsigned char R, unsigned char G, unsigned char B, float &L, float &A, float &B2)
Converts RGB triplets to CIELab space.
Static Public Attributes inherited from pcl::SHOTColorEstimation< PointInT, PointNT, pcl::SHOT1344, pcl::ReferenceFrame >
static float sRGB_LUT [256]
static float sXYZ_LUT [4000]
Protected Types inherited from pcl::FeatureWithLocalReferenceFrames< PointInT, pcl::ReferenceFrame >
using LRFEstimationPtr = typename Feature< PointInT, pcl::ReferenceFrame >::Ptr
Check if frames_ has been correctly initialized and compute it if needed.
Detailed Description
template<typename PointInT, typename PointNT, typename PointOutT = pcl::SHOT1344, typename PointRFT = pcl::ReferenceFrame>
class pcl::SHOTColorEstimationOMP< PointInT, PointNT, PointOutT, PointRFT >
SHOTColorEstimationOMP estimates the Signature of Histograms of OrienTations (SHOT) descriptor for a given point cloud dataset containing points, normals and colors, in parallel, using the OpenMP standard.
The suggested PointOutT is pcl::SHOT1344.
Note
If you use this code in any academic work, please cite:
F. Tombari, S. Salti, L. Di Stefano Unique Signatures of Histograms for Local Surface Description. In Proceedings of the 11th European Conference on Computer Vision (ECCV), Heraklion, Greece, September 5-11 2010.
F. Tombari, S. Salti, L. Di Stefano A Combined Texture-Shape Descriptor For Enhanced 3D Feature Matching. In Proceedings of the 18th International Conference on Image Processing (ICIP), Brussels, Belgium, September 11-14 2011.
Author
Samuele Salti
Definition at line 148 of file shot_omp.h.
Member Typedef Documentation
ConstPtr
template<typename PointInT , typename PointNT , typename PointOutT = pcl::SHOT1344, typename PointRFT = pcl::ReferenceFrame> using pcl::SHOTColorEstimationOMP< PointInT, PointNT, PointOutT, PointRFT >::ConstPtr = shared_ptr<const SHOTColorEstimationOMP<PointInT, PointNT, PointOutT, PointRFT> >
Definition at line 152 of file shot_omp.h.
PointCloudIn
template<typename PointInT , typename PointNT , typename PointOutT = pcl::SHOT1344, typename PointRFT = pcl::ReferenceFrame> using pcl::SHOTColorEstimationOMP< PointInT, PointNT, PointOutT, PointRFT >::PointCloudIn = typename Feature<PointInT, PointOutT>::PointCloudIn
Definition at line 177 of file shot_omp.h.
PointCloudOut
template<typename PointInT , typename PointNT , typename PointOutT = pcl::SHOT1344, typename PointRFT = pcl::ReferenceFrame> using pcl::SHOTColorEstimationOMP< PointInT, PointNT, PointOutT, PointRFT >::PointCloudOut = typename Feature<PointInT, PointOutT>::PointCloudOut
Definition at line 176 of file shot_omp.h.
Ptr
template<typename PointInT , typename PointNT , typename PointOutT = pcl::SHOT1344, typename PointRFT = pcl::ReferenceFrame> using pcl::SHOTColorEstimationOMP< PointInT, PointNT, PointOutT, PointRFT >::Ptr = shared_ptr<SHOTColorEstimationOMP<PointInT, PointNT, PointOutT, PointRFT> >
Definition at line 151 of file shot_omp.h.
Constructor & Destructor Documentation
SHOTColorEstimationOMP()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::SHOT1344, typename PointRFT = pcl::ReferenceFrame> pcl::SHOTColorEstimationOMP< PointInT, PointNT, PointOutT, PointRFT >::SHOTColorEstimationOMP (bool describe_shape = true, bool describe_color = true, unsigned int nr_threads = 0) inline
Empty constructor.
Definition at line 180 of file shot_omp.h.
References pcl::SHOTColorEstimationOMP< PointInT, PointNT, PointOutT, PointRFT >::setNumberOfThreads().
Member Function Documentation
computeFeature()
template<typename PointInT , typename PointNT , typename PointOutT , typename PointRFT > void pcl::SHOTColorEstimationOMP< PointInT, PointNT, PointOutT, PointRFT >::computeFeature (PointCloudOut & output) override protected
Estimate the Signatures of Histograms of OrienTations (SHOT) descriptors at a set of points given by <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Parameters
output the resultant point cloud model dataset that contains the SHOT feature estimates
Definition at line 223 of file shot_omp.hpp.
References pcl::isFinite().
initCompute()
template<typename PointInT , typename PointNT , typename PointOutT , typename PointRFT > bool pcl::SHOTColorEstimationOMP< PointInT, PointNT, PointOutT, PointRFT >::initCompute override protected virtual
This method should get called before starting the actual computation.
Reimplemented from pcl::FeatureFromNormals< PointInT, PointNT, pcl::SHOT1344 >.
Definition at line 88 of file shot_omp.hpp.
References pcl::PCLBase< PointInT >::setIndices(), pcl::PCLBase< PointInT >::setInputCloud(), pcl::SHOTLocalReferenceFrameEstimationOMP< PointInT, PointOutT >::setNumberOfThreads(), pcl::Feature< PointInT, ReferenceFrame >::setRadiusSearch(), and pcl::Feature< PointInT, ReferenceFrame >::setSearchSurface().
setNumberOfThreads()
template<typename PointInT , typename PointNT , typename PointOutT , typename PointRFT > void pcl::SHOTColorEstimationOMP< PointInT, PointNT, PointOutT, PointRFT >::setNumberOfThreads (unsigned int nr_threads = 0)
Initialize the scheduler and set the number of threads to use.
Parameters
nr_threads the number of hardware threads to use (0 sets the value back to automatic)
Definition at line 209 of file shot_omp.hpp.
Referenced by pcl::SHOTColorEstimationOMP< PointInT, PointNT, PointOutT, PointRFT >::SHOTColorEstimationOMP().
Member Data Documentation
threads_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::SHOT1344, typename PointRFT = pcl::ReferenceFrame> unsigned int pcl::SHOTColorEstimationOMP< PointInT, PointNT, PointOutT, PointRFT >::threads_ protected
The number of threads the scheduler should use.
Definition at line 209 of file shot_omp.h.
The documentation for this class was generated from the following files:
pcl/features/shot_omp.h
pcl/features/impl/shot_omp.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Jun 2 2020 14:12:59