Point Cloud Library (PCL): pcl::poisson::OctNode< NodeData, Real > Class Template Reference
pcl::poisson::OctNode< NodeData, Real > Class Template Reference
#include <pcl/surface/3rdparty/poisson4/octree_poisson.h>
Classes
class ConstNeighborKey3
class ConstNeighborKey5
class ConstNeighbors3
class ConstNeighbors5
class NeighborKey3
class NeighborKey5
class Neighbors3
class Neighbors5
Public Member Functions
OctNode (void)
~OctNode (void)
int initChildren (void)
void depthAndOffset (int &depth, int offset[DIMENSION]) const
int depth (void) const
void centerAndWidth (Point3D< Real > &center, Real &width) const
bool isInside (Point3D< Real > p) const
int leaves (void) const
int maxDepthLeaves (int maxDepth) const
int nodes (void) const
int maxDepth (void) const
const OctNode * root (void) const
const OctNode * nextLeaf (const OctNode *currentLeaf=NULL) const
OctNode * nextLeaf (OctNode *currentLeaf=NULL)
const OctNode * nextNode (const OctNode *currentNode=NULL) const
OctNode * nextNode (OctNode *currentNode=NULL)
const OctNode * nextBranch (const OctNode *current) const
OctNode * nextBranch (OctNode *current)
const OctNode * prevBranch (const OctNode *current) const
OctNode * prevBranch (OctNode *current)
void setFullDepth (int maxDepth)
void printLeaves (void) const
void printRange (void) const
template<class NodeAdjacencyFunction >
void processNodeFaces (OctNode *node, NodeAdjacencyFunction *F, int fIndex, int processCurrent=1)
template<class NodeAdjacencyFunction >
void processNodeEdges (OctNode *node, NodeAdjacencyFunction *F, int eIndex, int processCurrent=1)
template<class NodeAdjacencyFunction >
void processNodeCorners (OctNode *node, NodeAdjacencyFunction *F, int cIndex, int processCurrent=1)
template<class NodeAdjacencyFunction >
void processNodeNodes (OctNode *node, NodeAdjacencyFunction *F, int processCurrent=1)
OctNode * faceNeighbor (int faceIndex, int forceChildren=0)
const OctNode * faceNeighbor (int faceIndex) const
OctNode * edgeNeighbor (int edgeIndex, int forceChildren=0)
const OctNode * edgeNeighbor (int edgeIndex) const
OctNode * cornerNeighbor (int cornerIndex, int forceChildren=0)
const OctNode * cornerNeighbor (int cornerIndex) const
OctNode * getNearestLeaf (const Point3D< Real > &p)
const OctNode * getNearestLeaf (const Point3D< Real > &p) const
template<class NodeData2 >
OctNode & operator= (const OctNode< NodeData2, Real > &node)
int write (const char *fileName) const
int write (FILE *fp) const
int read (const char *fileName)
int read (FILE *fp)
void centerIndex (int maxDepth, int index[DIMENSION]) const
int width (int maxDepth) const
template<class NodeAdjacencyFunction >
void ProcessNodeAdjacentNodes (int dx, int dy, int dz, OctNode< NodeData, Real > *node1, int radius1, OctNode< NodeData, Real > *node2, int radius2, int width2, NodeAdjacencyFunction *F, int processCurrent)
template<class TerminatingNodeAdjacencyFunction >
void ProcessTerminatingNodeAdjacentNodes (int dx, int dy, int dz, OctNode< NodeData, Real > *node1, int radius1, OctNode< NodeData, Real > *node2, int radius2, int width2, TerminatingNodeAdjacencyFunction *F, int processCurrent)
template<class PointAdjacencyFunction >
void ProcessPointAdjacentNodes (int dx, int dy, int dz, OctNode< NodeData, Real > *node2, int radius2, int width2, PointAdjacencyFunction *F, int processCurrent)
template<class NodeAdjacencyFunction >
void ProcessFixedDepthNodeAdjacentNodes (int maxDepth, OctNode< NodeData, Real > *node1, int width1, OctNode< NodeData, Real > *node2, int width2, int depth, NodeAdjacencyFunction *F, int processCurrent)
template<class NodeAdjacencyFunction >
void ProcessFixedDepthNodeAdjacentNodes (int dx, int dy, int dz, OctNode< NodeData, Real > *node1, int radius1, OctNode< NodeData, Real > *node2, int radius2, int width2, int depth, NodeAdjacencyFunction *F, int processCurrent)
template<class NodeAdjacencyFunction >
void ProcessMaxDepthNodeAdjacentNodes (int maxDepth, OctNode< NodeData, Real > *node1, int width1, OctNode< NodeData, Real > *node2, int width2, int depth, NodeAdjacencyFunction *F, int processCurrent)
template<class NodeAdjacencyFunction >
void ProcessMaxDepthNodeAdjacentNodes (int dx, int dy, int dz, OctNode< NodeData, Real > *node1, int radius1, OctNode< NodeData, Real > *node2, int radius2, int width2, int depth, NodeAdjacencyFunction *F, int processCurrent)
template<class NodeData2 >
OctNode< NodeData, Real > & operator= (const OctNode< NodeData2, Real > &node)
Static Public Member Functions
static int UseAllocator (void)
static void SetAllocator (int blockSize)
static void DepthAndOffset (const long long &index, int &depth, int offset[DIMENSION])
static void CenterAndWidth (const long long &index, Point3D< Real > &center, Real &width)
static int Depth (const long long &index)
static void Index (int depth, const int offset[3], short &d, short off[DIMENSION])
template<class NodeAdjacencyFunction >
static void ProcessNodeAdjacentNodes (int maxDepth, OctNode *node1, int width1, OctNode *node2, int width2, NodeAdjacencyFunction *F, int processCurrent=1)
template<class NodeAdjacencyFunction >
static void ProcessNodeAdjacentNodes (int dx, int dy, int dz, OctNode *node1, int radius1, OctNode *node2, int radius2, int width2, NodeAdjacencyFunction *F, int processCurrent=1)
template<class TerminatingNodeAdjacencyFunction >
static void ProcessTerminatingNodeAdjacentNodes (int maxDepth, OctNode *node1, int width1, OctNode *node2, int width2, TerminatingNodeAdjacencyFunction *F, int processCurrent=1)
template<class TerminatingNodeAdjacencyFunction >
static void ProcessTerminatingNodeAdjacentNodes (int dx, int dy, int dz, OctNode *node1, int radius1, OctNode *node2, int radius2, int width2, TerminatingNodeAdjacencyFunction *F, int processCurrent=1)
template<class PointAdjacencyFunction >
static void ProcessPointAdjacentNodes (int maxDepth, const int center1[3], OctNode *node2, int width2, PointAdjacencyFunction *F, int processCurrent=1)
template<class PointAdjacencyFunction >
static void ProcessPointAdjacentNodes (int dx, int dy, int dz, OctNode *node2, int radius2, int width2, PointAdjacencyFunction *F, int processCurrent=1)
template<class NodeAdjacencyFunction >
static void ProcessFixedDepthNodeAdjacentNodes (int maxDepth, OctNode *node1, int width1, OctNode *node2, int width2, int depth, NodeAdjacencyFunction *F, int processCurrent=1)
template<class NodeAdjacencyFunction >
static void ProcessFixedDepthNodeAdjacentNodes (int dx, int dy, int dz, OctNode *node1, int radius1, OctNode *node2, int radius2, int width2, int depth, NodeAdjacencyFunction *F, int processCurrent=1)
template<class NodeAdjacencyFunction >
static void ProcessMaxDepthNodeAdjacentNodes (int maxDepth, OctNode *node1, int width1, OctNode *node2, int width2, int depth, NodeAdjacencyFunction *F, int processCurrent=1)
template<class NodeAdjacencyFunction >
static void ProcessMaxDepthNodeAdjacentNodes (int dx, int dy, int dz, OctNode *node1, int radius1, OctNode *node2, int radius2, int width2, int depth, NodeAdjacencyFunction *F, int processCurrent=1)
static int CornerIndex (const Point3D< Real > &center, const Point3D< Real > &p)
static int CommonEdge (const OctNode *node1, int eIndex1, const OctNode *node2, int eIndex2)
static int CompareForwardDepths (const void *v1, const void *v2)
static int CompareByDepthAndXYZ (const void *v1, const void *v2)
static int CompareByDepthAndZIndex (const void *v1, const void *v2)
static int CompareForwardPointerDepths (const void *v1, const void *v2)
static int CompareBackwardDepths (const void *v1, const void *v2)
static int CompareBackwardPointerDepths (const void *v1, const void *v2)
static int Overlap2 (const int &depth1, const int offSet1[DIMENSION], const Real &multiplier1, const int &depth2, const int offSet2[DIMENSION], const Real &multiplier2)
Public Attributes
OctNode * parent
OctNode * children
short d
short off [DIMENSION]
NodeData nodeData
Static Public Attributes
static const int DepthShift =5
static const int OffsetShift =19
static const int OffsetShift1 =DepthShift
static const int OffsetShift2 =OffsetShift1+OffsetShift
static const int OffsetShift3 =OffsetShift2+OffsetShift
static const int DepthMask =(1<<DepthShift)-1
static const int OffsetMask =(1<<OffsetShift)-1
static Allocator< OctNode > internalAllocator
Detailed Description
template<class NodeData, class Real = float>
class pcl::poisson::OctNode< NodeData, Real >
Definition at line 48 of file octree_poisson.h.
Constructor & Destructor Documentation
OctNode()
template<class NodeData , class Real > pcl::poisson::OctNode< NodeData, Real >::OctNode (void)
Definition at line 68 of file octree_poisson.hpp.
~OctNode()
template<class NodeData , class Real > pcl::poisson::OctNode< NodeData, Real >::~OctNode (void)
Definition at line 74 of file octree_poisson.hpp.
Member Function Documentation
CenterAndWidth()
template<class NodeData , class Real > void pcl::poisson::OctNode< NodeData, Real >::CenterAndWidth (const long long & index, Point3D< Real > & center, Real & width) inline static
Definition at line 170 of file octree_poisson.hpp.
centerAndWidth()
template<class NodeData , class Real > void pcl::poisson::OctNode< NodeData, Real >::centerAndWidth (Point3D< Real > & center, Real & width) const
Definition at line 149 of file octree_poisson.hpp.
References pcl::poisson::Point3D< Real >::coords.
centerIndex()
template<class NodeData , class Real > void pcl::poisson::OctNode< NodeData, Real >::centerIndex (int maxDepth, int index[DIMENSION]) const
Definition at line 1990 of file octree_poisson.hpp.
References pcl::poisson::BinaryNode< Real >::CornerIndex(), pcl::poisson::OctNode< NodeData, Real >::d, pcl::poisson::OctNode< NodeData, Real >::depthAndOffset(), and pcl::poisson::OctNode< NodeData, Real >::maxDepth().
Referenced by pcl::poisson::OctNode< NodeData, Real >::ProcessFixedDepthNodeAdjacentNodes(), pcl::poisson::OctNode< NodeData, Real >::ProcessMaxDepthNodeAdjacentNodes(), pcl::poisson::OctNode< NodeData, Real >::ProcessNodeAdjacentNodes(), pcl::poisson::OctNode< NodeData, Real >::ProcessPointAdjacentNodes(), and pcl::poisson::OctNode< NodeData, Real >::ProcessTerminatingNodeAdjacentNodes().
CommonEdge()
template<class NodeData , class Real = float> int pcl::poisson::OctNode< NodeData, Real >::CommonEdge (const OctNode< NodeData, Real > * node1, int eIndex1, const OctNode< NodeData, Real > * node2, int eIndex2) static
Definition at line 762 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::depthAndOffset(), and pcl::poisson::Cube::FactorEdgeIndex().
CompareBackwardDepths()
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::CompareBackwardDepths (const void * v1, const void * v2) static
Definition at line 879 of file octree_poisson.hpp.
CompareBackwardPointerDepths()
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::CompareBackwardPointerDepths (const void * v1, const void * v2) static
Definition at line 884 of file octree_poisson.hpp.
CompareByDepthAndXYZ()
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::CompareByDepthAndXYZ (const void * v1, const void * v2) static
Definition at line 827 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::d, and pcl::poisson::OctNode< NodeData, Real >::off.
CompareByDepthAndZIndex()
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::CompareByDepthAndZIndex (const void * v1, const void * v2) static
Definition at line 847 of file octree_poisson.hpp.
References pcl::poisson::_InterleaveBits(), and pcl::poisson::OctNode< NodeData, Real >::depthAndOffset().
CompareForwardDepths()
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::CompareForwardDepths (const void * v1, const void * v2) static
Definition at line 822 of file octree_poisson.hpp.
CompareForwardPointerDepths()
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::CompareForwardPointerDepths (const void * v1, const void * v2) static
Definition at line 862 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::d, pcl::poisson::OctNode< NodeData, Real >::off, and pcl::poisson::OctNode< NodeData, Real >::parent.
CornerIndex()
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::CornerIndex (const Point3D< Real > & center, const Point3D< Real > & p) static
Definition at line 797 of file octree_poisson.hpp.
References pcl::poisson::Point3D< Real >::coords.
cornerNeighbor() [1/2]
template<class NodeData , class Real > const OctNode< NodeData, Real > * pcl::poisson::OctNode< NodeData, Real >::cornerNeighbor (int cornerIndex) const
Definition at line 1030 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::children, pcl::poisson::OctNode< NodeData, Real >::cornerNeighbor(), and pcl::poisson::OctNode< NodeData, Real >::edgeNeighbor().
cornerNeighbor() [2/2]
template<class NodeData , class Real > OctNode< NodeData, Real > * pcl::poisson::OctNode< NodeData, Real >::cornerNeighbor (int cornerIndex, int forceChildren = 0)
Definition at line 1079 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::children, pcl::poisson::OctNode< NodeData, Real >::cornerNeighbor(), pcl::poisson::OctNode< NodeData, Real >::edgeNeighbor(), and pcl::poisson::OctNode< NodeData, Real >::initChildren().
Referenced by pcl::poisson::OctNode< NodeData, Real >::cornerNeighbor().
Depth()
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::Depth (const long long & index) inline static
Definition at line 147 of file octree_poisson.hpp.
depth()
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::depth (void) const inline
Definition at line 137 of file octree_poisson.hpp.
Referenced by pcl::poisson::OctNode< NodeData, Real >::ConstNeighborKey5::getNeighbors(), pcl::poisson::OctNode< NodeData, Real >::NeighborKey5::getNeighbors(), pcl::poisson::OctNode< NodeData, Real >::operator=(), pcl::poisson::OctNode< NodeData, Real >::ProcessFixedDepthNodeAdjacentNodes(), pcl::poisson::OctNode< NodeData, Real >::ProcessMaxDepthNodeAdjacentNodes(), pcl::poisson::SortedTreeNodes::setCornerTable(), pcl::poisson::Octree< Degree >::SetLaplacianConstraints(), pcl::poisson::OctNode< NodeData, Real >::NeighborKey5::setNeighbors(), and pcl::poisson::OctNode< NodeData, Real >::width().
DepthAndOffset()
template<class NodeData , class Real = float> void pcl::poisson::OctNode< NodeData, Real >::DepthAndOffset (const long long & index, int & depth, int offset[DIMENSION]) inline static
Definition at line 139 of file octree_poisson.hpp.
depthAndOffset()
template<class NodeData , class Real = float> void pcl::poisson::OctNode< NodeData, Real >::depthAndOffset (int & depth, int offset[DIMENSION]) const inline
Definition at line 129 of file octree_poisson.hpp.
Referenced by pcl::poisson::VertexData::CenterIndex(), pcl::poisson::OctNode< NodeData, Real >::centerIndex(), pcl::poisson::OctNode< NodeData, Real >::CommonEdge(), pcl::poisson::OctNode< NodeData, Real >::CompareByDepthAndZIndex(), pcl::poisson::VertexData::CornerIndex(), pcl::poisson::VertexData::EdgeIndex(), pcl::poisson::VertexData::FaceIndex(), pcl::poisson::SortedTreeNodes::getMaxCornerCount(), pcl::poisson::SortedTreeNodes::getMaxEdgeCount(), pcl::poisson::Octree< Degree >::GetMCIsoTriangles(), pcl::poisson::SortedTreeNodes::setCornerTable(), pcl::poisson::SortedTreeNodes::setEdgeTable(), and pcl::poisson::Octree< Degree >::SetLaplacianConstraints().
edgeNeighbor() [1/2]
template<class NodeData , class Real > const OctNode< NodeData, Real > * pcl::poisson::OctNode< NodeData, Real >::edgeNeighbor (int edgeIndex) const
Definition at line 954 of file octree_poisson.hpp.
References pcl::poisson::Cube::FactorEdgeIndex().
edgeNeighbor() [2/2]
template<class NodeData , class Real > OctNode< NodeData, Real > * pcl::poisson::OctNode< NodeData, Real >::edgeNeighbor (int edgeIndex, int forceChildren = 0)
Definition at line 942 of file octree_poisson.hpp.
References pcl::poisson::Cube::FactorEdgeIndex().
Referenced by pcl::poisson::OctNode< NodeData, Real >::cornerNeighbor().
faceNeighbor() [1/2]
template<class NodeData , class Real > const OctNode< NodeData, Real > * pcl::poisson::OctNode< NodeData, Real >::faceNeighbor (int faceIndex) const
Definition at line 910 of file octree_poisson.hpp.
faceNeighbor() [2/2]
template<class NodeData , class Real > OctNode< NodeData, Real > * pcl::poisson::OctNode< NodeData, Real >::faceNeighbor (int faceIndex, int forceChildren = 0)
Definition at line 908 of file octree_poisson.hpp.
getNearestLeaf() [1/2]
template<class NodeData , class Real > OctNode< NodeData, Real > * pcl::poisson::OctNode< NodeData, Real >::getNearestLeaf (const Point3D< Real > & p)
Definition at line 721 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::children, and pcl::poisson::Point3D< Real >::coords.
getNearestLeaf() [2/2]
template<class NodeData , class Real > const OctNode< NodeData, Real > * pcl::poisson::OctNode< NodeData, Real >::getNearestLeaf (const Point3D< Real > & p) const
Definition at line 744 of file octree_poisson.hpp.
References pcl::poisson::Cube::CORNERS, and pcl::poisson::SquareDistance().
Index()
template<class NodeData , class Real = float> void pcl::poisson::OctNode< NodeData, Real >::Index (int depth, const int offset[3], short & d, short off[DIMENSION]) inline static
Definition at line 121 of file octree_poisson.hpp.
initChildren()
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::initChildren (void)
Definition at line 89 of file octree_poisson.hpp.
Referenced by pcl::poisson::OctNode< NodeData, Real >::cornerNeighbor(), pcl::poisson::OctNode< NodeData, Real >::read(), pcl::poisson::OctNode< NodeData, Real >::NeighborKey5::setNeighbors(), and pcl::poisson::Octree< Degree >::setTree().
isInside()
template<class NodeData , class Real > bool pcl::poisson::OctNode< NodeData, Real >::isInside (Point3D< Real > p) const
Definition at line 160 of file octree_poisson.hpp.
leaves()
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::leaves (void) const
Definition at line 204 of file octree_poisson.hpp.
maxDepth()
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::maxDepth (void) const
Definition at line 181 of file octree_poisson.hpp.
Referenced by pcl::poisson::OctNode< NodeData, Real >::centerIndex(), pcl::poisson::SortedTreeNodes::set(), and pcl::poisson::OctNode< NodeData, Real >::width().
maxDepthLeaves()
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::maxDepthLeaves (int maxDepth) const
Definition at line 214 of file octree_poisson.hpp.
nextBranch() [1/2]
template<class NodeData , class Real > const OctNode< NodeData, Real > * pcl::poisson::OctNode< NodeData, Real >::nextBranch (const OctNode< NodeData, Real > * current) const
Definition at line 232 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::children, pcl::poisson::Cube::CORNERS, and pcl::poisson::OctNode< NodeData, Real >::parent.
nextBranch() [2/2]
template<class NodeData , class Real > OctNode< NodeData, Real > * pcl::poisson::OctNode< NodeData, Real >::nextBranch (OctNode< NodeData, Real > * current)
Definition at line 240 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::children, pcl::poisson::Cube::CORNERS, and pcl::poisson::OctNode< NodeData, Real >::parent.
nextLeaf() [1/2]
template<class NodeData , class Real > const OctNode< NodeData, Real > * pcl::poisson::OctNode< NodeData, Real >::nextLeaf (const OctNode< NodeData, Real > * currentLeaf = NULL) const
Definition at line 263 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::children.
Referenced by pcl::poisson::Octree< Degree >::GetMCIsoTriangles(), pcl::poisson::OctNode< class TreeNodeData, Real >::ConstNeighborKey5::getNeighbors(), pcl::poisson::OctNode< NodeData, Real >::nextLeaf(), pcl::poisson::Octree< Degree >::RefineBoundary(), and pcl::poisson::OctNode< class TreeNodeData, Real >::ConstNeighborKey5::~ConstNeighborKey5().
nextLeaf() [2/2]
template<class NodeData , class Real > OctNode< NodeData, Real > * pcl::poisson::OctNode< NodeData, Real >::nextLeaf (OctNode< NodeData, Real > * currentLeaf = NULL)
Definition at line 276 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::children, and pcl::poisson::OctNode< NodeData, Real >::nextLeaf().
nextNode() [1/2]
template<class NodeData , class Real > const OctNode< NodeData, Real > * pcl::poisson::OctNode< NodeData, Real >::nextNode (const OctNode< NodeData, Real > * currentNode = NULL) const
Definition at line 289 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::children.
Referenced by pcl::poisson::Octree< Degree >::ClipTree(), pcl::poisson::Octree< Degree >::finalize(), pcl::poisson::Octree< Degree >::GetSolutionGrid(), pcl::poisson::Octree< Degree >::GetWeightGrid(), and pcl::poisson::Octree< Degree >::setTree().
nextNode() [2/2]
template<class NodeData , class Real > OctNode< NodeData, Real > * pcl::poisson::OctNode< NodeData, Real >::nextNode (OctNode< NodeData, Real > * currentNode = NULL)
Definition at line 297 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::children.
nodes()
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::nodes (void) const
Definition at line 194 of file octree_poisson.hpp.
Referenced by pcl::poisson::SortedTreeNodes::set().
operator=() [1/2]
template<class NodeData , class Real = float> template<class NodeData2 > OctNode& pcl::poisson::OctNode< NodeData, Real >::operator= (const OctNode< NodeData2, Real > & node)
operator=() [2/2]
template<class NodeData , class Real = float> template<class NodeData2 > OctNode<NodeData,Real>& pcl::poisson::OctNode< NodeData, Real >::operator= (const OctNode< NodeData2, Real > & node)
Definition at line 807 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::children, pcl::poisson::Cube::CORNERS, pcl::poisson::OctNode< NodeData, Real >::depth(), and pcl::poisson::OctNode< NodeData, Real >::off.
Overlap2()
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::Overlap2 (const int & depth1, const int offSet1[DIMENSION], const Real & multiplier1, const int & depth2, const int offSet2[DIMENSION], const Real & multiplier2) inline static
Definition at line 889 of file octree_poisson.hpp.
prevBranch() [1/2]
template<class NodeData , class Real > const OctNode< NodeData, Real > * pcl::poisson::OctNode< NodeData, Real >::prevBranch (const OctNode< NodeData, Real > * current) const
Definition at line 247 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::children, and pcl::poisson::OctNode< NodeData, Real >::parent.
prevBranch() [2/2]
template<class NodeData , class Real > OctNode< NodeData, Real > * pcl::poisson::OctNode< NodeData, Real >::prevBranch (OctNode< NodeData, Real > * current)
Definition at line 255 of file octree_poisson.hpp.
printLeaves()
template<class NodeData , class Real = float> void pcl::poisson::OctNode< NodeData, Real >::printLeaves (void) const
printRange()
template<class NodeData , class Real > void pcl::poisson::OctNode< NodeData, Real >::printRange (void) const
Definition at line 305 of file octree_poisson.hpp.
References pcl::poisson::Point3D< Real >::coords.
ProcessFixedDepthNodeAdjacentNodes() [1/4]
template<class NodeData , class Real = float> template<class NodeAdjacencyFunction > static void pcl::poisson::OctNode< NodeData, Real >::ProcessFixedDepthNodeAdjacentNodes (int dx, int dy, int dz, OctNode< NodeData, Real > * node1, int radius1, OctNode< NodeData, Real > * node2, int radius2, int width2, int depth, NodeAdjacencyFunction * F, int processCurrent = 1) static
ProcessFixedDepthNodeAdjacentNodes() [2/4]
template<class NodeData , class Real = float> template<class NodeAdjacencyFunction > void pcl::poisson::OctNode< NodeData, Real >::ProcessFixedDepthNodeAdjacentNodes (int dx, int dy, int dz, OctNode< NodeData, Real > * node1, int radius1, OctNode< NodeData, Real > * node2, int radius2, int width2, int depth, NodeAdjacencyFunction * F, int processCurrent)
Definition at line 491 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::children, and pcl::poisson::OctNode< NodeData, Real >::depth().
ProcessFixedDepthNodeAdjacentNodes() [3/4]
template<class NodeData , class Real = float> template<class NodeAdjacencyFunction > static void pcl::poisson::OctNode< NodeData, Real >::ProcessFixedDepthNodeAdjacentNodes (int maxDepth, OctNode< NodeData, Real > * node1, int width1, OctNode< NodeData, Real > * node2, int width2, int depth, NodeAdjacencyFunction * F, int processCurrent = 1) static
ProcessFixedDepthNodeAdjacentNodes() [4/4]
template<class NodeData , class Real = float> template<class NodeAdjacencyFunction > void pcl::poisson::OctNode< NodeData, Real >::ProcessFixedDepthNodeAdjacentNodes (int maxDepth, OctNode< NodeData, Real > * node1, int width1, OctNode< NodeData, Real > * node2, int width2, int depth, NodeAdjacencyFunction * F, int processCurrent)
Definition at line 475 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::centerIndex(), and pcl::poisson::OctNode< NodeData, Real >::width().
ProcessMaxDepthNodeAdjacentNodes() [1/4]
template<class NodeData , class Real = float> template<class NodeAdjacencyFunction > static void pcl::poisson::OctNode< NodeData, Real >::ProcessMaxDepthNodeAdjacentNodes (int dx, int dy, int dz, OctNode< NodeData, Real > * node1, int radius1, OctNode< NodeData, Real > * node2, int radius2, int width2, int depth, NodeAdjacencyFunction * F, int processCurrent = 1) static
ProcessMaxDepthNodeAdjacentNodes() [2/4]
template<class NodeData , class Real = float> template<class NodeAdjacencyFunction > void pcl::poisson::OctNode< NodeData, Real >::ProcessMaxDepthNodeAdjacentNodes (int dx, int dy, int dz, OctNode< NodeData, Real > * node1, int radius1, OctNode< NodeData, Real > * node2, int radius2, int width2, int depth, NodeAdjacencyFunction * F, int processCurrent)
Definition at line 523 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::depth().
ProcessMaxDepthNodeAdjacentNodes() [3/4]
template<class NodeData , class Real = float> template<class NodeAdjacencyFunction > static void pcl::poisson::OctNode< NodeData, Real >::ProcessMaxDepthNodeAdjacentNodes (int maxDepth, OctNode< NodeData, Real > * node1, int width1, OctNode< NodeData, Real > * node2, int width2, int depth, NodeAdjacencyFunction * F, int processCurrent = 1) static
ProcessMaxDepthNodeAdjacentNodes() [4/4]
template<class NodeData , class Real = float> template<class NodeAdjacencyFunction > void pcl::poisson::OctNode< NodeData, Real >::ProcessMaxDepthNodeAdjacentNodes (int maxDepth, OctNode< NodeData, Real > * node1, int width1, OctNode< NodeData, Real > * node2, int width2, int depth, NodeAdjacencyFunction * F, int processCurrent)
Definition at line 508 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::centerIndex(), and pcl::poisson::OctNode< NodeData, Real >::width().
ProcessNodeAdjacentNodes() [1/3]
template<class NodeData , class Real = float> template<class NodeAdjacencyFunction > static void pcl::poisson::OctNode< NodeData, Real >::ProcessNodeAdjacentNodes (int dx, int dy, int dz, OctNode< NodeData, Real > * node1, int radius1, OctNode< NodeData, Real > * node2, int radius2, int width2, NodeAdjacencyFunction * F, int processCurrent = 1) static
ProcessNodeAdjacentNodes() [2/3]
template<class NodeData , class Real = float> template<class NodeAdjacencyFunction > void pcl::poisson::OctNode< NodeData, Real >::ProcessNodeAdjacentNodes (int dx, int dy, int dz, OctNode< NodeData, Real > * node1, int radius1, OctNode< NodeData, Real > * node2, int radius2, int width2, NodeAdjacencyFunction * F, int processCurrent)
Definition at line 416 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::children.
ProcessNodeAdjacentNodes() [3/3]
template<class NodeData , class Real > template<class NodeAdjacencyFunction > void pcl::poisson::OctNode< NodeData, Real >::ProcessNodeAdjacentNodes (int maxDepth, OctNode< NodeData, Real > * node1, int width1, OctNode< NodeData, Real > * node2, int width2, NodeAdjacencyFunction * F, int processCurrent = 1) static
Definition at line 404 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::centerIndex(), and pcl::poisson::OctNode< NodeData, Real >::width().
processNodeCorners()
template<class NodeData , class Real > template<class NodeAdjacencyFunction > void pcl::poisson::OctNode< NodeData, Real >::processNodeCorners (OctNode< NodeData, Real > * node, NodeAdjacencyFunction * F, int cIndex, int processCurrent = 1)
Definition at line 350 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::children.
processNodeEdges()
template<class NodeData , class Real > template<class NodeAdjacencyFunction > void pcl::poisson::OctNode< NodeData, Real >::processNodeEdges (OctNode< NodeData, Real > * node, NodeAdjacencyFunction * F, int eIndex, int processCurrent = 1)
Definition at line 339 of file octree_poisson.hpp.
References pcl::poisson::Cube::EdgeCorners().
processNodeFaces()
template<class NodeData , class Real > template<class NodeAdjacencyFunction > void pcl::poisson::OctNode< NodeData, Real >::processNodeFaces (OctNode< NodeData, Real > * node, NodeAdjacencyFunction * F, int fIndex, int processCurrent = 1)
Definition at line 328 of file octree_poisson.hpp.
References pcl::poisson::Cube::FaceCorners().
processNodeNodes()
template<class NodeData , class Real > template<class NodeAdjacencyFunction > void pcl::poisson::OctNode< NodeData, Real >::processNodeNodes (OctNode< NodeData, Real > * node, NodeAdjacencyFunction * F, int processCurrent = 1)
Definition at line 321 of file octree_poisson.hpp.
ProcessPointAdjacentNodes() [1/3]
template<class NodeData , class Real = float> template<class PointAdjacencyFunction > static void pcl::poisson::OctNode< NodeData, Real >::ProcessPointAdjacentNodes (int dx, int dy, int dz, OctNode< NodeData, Real > * node2, int radius2, int width2, PointAdjacencyFunction * F, int processCurrent = 1) static
ProcessPointAdjacentNodes() [2/3]
template<class NodeData , class Real = float> template<class PointAdjacencyFunction > void pcl::poisson::OctNode< NodeData, Real >::ProcessPointAdjacentNodes (int dx, int dy, int dz, OctNode< NodeData, Real > * node2, int radius2, int width2, PointAdjacencyFunction * F, int processCurrent)
Definition at line 463 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::children.
ProcessPointAdjacentNodes() [3/3]
template<class NodeData , class Real > template<class PointAdjacencyFunction > void pcl::poisson::OctNode< NodeData, Real >::ProcessPointAdjacentNodes (int maxDepth, const int center1[3], OctNode< NodeData, Real > * node2, int width2, PointAdjacencyFunction * F, int processCurrent = 1) static
Definition at line 453 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::centerIndex(), and pcl::poisson::OctNode< NodeData, Real >::width().
ProcessTerminatingNodeAdjacentNodes() [1/3]
template<class NodeData , class Real = float> template<class TerminatingNodeAdjacencyFunction > static void pcl::poisson::OctNode< NodeData, Real >::ProcessTerminatingNodeAdjacentNodes (int dx, int dy, int dz, OctNode< NodeData, Real > * node1, int radius1, OctNode< NodeData, Real > * node2, int radius2, int width2, TerminatingNodeAdjacencyFunction * F, int processCurrent = 1) static
ProcessTerminatingNodeAdjacentNodes() [2/3]
template<class NodeData , class Real = float> template<class TerminatingNodeAdjacencyFunction > void pcl::poisson::OctNode< NodeData, Real >::ProcessTerminatingNodeAdjacentNodes (int dx, int dy, int dz, OctNode< NodeData, Real > * node1, int radius1, OctNode< NodeData, Real > * node2, int radius2, int width2, TerminatingNodeAdjacencyFunction * F, int processCurrent)
Definition at line 440 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::children.
ProcessTerminatingNodeAdjacentNodes() [3/3]
template<class NodeData , class Real > template<class TerminatingNodeAdjacencyFunction > void pcl::poisson::OctNode< NodeData, Real >::ProcessTerminatingNodeAdjacentNodes (int maxDepth, OctNode< NodeData, Real > * node1, int width1, OctNode< NodeData, Real > * node2, int width2, TerminatingNodeAdjacencyFunction * F, int processCurrent = 1) static
Definition at line 428 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::centerIndex(), and pcl::poisson::OctNode< NodeData, Real >::width().
read() [1/2]
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::read (const char * fileName)
Definition at line 1960 of file octree_poisson.hpp.
Referenced by pcl::poisson::OctNode< NodeData, Real >::read().
read() [2/2]
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::read (FILE * fp)
Definition at line 1969 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::children, pcl::poisson::Cube::CORNERS, pcl::poisson::OctNode< NodeData, Real >::initChildren(), pcl::poisson::OctNode< NodeData, Real >::parent, and pcl::poisson::OctNode< NodeData, Real >::read().
root()
template<class NodeData , class Real > const OctNode< NodeData, Real > * pcl::poisson::OctNode< NodeData, Real >::root (void) const
Definition at line 225 of file octree_poisson.hpp.
SetAllocator()
template<class NodeData , class Real > void pcl::poisson::OctNode< NodeData, Real >::SetAllocator (int blockSize) static
Definition at line 54 of file octree_poisson.hpp.
setFullDepth()
template<class NodeData , class Real > void pcl::poisson::OctNode< NodeData, Real >::setFullDepth (int maxDepth)
Definition at line 80 of file octree_poisson.hpp.
UseAllocator()
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::UseAllocator (void) static
Definition at line 65 of file octree_poisson.hpp.
width()
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::width (int maxDepth) const
Definition at line 1984 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::d, pcl::poisson::OctNode< NodeData, Real >::depth(), and pcl::poisson::OctNode< NodeData, Real >::maxDepth().
Referenced by pcl::poisson::OctNode< NodeData, Real >::ProcessFixedDepthNodeAdjacentNodes(), pcl::poisson::OctNode< NodeData, Real >::ProcessMaxDepthNodeAdjacentNodes(), pcl::poisson::OctNode< NodeData, Real >::ProcessNodeAdjacentNodes(), pcl::poisson::OctNode< NodeData, Real >::ProcessPointAdjacentNodes(), and pcl::poisson::OctNode< NodeData, Real >::ProcessTerminatingNodeAdjacentNodes().
write() [1/2]
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::write (const char * fileName) const
Definition at line 1944 of file octree_poisson.hpp.
Referenced by pcl::poisson::OctNode< NodeData, Real >::write().
write() [2/2]
template<class NodeData , class Real > int pcl::poisson::OctNode< NodeData, Real >::write (FILE * fp) const
Definition at line 1953 of file octree_poisson.hpp.
References pcl::poisson::OctNode< NodeData, Real >::children, pcl::poisson::Cube::CORNERS, and pcl::poisson::OctNode< NodeData, Real >::write().
Member Data Documentation
children
template<class NodeData , class Real = float> OctNode* pcl::poisson::OctNode< NodeData, Real >::children
Definition at line 93 of file octree_poisson.h.
Referenced by pcl::poisson::OctNode< NodeData, Real >::cornerNeighbor(), pcl::poisson::Octree< Degree >::GetMCIsoTriangles(), pcl::poisson::OctNode< NodeData, Real >::getNearestLeaf(), pcl::poisson::OctNode< NodeData, Real >::ConstNeighborKey5::getNeighbors(), pcl::poisson::OctNode< NodeData, Real >::NeighborKey5::getNeighbors(), pcl::poisson::OctNode< NodeData, Real >::nextBranch(), pcl::poisson::OctNode< NodeData, Real >::nextLeaf(), pcl::poisson::OctNode< NodeData, Real >::nextNode(), pcl::poisson::OctNode< NodeData, Real >::operator=(), pcl::poisson::OctNode< NodeData, Real >::prevBranch(), pcl::poisson::OctNode< NodeData, Real >::ProcessFixedDepthNodeAdjacentNodes(), pcl::poisson::OctNode< NodeData, Real >::ProcessNodeAdjacentNodes(), pcl::poisson::OctNode< NodeData, Real >::processNodeCorners(), pcl::poisson::OctNode< NodeData, Real >::ProcessPointAdjacentNodes(), pcl::poisson::OctNode< NodeData, Real >::ProcessTerminatingNodeAdjacentNodes(), pcl::poisson::OctNode< NodeData, Real >::read(), pcl::poisson::SortedTreeNodes::set(), pcl::poisson::SortedTreeNodes::setCornerTable(), pcl::poisson::SortedTreeNodes::setEdgeTable(), pcl::poisson::Octree< Degree >::SetLaplacianConstraints(), pcl::poisson::OctNode< NodeData, Real >::NeighborKey5::setNeighbors(), pcl::poisson::Octree< Degree >::setTree(), and pcl::poisson::OctNode< NodeData, Real >::write().
d
template<class NodeData , class Real = float> short pcl::poisson::OctNode< NodeData, Real >::d
Definition at line 94 of file octree_poisson.h.
Referenced by pcl::poisson::OctNode< NodeData, Real >::centerIndex(), pcl::poisson::OctNode< NodeData, Real >::CompareByDepthAndXYZ(), pcl::poisson::OctNode< NodeData, Real >::CompareForwardPointerDepths(), pcl::poisson::SortedTreeNodes::CornerTableData::cornerIndices(), pcl::poisson::SortedTreeNodes::EdgeTableData::edgeIndices(), pcl::poisson::Octree< Degree >::GetMCIsoTriangles(), pcl::poisson::OctNode< NodeData, Real >::ConstNeighborKey5::getNeighbors(), pcl::poisson::OctNode< NodeData, Real >::NeighborKey5::getNeighbors(), pcl::poisson::SortedTreeNodes::CornerTableData::operator[](), pcl::poisson::SortedTreeNodes::EdgeTableData::operator[](), pcl::poisson::OctNode< NodeData, Real >::NeighborKey3::set(), pcl::poisson::OctNode< NodeData, Real >::ConstNeighborKey3::set(), pcl::poisson::OctNode< NodeData, Real >::NeighborKey5::set(), pcl::poisson::OctNode< NodeData, Real >::ConstNeighborKey5::set(), pcl::poisson::OctNode< NodeData, Real >::NeighborKey5::setNeighbors(), and pcl::poisson::OctNode< NodeData, Real >::width().
DepthMask
template<class NodeData , class Real > const int pcl::poisson::OctNode< NodeData, Real >::DepthMask =(1<<DepthShift)-1 static
Definition at line 86 of file octree_poisson.h.
DepthShift
template<class NodeData , class Real > const int pcl::poisson::OctNode< NodeData, Real >::DepthShift =5 static
Definition at line 85 of file octree_poisson.h.
internalAllocator
template<class NodeData , class Real > Allocator< OctNode< NodeData, Real > > pcl::poisson::OctNode< NodeData, Real >::internalAllocator static
Definition at line 88 of file octree_poisson.h.
nodeData
template<class NodeData , class Real = float> NodeData pcl::poisson::OctNode< NodeData, Real >::nodeData
Definition at line 95 of file octree_poisson.h.
Referenced by pcl::poisson::SortedTreeNodes::CornerTableData::cornerIndices(), pcl::poisson::SortedTreeNodes::EdgeTableData::edgeIndices(), pcl::poisson::Octree< Degree >::GetIsoValue(), pcl::poisson::Octree< Degree >::GetMCIsoTriangles(), pcl::poisson::SortedTreeNodes::CornerTableData::operator[](), pcl::poisson::SortedTreeNodes::EdgeTableData::operator[](), pcl::poisson::SortedTreeNodes::setCornerTable(), pcl::poisson::SortedTreeNodes::setEdgeTable(), pcl::poisson::Octree< Degree >::SetLaplacianConstraints(), and pcl::poisson::Octree< Degree >::setTree().
off
template<class NodeData , class Real = float> short pcl::poisson::OctNode< NodeData, Real >::off[DIMENSION]
Definition at line 94 of file octree_poisson.h.
Referenced by pcl::poisson::OctNode< NodeData, Real >::CompareByDepthAndXYZ(), pcl::poisson::OctNode< NodeData, Real >::CompareForwardPointerDepths(), and pcl::poisson::OctNode< NodeData, Real >::operator=().
OffsetMask
template<class NodeData , class Real > const int pcl::poisson::OctNode< NodeData, Real >::OffsetMask =(1<<OffsetShift)-1 static
Definition at line 86 of file octree_poisson.h.
OffsetShift
template<class NodeData , class Real > const int pcl::poisson::OctNode< NodeData, Real >::OffsetShift =19 static
Definition at line 85 of file octree_poisson.h.
OffsetShift1
template<class NodeData , class Real > const int pcl::poisson::OctNode< NodeData, Real >::OffsetShift1 =DepthShift static
Definition at line 85 of file octree_poisson.h.
OffsetShift2
template<class NodeData , class Real > const int pcl::poisson::OctNode< NodeData, Real >::OffsetShift2 =OffsetShift1+OffsetShift static
Definition at line 85 of file octree_poisson.h.
OffsetShift3
template<class NodeData , class Real > const int pcl::poisson::OctNode< NodeData, Real >::OffsetShift3 =OffsetShift2+OffsetShift static
Definition at line 85 of file octree_poisson.h.
parent
template<class NodeData , class Real = float> OctNode* pcl::poisson::OctNode< NodeData, Real >::parent
Definition at line 92 of file octree_poisson.h.
Referenced by pcl::poisson::OctNode< NodeData, Real >::CompareForwardPointerDepths(), pcl::poisson::OctNode< class TreeNodeData, Real >::ConstNeighborKey3::ConstNeighborKey3(), pcl::poisson::Octree< Degree >::GetMCIsoTriangles(), pcl::poisson::OctNode< NodeData, Real >::ConstNeighborKey5::getNeighbors(), pcl::poisson::OctNode< NodeData, Real >::NeighborKey5::getNeighbors(), pcl::poisson::OctNode< NodeData, Real >::nextBranch(), pcl::poisson::OctNode< NodeData, Real >::prevBranch(), pcl::poisson::OctNode< NodeData, Real >::read(), pcl::poisson::SortedTreeNodes::setCornerTable(), pcl::poisson::Octree< Degree >::SetLaplacianConstraints(), pcl::poisson::OctNode< NodeData, Real >::NeighborKey5::setNeighbors(), and pcl::poisson::OctNode< class TreeNodeData, Real >::NeighborKey5::~NeighborKey5().
The documentation for this class was generated from the following files:
pcl/surface/3rdparty/poisson4/octree_poisson.h
pcl/surface/3rdparty/poisson4/octree_poisson.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:42