Point Cloud Library (PCL): INCVMemAllocator Class Reference
INCVMemAllocator Class Reference abstract
INCVMemAllocator (Interface)
#include </__w/1/s/gpu/people/src/cuda/nvidia/NCV.hpp>
Public Member Functions
virtual ~INCVMemAllocator ()=0
virtual NCVStatus alloc (NCVMemSegment &seg, std::size_t size)=0
virtual NCVStatus dealloc (NCVMemSegment &seg)=0
virtual NcvBool isInitialized () const =0
virtual NcvBool isCounting () const =0
virtual NCVMemoryType memType () const =0
virtual Ncv32u alignment () const =0
virtual std::size_t maxSize () const =0
Detailed Description
INCVMemAllocator (Interface)
Definition at line 402 of file NCV.hpp.
Constructor & Destructor Documentation
~INCVMemAllocator()
INCVMemAllocator::~INCVMemAllocator () inline pure virtual
Definition at line 418 of file NCV.hpp.
Member Function Documentation
alignment()
virtual Ncv32u INCVMemAllocator::alignment () const pure virtual
Implemented in NCVMemNativeAllocator, and NCVMemStackAllocator.
Referenced by NCVVectorAlloc< HaarClassifierNode128 >::getAllocatorsAlignment(), NCVMatrixAlloc< T >::getAllocatorsAlignment(), and NCVMatrixAlloc< T >::NCVMatrixAlloc().
alloc()
virtual NCVStatus INCVMemAllocator::alloc (NCVMemSegment & seg, std::size_t size) pure virtual
Implemented in NCVMemNativeAllocator, and NCVMemStackAllocator.
Referenced by NCVMatrixAlloc< T >::NCVMatrixAlloc(), and NCVVectorAlloc< HaarClassifierNode128 >::NCVVectorAlloc().
dealloc()
virtual NCVStatus INCVMemAllocator::dealloc (NCVMemSegment & seg) pure virtual
Implemented in NCVMemNativeAllocator, and NCVMemStackAllocator.
Referenced by NCVMatrixAlloc< T >::~NCVMatrixAlloc(), and NCVVectorAlloc< HaarClassifierNode128 >::~NCVVectorAlloc().
isCounting()
virtual NcvBool INCVMemAllocator::isCounting () const pure virtual
Implemented in NCVMemNativeAllocator, and NCVMemStackAllocator.
Referenced by NCVVectorAlloc< HaarClassifierNode128 >::isMemAllocated(), and NCVMatrixAlloc< T >::isMemAllocated().
isInitialized()
virtual NcvBool INCVMemAllocator::isInitialized () const pure virtual
Implemented in NCVMemNativeAllocator, and NCVMemStackAllocator.
maxSize()
virtual std::size_t INCVMemAllocator::maxSize () const pure virtual
Implemented in NCVMemNativeAllocator, and NCVMemStackAllocator.
memType()
virtual NCVMemoryType INCVMemAllocator::memType () const pure virtual
Implemented in NCVMemNativeAllocator, and NCVMemStackAllocator.
The documentation for this class was generated from the following file:
/__w/1/s/gpu/people/src/cuda/nvidia/NCV.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Jun 2 2020 14:11:05