Point Cloud Library (PCL): pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT > Class Template Reference
pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT > Class Template Reference
Module features
ShapeContext3DEstimation implements the 3D shape context descriptor as described in:
#include <pcl/features/3dsc.h>
Public Types
using Ptr = shared_ptr< ShapeContext3DEstimation< PointInT, PointNT, PointOutT > >
using ConstPtr = shared_ptr< const ShapeContext3DEstimation< PointInT, PointNT, PointOutT > >
using PointCloudOut = typename Feature< PointInT, PointOutT >::PointCloudOut
using PointCloudIn = typename Feature< PointInT, PointOutT >::PointCloudIn
Public Types inherited from pcl::FeatureFromNormals< PointInT, PointNT, pcl::ShapeContext1980 >
using PointCloudN = pcl::PointCloud< PointNT >
using PointCloudNPtr = typename PointCloudN::Ptr
using PointCloudNConstPtr = typename PointCloudN::ConstPtr
using Ptr = shared_ptr< FeatureFromNormals< PointInT, PointNT, pcl::ShapeContext1980 > >
using ConstPtr = shared_ptr< const FeatureFromNormals< PointInT, PointNT, pcl::ShapeContext1980 > >
Public Types inherited from pcl::Feature< PointInT, PointOutT >
using BaseClass = PCLBase< PointInT >
using Ptr = shared_ptr< Feature< PointInT, PointOutT > >
using ConstPtr = shared_ptr< const Feature< PointInT, PointOutT > >
using KdTree = pcl::search::Search< PointInT >
using KdTreePtr = typename KdTree::Ptr
using PointCloudIn = pcl::PointCloud< PointInT >
using PointCloudInPtr = typename PointCloudIn::Ptr
using PointCloudInConstPtr = typename PointCloudIn::ConstPtr
using PointCloudOut = pcl::PointCloud< PointOutT >
using SearchMethod = std::function< int(std::size_t, double, pcl::Indices &, std::vector< float > &)>
using SearchMethodSurface = std::function< int(const PointCloudIn &cloud, std::size_t index, double, pcl::Indices &, std::vector< float > &)>
Public Types inherited from pcl::PCLBase< PointInT >
using PointCloud = pcl::PointCloud< PointInT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
ShapeContext3DEstimation (bool random=false)
Constructor.
~ShapeContext3DEstimation () override=default
std::size_t getAzimuthBins ()
std::size_t getElevationBins ()
std::size_t getRadiusBins ()
void setMinimalRadius (double radius)
The minimal radius value for the search sphere (rmin) in the original paper.
double getMinimalRadius ()
void setPointDensityRadius (double radius)
This radius is used to compute local point density density = number of points within this radius.
double getPointDensityRadius ()
Public Member Functions inherited from pcl::FeatureFromNormals< PointInT, PointNT, pcl::ShapeContext1980 >
FeatureFromNormals ()
Empty constructor.
void setInputNormals (const PointCloudNConstPtr &normals)
Provide a pointer to the input dataset that contains the point normals of the XYZ dataset.
PointCloudNConstPtr getInputNormals () const
Get a pointer to the normals of the input XYZ point cloud dataset.
Public Member Functions inherited from pcl::Feature< PointInT, PointOutT >
Feature ()
Empty constructor.
void setSearchSurface (const PointCloudInConstPtr &cloud)
Provide a pointer to a dataset to add additional information to estimate the features for every point in the input dataset.
PointCloudInConstPtr getSearchSurface () const
Get a pointer to the surface point cloud dataset.
void setSearchMethod (const KdTreePtr &tree)
Provide a pointer to the search object.
KdTreePtr getSearchMethod () const
Get a pointer to the search method used.
double getSearchParameter () const
Get the internal search parameter.
void setKSearch (int k)
Set the number of k nearest neighbors to use for the feature estimation.
int getKSearch () const
get the number of k nearest neighbors used for the feature estimation.
void setRadiusSearch (double radius)
Set the sphere radius that is to be used for determining the nearest neighbors used for the feature estimation.
double getRadiusSearch () const
Get the sphere radius used for determining the neighbors.
void compute (PointCloudOut &output)
Base method for feature estimation for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Public Member Functions inherited from pcl::PCLBase< PointInT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointInT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
bool initCompute () override
Initialize computation by allocating all the intervals and the volume lookup table.
bool computePoint (std::size_t index, const pcl::PointCloud< PointNT > &normals, float rf[9], std::vector< float > &desc)
Estimate a descriptor for a given point.
void computeFeature (PointCloudOut &output) override
Estimate the actual feature.
float rnd ()
Boost-based random number generator.
Protected Member Functions inherited from pcl::Feature< PointInT, PointOutT >
const std::string & getClassName () const
Get a string representation of the name of this class.
virtual bool deinitCompute ()
This method should get called after ending the actual computation.
int searchForNeighbors (std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
int searchForNeighbors (const PointCloudIn &cloud, std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
Protected Member Functions inherited from pcl::PCLBase< PointInT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Protected Attributes
std::vector< float > radii_interval_
Values of the radii interval.
std::vector< float > theta_divisions_
Theta divisions interval.
std::vector< float > phi_divisions_
Phi divisions interval.
std::vector< float > volume_lut_
Volumes look up table.
std::size_t azimuth_bins_ {12}
Bins along the azimuth dimension.
std::size_t elevation_bins_ {11}
Bins along the elevation dimension.
std::size_t radius_bins_ {15}
Bins along the radius dimension.
double min_radius_ {0.1}
Minimal radius value.
double point_density_radius_ {0.2}
Point density radius.
std::size_t descriptor_length_ {}
Descriptor length.
std::mt19937 rng_
Random number generator algorithm.
std::uniform_real_distribution< float > rng_dist_
Random number generator distribution.
Protected Attributes inherited from pcl::FeatureFromNormals< PointInT, PointNT, pcl::ShapeContext1980 >
PointCloudNConstPtr normals_
A pointer to the input dataset that contains the point normals of the XYZ dataset.
Protected Attributes inherited from pcl::Feature< PointInT, PointOutT >
std::string feature_name_
The feature name.
SearchMethodSurface search_method_surface_
The search method template for points.
PointCloudInConstPtr surface_
An input point cloud describing the surface that is to be used for nearest neighbors estimation.
KdTreePtr tree_
A pointer to the spatial search object.
double search_parameter_
The actual search parameter (from either search_radius_ or k_).
double search_radius_
The nearest neighbors search radius for each point.
int k_
The number of K nearest neighbors to use for each point.
bool fake_surface_
If no surface is given, we use the input PointCloud as the surface.
Protected Attributes inherited from pcl::PCLBase< PointInT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointInT, typename PointNT, typename PointOutT = pcl::ShapeContext1980>
class pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >
ShapeContext3DEstimation implements the 3D shape context descriptor as described in:
Andrea Frome, Daniel Huber, Ravi Kolluri and Thomas Blow, Jitendra Malik Recognizing Objects in Range Data Using Regional Point Descriptors, In proceedings of the 8th European Conference on Computer Vision (ECCV), Prague, May 11-14, 2004
The suggested PointOutT is pcl::ShapeContext1980
Attention
The convention for a 3D shape context descriptor is:
if a query point's nearest neighbors cannot be estimated, the feature descriptor will be set to NaN (not a number), and the RF to 0
it is impossible to estimate a 3D shape context descriptor for a point that doesn't have finite 3D coordinates. Therefore, any point that contains NaN data on x, y, or z, will have its boundary feature property set to NaN.
Author
Alessandro Franchi, Samuele Salti, Federico Tombari (original code)
Nizar Sallem (port to PCL)
Definition at line 72 of file 3dsc.h.
Member Typedef Documentation
ConstPtr
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> using pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::ConstPtr = shared_ptr<const ShapeContext3DEstimation<PointInT, PointNT, PointOutT> >
Definition at line 76 of file 3dsc.h.
PointCloudIn
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> using pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::PointCloudIn = typename Feature<PointInT, PointOutT>::PointCloudIn
Definition at line 89 of file 3dsc.h.
PointCloudOut
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> using pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::PointCloudOut = typename Feature<PointInT, PointOutT>::PointCloudOut
Definition at line 88 of file 3dsc.h.
Ptr
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> using pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::Ptr = shared_ptr<ShapeContext3DEstimation<PointInT, PointNT, PointOutT> >
Definition at line 75 of file 3dsc.h.
Constructor & Destructor Documentation
ShapeContext3DEstimation()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::ShapeContext3DEstimation (bool random = false) inline
Constructor.
Parameters
[in] random If true the random seed is set to current time, else it is set to 12345 prior to computing the descriptor (used to select X axis)
Definition at line 95 of file 3dsc.h.
References pcl::Feature< PointInT, PointOutT >::feature_name_, pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::rng_, and pcl::Feature< PointInT, PointOutT >::search_radius_.
~ShapeContext3DEstimation()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::~ShapeContext3DEstimation () override default
Member Function Documentation
computeFeature()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::computeFeature (PointCloudOut & output) override protected virtual
Estimate the actual feature.
Parameters
[out] output the resultant feature
Implements pcl::Feature< PointInT, PointOutT >.
Definition at line 255 of file 3dsc.hpp.
References pcl::isFinite().
computePoint()
template<typename PointInT , typename PointNT , typename PointOutT > bool pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::computePoint (std::size_t index, const pcl::PointCloud< PointNT > & normals, float rf[9], std::vector< float > & desc) protected
Estimate a descriptor for a given point.
Parameters
[in] index the index of the point to estimate a descriptor for
[in] normals a pointer to the set of normals
[out] rf the reference frame
[out] desc the resultant estimated descriptor
Returns
true if the descriptor was computed successfully, false if there was an error (e.g. the nearest neighbor didn't return any neighbors)
--— Compute current neighbour polar coordinates --— Get distance between the neighbour and the origin
Project point into the tangent plane
Normalize to compute the dot product
Compute the angle between the projection and the x axis in the interval [0,360]
Compute the angle between the neighbour and the z axis (normal) in the interval [0, 180]
Accumulate w into correspondent Bin(j,k,l)
Definition at line 133 of file 3dsc.hpp.
References pcl::geometry::distance(), pcl::utils::equal(), pcl::isNormalFinite(), pcl::geometry::project(), and pcl::rad2deg().
getAzimuthBins()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> std::size_t pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::getAzimuthBins () inline
Returns
the number of bins along the azimuth
Definition at line 123 of file 3dsc.h.
References pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::azimuth_bins_.
getElevationBins()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> std::size_t pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::getElevationBins () inline
Returns
The number of bins along the elevation
Definition at line 130 of file 3dsc.h.
References pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::elevation_bins_.
getMinimalRadius()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> double pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::getMinimalRadius () inline
Returns
The minimal sphere radius
Definition at line 147 of file 3dsc.h.
References pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::min_radius_.
getPointDensityRadius()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> double pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::getPointDensityRadius () inline
Returns
The point density search radius
Definition at line 158 of file 3dsc.h.
References pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::point_density_radius_.
getRadiusBins()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> std::size_t pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::getRadiusBins () inline
Returns
The number of bins along the radii direction
Definition at line 137 of file 3dsc.h.
References pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::radius_bins_.
initCompute()
template<typename PointInT , typename PointNT , typename PointOutT > bool pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::initCompute override protected virtual
Initialize computation by allocating all the intervals and the volume lookup table.
Reimplemented from pcl::FeatureFromNormals< PointInT, PointNT, pcl::ShapeContext1980 >.
Definition at line 53 of file 3dsc.hpp.
References pcl::deg2rad().
rnd()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> float pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::rnd () inline protected
Boost-based random number generator.
Definition at line 228 of file 3dsc.h.
References pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::rng_, and pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::rng_dist_.
setMinimalRadius()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> void pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::setMinimalRadius (double radius) inline
The minimal radius value for the search sphere (rmin) in the original paper.
Parameters
[in] radius the desired minimal radius
Definition at line 143 of file 3dsc.h.
References pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::min_radius_.
setPointDensityRadius()
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> void pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::setPointDensityRadius (double radius) inline
This radius is used to compute local point density density = number of points within this radius.
Parameters
[in] radius value of the point density search radius
Definition at line 154 of file 3dsc.h.
References pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::point_density_radius_.
Member Data Documentation
azimuth_bins_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> std::size_t pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::azimuth_bins_ {12} protected
Bins along the azimuth dimension.
Definition at line 195 of file 3dsc.h.
Referenced by pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::getAzimuthBins().
descriptor_length_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> std::size_t pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::descriptor_length_ {} protected
Descriptor length.
Definition at line 210 of file 3dsc.h.
elevation_bins_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> std::size_t pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::elevation_bins_ {11} protected
Bins along the elevation dimension.
Definition at line 198 of file 3dsc.h.
Referenced by pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::getElevationBins().
min_radius_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> double pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::min_radius_ {0.1} protected
Minimal radius value.
Definition at line 204 of file 3dsc.h.
Referenced by pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::getMinimalRadius(), and pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::setMinimalRadius().
phi_divisions_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> std::vector<float> pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::phi_divisions_ protected
Phi divisions interval.
Definition at line 189 of file 3dsc.h.
point_density_radius_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> double pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::point_density_radius_ {0.2} protected
Point density radius.
Definition at line 207 of file 3dsc.h.
Referenced by pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::getPointDensityRadius(), and pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::setPointDensityRadius().
radii_interval_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> std::vector<float> pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::radii_interval_ protected
Values of the radii interval.
Definition at line 183 of file 3dsc.h.
radius_bins_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> std::size_t pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::radius_bins_ {15} protected
Bins along the radius dimension.
Definition at line 201 of file 3dsc.h.
Referenced by pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::getRadiusBins().
rng_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> std::mt19937 pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::rng_ protected
Random number generator algorithm.
Definition at line 213 of file 3dsc.h.
Referenced by pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::rnd(), and pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::ShapeContext3DEstimation().
rng_dist_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> std::uniform_real_distribution<float> pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::rng_dist_ protected
Random number generator distribution.
Definition at line 216 of file 3dsc.h.
Referenced by pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::rnd().
theta_divisions_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> std::vector<float> pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::theta_divisions_ protected
Theta divisions interval.
Definition at line 186 of file 3dsc.h.
volume_lut_
template<typename PointInT , typename PointNT , typename PointOutT = pcl::ShapeContext1980> std::vector<float> pcl::ShapeContext3DEstimation< PointInT, PointNT, PointOutT >::volume_lut_ protected
Volumes look up table.
Definition at line 192 of file 3dsc.h.
The documentation for this class was generated from the following files:
pcl/features/3dsc.h
pcl/features/impl/3dsc.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:09