Point Cloud Library (PCL): pcl::IntegralImageNormalEstimation< PointInT, PointOutT > Class Template Reference
pcl::IntegralImageNormalEstimation< PointInT, PointOutT > Class Template Reference
Surface normal estimation on organized data using integral images.
#include <pcl/features/integral_image_normal.h>
Public Types
enum BorderPolicy { BORDER_POLICY_IGNORE , BORDER_POLICY_MIRROR }
Different types of border handling.
enum NormalEstimationMethod { COVARIANCE_MATRIX , AVERAGE_3D_GRADIENT , AVERAGE_DEPTH_CHANGE , SIMPLE_3D_GRADIENT }
Different normal estimation methods.
using Ptr = shared_ptr< IntegralImageNormalEstimation< PointInT, PointOutT > >
using ConstPtr = shared_ptr< const IntegralImageNormalEstimation< PointInT, PointOutT > >
using PointCloudIn = typename Feature< PointInT, PointOutT >::PointCloudIn
using PointCloudOut = typename Feature< PointInT, PointOutT >::PointCloudOut
Public Types inherited from pcl::Feature< PointInT, PointOutT >
using BaseClass = PCLBase< PointInT >
using Ptr = shared_ptr< Feature< PointInT, PointOutT > >
using ConstPtr = shared_ptr< const Feature< PointInT, PointOutT > >
using KdTree = pcl::search::Search< PointInT >
using KdTreePtr = typename KdTree::Ptr
using PointCloudIn = pcl::PointCloud< PointInT >
using PointCloudInPtr = typename PointCloudIn::Ptr
using PointCloudInConstPtr = typename PointCloudIn::ConstPtr
using PointCloudOut = pcl::PointCloud< PointOutT >
using SearchMethod = std::function< int(std::size_t, double, pcl::Indices &, std::vector< float > &)>
using SearchMethodSurface = std::function< int(const PointCloudIn &cloud, std::size_t index, double, pcl::Indices &, std::vector< float > &)>
Public Types inherited from pcl::PCLBase< PointInT >
using PointCloud = pcl::PointCloud< PointInT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
IntegralImageNormalEstimation ()
Constructor.
~IntegralImageNormalEstimation () override
Destructor.
void setRectSize (const int width, const int height)
Set the regions size which is considered for normal estimation.
void setBorderPolicy (const BorderPolicy border_policy)
Sets the policy for handling borders.
void computePointNormal (const int pos_x, const int pos_y, const unsigned point_index, PointOutT &normal)
Computes the normal at the specified position.
void computePointNormalMirror (const int pos_x, const int pos_y, const unsigned point_index, PointOutT &normal)
Computes the normal at the specified position with mirroring for border handling.
void setMaxDepthChangeFactor (float max_depth_change_factor)
The depth change threshold for computing object borders.
void setNormalSmoothingSize (float normal_smoothing_size)
Set the normal smoothing size.
void setNormalEstimationMethod (NormalEstimationMethod normal_estimation_method)
Set the normal estimation method.
void setDepthDependentSmoothing (bool use_depth_dependent_smoothing)
Set whether to use depth depending smoothing or not.
void setInputCloud (const typename PointCloudIn::ConstPtr &cloud) override
Provide a pointer to the input dataset (overwrites the PCLBase::setInputCloud method)
float * getDistanceMap ()
Returns a pointer to the distance map which was computed internally.
void setViewPoint (float vpx, float vpy, float vpz)
Set the viewpoint.
void getViewPoint (float &vpx, float &vpy, float &vpz)
Get the viewpoint.
void useSensorOriginAsViewPoint ()
sets whether the sensor origin or a user given viewpoint should be used.
Public Member Functions inherited from pcl::Feature< PointInT, PointOutT >
Feature ()
Empty constructor.
void setSearchSurface (const PointCloudInConstPtr &cloud)
Provide a pointer to a dataset to add additional information to estimate the features for every point in the input dataset.
PointCloudInConstPtr getSearchSurface () const
Get a pointer to the surface point cloud dataset.
void setSearchMethod (const KdTreePtr &tree)
Provide a pointer to the search object.
KdTreePtr getSearchMethod () const
Get a pointer to the search method used.
double getSearchParameter () const
Get the internal search parameter.
void setKSearch (int k)
Set the number of k nearest neighbors to use for the feature estimation.
int getKSearch () const
get the number of k nearest neighbors used for the feature estimation.
void setRadiusSearch (double radius)
Set the sphere radius that is to be used for determining the nearest neighbors used for the feature estimation.
double getRadiusSearch () const
Get the sphere radius used for determining the neighbors.
void compute (PointCloudOut &output)
Base method for feature estimation for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Public Member Functions inherited from pcl::PCLBase< PointInT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointInT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
void computeFeature (PointCloudOut &output) override
Computes the normal for the complete cloud or only indices_ if provided.
void computeFeatureFull (const float *distance_map, const float &bad_point, PointCloudOut &output)
Computes the normal for the complete cloud.
void computeFeaturePart (const float *distance_map, const float &bad_point, PointCloudOut &output)
Computes the normal for part of the cloud specified by indices_.
void initData ()
Initialize the data structures, based on the normal estimation method chosen.
Protected Member Functions inherited from pcl::Feature< PointInT, PointOutT >
const std::string & getClassName () const
Get a string representation of the name of this class.
virtual bool deinitCompute ()
This method should get called after ending the actual computation.
int searchForNeighbors (std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
int searchForNeighbors (const PointCloudIn &cloud, std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
Protected Member Functions inherited from pcl::PCLBase< PointInT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Additional Inherited Members
Protected Attributes inherited from pcl::Feature< PointInT, PointOutT >
std::string feature_name_
The feature name.
SearchMethodSurface search_method_surface_
The search method template for points.
PointCloudInConstPtr surface_
An input point cloud describing the surface that is to be used for nearest neighbors estimation.
KdTreePtr tree_
A pointer to the spatial search object.
double search_parameter_
The actual search parameter (from either search_radius_ or k_).
double search_radius_
The nearest neighbors search radius for each point.
int k_
The number of K nearest neighbors to use for each point.
bool fake_surface_
If no surface is given, we use the input PointCloud as the surface.
Protected Attributes inherited from pcl::PCLBase< PointInT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointInT, typename PointOutT>
class pcl::IntegralImageNormalEstimation< PointInT, PointOutT >
Surface normal estimation on organized data using integral images.
   For detailed information about this method see:
   S. Holzer and R. B. Rusu and M. Dixon and S. Gedikli and N. Navab,
   Adaptive Neighborhood Selection for Real-Time Surface Normal Estimation
   from Organized Point Cloud Data Using Integral Images, IROS 2012.
   D. Holz, S. Holzer, R. B. Rusu, and S. Behnke (2011, July).
   Real-Time Plane Segmentation using RGB-D Cameras. In Proceedings of
   the 15th RoboCup International Symposium, Istanbul, Turkey.
   http://www.ais.uni-bonn.de/~holz/papers/holz_2011_robocup.pdf
Author
Stefan Holzer
Definition at line 65 of file integral_image_normal.h.
Member Typedef Documentation
ConstPtr
template<typename PointInT , typename PointOutT > using pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::ConstPtr = shared_ptr<const IntegralImageNormalEstimation<PointInT, PointOutT> >
Definition at line 75 of file integral_image_normal.h.
PointCloudIn
template<typename PointInT , typename PointOutT > using pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::PointCloudIn = typename Feature<PointInT, PointOutT>::PointCloudIn
Definition at line 103 of file integral_image_normal.h.
PointCloudOut
template<typename PointInT , typename PointOutT > using pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::PointCloudOut = typename Feature<PointInT, PointOutT>::PointCloudOut
Definition at line 104 of file integral_image_normal.h.
Ptr
template<typename PointInT , typename PointOutT > using pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::Ptr = shared_ptr<IntegralImageNormalEstimation<PointInT, PointOutT> >
Definition at line 74 of file integral_image_normal.h.
Member Enumeration Documentation
BorderPolicy
template<typename PointInT , typename PointOutT > enum pcl::IntegralImageNormalEstimation::BorderPolicy
Different types of border handling.
Enumerator
BORDER_POLICY_IGNORE
BORDER_POLICY_MIRROR
Definition at line 78 of file integral_image_normal.h.
NormalEstimationMethod
template<typename PointInT , typename PointOutT > enum pcl::IntegralImageNormalEstimation::NormalEstimationMethod
Different normal estimation methods.
COVARIANCE_MATRIX - creates 9 integral images to compute the normal for a specific point from the covariance matrix of its local neighborhood.
AVERAGE_3D_GRADIENT - creates 6 integral images to compute smoothed versions of horizontal and vertical 3D gradients and computes the normals using the cross-product between these two gradients.
AVERAGE_DEPTH_CHANGE - creates only a single integral image and computes the normals from the average depth changes.
Enumerator
COVARIANCE_MATRIX
AVERAGE_3D_GRADIENT
AVERAGE_DEPTH_CHANGE
SIMPLE_3D_GRADIENT
Definition at line 95 of file integral_image_normal.h.
Constructor & Destructor Documentation
IntegralImageNormalEstimation()
template<typename PointInT , typename PointOutT > pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::IntegralImageNormalEstimation () inline
Constructor.
Definition at line 107 of file integral_image_normal.h.
References pcl::Feature< PointInT, PointOutT >::feature_name_, pcl::Feature< PointInT, PointOutT >::k_, and pcl::Feature< PointInT, PointOutT >::tree_.
~IntegralImageNormalEstimation()
template<typename PointInT , typename PointOutT > pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::~IntegralImageNormalEstimation override
Destructor.
Definition at line 45 of file integral_image_normal.hpp.
Member Function Documentation
computeFeature()
template<typename PointInT , typename PointOutT > void pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::computeFeature (PointCloudOut & output) override protected virtual
Computes the normal for the complete cloud or only indices_ if provided.
Parameters
[out] output the resultant normals
Implements pcl::Feature< PointInT, PointOutT >.
Definition at line 729 of file integral_image_normal.hpp.
References pcl::PointCloud< PointT >::sensor_orientation_, and pcl::PointCloud< PointT >::sensor_origin_.
computeFeatureFull()
template<typename PointInT , typename PointOutT > void pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::computeFeatureFull (const float * distance_map, const float & bad_point, PointCloudOut & output) protected
Computes the normal for the complete cloud.
Parameters
[in] distance_map distance map
[in] bad_point constant given to invalid normal components
[out] output the resultant normals
Definition at line 836 of file integral_image_normal.hpp.
References pcl::computePointNormal(), pcl::PointCloud< PointT >::is_dense, and pcl::PointCloud< PointT >::width.
computeFeaturePart()
template<typename PointInT , typename PointOutT > void pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::computeFeaturePart (const float * distance_map, const float & bad_point, PointCloudOut & output) protected
Computes the normal for part of the cloud specified by indices_.
Parameters
[in] distance_map distance map
[in] bad_point constant given to invalid normal components
[out] output the resultant normals
Definition at line 1025 of file integral_image_normal.hpp.
References pcl::computePointNormal(), pcl::PointCloud< PointT >::is_dense, and pcl::PointCloud< PointT >::width.
computePointNormal()
template<typename PointInT , typename PointOutT > void pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::computePointNormal (const int pos_x, const int pos_y, const unsigned point_index, PointOutT & normal)
Computes the normal at the specified position.
Parameters
[in] pos_x x position (pixel)
[in] pos_y y position (pixel)
[in] point_index the position index of the point
[out] normal the output estimated normal
Definition at line 205 of file integral_image_normal.hpp.
References pcl::eigen33(), pcl::flipNormalTowardsViewpoint(), pcl::IntegralImage2D< DataType, Dimension >::getFirstOrderSum(), and pcl::IntegralImage2D< DataType, Dimension >::getSecondOrderSum().
computePointNormalMirror()
template<typename PointInT , typename PointOutT > void pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::computePointNormalMirror (const int pos_x, const int pos_y, const unsigned point_index, PointOutT & normal)
Computes the normal at the specified position with mirroring for border handling.
Parameters
[in] pos_x x position (pixel)
[in] pos_y y position (pixel)
[in] point_index the position index of the point
[out] normal the output estimated normal
Definition at line 460 of file integral_image_normal.hpp.
References pcl::eigen33(), pcl::flipNormalTowardsViewpoint(), and pcl::IntegralImage2D< DataType, Dimension >::getFirstOrderSumSE().
getDistanceMap()
template<typename PointInT , typename PointOutT > float* pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::getDistanceMap () inline
Returns a pointer to the distance map which was computed internally.
Definition at line 240 of file integral_image_normal.h.
getViewPoint()
template<typename PointInT , typename PointOutT > void pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::getViewPoint (float & vpx, float & vpy, float & vpz) inline
Get the viewpoint.
Parameters
[out] vpx x-coordinate of the view point
[out] vpy y-coordinate of the view point
[out] vpz z-coordinate of the view point
Note
this method returns the currently used viewpoint for normal flipping. If the viewpoint is set manually using the setViewPoint method, this method will return the set view point coordinates. If an input cloud is set, it will return the sensor origin otherwise it will return the origin (0, 0, 0)
Definition at line 268 of file integral_image_normal.h.
initData()
template<typename PointInT , typename PointOutT > void pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::initData protected
Initialize the data structures, based on the normal estimation method chosen.
Definition at line 55 of file integral_image_normal.hpp.
Referenced by pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::setInputCloud().
setBorderPolicy()
template<typename PointInT , typename PointOutT > void pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::setBorderPolicy (const BorderPolicy border_policy) inline
Sets the policy for handling borders.
Parameters
[in] border_policy the border policy.
Definition at line 135 of file integral_image_normal.h.
setDepthDependentSmoothing()
template<typename PointInT , typename PointOutT > void pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::setDepthDependentSmoothing (bool use_depth_dependent_smoothing) inline
Set whether to use depth depending smoothing or not.
Parameters
[in] use_depth_dependent_smoothing decides whether the smoothing is depth dependent
Definition at line 206 of file integral_image_normal.h.
setInputCloud()
template<typename PointInT , typename PointOutT > void pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::setInputCloud (const typename PointCloudIn::ConstPtr & cloud) inline override
Provide a pointer to the input dataset (overwrites the PCLBase::setInputCloud method)
Parameters
[in] cloud the const boost shared pointer to a PointCloud message
Definition at line 215 of file integral_image_normal.h.
References pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::initData(), and pcl::PCLBase< PointInT >::input_.
Referenced by pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::detectKeypoints(), pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::initCompute(), pcl::ISSKeypoint3D< PointInT, PointOutT, NormalT >::initCompute(), pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::initCompute(), and pcl::TrajkovicKeypoint3D< PointInT, PointOutT, NormalT >::initCompute().
setMaxDepthChangeFactor()
template<typename PointInT , typename PointOutT > void pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::setMaxDepthChangeFactor (float max_depth_change_factor) inline
The depth change threshold for computing object borders.
Parameters
[in] max_depth_change_factor the depth change threshold for computing object borders based on depth changes
Definition at line 163 of file integral_image_normal.h.
setNormalEstimationMethod()
template<typename PointInT , typename PointOutT > void pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::setNormalEstimationMethod (NormalEstimationMethod normal_estimation_method) inline
Set the normal estimation method.
The current implemented algorithms are:
COVARIANCE_MATRIX - creates 9 integral images to compute the normal for a specific point from the covariance matrix of its local neighborhood.
AVERAGE_3D_GRADIENT - creates 6 integral images to compute smoothed versions of horizontal and vertical 3D gradients and computes the normals using the cross-product between these two gradients.
AVERAGE_DEPTH_CHANGE - creates only a single integral image and computes the normals from the average depth changes.
Parameters
[in] normal_estimation_method the method used for normal estimation
Definition at line 197 of file integral_image_normal.h.
Referenced by pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::detectKeypoints(), pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::initCompute(), pcl::ISSKeypoint3D< PointInT, PointOutT, NormalT >::initCompute(), pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::initCompute(), and pcl::TrajkovicKeypoint3D< PointInT, PointOutT, NormalT >::initCompute().
setNormalSmoothingSize()
template<typename PointInT , typename PointOutT > void pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::setNormalSmoothingSize (float normal_smoothing_size) inline
Set the normal smoothing size.
Parameters
[in] normal_smoothing_size factor which influences the size of the area used to smooth normals (depth dependent if useDepthDependentSmoothing is true)
Definition at line 173 of file integral_image_normal.h.
References pcl::Feature< PointInT, PointOutT >::feature_name_.
Referenced by pcl::HarrisKeypoint6D< PointInT, PointOutT, NormalT >::detectKeypoints(), pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::initCompute(), pcl::ISSKeypoint3D< PointInT, PointOutT, NormalT >::initCompute(), pcl::SUSANKeypoint< PointInT, PointOutT, NormalT, IntensityT >::initCompute(), and pcl::TrajkovicKeypoint3D< PointInT, PointOutT, NormalT >::initCompute().
setRectSize()
template<typename PointInT , typename PointOutT > void pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::setRectSize (const int width, const int height)
Set the regions size which is considered for normal estimation.
Parameters
[in] width the width of the search rectangle
[in] height the height of the search rectangle
Definition at line 92 of file integral_image_normal.hpp.
setViewPoint()
template<typename PointInT , typename PointOutT > void pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::setViewPoint (float vpx, float vpy, float vpz) inline
Set the viewpoint.
Parameters
vpx the X coordinate of the viewpoint
vpy the Y coordinate of the viewpoint
vpz the Z coordinate of the viewpoint
Definition at line 251 of file integral_image_normal.h.
useSensorOriginAsViewPoint()
template<typename PointInT , typename PointOutT > void pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::useSensorOriginAsViewPoint () inline
sets whether the sensor origin or a user given viewpoint should be used.
After this method, the normal estimation method uses the sensor origin of the input cloud. to use a user defined view point, use the method setViewPoint
Definition at line 280 of file integral_image_normal.h.
References pcl::PCLBase< PointInT >::input_.
The documentation for this class was generated from the following files:
pcl/features/integral_image_normal.h
pcl/features/impl/integral_image_normal.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:10