Point Cloud Library (PCL): pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT > Class Template Reference
pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT > Class Template Reference
Module octree
Octree pointcloud voxel class which maintains adjacency information for its voxels.
#include <pcl/octree/octree_pointcloud_adjacency.h>
Public Types
using OctreeBaseT = OctreeBase< LeafContainerT, BranchContainerT >
using OctreeAdjacencyT = OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >
using Ptr = shared_ptr< OctreeAdjacencyT >
using ConstPtr = shared_ptr< const OctreeAdjacencyT >
using OctreePointCloudT = OctreePointCloud< PointT, LeafContainerT, BranchContainerT, OctreeBaseT >
using LeafNode = typename OctreePointCloudT::LeafNode
using BranchNode = typename OctreePointCloudT::BranchNode
using PointCloud = pcl::PointCloud< PointT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using VoxelAdjacencyList = boost::adjacency_list< boost::setS, boost::setS, boost::undirectedS, PointT, float >
using VoxelID = typename VoxelAdjacencyList::vertex_descriptor
using EdgeID = typename VoxelAdjacencyList::edge_descriptor
using LeafVectorT = std::vector< LeafContainerT * >
using iterator = typename LeafVectorT::iterator
using const_iterator = typename LeafVectorT::const_iterator
Public Types inherited from pcl::octree::OctreePointCloud< PointT, OctreePointCloudAdjacencyContainer< PointT >, OctreeContainerEmpty >
using Base = OctreeBase< OctreePointCloudAdjacencyContainer< PointT >, OctreeContainerEmpty >
using LeafNode = typename OctreeBase< OctreePointCloudAdjacencyContainer< PointT >, OctreeContainerEmpty > ::LeafNode
using BranchNode = typename OctreeBase< OctreePointCloudAdjacencyContainer< PointT >, OctreeContainerEmpty > ::BranchNode
using IndicesPtr = shared_ptr< std::vector< int > >
using IndicesConstPtr = shared_ptr< const std::vector< int > >
using PointCloud = pcl::PointCloud< PointT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using SingleBuffer = OctreePointCloud< PointT, OctreePointCloudAdjacencyContainer< PointT >, OctreeContainerEmpty, OctreeBase< OctreePointCloudAdjacencyContainer< PointT > > >
using Ptr = shared_ptr< OctreePointCloud< PointT, OctreePointCloudAdjacencyContainer< PointT >, OctreeContainerEmpty, OctreeBase< OctreePointCloudAdjacencyContainer< PointT >, OctreeContainerEmpty > > >
using ConstPtr = shared_ptr< const OctreePointCloud< PointT, OctreePointCloudAdjacencyContainer< PointT >, OctreeContainerEmpty, OctreeBase< OctreePointCloudAdjacencyContainer< PointT >, OctreeContainerEmpty > > >
using AlignedPointTVector = std::vector< PointT, Eigen::aligned_allocator< PointT > >
using AlignedPointXYZVector = std::vector< PointXYZ, Eigen::aligned_allocator< PointXYZ > >
Public Types inherited from pcl::octree::OctreeBase< OctreePointCloudAdjacencyContainer< PointT >, OctreeContainerEmpty >
using OctreeT = OctreeBase< OctreePointCloudAdjacencyContainer< PointT >, OctreeContainerEmpty >
using BranchNode = OctreeBranchNode< OctreeContainerEmpty >
using LeafNode = OctreeLeafNode< OctreePointCloudAdjacencyContainer< PointT > >
using BranchContainer = OctreeContainerEmpty
using LeafContainer = OctreePointCloudAdjacencyContainer< PointT >
using Iterator = OctreeDepthFirstIterator< OctreeT >
using ConstIterator = const OctreeDepthFirstIterator< OctreeT >
using LeafNodeIterator = OctreeLeafNodeDepthFirstIterator< OctreeT >
using ConstLeafNodeIterator = const OctreeLeafNodeDepthFirstIterator< OctreeT >
using LeafNodeDepthFirstIterator = OctreeLeafNodeDepthFirstIterator< OctreeT >
using ConstLeafNodeDepthFirstIterator = const OctreeLeafNodeDepthFirstIterator< OctreeT >
using DepthFirstIterator = OctreeDepthFirstIterator< OctreeT >
using ConstDepthFirstIterator = const OctreeDepthFirstIterator< OctreeT >
using BreadthFirstIterator = OctreeBreadthFirstIterator< OctreeT >
using ConstBreadthFirstIterator = const OctreeBreadthFirstIterator< OctreeT >
using FixedDepthIterator = OctreeFixedDepthIterator< OctreeT >
using ConstFixedDepthIterator = const OctreeFixedDepthIterator< OctreeT >
using LeafNodeBreadthFirstIterator = OctreeLeafNodeBreadthFirstIterator< OctreeT >
using ConstLeafNodeBreadthFirstIterator = const OctreeLeafNodeBreadthFirstIterator< OctreeT >
Public Member Functions
iterator begin ()
iterator end ()
LeafContainerT * at (std::size_t idx)
std::size_t size () const
OctreePointCloudAdjacency (const double resolution_arg)
Constructor.
void addPointsFromInputCloud ()
Adds points from cloud to the octree.
LeafContainerT * getLeafContainerAtPoint (const PointT &point_arg) const
Gets the leaf container for a given point.
void computeVoxelAdjacencyGraph (VoxelAdjacencyList &voxel_adjacency_graph)
Computes an adjacency graph of voxel relations.
void setTransformFunction (std::function< void(PointT &p)> transform_func)
Sets a point transform (and inverse) used to transform the space of the input cloud.
bool testForOcclusion (const PointT &point_arg, const PointXYZ &camera_pos=PointXYZ(0, 0, 0))
Tests whether input point is occluded from specified camera point by other voxels.
Public Member Functions inherited from pcl::octree::OctreePointCloud< PointT, OctreePointCloudAdjacencyContainer< PointT >, OctreeContainerEmpty >
OctreePointCloud (const double resolution_arg)
Octree pointcloud constructor.
void setInputCloud (const PointCloudConstPtr &cloud_arg, const IndicesConstPtr &indices_arg=IndicesConstPtr())
Provide a pointer to the input data set.
const IndicesConstPtr getIndices () const
Get a pointer to the vector of indices used.
PointCloudConstPtr getInputCloud () const
Get a pointer to the input point cloud dataset.
void setEpsilon (double eps)
Set the search epsilon precision (error bound) for nearest neighbors searches.
double getEpsilon () const
Get the search epsilon precision (error bound) for nearest neighbors searches.
void setResolution (double resolution_arg)
Set/change the octree voxel resolution.
double getResolution () const
Get octree voxel resolution.
unsigned int getTreeDepth () const
Get the maximum depth of the octree.
void addPointsFromInputCloud ()
Add points from input point cloud to octree.
void addPointFromCloud (const int point_idx_arg, IndicesPtr indices_arg)
Add point at given index from input point cloud to octree.
void addPointToCloud (const PointT &point_arg, PointCloudPtr cloud_arg)
Add point simultaneously to octree and input point cloud.
void addPointToCloud (const PointT &point_arg, PointCloudPtr cloud_arg, IndicesPtr indices_arg)
Add point simultaneously to octree and input point cloud.
bool isVoxelOccupiedAtPoint (const PointT &point_arg) const
Check if voxel at given point exist.
bool isVoxelOccupiedAtPoint (const double point_x_arg, const double point_y_arg, const double point_z_arg) const
Check if voxel at given point coordinates exist.
bool isVoxelOccupiedAtPoint (const int &point_idx_arg) const
Check if voxel at given point from input cloud exist.
void deleteTree ()
Delete the octree structure and its leaf nodes.
int getOccupiedVoxelCenters (AlignedPointTVector &voxel_center_list_arg) const
Get a PointT vector of centers of all occupied voxels.
int getApproxIntersectedVoxelCentersBySegment (const Eigen::Vector3f &origin, const Eigen::Vector3f &end, AlignedPointTVector &voxel_center_list, float precision=0.2)
Get a PointT vector of centers of voxels intersected by a line segment.
void deleteVoxelAtPoint (const PointT &point_arg)
Delete leaf node / voxel at given point.
void deleteVoxelAtPoint (const int &point_idx_arg)
Delete leaf node / voxel at given point from input cloud.
void defineBoundingBox ()
Investigate dimensions of pointcloud data set and define corresponding bounding box for octree.
void defineBoundingBox (const double min_x_arg, const double min_y_arg, const double min_z_arg, const double max_x_arg, const double max_y_arg, const double max_z_arg)
Define bounding box for octree.
void defineBoundingBox (const double max_x_arg, const double max_y_arg, const double max_z_arg)
Define bounding box for octree.
void defineBoundingBox (const double cubeLen_arg)
Define bounding box cube for octree.
void getBoundingBox (double &min_x_arg, double &min_y_arg, double &min_z_arg, double &max_x_arg, double &max_y_arg, double &max_z_arg) const
Get bounding box for octree.
double getVoxelSquaredDiameter (unsigned int tree_depth_arg) const
Calculates the squared diameter of a voxel at given tree depth.
double getVoxelSquaredDiameter () const
Calculates the squared diameter of a voxel at leaf depth.
double getVoxelSquaredSideLen (unsigned int tree_depth_arg) const
Calculates the squared voxel cube side length at given tree depth.
double getVoxelSquaredSideLen () const
Calculates the squared voxel cube side length at leaf level.
void getVoxelBounds (const OctreeIteratorBase< OctreeBase< OctreePointCloudAdjacencyContainer< PointT >, OctreeContainerEmpty > > &iterator, Eigen::Vector3f &min_pt, Eigen::Vector3f &max_pt) const
Generate bounds of the current voxel of an octree iterator.
void enableDynamicDepth (std::size_t maxObjsPerLeaf)
Enable dynamic octree structure.
Public Member Functions inherited from pcl::octree::OctreeBase< OctreePointCloudAdjacencyContainer< PointT >, OctreeContainerEmpty >
Iterator begin (unsigned int max_depth_arg=0u)
const Iterator end ()
LeafNodeIterator leaf_begin (unsigned int max_depth_arg=0u)
const LeafNodeIterator leaf_end ()
LeafNodeDepthFirstIterator leaf_depth_begin (unsigned int max_depth_arg=0u)
const LeafNodeDepthFirstIterator leaf_depth_end ()
DepthFirstIterator depth_begin (unsigned int max_depth_arg=0u)
const DepthFirstIterator depth_end ()
BreadthFirstIterator breadth_begin (unsigned int max_depth_arg=0u)
const BreadthFirstIterator breadth_end ()
FixedDepthIterator fixed_depth_begin (unsigned int fixed_depth_arg=0u)
const FixedDepthIterator fixed_depth_end ()
LeafNodeBreadthFirstIterator leaf_breadth_begin (unsigned int max_depth_arg=0u)
const LeafNodeBreadthFirstIterator leaf_breadth_end ()
OctreeBase ()
Empty constructor.
OctreeBase (const OctreeBase &source)
Copy constructor.
virtual ~OctreeBase ()
Empty deconstructor.
OctreeBase & operator= (const OctreeBase &source)
Copy operator.
void setMaxVoxelIndex (unsigned int max_voxel_index_arg)
Set the maximum amount of voxels per dimension.
void setTreeDepth (unsigned int max_depth_arg)
Set the maximum depth of the octree.
unsigned int getTreeDepth () const
Get the maximum depth of the octree.
OctreePointCloudAdjacencyContainer< PointT > * createLeaf (unsigned int idx_x_arg, unsigned int idx_y_arg, unsigned int idx_z_arg)
Create new leaf node at (idx_x_arg, idx_y_arg, idx_z_arg).
OctreePointCloudAdjacencyContainer< PointT > * findLeaf (unsigned int idx_x_arg, unsigned int idx_y_arg, unsigned int idx_z_arg)
Find leaf node at (idx_x_arg, idx_y_arg, idx_z_arg).
bool existLeaf (unsigned int idx_x_arg, unsigned int idx_y_arg, unsigned int idx_z_arg) const
idx_x_arg for the existence of leaf node at (idx_x_arg, idx_y_arg, idx_z_arg).
void removeLeaf (unsigned int idx_x_arg, unsigned int idx_y_arg, unsigned int idx_z_arg)
Remove leaf node at (idx_x_arg, idx_y_arg, idx_z_arg).
std::size_t getLeafCount () const
Return the amount of existing leafs in the octree.
std::size_t getBranchCount () const
Return the amount of existing branch nodes in the octree.
void deleteTree ()
Delete the octree structure and its leaf nodes.
void serializeTree (std::vector< char > &binary_tree_out_arg)
Serialize octree into a binary output vector describing its branch node structure.
void serializeTree (std::vector< char > &binary_tree_out_arg, std::vector< OctreePointCloudAdjacencyContainer< PointT > * > &leaf_container_vector_arg)
Serialize octree into a binary output vector describing its branch node structure and push all LeafContainerT elements stored in the octree to a vector.
void serializeLeafs (std::vector< OctreePointCloudAdjacencyContainer< PointT > * > &leaf_container_vector_arg)
Outputs a vector of all LeafContainerT elements that are stored within the octree leaf nodes.
void deserializeTree (std::vector< char > &binary_tree_input_arg)
Deserialize a binary octree description vector and create a corresponding octree structure.
void deserializeTree (std::vector< char > &binary_tree_input_arg, std::vector< OctreePointCloudAdjacencyContainer< PointT > * > &leaf_container_vector_arg)
Deserialize a binary octree description and create a corresponding octree structure.
Protected Member Functions
void addPointIdx (const int point_idx_arg) override
Add point at index from input pointcloud dataset to octree.
void computeNeighbors (OctreeKey &key_arg, LeafContainerT *leaf_container)
Fills in the neighbors fields for new voxels.
void genOctreeKeyforPoint (const PointT &point_arg, OctreeKey &key_arg) const
Generates octree key for specified point (uses transform if provided).
Protected Member Functions inherited from pcl::octree::OctreePointCloud< PointT, OctreePointCloudAdjacencyContainer< PointT >, OctreeContainerEmpty >
void expandLeafNode (LeafNode *leaf_node, BranchNode *parent_branch, unsigned char child_idx, unsigned int depth_mask)
Add point at index from input pointcloud dataset to octree.
const PointT & getPointByIndex (const unsigned int index_arg) const
Get point at index from input pointcloud dataset.
OctreePointCloudAdjacencyContainer< PointT > * findLeafAtPoint (const PointT &point_arg) const
Find octree leaf node at a given point.
void getKeyBitSize ()
Define octree key setting and octree depth based on defined bounding box.
void adoptBoundingBoxToPoint (const PointT &point_idx_arg)
Grow the bounding box/octree until point fits.
bool isPointWithinBoundingBox (const PointT &point_idx_arg) const
Checks if given point is within the bounding box of the octree.
void genOctreeKeyforPoint (const PointT &point_arg, OctreeKey &key_arg) const
Generate octree key for voxel at a given point.
void genOctreeKeyforPoint (const double point_x_arg, const double point_y_arg, const double point_z_arg, OctreeKey &key_arg) const
Generate octree key for voxel at a given point.
virtual bool genOctreeKeyForDataT (const int &data_arg, OctreeKey &key_arg) const
Virtual method for generating octree key for a given point index.
void genLeafNodeCenterFromOctreeKey (const OctreeKey &key_arg, PointT &point_arg) const
Generate a point at center of leaf node voxel.
void genVoxelCenterFromOctreeKey (const OctreeKey &key_arg, unsigned int tree_depth_arg, PointT &point_arg) const
Generate a point at center of octree voxel at given tree level.
void genVoxelBoundsFromOctreeKey (const OctreeKey &key_arg, unsigned int tree_depth_arg, Eigen::Vector3f &min_pt, Eigen::Vector3f &max_pt) const
Generate bounds of an octree voxel using octree key and tree depth arguments.
int getOccupiedVoxelCentersRecursive (const BranchNode *node_arg, const OctreeKey &key_arg, AlignedPointTVector &voxel_center_list_arg) const
Recursively search the tree for all leaf nodes and return a vector of voxel centers.
Protected Member Functions inherited from pcl::octree::OctreeBase< OctreePointCloudAdjacencyContainer< PointT >, OctreeContainerEmpty >
OctreePointCloudAdjacencyContainer< PointT > * createLeaf (const OctreeKey &key_arg)
Create a leaf node.
OctreePointCloudAdjacencyContainer< PointT > * findLeaf (const OctreeKey &key_arg) const
Find leaf node.
bool existLeaf (const OctreeKey &key_arg) const
Check for existence of a leaf node in the octree.
void removeLeaf (const OctreeKey &key_arg)
Remove leaf node from octree.
OctreeNode * getRootNode () const
Retrieve root node.
bool branchHasChild (const BranchNode &branch_arg, unsigned char child_idx_arg) const
Check if branch is pointing to a particular child node.
OctreeNode * getBranchChildPtr (const BranchNode &branch_arg, unsigned char child_idx_arg) const
Retrieve a child node pointer for child node at child_idx.
void setBranchChildPtr (BranchNode &branch_arg, unsigned char child_idx_arg, OctreeNode *new_child_arg)
Assign new child node to branch.
char getBranchBitPattern (const BranchNode &branch_arg) const
Generate bit pattern reflecting the existence of child node pointers.
void deleteBranchChild (BranchNode &branch_arg, unsigned char child_idx_arg)
Delete child node and all its subchilds from octree.
void deleteBranch (BranchNode &branch_arg)
Delete branch and all its subchilds from octree.
BranchNode * createBranchChild (BranchNode &branch_arg, unsigned char child_idx_arg)
Create and add a new branch child to a branch class.
LeafNode * createLeafChild (BranchNode &branch_arg, unsigned char child_idx_arg)
Create and add a new leaf child to a branch class.
unsigned int createLeafRecursive (const OctreeKey &key_arg, unsigned int depth_mask_arg, BranchNode *branch_arg, LeafNode *&return_leaf_arg, BranchNode *&parent_of_leaf_arg)
Create a leaf node at octree key.
void findLeafRecursive (const OctreeKey &key_arg, unsigned int depth_mask_arg, BranchNode *branch_arg, OctreePointCloudAdjacencyContainer< PointT > *&result_arg) const
Recursively search for a given leaf node and return a pointer.
bool deleteLeafRecursive (const OctreeKey &key_arg, unsigned int depth_mask_arg, BranchNode *branch_arg)
Recursively search and delete leaf node.
void serializeTreeRecursive (const BranchNode *branch_arg, OctreeKey &key_arg, std::vector< char > *binary_tree_out_arg, typename std::vector< OctreePointCloudAdjacencyContainer< PointT > * > *leaf_container_vector_arg) const
Recursively explore the octree and output binary octree description together with a vector of leaf node LeafContainerTs.
void deserializeTreeRecursive (BranchNode *branch_arg, unsigned int depth_mask_arg, OctreeKey &key_arg, typename std::vector< char >::const_iterator &binary_tree_input_it_arg, typename std::vector< char >::const_iterator &binary_tree_input_it_end_arg, typename std::vector< OctreePointCloudAdjacencyContainer< PointT > * >::const_iterator *leaf_container_vector_it_arg, typename std::vector< OctreePointCloudAdjacencyContainer< PointT > * >::const_iterator *leaf_container_vector_it_end_arg)
Recursive method for deserializing octree structure.
virtual void serializeTreeCallback (OctreePointCloudAdjacencyContainer< PointT > &, const OctreeKey &) const
Callback executed for every leaf node during serialization.
virtual void deserializeTreeCallback (OctreePointCloudAdjacencyContainer< PointT > &, const OctreeKey &)
Callback executed for every leaf node during deserialization.
double Log2 (double n_arg)
Helper function to calculate the binary logarithm.
bool octreeCanResize ()
Test if octree is able to dynamically change its depth.
Additional Inherited Members
Protected Attributes inherited from pcl::octree::OctreePointCloud< PointT, OctreePointCloudAdjacencyContainer< PointT >, OctreeContainerEmpty >
PointCloudConstPtr input_
Pointer to input point cloud dataset.
IndicesConstPtr indices_
A pointer to the vector of point indices to use.
double epsilon_
Epsilon precision (error bound) for nearest neighbors searches.
double resolution_
Octree resolution.
double min_x_
double max_x_
double min_y_
double max_y_
double min_z_
double max_z_
bool bounding_box_defined_
Flag indicating if octree has defined bounding box.
std::size_t max_objs_per_leaf_
Amount of DataT objects per leafNode before expanding branch.
Protected Attributes inherited from pcl::octree::OctreeBase< OctreePointCloudAdjacencyContainer< PointT >, OctreeContainerEmpty >
std::size_t leaf_count_
Amount of leaf nodes
std::size_t branch_count_
Amount of branch nodes
BranchNode * root_node_
Pointer to root branch node of octree
unsigned int depth_mask_
Depth mask based on octree depth
unsigned int octree_depth_
Octree depth.
bool dynamic_depth_enabled_
Enable dynamic_depth.
OctreeKey max_key_
key range
Detailed Description
template<typename PointT, typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty>
class pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >
Octree pointcloud voxel class which maintains adjacency information for its voxels.
This pointcloud octree class generates an octree from a point cloud (zero-copy). The octree pointcloud is initialized with its voxel resolution. Its bounding box is automatically adjusted or can be predefined.
The OctreePointCloudAdjacencyContainer class can be used to store data in leaf nodes.
An optional transform function can be provided which changes how the voxel grid is computed - this can be used to, for example, make voxel bins larger as they increase in distance from the origin (camera).
Note
See SupervoxelClustering for an example of how to provide a transform function.
If used in academic work, please cite:
J. Papon, A. Abramov, M. Schoeler, F. Woergoetter Voxel Cloud Connectivity Segmentation - Supervoxels from PointClouds In Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition (CVPR) 2013
Author
Jeremie Papon (jpapo.nosp@m.n@gm.nosp@m.ail.c.nosp@m.om)
Definition at line 80 of file octree_pointcloud_adjacency.h.
Member Typedef Documentation
BranchNode
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> using pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::BranchNode = typename OctreePointCloudT::BranchNode
Definition at line 94 of file octree_pointcloud_adjacency.h.
const_iterator
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> using pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::const_iterator = typename LeafVectorT::const_iterator
Definition at line 111 of file octree_pointcloud_adjacency.h.
ConstPtr
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> using pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::ConstPtr = shared_ptr<const OctreeAdjacencyT>
Definition at line 89 of file octree_pointcloud_adjacency.h.
EdgeID
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> using pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::EdgeID = typename VoxelAdjacencyList::edge_descriptor
Definition at line 104 of file octree_pointcloud_adjacency.h.
iterator
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> using pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::iterator = typename LeafVectorT::iterator
Definition at line 110 of file octree_pointcloud_adjacency.h.
LeafNode
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> using pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::LeafNode = typename OctreePointCloudT::LeafNode
Definition at line 93 of file octree_pointcloud_adjacency.h.
LeafVectorT
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> using pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::LeafVectorT = std::vector<LeafContainerT*>
Definition at line 107 of file octree_pointcloud_adjacency.h.
OctreeAdjacencyT
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> using pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::OctreeAdjacencyT = OctreePointCloudAdjacency<PointT, LeafContainerT, BranchContainerT>
Definition at line 87 of file octree_pointcloud_adjacency.h.
OctreeBaseT
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> using pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::OctreeBaseT = OctreeBase<LeafContainerT, BranchContainerT>
Definition at line 84 of file octree_pointcloud_adjacency.h.
OctreePointCloudT
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> using pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::OctreePointCloudT = OctreePointCloud<PointT, LeafContainerT, BranchContainerT, OctreeBaseT>
Definition at line 92 of file octree_pointcloud_adjacency.h.
PointCloud
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> using pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::PointCloud = pcl::PointCloud<PointT>
Definition at line 96 of file octree_pointcloud_adjacency.h.
PointCloudConstPtr
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> using pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::PointCloudConstPtr = typename PointCloud::ConstPtr
Definition at line 98 of file octree_pointcloud_adjacency.h.
PointCloudPtr
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> using pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::PointCloudPtr = typename PointCloud::Ptr
Definition at line 97 of file octree_pointcloud_adjacency.h.
Ptr
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> using pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::Ptr = shared_ptr<OctreeAdjacencyT>
Definition at line 88 of file octree_pointcloud_adjacency.h.
VoxelAdjacencyList
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> using pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::VoxelAdjacencyList = boost:: adjacency_list<boost::setS, boost::setS, boost::undirectedS, PointT, float>
Definition at line 102 of file octree_pointcloud_adjacency.h.
VoxelID
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> using pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::VoxelID = typename VoxelAdjacencyList::vertex_descriptor
Definition at line 103 of file octree_pointcloud_adjacency.h.
Constructor & Destructor Documentation
OctreePointCloudAdjacency()
template<typename PointT , typename LeafContainerT , typename BranchContainerT > pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::OctreePointCloudAdjacency (const double resolution_arg)
Constructor.
Parameters
[in] resolution_arg Octree resolution at lowest octree level (voxel size)
Definition at line 56 of file octree_pointcloud_adjacency.hpp.
Member Function Documentation
addPointIdx()
template<typename PointT , typename LeafContainerT , typename BranchContainerT > void pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::addPointIdx (const int point_idx_arg) override protected virtual
Add point at index from input pointcloud dataset to octree.
Parameters
[in] point_idx_arg The index representing the point in the dataset given by setInputCloud() to be added
Note
This virtual implementation allows the use of a transform function to compute keys.
Reimplemented from pcl::octree::OctreePointCloud< PointT, OctreePointCloudAdjacencyContainer< PointT >, OctreeContainerEmpty >.
Definition at line 157 of file octree_pointcloud_adjacency.hpp.
References pcl::isFinite().
addPointsFromInputCloud()
template<typename PointT , typename LeafContainerT , typename BranchContainerT > void pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::addPointsFromInputCloud
Adds points from cloud to the octree.
Note
This overrides addPointsFromInputCloud() from the OctreePointCloud class.
Definition at line 67 of file octree_pointcloud_adjacency.hpp.
References pcl::octree::OctreePointCloud< PointT, LeafContainerT, BranchContainerT, OctreeT >::addPointsFromInputCloud(), and pcl::isFinite().
at()
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> LeafContainerT* pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::at (std::size_t idx) inline
Definition at line 124 of file octree_pointcloud_adjacency.h.
begin()
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> iterator pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::begin () inline
Definition at line 114 of file octree_pointcloud_adjacency.h.
computeNeighbors()
template<typename PointT , typename LeafContainerT , typename BranchContainerT > void pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::computeNeighbors (OctreeKey & key_arg, LeafContainerT * leaf_container) protected
Fills in the neighbors fields for new voxels.
Parameters
[in] key_arg Key of the voxel to check neighbors for
[in] leaf_container Pointer to container of the leaf to check neighbors for
Definition at line 178 of file octree_pointcloud_adjacency.hpp.
References pcl::octree::OctreeKey::x, pcl::octree::OctreeKey::y, and pcl::octree::OctreeKey::z.
computeVoxelAdjacencyGraph()
template<typename PointT , typename LeafContainerT , typename BranchContainerT > void pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::computeVoxelAdjacencyGraph (VoxelAdjacencyList & voxel_adjacency_graph)
Computes an adjacency graph of voxel relations.
Warning
This slows down rapidly as cloud size increases due to the number of edges.
Parameters
[out] voxel_adjacency_graph Boost Graph Library Adjacency graph of the voxel touching relationships. Vertices are PointT, edges represent touching, and edge lengths are the distance between the points.
Definition at line 231 of file octree_pointcloud_adjacency.hpp.
end()
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> iterator pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::end () inline
Definition at line 119 of file octree_pointcloud_adjacency.h.
genOctreeKeyforPoint()
template<typename PointT , typename LeafContainerT , typename BranchContainerT > void pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::genOctreeKeyforPoint (const PointT & point_arg, OctreeKey & key_arg) const protected
Generates octree key for specified point (uses transform if provided).
Parameters
[in] point_arg Point to generate key for
[out] key_arg Resulting octree key
Definition at line 122 of file octree_pointcloud_adjacency.hpp.
References pcl::isFinite(), pcl::octree::OctreeKey::x, pcl::octree::OctreeKey::y, and pcl::octree::OctreeKey::z.
getLeafContainerAtPoint()
template<typename PointT , typename LeafContainerT , typename BranchContainerT > LeafContainerT * pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::getLeafContainerAtPoint (const PointT & point_arg) const
Gets the leaf container for a given point.
Parameters
[in] point_arg Point to search for
Returns
Pointer to the leaf container - null if no leaf container found.
Definition at line 215 of file octree_pointcloud_adjacency.hpp.
setTransformFunction()
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> void pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::setTransformFunction (std::function< void(PointT &p)> transform_func) inline
Sets a point transform (and inverse) used to transform the space of the input cloud.
This is useful for changing how adjacency is calculated - such as relaxing the adjacency criterion for points further from the camera.
Parameters
[in] transform_func A boost:function pointer to the transform to be used. The transform must have one parameter (a point) which it modifies in place.
Definition at line 175 of file octree_pointcloud_adjacency.h.
size()
template<typename PointT , typename LeafContainerT = OctreePointCloudAdjacencyContainer<PointT>, typename BranchContainerT = OctreeContainerEmpty> std::size_t pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::size () const inline
Definition at line 131 of file octree_pointcloud_adjacency.h.
testForOcclusion()
template<typename PointT , typename LeafContainerT , typename BranchContainerT > bool pcl::octree::OctreePointCloudAdjacency< PointT, LeafContainerT, BranchContainerT >::testForOcclusion (const PointT & point_arg, const PointXYZ & camera_pos = PointXYZ(0, 0, 0))
Tests whether input point is occluded from specified camera point by other voxels.
Parameters
[in] point_arg Point to test for
[in] camera_pos Position of camera, defaults to origin
Returns
True if path to camera is blocked by a voxel, false otherwise.
Definition at line 278 of file octree_pointcloud_adjacency.hpp.
References pcl::octree::OctreeKey::x, pcl::octree::OctreeKey::y, and pcl::octree::OctreeKey::z.
The documentation for this class was generated from the following files:
pcl/octree/octree_pointcloud_adjacency.h
pcl/octree/impl/octree_pointcloud_adjacency.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Jun 2 2020 14:13:53