Point Cloud Library (PCL): pcl::poisson::FunctionData< Degree, Real > Class Template Reference
pcl::poisson::FunctionData< Degree, Real > Class Template Reference
#include <pcl/surface/3rdparty/poisson4/function_data.h>
Public Member Functions
FunctionData (void)
~FunctionData (void)
virtual void setDotTables (const int &flags)
virtual void clearDotTables (const int &flags)
virtual void setValueTables (const int &flags, const double &smooth=0)
virtual void setValueTables (const int &flags, const double &valueSmooth, const double &normalSmooth)
virtual void clearValueTables (void)
void set (const int &maxDepth, const PPolynomial< Degree > &F, const int &normalize, bool useDotRatios=true, bool reflectBoundary=false)
Real dotProduct (const double &center1, const double &width1, const double &center2, const double &width2, int boundary1, int boundary2) const
Real dDotProduct (const double &center1, const double &width1, const double &center2, const double &width2, int boundary1, int boundary2) const
Real d2DotProduct (const double &center1, const double &width1, const double &center2, const double &width2, int boundary1, int boundary2) const
Static Public Member Functions
static int SymmetricIndex (const int &i1, const int &i2)
static int SymmetricIndex (const int &i1, const int &i2, int &index)
Public Attributes
int depth
int res
int res2
Real * dotTable
Real * dDotTable
Real * d2DotTable
Real * valueTables
Real * dValueTables
PPolynomial< Degree > baseFunction
PPolynomial< Degree > leftBaseFunction
PPolynomial< Degree > rightBaseFunction
PPolynomial< Degree-1 > dBaseFunction
PPolynomial< Degree-1 > dLeftBaseFunction
PPolynomial< Degree-1 > dRightBaseFunction
PPolynomial< Degree+1 > * baseFunctions
Static Public Attributes
const static int DOT_FLAG = 1
const static int D_DOT_FLAG = 2
const static int D2_DOT_FLAG = 4
const static int VALUE_FLAG = 1
const static int D_VALUE_FLAG = 2
Detailed Description
template<int Degree, class Real>
class pcl::poisson::FunctionData< Degree, Real >
Definition at line 47 of file function_data.h.
Constructor & Destructor Documentation
FunctionData()
template<int Degree, class Real > pcl::poisson::FunctionData< Degree, Real >::FunctionData (void)
Definition at line 39 of file function_data.hpp.
~FunctionData()
template<int Degree, class Real > pcl::poisson::FunctionData< Degree, Real >::~FunctionData (void)
Definition at line 47 of file function_data.hpp.
Member Function Documentation
clearDotTables()
template<int Degree, class Real > void pcl::poisson::FunctionData< Degree, Real >::clearDotTables (const int & flags) virtual
Definition at line 225 of file function_data.hpp.
clearValueTables()
template<int Degree, class Real > void pcl::poisson::FunctionData< Degree, Real >::clearValueTables (void) virtual
Definition at line 288 of file function_data.hpp.
d2DotProduct()
template<int Degree, class Real > Real pcl::poisson::FunctionData< Degree, Real >::d2DotProduct (const double & center1, const double & width1, const double & center2, const double & width2, int boundary1, int boundary2) const
Definition at line 385 of file function_data.hpp.
dDotProduct()
template<int Degree, class Real > Real pcl::poisson::FunctionData< Degree, Real >::dDotProduct (const double & center1, const double & width1, const double & center2, const double & width2, int boundary1, int boundary2) const
Definition at line 373 of file function_data.hpp.
dotProduct()
template<int Degree, class Real > Real pcl::poisson::FunctionData< Degree, Real >::dotProduct (const double & center1, const double & width1, const double & center2, const double & width2, int boundary1, int boundary2) const
Definition at line 360 of file function_data.hpp.
set()
template<int Degree, class Real > void pcl::poisson::FunctionData< Degree, Real >::set (const int & maxDepth, const PPolynomial< Degree > & F, const int & normalize, bool useDotRatios = true, bool reflectBoundary = false)
Definition at line 66 of file function_data.hpp.
References pcl::poisson::BinaryNode< Real >::CenterAndWidth(), pcl::poisson::BinaryNode< Real >::CumulativeCenterCount(), and pcl::poisson::BinaryNode< Real >::DepthAndOffset().
setDotTables()
template<int Degree, class Real > void pcl::poisson::FunctionData< Degree, Real >::setDotTables (const int & flags) virtual
Definition at line 131 of file function_data.hpp.
References pcl::poisson::BinaryNode< Real >::CenterAndWidth(), and pcl::poisson::BinaryNode< Real >::DepthAndOffset().
setValueTables() [1/2]
template<int Degree, class Real > void pcl::poisson::FunctionData< Degree, Real >::setValueTables (const int & flags, const double & smooth = 0) virtual
Definition at line 238 of file function_data.hpp.
References pcl::poisson::PPolynomial< Degree >::derivative(), and pcl::poisson::PPolynomial< Degree >::MovingAverage().
setValueTables() [2/2]
template<int Degree, class Real > void pcl::poisson::FunctionData< Degree, Real >::setValueTables (const int & flags, const double & valueSmooth, const double & normalSmooth) virtual
Definition at line 266 of file function_data.hpp.
References pcl::poisson::PPolynomial< Degree >::derivative(), and pcl::poisson::PPolynomial< Degree >::MovingAverage().
SymmetricIndex() [1/2]
template<int Degree, class Real > int pcl::poisson::FunctionData< Degree, Real >::SymmetricIndex (const int & i1, const int & i2) inline static
Definition at line 398 of file function_data.hpp.
SymmetricIndex() [2/2]
template<int Degree, class Real > int pcl::poisson::FunctionData< Degree, Real >::SymmetricIndex (const int & i1, const int & i2, int & index) inline static
Definition at line 404 of file function_data.hpp.
Member Data Documentation
baseFunction
template<int Degree, class Real > PPolynomial<Degree> pcl::poisson::FunctionData< Degree, Real >::baseFunction
Definition at line 64 of file function_data.h.
baseFunctions
template<int Degree, class Real > PPolynomial<Degree+1>* pcl::poisson::FunctionData< Degree, Real >::baseFunctions
Definition at line 70 of file function_data.h.
D2_DOT_FLAG
template<int Degree, class Real > const static int pcl::poisson::FunctionData< Degree, Real >::D2_DOT_FLAG = 4 static
Definition at line 56 of file function_data.h.
d2DotTable
template<int Degree, class Real > Real * pcl::poisson::FunctionData< Degree, Real >::d2DotTable
Definition at line 61 of file function_data.h.
D_DOT_FLAG
template<int Degree, class Real > const static int pcl::poisson::FunctionData< Degree, Real >::D_DOT_FLAG = 2 static
Definition at line 55 of file function_data.h.
D_VALUE_FLAG
template<int Degree, class Real > const static int pcl::poisson::FunctionData< Degree, Real >::D_VALUE_FLAG = 2 static
Definition at line 58 of file function_data.h.
dBaseFunction
template<int Degree, class Real > PPolynomial<Degree-1> pcl::poisson::FunctionData< Degree, Real >::dBaseFunction
Definition at line 65 of file function_data.h.
dDotTable
template<int Degree, class Real > Real * pcl::poisson::FunctionData< Degree, Real >::dDotTable
Definition at line 61 of file function_data.h.
depth
template<int Degree, class Real > int pcl::poisson::FunctionData< Degree, Real >::depth
Definition at line 60 of file function_data.h.
dLeftBaseFunction
template<int Degree, class Real > PPolynomial<Degree-1> pcl::poisson::FunctionData< Degree, Real >::dLeftBaseFunction
Definition at line 65 of file function_data.h.
DOT_FLAG
template<int Degree, class Real > const static int pcl::poisson::FunctionData< Degree, Real >::DOT_FLAG = 1 static
Definition at line 54 of file function_data.h.
dotTable
template<int Degree, class Real > Real* pcl::poisson::FunctionData< Degree, Real >::dotTable
Definition at line 61 of file function_data.h.
dRightBaseFunction
template<int Degree, class Real > PPolynomial<Degree-1> pcl::poisson::FunctionData< Degree, Real >::dRightBaseFunction
Definition at line 65 of file function_data.h.
dValueTables
template<int Degree, class Real > Real * pcl::poisson::FunctionData< Degree, Real >::dValueTables
Definition at line 62 of file function_data.h.
leftBaseFunction
template<int Degree, class Real > PPolynomial<Degree> pcl::poisson::FunctionData< Degree, Real >::leftBaseFunction
Definition at line 64 of file function_data.h.
res
template<int Degree, class Real > int pcl::poisson::FunctionData< Degree, Real >::res
Definition at line 60 of file function_data.h.
res2
template<int Degree, class Real > int pcl::poisson::FunctionData< Degree, Real >::res2
Definition at line 60 of file function_data.h.
rightBaseFunction
template<int Degree, class Real > PPolynomial<Degree> pcl::poisson::FunctionData< Degree, Real >::rightBaseFunction
Definition at line 64 of file function_data.h.
VALUE_FLAG
template<int Degree, class Real > const static int pcl::poisson::FunctionData< Degree, Real >::VALUE_FLAG = 1 static
Definition at line 57 of file function_data.h.
valueTables
template<int Degree, class Real > Real* pcl::poisson::FunctionData< Degree, Real >::valueTables
Definition at line 62 of file function_data.h.
The documentation for this class was generated from the following files:
pcl/surface/3rdparty/poisson4/function_data.h
pcl/surface/3rdparty/poisson4/function_data.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Jun 2 2020 14:14:17