Point Cloud Library (PCL): pcl::SampleConsensusModelNormalPlane< PointT, PointNT > Class Template Reference
pcl::SampleConsensusModelNormalPlane< PointT, PointNT > Class Template Reference
Module sample_consensus
SampleConsensusModelNormalPlane defines a model for 3D plane segmentation using additional surface normal constraints.
#include <pcl/sample_consensus/sac_model_normal_plane.h>
Public Types
using PointCloud = typename SampleConsensusModel< PointT >::PointCloud
using PointCloudPtr = typename SampleConsensusModel< PointT >::PointCloudPtr
using PointCloudConstPtr = typename SampleConsensusModel< PointT >::PointCloudConstPtr
using PointCloudNPtr = typename SampleConsensusModelFromNormals< PointT, PointNT >::PointCloudNPtr
using PointCloudNConstPtr = typename SampleConsensusModelFromNormals< PointT, PointNT >::PointCloudNConstPtr
using Ptr = shared_ptr< SampleConsensusModelNormalPlane< PointT, PointNT > >
using ConstPtr = shared_ptr< const SampleConsensusModelNormalPlane< PointT, PointNT > >
Public Types inherited from pcl::SampleConsensusModelPlane< PointT >
using PointCloud = typename SampleConsensusModel< PointT >::PointCloud
using PointCloudPtr = typename SampleConsensusModel< PointT >::PointCloudPtr
using PointCloudConstPtr = typename SampleConsensusModel< PointT >::PointCloudConstPtr
using Ptr = shared_ptr< SampleConsensusModelPlane< PointT > >
using ConstPtr = shared_ptr< const SampleConsensusModelPlane< PointT > >
Public Types inherited from pcl::SampleConsensusModel< PointT >
using PointCloud = pcl::PointCloud< PointT >
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointCloudPtr = typename PointCloud::Ptr
using SearchPtr = typename pcl::search::Search< PointT >::Ptr
using Ptr = shared_ptr< SampleConsensusModel< PointT > >
using ConstPtr = shared_ptr< const SampleConsensusModel< PointT > >
Public Types inherited from pcl::SampleConsensusModelFromNormals< PointT, PointNT >
using PointCloudNConstPtr = typename pcl::PointCloud< PointNT >::ConstPtr
using PointCloudNPtr = typename pcl::PointCloud< PointNT >::Ptr
using Ptr = shared_ptr< SampleConsensusModelFromNormals< PointT, PointNT > >
using ConstPtr = shared_ptr< const SampleConsensusModelFromNormals< PointT, PointNT > >
Public Member Functions
SampleConsensusModelNormalPlane (const PointCloudConstPtr &cloud, bool random=false)
Constructor for base SampleConsensusModelNormalPlane.
SampleConsensusModelNormalPlane (const PointCloudConstPtr &cloud, const Indices &indices, bool random=false)
Constructor for base SampleConsensusModelNormalPlane.
~SampleConsensusModelNormalPlane () override=default
Empty destructor.
void selectWithinDistance (const Eigen::VectorXf &model_coefficients, const double threshold, Indices &inliers) override
Select all the points which respect the given model coefficients as inliers.
std::size_t countWithinDistance (const Eigen::VectorXf &model_coefficients, const double threshold) const override
Count all the points which respect the given model coefficients as inliers.
void getDistancesToModel (const Eigen::VectorXf &model_coefficients, std::vector< double > &distances) const override
Compute all distances from the cloud data to a given plane model.
pcl::SacModel getModelType () const override
Return a unique id for this model (SACMODEL_NORMAL_PLANE).
Public Member Functions inherited from pcl::SampleConsensusModelPlane< PointT >
SampleConsensusModelPlane (const PointCloudConstPtr &cloud, bool random=false)
Constructor for base SampleConsensusModelPlane.
SampleConsensusModelPlane (const PointCloudConstPtr &cloud, const Indices &indices, bool random=false)
Constructor for base SampleConsensusModelPlane.
~SampleConsensusModelPlane () override=default
Empty destructor.
bool computeModelCoefficients (const Indices &samples, Eigen::VectorXf &model_coefficients) const override
Check whether the given index samples can form a valid plane model, compute the model coefficients from these samples and store them internally in model_coefficients_.
void getDistancesToModel (const Eigen::VectorXf &model_coefficients, std::vector< double > &distances) const override
Compute all distances from the cloud data to a given plane model.
void selectWithinDistance (const Eigen::VectorXf &model_coefficients, const double threshold, Indices &inliers) override
Select all the points which respect the given model coefficients as inliers.
std::size_t countWithinDistance (const Eigen::VectorXf &model_coefficients, const double threshold) const override
Count all the points which respect the given model coefficients as inliers.
void optimizeModelCoefficients (const Indices &inliers, const Eigen::VectorXf &model_coefficients, Eigen::VectorXf &optimized_coefficients) const override
Recompute the plane coefficients using the given inlier set and return them to the user.
void projectPoints (const Indices &inliers, const Eigen::VectorXf &model_coefficients, PointCloud &projected_points, bool copy_data_fields=true) const override
Create a new point cloud with inliers projected onto the plane model.
bool doSamplesVerifyModel (const std::set< index_t > &indices, const Eigen::VectorXf &model_coefficients, const double threshold) const override
Verify whether a subset of indices verifies the given plane model coefficients.
pcl::SacModel getModelType () const override
Return a unique id for this model (SACMODEL_PLANE).
Public Member Functions inherited from pcl::SampleConsensusModel< PointT >
SampleConsensusModel (const PointCloudConstPtr &cloud, bool random=false)
Constructor for base SampleConsensusModel.
SampleConsensusModel (const PointCloudConstPtr &cloud, const Indices &indices, bool random=false)
Constructor for base SampleConsensusModel.
virtual ~SampleConsensusModel ()=default
Destructor for base SampleConsensusModel.
virtual void getSamples (int &iterations, Indices &samples)
Get a set of random data samples and return them as point indices.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr getInputCloud () const
Get a pointer to the input point cloud dataset.
void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
void setIndices (const Indices &indices)
Provide the vector of indices that represents the input data.
IndicesPtr getIndices () const
Get a pointer to the vector of indices used.
const std::string & getClassName () const
Get a string representation of the name of this class.
unsigned int getSampleSize () const
Return the size of a sample from which the model is computed.
unsigned int getModelSize () const
Return the number of coefficients in the model.
void setRadiusLimits (const double &min_radius, const double &max_radius)
Set the minimum and maximum allowable radius limits for the model (applicable to models that estimate a radius)
void getRadiusLimits (double &min_radius, double &max_radius) const
Get the minimum and maximum allowable radius limits for the model as set by the user.
void setModelConstraints (std::function< bool(const Eigen::VectorXf &)> function)
This can be used to impose any kind of constraint on the model, e.g.
void setSamplesMaxDist (const double &radius, SearchPtr search)
Set the maximum distance allowed when drawing random samples.
void getSamplesMaxDist (double &radius) const
Get maximum distance allowed when drawing random samples.
double computeVariance (const std::vector< double > &error_sqr_dists) const
Compute the variance of the errors to the model.
double computeVariance () const
Compute the variance of the errors to the model from the internally estimated vector of distances.
Public Member Functions inherited from pcl::SampleConsensusModelFromNormals< PointT, PointNT >
SampleConsensusModelFromNormals ()
Empty constructor for base SampleConsensusModelFromNormals.
virtual ~SampleConsensusModelFromNormals ()=default
Destructor.
void setNormalDistanceWeight (const double w)
Set the normal angular distance weight.
double getNormalDistanceWeight () const
Get the normal angular distance weight.
void setInputNormals (const PointCloudNConstPtr &normals)
Provide a pointer to the input dataset that contains the point normals of the XYZ dataset.
PointCloudNConstPtr getInputNormals () const
Get a pointer to the normals of the input XYZ point cloud dataset.
Protected Member Functions
std::size_t countWithinDistanceStandard (const Eigen::VectorXf &model_coefficients, const double threshold, std::size_t i=0) const
This implementation uses no SIMD instructions.
Protected Member Functions inherited from pcl::SampleConsensusModelPlane< PointT >
std::size_t countWithinDistanceStandard (const Eigen::VectorXf &model_coefficients, const double threshold, std::size_t i=0) const
This implementation uses no SIMD instructions.
Protected Member Functions inherited from pcl::SampleConsensusModel< PointT >
SampleConsensusModel (bool random=false)
Empty constructor for base SampleConsensusModel.
void drawIndexSample (Indices &sample)
Fills a sample array with random samples from the indices_ vector.
void drawIndexSampleRadius (Indices &sample)
Fills a sample array with one random sample from the indices_ vector and other random samples that are closer than samples_radius_.
virtual bool isModelValid (const Eigen::VectorXf &model_coefficients) const
Check whether a model is valid given the user constraints.
int rnd ()
Boost-based random number generator.
Additional Inherited Members
Protected Attributes inherited from pcl::SampleConsensusModel< PointT >
std::string model_name_
The model name.
PointCloudConstPtr input_
A boost shared pointer to the point cloud data array.
IndicesPtr indices_
A pointer to the vector of point indices to use.
double radius_min_
The minimum and maximum radius limits for the model.
double radius_max_
double samples_radius_
The maximum distance of subsequent samples from the first (radius search)
SearchPtr samples_radius_search_
The search object for picking subsequent samples using radius search.
Indices shuffled_indices_
Data containing a shuffled version of the indices.
boost::mt19937 rng_alg_
Boost-based random number generator algorithm.
std::shared_ptr< boost::uniform_int<> > rng_dist_
Boost-based random number generator distribution.
std::shared_ptr< boost::variate_generator< boost::mt19937 &, boost::uniform_int<> > > rng_gen_
Boost-based random number generator.
std::vector< double > error_sqr_dists_
A vector holding the distances to the computed model.
unsigned int sample_size_
The size of a sample from which the model is computed.
unsigned int model_size_
The number of coefficients in the model.
std::function< bool(const Eigen::VectorXf &)> custom_model_constraints_
A user defined function that takes model coefficients and returns whether the model is acceptable or not.
Protected Attributes inherited from pcl::SampleConsensusModelFromNormals< PointT, PointNT >
double normal_distance_weight_ {0.0}
The relative weight (between 0 and 1) to give to the angular distance (0 to pi/2) between point normals and the plane normal.
PointCloudNConstPtr normals_
A pointer to the input dataset that contains the point normals of the XYZ dataset.
Static Protected Attributes inherited from pcl::SampleConsensusModel< PointT >
static const unsigned int max_sample_checks_ = 1000
The maximum number of samples to try until we get a good one.
Detailed Description
template<typename PointT, typename PointNT>
class pcl::SampleConsensusModelNormalPlane< PointT, PointNT >
SampleConsensusModelNormalPlane defines a model for 3D plane segmentation using additional surface normal constraints.
Basically this means that checking for inliers will not only involve a "distance to model" criterion, but also an additional "maximum angular deviation" between the plane's normal and the inlier points normals.
The model coefficients are defined as:
a : the X coordinate of the plane's normal (normalized)
b : the Y coordinate of the plane's normal (normalized)
c : the Z coordinate of the plane's normal (normalized)
d : the fourth Hessian component of the plane's equation
To set the influence of the surface normals in the inlier estimation process, set the normal weight (0.0-1.0), e.g.:
SampleConsensusModelNormalPlane<pcl::PointXYZ, pcl::Normal> sac_model;
...
sac_model.setNormalDistanceWeight (0.1);
...
Author
Radu B. Rusu and Jared Glover
Definition at line 76 of file sac_model_normal_plane.h.
Member Typedef Documentation
ConstPtr
template<typename PointT , typename PointNT > using pcl::SampleConsensusModelNormalPlane< PointT, PointNT >::ConstPtr = shared_ptr<const SampleConsensusModelNormalPlane<PointT, PointNT> >
Definition at line 95 of file sac_model_normal_plane.h.
PointCloud
template<typename PointT , typename PointNT > using pcl::SampleConsensusModelNormalPlane< PointT, PointNT >::PointCloud = typename SampleConsensusModel<PointT>::PointCloud
Definition at line 87 of file sac_model_normal_plane.h.
PointCloudConstPtr
template<typename PointT , typename PointNT > using pcl::SampleConsensusModelNormalPlane< PointT, PointNT >::PointCloudConstPtr = typename SampleConsensusModel<PointT>::PointCloudConstPtr
Definition at line 89 of file sac_model_normal_plane.h.
PointCloudNConstPtr
template<typename PointT , typename PointNT > using pcl::SampleConsensusModelNormalPlane< PointT, PointNT >::PointCloudNConstPtr = typename SampleConsensusModelFromNormals<PointT, PointNT>::PointCloudNConstPtr
Definition at line 92 of file sac_model_normal_plane.h.
PointCloudNPtr
template<typename PointT , typename PointNT > using pcl::SampleConsensusModelNormalPlane< PointT, PointNT >::PointCloudNPtr = typename SampleConsensusModelFromNormals<PointT, PointNT>::PointCloudNPtr
Definition at line 91 of file sac_model_normal_plane.h.
PointCloudPtr
template<typename PointT , typename PointNT > using pcl::SampleConsensusModelNormalPlane< PointT, PointNT >::PointCloudPtr = typename SampleConsensusModel<PointT>::PointCloudPtr
Definition at line 88 of file sac_model_normal_plane.h.
Ptr
template<typename PointT , typename PointNT > using pcl::SampleConsensusModelNormalPlane< PointT, PointNT >::Ptr = shared_ptr<SampleConsensusModelNormalPlane<PointT, PointNT> >
Definition at line 94 of file sac_model_normal_plane.h.
Constructor & Destructor Documentation
SampleConsensusModelNormalPlane() [1/2]
template<typename PointT , typename PointNT > pcl::SampleConsensusModelNormalPlane< PointT, PointNT >::SampleConsensusModelNormalPlane (const PointCloudConstPtr & cloud, bool random = false) inline
Constructor for base SampleConsensusModelNormalPlane.
Parameters
[in] cloud the input point cloud dataset
[in] random if true set the random seed to the current time, else set to 12345 (default: false)
Definition at line 101 of file sac_model_normal_plane.h.
References pcl::SampleConsensusModel< PointT >::model_name_, pcl::SampleConsensusModel< PointT >::model_size_, and pcl::SampleConsensusModel< PointT >::sample_size_.
SampleConsensusModelNormalPlane() [2/2]
template<typename PointT , typename PointNT > pcl::SampleConsensusModelNormalPlane< PointT, PointNT >::SampleConsensusModelNormalPlane (const PointCloudConstPtr & cloud, const Indices & indices, bool random = false) inline
Constructor for base SampleConsensusModelNormalPlane.
Parameters
[in] cloud the input point cloud dataset
[in] indices a vector of point indices to be used from cloud
[in] random if true set the random seed to the current time, else set to 12345 (default: false)
Definition at line 116 of file sac_model_normal_plane.h.
References pcl::SampleConsensusModel< PointT >::model_name_, pcl::SampleConsensusModel< PointT >::model_size_, and pcl::SampleConsensusModel< PointT >::sample_size_.
~SampleConsensusModelNormalPlane()
template<typename PointT , typename PointNT > pcl::SampleConsensusModelNormalPlane< PointT, PointNT >::~SampleConsensusModelNormalPlane () override default
Empty destructor.
Member Function Documentation
countWithinDistance()
template<typename PointT , typename PointNT > std::size_t pcl::SampleConsensusModelNormalPlane< PointT, PointNT >::countWithinDistance (const Eigen::VectorXf & model_coefficients, const double threshold) const override virtual
Count all the points which respect the given model coefficients as inliers.
Parameters
[in] model_coefficients the coefficients of a model that we need to compute distances to
[in] threshold maximum admissible distance threshold for determining the inliers from the outliers
Returns
the resultant number of inliers
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 105 of file sac_model_normal_plane.hpp.
countWithinDistanceStandard()
template<typename PointT , typename PointNT > std::size_t pcl::SampleConsensusModelNormalPlane< PointT, PointNT >::countWithinDistanceStandard (const Eigen::VectorXf & model_coefficients, const double threshold, std::size_t i = 0) const protected
This implementation uses no SIMD instructions.
It is not intended for normal use. See countWithinDistance which automatically uses the fastest implementation.
Definition at line 129 of file sac_model_normal_plane.hpp.
References pcl::getAngle3D(), and M_PI.
getDistancesToModel()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelNormalPlane< PointT, PointNT >::getDistancesToModel (const Eigen::VectorXf & model_coefficients, std::vector< double > & distances) const override virtual
Compute all distances from the cloud data to a given plane model.
Parameters
[in] model_coefficients the coefficients of a plane model that we need to compute distances to
[out] distances the resultant estimated distances
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 292 of file sac_model_normal_plane.hpp.
References pcl::getAngle3D(), and M_PI.
getModelType()
template<typename PointT , typename PointNT > pcl::SacModel pcl::SampleConsensusModelNormalPlane< PointT, PointNT >::getModelType () const inline override virtual
Return a unique id for this model (SACMODEL_NORMAL_PLANE).
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 160 of file sac_model_normal_plane.h.
References pcl::SACMODEL_NORMAL_PLANE.
selectWithinDistance()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelNormalPlane< PointT, PointNT >::selectWithinDistance (const Eigen::VectorXf & model_coefficients, const double threshold, Indices & inliers) override virtual
Select all the points which respect the given model coefficients as inliers.
Parameters
[in] model_coefficients the coefficients of a plane model that we need to compute distances to
[in] threshold a maximum admissible distance threshold for determining the inliers from the outliers
[out] inliers the resultant model inliers
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 49 of file sac_model_normal_plane.hpp.
References pcl::geometry::distance(), pcl::getAngle3D(), and M_PI.
The documentation for this class was generated from the following files:
pcl/sample_consensus/sac_model_normal_plane.h
pcl/sample_consensus/impl/sac_model_normal_plane.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:20