Point Cloud Library (PCL): NCVMatrix< T > Class Template Reference
NCVMatrix< T > Class Template Reference
NCVMatrix (2D)
#include </__w/1/s/gpu/people/src/cuda/nvidia/NCV.hpp>
Public Member Functions
NCVMatrix ()
void clear ()
Ncv32u stride () const
NCVStatus copySolid (NCVMatrix< T > &dst, cudaStream_t cuStream, std::size_t howMuch=0) const
NCVStatus copy2D (NCVMatrix< T > &dst, NcvSize32u roi, cudaStream_t cuStream) const
T & at (Ncv32u x, Ncv32u y) const
T * ptr () const
Ncv32u width () const
Ncv32u height () const
NcvSize32u size () const
Ncv32u pitch () const
NCVMemoryType memType () const
Protected Attributes
T * _ptr
Ncv32u _width
Ncv32u _height
Ncv32u _pitch
NCVMemoryType _memtype
Detailed Description
template<class T>
class NCVMatrix< T >
NCVMatrix (2D)
Definition at line 674 of file NCV.hpp.
Constructor & Destructor Documentation
NCVMatrix()
template<class T > NCVMatrix< T >::NCVMatrix () inline
Definition at line 680 of file NCV.hpp.
References NCVMatrix< T >::clear().
Member Function Documentation
at()
template<class T > T& NCVMatrix< T >::at (Ncv32u x, Ncv32u y) const inline
Definition at line 746 of file NCV.hpp.
References NCVMatrix< T >::_height, NCVMatrix< T >::_pitch, NCVMatrix< T >::_ptr, and NCVMatrix< T >::_width.
Referenced by NCVMatrixReuse< T >::NCVMatrixReuse().
clear()
template<class T > void NCVMatrix< T >::clear () inline
Definition at line 685 of file NCV.hpp.
References NCVMatrix< T >::_height, NCVMatrix< T >::_memtype, NCVMatrix< T >::_pitch, NCVMatrix< T >::_ptr, and NCVMatrix< T >::_width.
Referenced by NCVMatrix< T >::NCVMatrix(), NCVMatrixAlloc< T >::NCVMatrixAlloc(), NCVMatrixReuse< T >::NCVMatrixReuse(), and NCVMatrixAlloc< T >::~NCVMatrixAlloc().
copy2D()
template<class T > NCVStatus NCVMatrix< T >::copy2D (NCVMatrix< T > & dst, NcvSize32u roi, cudaStream_t cuStream) const inline
Definition at line 728 of file NCV.hpp.
References NCVMatrix< T >::_memtype, NCVMatrix< T >::_pitch, NCVMatrix< T >::_ptr, NcvSize32u::height, NCVMatrix< T >::height(), NcvSize32u::width, and NCVMatrix< T >::width().
copySolid()
template<class T > NCVStatus NCVMatrix< T >::copySolid (NCVMatrix< T > & dst, cudaStream_t cuStream, std::size_t howMuch = 0) const inline
Definition at line 700 of file NCV.hpp.
References NCVMatrix< T >::_height, NCVMatrix< T >::_memtype, NCVMatrix< T >::_pitch, and NCVMatrix< T >::_ptr.
height()
template<class T > Ncv32u NCVMatrix< T >::height () const inline
Definition at line 759 of file NCV.hpp.
References NCVMatrix< T >::_height.
Referenced by NCVMatrix< T >::copy2D(), NCVMatrixAlloc< T >::NCVMatrixAlloc(), and NCVMatrixReuse< T >::NCVMatrixReuse().
memType()
template<class T > NCVMemoryType NCVMatrix< T >::memType () const inline
Definition at line 762 of file NCV.hpp.
References NCVMatrix< T >::_memtype.
Referenced by NCVMatrixReuse< T >::NCVMatrixReuse().
pitch()
template<class T > Ncv32u NCVMatrix< T >::pitch () const inline
Definition at line 761 of file NCV.hpp.
References NCVMatrix< T >::_pitch.
Referenced by NCVMatrixAlloc< T >::NCVMatrixAlloc(), and NCVMatrixReuse< T >::NCVMatrixReuse().
ptr()
template<class T > T* NCVMatrix< T >::ptr () const inline
Definition at line 757 of file NCV.hpp.
References NCVMatrix< T >::_ptr.
size()
template<class T > NcvSize32u NCVMatrix< T >::size () const inline
Definition at line 760 of file NCV.hpp.
References NCVMatrix< T >::_height, and NCVMatrix< T >::_width.
stride()
template<class T > Ncv32u NCVMatrix< T >::stride () const inline
Definition at line 694 of file NCV.hpp.
References NCVMatrix< T >::_pitch.
width()
template<class T > Ncv32u NCVMatrix< T >::width () const inline
Definition at line 758 of file NCV.hpp.
References NCVMatrix< T >::_width.
Referenced by NCVMatrix< T >::copy2D(), NCVMatrixAlloc< T >::NCVMatrixAlloc(), and NCVMatrixReuse< T >::NCVMatrixReuse().
Member Data Documentation
_height
template<class T > Ncv32u NCVMatrix< T >::_height protected
Definition at line 768 of file NCV.hpp.
Referenced by NCVMatrix< T >::at(), NCVMatrix< T >::clear(), NCVMatrix< T >::copySolid(), NCVMatrix< T >::height(), NCVMatrixReuse< T >::NCVMatrixReuse(), and NCVMatrix< T >::size().
_memtype
template<class T > NCVMemoryType NCVMatrix< T >::_memtype protected
Definition at line 770 of file NCV.hpp.
Referenced by NCVMatrix< T >::clear(), NCVMatrix< T >::copy2D(), NCVMatrix< T >::copySolid(), NCVMatrix< T >::memType(), and NCVMatrixReuse< T >::NCVMatrixReuse().
_pitch
template<class T > Ncv32u NCVMatrix< T >::_pitch protected
Definition at line 769 of file NCV.hpp.
Referenced by NCVMatrix< T >::at(), NCVMatrix< T >::clear(), NCVMatrix< T >::copy2D(), NCVMatrix< T >::copySolid(), NCVMatrixReuse< T >::NCVMatrixReuse(), NCVMatrix< T >::pitch(), and NCVMatrix< T >::stride().
_ptr
template<class T > T* NCVMatrix< T >::_ptr protected
Definition at line 766 of file NCV.hpp.
Referenced by NCVMatrix< T >::at(), NCVMatrix< T >::clear(), NCVMatrix< T >::copy2D(), NCVMatrix< T >::copySolid(), NCVMatrixAlloc< T >::NCVMatrixAlloc(), NCVMatrixReuse< T >::NCVMatrixReuse(), and NCVMatrix< T >::ptr().
_width
template<class T > Ncv32u NCVMatrix< T >::_width protected
Definition at line 767 of file NCV.hpp.
Referenced by NCVMatrix< T >::at(), NCVMatrix< T >::clear(), NCVMatrixReuse< T >::NCVMatrixReuse(), NCVMatrix< T >::size(), and NCVMatrix< T >::width().
The documentation for this class was generated from the following file:
/__w/1/s/gpu/people/src/cuda/nvidia/NCV.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:06