Point Cloud Library (PCL): NCVVector< T > Class Template Reference
NCVVector< T > Class Template Reference
NCVVector (1D)
#include </__w/1/s/gpu/people/src/cuda/nvidia/NCV.hpp>
Public Member Functions
NCVVector ()
virtual ~NCVVector ()
void clear ()
NCVStatus copySolid (NCVVector< T > &dst, cudaStream_t cuStream, std::size_t howMuch=0) const
T * ptr () const
std::size_t length () const
NCVMemoryType memType () const
Protected Attributes
T * _ptr
std::size_t _length
NCVMemoryType _memtype
Detailed Description
template<class T>
class NCVVector< T >
NCVVector (1D)
Definition at line 507 of file NCV.hpp.
Constructor & Destructor Documentation
NCVVector()
template<class T > NCVVector< T >::NCVVector () inline
Definition at line 513 of file NCV.hpp.
~NCVVector()
template<class T > virtual NCVVector< T >::~NCVVector () inline virtual
Definition at line 518 of file NCV.hpp.
Member Function Documentation
clear()
template<class T > void NCVVector< T >::clear () inline
Definition at line 520 of file NCV.hpp.
Referenced by NCVVector< HaarClassifierNode128 >::NCVVector(), NCVVectorAlloc< HaarClassifierNode128 >::NCVVectorAlloc(), NCVVectorReuse< T >::NCVVectorReuse(), and NCVVectorAlloc< HaarClassifierNode128 >::~NCVVectorAlloc().
copySolid()
template<class T > NCVStatus NCVVector< T >::copySolid (NCVVector< T > & dst, cudaStream_t cuStream, std::size_t howMuch = 0) const inline
Definition at line 527 of file NCV.hpp.
length()
template<class T > std::size_t NCVVector< T >::length () const inline
Definition at line 555 of file NCV.hpp.
Referenced by NCVVectorAlloc< HaarClassifierNode128 >::NCVVectorAlloc(), and NCVVectorReuse< T >::NCVVectorReuse().
memType()
template<class T > NCVMemoryType NCVVector< T >::memType () const inline
Definition at line 556 of file NCV.hpp.
ptr()
template<class T > T* NCVVector< T >::ptr () const inline
Definition at line 554 of file NCV.hpp.
Member Data Documentation
_length
template<class T > std::size_t NCVVector< T >::_length protected
Definition at line 561 of file NCV.hpp.
Referenced by NCVVector< HaarClassifierNode128 >::clear(), NCVVector< HaarClassifierNode128 >::copySolid(), NCVVector< HaarClassifierNode128 >::length(), and NCVVectorReuse< T >::NCVVectorReuse().
_memtype
template<class T > NCVMemoryType NCVVector< T >::_memtype protected
Definition at line 562 of file NCV.hpp.
Referenced by NCVVector< HaarClassifierNode128 >::clear(), NCVVector< HaarClassifierNode128 >::copySolid(), and NCVVector< HaarClassifierNode128 >::memType().
_ptr
template<class T > T* NCVVector< T >::_ptr protected
Definition at line 560 of file NCV.hpp.
Referenced by NCVVector< HaarClassifierNode128 >::clear(), NCVVector< HaarClassifierNode128 >::copySolid(), NCVVectorAlloc< HaarClassifierNode128 >::NCVVectorAlloc(), NCVVectorReuse< T >::NCVVectorReuse(), and NCVVector< HaarClassifierNode128 >::ptr().
The documentation for this class was generated from the following file:
/__w/1/s/gpu/people/src/cuda/nvidia/NCV.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Jun 2 2020 14:11:06