Point Cloud Library (PCL): pcl::PlanarPolygon< PointT > Class Template Reference
pcl::PlanarPolygon< PointT > Class Template Reference
PlanarPolygon represents a planar (2D) polygon, potentially in a 3D space.
#include <pcl/geometry/planar_polygon.h>
Public Types
using Ptr = shared_ptr< PlanarPolygon< PointT > >
using ConstPtr = shared_ptr< const PlanarPolygon< PointT > >
Public Member Functions
PlanarPolygon ()
Empty constructor for PlanarPolygon.
PlanarPolygon (typename pcl::PointCloud< PointT >::VectorType &contour, Eigen::Vector4f &coefficients)
Constructor for PlanarPolygon.
virtual ~PlanarPolygon ()
Destructor.
void setContour (const pcl::PointCloud< PointT > &contour)
Set the internal contour.
pcl::PointCloud< PointT >::VectorType & getContour ()
Getter for the contour / boundary.
const pcl::PointCloud< PointT >::VectorType & getContour () const
Getter for the contour / boundary.
void setCoefficients (const Eigen::Vector4f &coefficients)
Setr the internal coefficients.
void setCoefficients (const pcl::ModelCoefficients &coefficients)
Set the internal coefficients.
Eigen::Vector4f & getCoefficients ()
Getter for the coefficients.
const Eigen::Vector4f & getCoefficients () const
Getter for the coefficients.
Protected Attributes
pcl::PointCloud< PointT >::VectorType contour_
A list of points on the boundary/contour of the planar region.
Eigen::Vector4f coefficients_
A list of model coefficients (a,b,c,d).
Detailed Description
template<typename PointT>
class pcl::PlanarPolygon< PointT >
PlanarPolygon represents a planar (2D) polygon, potentially in a 3D space.
Author
Alex Trevor
Definition at line 54 of file planar_polygon.h.
Member Typedef Documentation
ConstPtr
template<typename PointT > using pcl::PlanarPolygon< PointT >::ConstPtr = shared_ptr<const PlanarPolygon<PointT> >
Definition at line 58 of file planar_polygon.h.
Ptr
template<typename PointT > using pcl::PlanarPolygon< PointT >::Ptr = shared_ptr<PlanarPolygon<PointT> >
Definition at line 57 of file planar_polygon.h.
Constructor & Destructor Documentation
PlanarPolygon() [1/2]
template<typename PointT > pcl::PlanarPolygon< PointT >::PlanarPolygon () inline
Empty constructor for PlanarPolygon.
Definition at line 61 of file planar_polygon.h.
PlanarPolygon() [2/2]
template<typename PointT > pcl::PlanarPolygon< PointT >::PlanarPolygon (typename pcl::PointCloud< PointT >::VectorType & contour, Eigen::Vector4f & coefficients) inline
Constructor for PlanarPolygon.
Parameters
[in] contour a vector of points bounding the polygon
[in] coefficients a vector of the plane's coefficients (a,b,c,d)
Definition at line 68 of file planar_polygon.h.
~PlanarPolygon()
template<typename PointT > virtual pcl::PlanarPolygon< PointT >::~PlanarPolygon () inline virtual
Destructor.
Definition at line 74 of file planar_polygon.h.
Member Function Documentation
getCoefficients() [1/2]
template<typename PointT > Eigen::Vector4f& pcl::PlanarPolygon< PointT >::getCoefficients () inline
Getter for the coefficients.
Definition at line 120 of file planar_polygon.h.
References pcl::PlanarPolygon< PointT >::coefficients_.
Referenced by pcl::approximatePolygon().
getCoefficients() [2/2]
template<typename PointT > const Eigen::Vector4f& pcl::PlanarPolygon< PointT >::getCoefficients () const inline
Getter for the coefficients.
Definition at line 127 of file planar_polygon.h.
References pcl::PlanarPolygon< PointT >::coefficients_.
getContour() [1/2]
template<typename PointT > pcl::PointCloud<PointT>::VectorType& pcl::PlanarPolygon< PointT >::getContour () inline
Getter for the contour / boundary.
Definition at line 87 of file planar_polygon.h.
References pcl::PlanarPolygon< PointT >::contour_.
Referenced by pcl::visualization::ImageViewer::addPlanarPolygon(), pcl::approximatePolygon(), and pcl::visualization::createPolygon().
getContour() [2/2]
template<typename PointT > const pcl::PointCloud<PointT>::VectorType& pcl::PlanarPolygon< PointT >::getContour () const inline
Getter for the contour / boundary.
Definition at line 94 of file planar_polygon.h.
References pcl::PlanarPolygon< PointT >::contour_.
setCoefficients() [1/2]
template<typename PointT > void pcl::PlanarPolygon< PointT >::setCoefficients (const Eigen::Vector4f & coefficients) inline
Setr the internal coefficients.
Parameters
[in] coefficients the new coefficients to be set
Definition at line 103 of file planar_polygon.h.
References pcl::PlanarPolygon< PointT >::coefficients_.
setCoefficients() [2/2]
template<typename PointT > void pcl::PlanarPolygon< PointT >::setCoefficients (const pcl::ModelCoefficients & coefficients) inline
Set the internal coefficients.
Parameters
[in] coefficients the new coefficients to be set
Definition at line 112 of file planar_polygon.h.
References pcl::PlanarPolygon< PointT >::coefficients_, and pcl::ModelCoefficients::values.
setContour()
template<typename PointT > void pcl::PlanarPolygon< PointT >::setContour (const pcl::PointCloud< PointT > & contour) inline
Set the internal contour.
Parameters
[in] contour the new planar polygonal contour
Definition at line 80 of file planar_polygon.h.
References pcl::PlanarPolygon< PointT >::contour_, and pcl::PointCloud< PointT >::points.
Member Data Documentation
coefficients_
template<typename PointT > Eigen::Vector4f pcl::PlanarPolygon< PointT >::coefficients_ protected
A list of model coefficients (a,b,c,d).
Definition at line 137 of file planar_polygon.h.
Referenced by pcl::PlanarPolygon< PointT >::getCoefficients(), pcl::PlanarRegion< PointT >::PlanarRegion(), and pcl::PlanarPolygon< PointT >::setCoefficients().
contour_
template<typename PointT > pcl::PointCloud<PointT>::VectorType pcl::PlanarPolygon< PointT >::contour_ protected
A list of points on the boundary/contour of the planar region.
Definition at line 134 of file planar_polygon.h.
Referenced by pcl::PlanarPolygon< PointT >::getContour(), pcl::PlanarRegion< PointT >::PlanarRegion(), and pcl::PlanarPolygon< PointT >::setContour().
The documentation for this class was generated from the following file:
pcl/geometry/planar_polygon.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Jun 2 2020 14:12:34