Point Cloud Library (PCL): pcl::octree::OctreeLeafNodeDepthFirstIterator< OctreeT > Class Template Reference
pcl::octree::OctreeLeafNodeDepthFirstIterator< OctreeT > Class Template Reference
Module octree
Octree leaf node iterator class.
#include <pcl/octree/octree_iterator.h>
Public Member Functions
OctreeLeafNodeDepthFirstIterator (uindex_t max_depth_arg=0)
Empty constructor.
OctreeLeafNodeDepthFirstIterator (OctreeT *octree_arg, uindex_t max_depth_arg=0)
Constructor.
OctreeLeafNodeDepthFirstIterator (OctreeT *octree_arg, uindex_t max_depth_arg, IteratorState *current_state, const std::vector< IteratorState > &stack=std::vector< IteratorState >())
Constructor.
void reset ()
Reset the iterator to the root node of the octree.
OctreeLeafNodeDepthFirstIterator & operator++ ()
Preincrement operator.
OctreeLeafNodeDepthFirstIterator operator++ (int)
postincrement operator.
OctreeNode * operator* () const override
*operator.
Public Member Functions inherited from pcl::octree::OctreeDepthFirstIterator< OctreeT >
OctreeDepthFirstIterator (uindex_t max_depth_arg=0)
Empty constructor.
OctreeDepthFirstIterator (OctreeT *octree_arg, uindex_t max_depth_arg=0)
Constructor.
OctreeDepthFirstIterator (OctreeT *octree_arg, uindex_t max_depth_arg, IteratorState *current_state, const std::vector< IteratorState > &stack=std::vector< IteratorState >())
Constructor.
OctreeDepthFirstIterator (const OctreeDepthFirstIterator &other)
Copy Constructor.
OctreeDepthFirstIterator & operator= (const OctreeDepthFirstIterator &src)
Copy assignment.
OctreeDepthFirstIterator operator++ (int)
postincrement operator.
void skipChildVoxels ()
Skip all child voxels of current node and return to parent node.
Public Member Functions inherited from pcl::octree::OctreeIteratorBase< OctreeT >
OctreeIteratorBase ()
Empty constructor.
OctreeIteratorBase (uindex_t max_depth_arg)
Constructor.
OctreeIteratorBase (OctreeT *octree_arg)
Constructor.
OctreeIteratorBase (OctreeT *octree_arg, uindex_t max_depth_arg)
Constructor.
OctreeIteratorBase (OctreeT *octree_arg, uindex_t max_depth_arg, IteratorState *current_state)
Constructor.
virtual ~OctreeIteratorBase ()=default
Empty deconstructor.
bool operator== (const OctreeIteratorBase &other) const
Equal comparison operator.
bool operator!= (const OctreeIteratorBase &other) const
Inequal comparison operator.
void reset ()
Reset iterator.
const OctreeKey & getCurrentOctreeKey () const
Get octree key for the current iterator octree node.
uindex_t getCurrentOctreeDepth () const
Get the current depth level of octree.
OctreeNode * getCurrentOctreeNode () const
Get the current octree node.
bool isBranchNode () const
check if current node is a branch node
bool isLeafNode () const
check if current node is a branch node
char getNodeConfiguration () const
Get bit pattern of children configuration of current node.
const LeafContainer & getLeafContainer () const
Method for retrieving a single leaf container from the octree leaf node.
LeafContainer & getLeafContainer ()
Method for retrieving a single leaf container from the octree leaf node.
const BranchContainer & getBranchContainer () const
Method for retrieving the container from an octree branch node.
BranchContainer & getBranchContainer ()
Method for retrieving the container from an octree branch node.
virtual unsigned long getNodeID () const
get a integer identifier for current node (note: identifier depends on tree depth).
Additional Inherited Members
Public Types inherited from pcl::octree::OctreeDepthFirstIterator< OctreeT >
using LeafNode = typename OctreeIteratorBase< OctreeT >::LeafNode
using BranchNode = typename OctreeIteratorBase< OctreeT >::BranchNode
Public Types inherited from pcl::octree::OctreeIteratorBase< OctreeT >
using iterator_category = std::forward_iterator_tag
using value_type = const OctreeNode
using difference_type = void
using pointer = const OctreeNode *
using reference = const OctreeNode &
using LeafNode = typename OctreeT::LeafNode
using BranchNode = typename OctreeT::BranchNode
using LeafContainer = typename OctreeT::LeafContainer
using BranchContainer = typename OctreeT::BranchContainer
Protected Attributes inherited from pcl::octree::OctreeDepthFirstIterator< OctreeT >
std::vector< IteratorState > stack_
Stack structure.
Protected Attributes inherited from pcl::octree::OctreeIteratorBase< OctreeT >
OctreeT * octree_
Reference to octree class.
IteratorState * current_state_
Pointer to current iterator state.
uindex_t max_octree_depth_
Maximum octree depth.
Detailed Description
template<typename OctreeT>
class pcl::octree::OctreeLeafNodeDepthFirstIterator< OctreeT >
Octree leaf node iterator class.
Note
This class implements a forward iterator for traversing the leaf nodes of an octree data structure.
Author
Julius Kammerl (juliu.nosp@m.s@ka.nosp@m.mmerl.nosp@m..de)
Definition at line 673 of file octree_iterator.h.
Constructor & Destructor Documentation
OctreeLeafNodeDepthFirstIterator() [1/3]
template<typename OctreeT > pcl::octree::OctreeLeafNodeDepthFirstIterator< OctreeT >::OctreeLeafNodeDepthFirstIterator (uindex_t max_depth_arg = 0) inline explicit
Empty constructor.
Parameters
[in] max_depth_arg Depth limitation during traversal
Definition at line 681 of file octree_iterator.h.
References pcl::octree::OctreeLeafNodeDepthFirstIterator< OctreeT >::reset().
OctreeLeafNodeDepthFirstIterator() [2/3]
template<typename OctreeT > pcl::octree::OctreeLeafNodeDepthFirstIterator< OctreeT >::OctreeLeafNodeDepthFirstIterator (OctreeT * octree_arg, uindex_t max_depth_arg = 0) inline explicit
Constructor.
Parameters
[in] octree_arg Octree to be iterated. Initially the iterator is set to its root node.
[in] max_depth_arg Depth limitation during traversal
Definition at line 692 of file octree_iterator.h.
References pcl::octree::OctreeLeafNodeDepthFirstIterator< OctreeT >::reset().
OctreeLeafNodeDepthFirstIterator() [3/3]
template<typename OctreeT > pcl::octree::OctreeLeafNodeDepthFirstIterator< OctreeT >::OctreeLeafNodeDepthFirstIterator (OctreeT * octree_arg, uindex_t max_depth_arg, IteratorState * current_state, const std::vector< IteratorState > & stack = std::vector<IteratorState>()) inline explicit
Constructor.
Parameters
[in] octree_arg Octree to be iterated. Initially the iterator is set to its root node.
[in] max_depth_arg Depth limitation during traversal
[in] current_state A pointer to the current iterator state
Warning
For advanced users only.
Definition at line 707 of file octree_iterator.h.
Member Function Documentation
operator*()
template<typename OctreeT > OctreeNode* pcl::octree::OctreeLeafNodeDepthFirstIterator< OctreeT >::operator* () const inline override virtual
*operator.
Returns
pointer to the current octree leaf node
Reimplemented from pcl::octree::OctreeIteratorBase< OctreeT >.
Definition at line 753 of file octree_iterator.h.
References pcl::octree::OctreeIteratorBase< OctreeT >::current_state_, pcl::octree::OctreeNode::getNodeType(), pcl::octree::LEAF_NODE, and pcl::octree::IteratorState::node_.
operator++() [1/2]
template<typename OctreeT > OctreeLeafNodeDepthFirstIterator& pcl::octree::OctreeLeafNodeDepthFirstIterator< OctreeT >::operator++ () inline virtual
Preincrement operator.
Note
recursively step to next octree leaf node
Reimplemented from pcl::octree::OctreeDepthFirstIterator< OctreeT >.
Definition at line 728 of file octree_iterator.h.
References pcl::octree::OctreeIteratorBase< OctreeT >::current_state_, pcl::octree::OctreeNode::getNodeType(), pcl::octree::LEAF_NODE, pcl::octree::IteratorState::node_, and pcl::octree::OctreeDepthFirstIterator< OctreeT >::operator++().
Referenced by pcl::octree::OctreeLeafNodeDepthFirstIterator< OctreeT >::reset().
operator++() [2/2]
template<typename OctreeT > OctreeLeafNodeDepthFirstIterator pcl::octree::OctreeLeafNodeDepthFirstIterator< OctreeT >::operator++ (int) inline
postincrement operator.
Note
step to next octree node
Definition at line 742 of file octree_iterator.h.
reset()
template<typename OctreeT > void pcl::octree::OctreeLeafNodeDepthFirstIterator< OctreeT >::reset () inline virtual
Reset the iterator to the root node of the octree.
Reimplemented from pcl::octree::OctreeDepthFirstIterator< OctreeT >.
Definition at line 718 of file octree_iterator.h.
References pcl::octree::OctreeLeafNodeDepthFirstIterator< OctreeT >::operator++(), and pcl::octree::OctreeDepthFirstIterator< OctreeT >::reset().
Referenced by pcl::octree::OctreeLeafNodeDepthFirstIterator< OctreeT >::OctreeLeafNodeDepthFirstIterator().
The documentation for this class was generated from the following file:
pcl/octree/octree_iterator.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:32