Point Cloud Library (PCL): pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT > Class Template Reference
pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT > Class Template Reference
Module features
BOARDLocalReferenceFrameEstimation implements the BOrder Aware Repeatable Directions algorithm for local reference frame estimation as described here:
#include <pcl/features/board.h>
Public Types
using Ptr = shared_ptr< BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT > >
using ConstPtr = shared_ptr< const BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT > >
Public Types inherited from pcl::FeatureFromNormals< PointInT, PointNT, ReferenceFrame >
using PointCloudN = pcl::PointCloud< PointNT >
using PointCloudNPtr = typename PointCloudN::Ptr
using PointCloudNConstPtr = typename PointCloudN::ConstPtr
using Ptr = shared_ptr< FeatureFromNormals< PointInT, PointNT, ReferenceFrame > >
using ConstPtr = shared_ptr< const FeatureFromNormals< PointInT, PointNT, ReferenceFrame > >
Public Types inherited from pcl::Feature< PointInT, ReferenceFrame >
using BaseClass = PCLBase< PointInT >
using Ptr = shared_ptr< Feature< PointInT, ReferenceFrame > >
using ConstPtr = shared_ptr< const Feature< PointInT, ReferenceFrame > >
using KdTree = pcl::search::Search< PointInT >
using KdTreePtr = typename KdTree::Ptr
using PointCloudIn = pcl::PointCloud< PointInT >
using PointCloudInPtr = typename PointCloudIn::Ptr
using PointCloudInConstPtr = typename PointCloudIn::ConstPtr
using PointCloudOut = pcl::PointCloud< ReferenceFrame >
using SearchMethod = std::function< int(std::size_t, double, pcl::Indices &, std::vector< float > &)>
using SearchMethodSurface = std::function< int(const PointCloudIn &cloud, std::size_t index, double, pcl::Indices &, std::vector< float > &)>
Public Types inherited from pcl::PCLBase< PointInT >
using PointCloud = pcl::PointCloud< PointInT >
using PointCloudPtr = typename PointCloud::Ptr
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointIndicesPtr = PointIndices::Ptr
using PointIndicesConstPtr = PointIndices::ConstPtr
Public Member Functions
BOARDLocalReferenceFrameEstimation ()
Constructor.
~BOARDLocalReferenceFrameEstimation () override=default
Empty destructor.
void setTangentRadius (float radius)
Set the maximum distance of the points used to estimate the x_axis and y_axis of the BOARD Reference Frame for a given point.
float getTangentRadius () const
Get the maximum distance of the points used to estimate the x_axis and y_axis of the BOARD Reference Frame for a given point.
void setFindHoles (bool find_holes)
Sets whether holes in the margin of the support, for each point, are searched and accounted for in the estimation of the Reference Frame or not.
bool getFindHoles () const
Gets whether holes in the margin of the support, for each point, are searched and accounted for in the estimation of the Reference Frame or not.
void setMarginThresh (float margin_thresh)
Sets the percentage of the search radius (or tangent radius if set) after which a point is considered part of the support margin.
float getMarginThresh () const
Gets the percentage of the search radius (or tangent radius if set) after which a point is considered part of the support margin.
void setCheckMarginArraySize (int size)
Sets the number of slices in which is divided the margin for the search of missing regions.
int getCheckMarginArraySize () const
Gets the number of slices in which is divided the margin for the search of missing regions.
void setHoleSizeProbThresh (float prob_thresh)
Given the angle width of a hole in the support margin, sets the minimum percentage of a circumference this angle must cover to be considered a missing region in the support and hence used for the estimation of the Reference Frame.
float getHoleSizeProbThresh () const
Given the angle width of a hole in the support margin, gets the minimum percentage of a circumference this angle must cover to be considered a missing region in the support and hence used for the estimation of the Reference Frame.
void setSteepThresh (float steep_thresh)
Sets the minimum steepness that the normals of the points situated on the borders of the hole, with reference to the normal of the best point found by the algorithm, must have in order to be considered in the calculation of the Reference Frame.
float getSteepThresh () const
Gets the minimum steepness that the normals of the points situated on the borders of the hole, with reference to the normal of the best point found by the algorithm, must have in order to be considered in the calculation of the Reference Frame.
Public Member Functions inherited from pcl::FeatureFromNormals< PointInT, PointNT, ReferenceFrame >
FeatureFromNormals ()
Empty constructor.
void setInputNormals (const PointCloudNConstPtr &normals)
Provide a pointer to the input dataset that contains the point normals of the XYZ dataset.
PointCloudNConstPtr getInputNormals () const
Get a pointer to the normals of the input XYZ point cloud dataset.
Public Member Functions inherited from pcl::Feature< PointInT, ReferenceFrame >
Feature ()
Empty constructor.
void setSearchSurface (const PointCloudInConstPtr &cloud)
Provide a pointer to a dataset to add additional information to estimate the features for every point in the input dataset.
PointCloudInConstPtr getSearchSurface () const
Get a pointer to the surface point cloud dataset.
void setSearchMethod (const KdTreePtr &tree)
Provide a pointer to the search object.
KdTreePtr getSearchMethod () const
Get a pointer to the search method used.
double getSearchParameter () const
Get the internal search parameter.
void setKSearch (int k)
Set the number of k nearest neighbors to use for the feature estimation.
int getKSearch () const
get the number of k nearest neighbors used for the feature estimation.
void setRadiusSearch (double radius)
Set the sphere radius that is to be used for determining the nearest neighbors used for the feature estimation.
double getRadiusSearch () const
Get the sphere radius used for determining the neighbors.
void compute (PointCloudOut &output)
Base method for feature estimation for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Public Member Functions inherited from pcl::PCLBase< PointInT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()=default
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (std::size_t row_start, std::size_t col_start, std::size_t nb_rows, std::size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointInT & operator[] (std::size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Types
using PointCloudIn = typename Feature< PointInT, PointOutT >::PointCloudIn
using PointCloudOut = typename Feature< PointInT, PointOutT >::PointCloudOut
Protected Member Functions
void resetData ()
float computePointLRF (const int &index, Eigen::Matrix3f &lrf)
Estimate the LRF descriptor for a given point based on its spatial neighborhood of 3D points with normals.
void computeFeature (PointCloudOut &output) override
Abstract feature estimation method.
void directedOrthogonalAxis (Eigen::Vector3f const &axis, Eigen::Vector3f const &axis_origin, Eigen::Vector3f const &point, Eigen::Vector3f &directed_ortho_axis)
Given an axis (with origin axis_origin), return the orthogonal axis directed to point.
float getAngleBetweenUnitVectors (Eigen::Vector3f const &v1, Eigen::Vector3f const &v2, Eigen::Vector3f const &axis)
return the angle (in radians) that rotate v1 to v2 with respect to axis .
void normalDisambiguation (pcl::PointCloud< PointNT > const &normals_cloud, pcl::Indices const &normal_indices, Eigen::Vector3f &normal)
Disambiguates a normal direction using adjacent normals.
void planeFitting (Eigen::Matrix< float, Eigen::Dynamic, 3 > const &points, Eigen::Vector3f &center, Eigen::Vector3f &norm)
Compute Least Square Plane Fitting in a set of 3D points.
void projectPointOnPlane (Eigen::Vector3f const &point, Eigen::Vector3f const &origin_point, Eigen::Vector3f const &plane_normal, Eigen::Vector3f &projected_point)
Given a plane (origin and normal) and a point, return the projection of x on plane.
void randomOrthogonalAxis (Eigen::Vector3f const &axis, Eigen::Vector3f &rand_ortho_axis)
Given an axis, return a random orthogonal axis.
bool areEquals (float val1, float val2, float zero_float_eps=1E-8f) const
Check if val1 and val2 are equals.
Protected Member Functions inherited from pcl::FeatureFromNormals< PointInT, PointNT, ReferenceFrame >
virtual bool initCompute ()
This method should get called before starting the actual computation.
Protected Member Functions inherited from pcl::Feature< PointInT, ReferenceFrame >
const std::string & getClassName () const
Get a string representation of the name of this class.
virtual bool deinitCompute ()
This method should get called after ending the actual computation.
int searchForNeighbors (std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
int searchForNeighbors (const PointCloudIn &cloud, std::size_t index, double parameter, pcl::Indices &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
Protected Member Functions inherited from pcl::PCLBase< PointInT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Additional Inherited Members
Protected Attributes inherited from pcl::FeatureFromNormals< PointInT, PointNT, ReferenceFrame >
PointCloudNConstPtr normals_
A pointer to the input dataset that contains the point normals of the XYZ dataset.
Protected Attributes inherited from pcl::Feature< PointInT, ReferenceFrame >
std::string feature_name_
The feature name.
SearchMethodSurface search_method_surface_
The search method template for points.
PointCloudInConstPtr surface_
An input point cloud describing the surface that is to be used for nearest neighbors estimation.
KdTreePtr tree_
A pointer to the spatial search object.
double search_parameter_
The actual search parameter (from either search_radius_ or k_).
double search_radius_
The nearest neighbors search radius for each point.
int k_
The number of K nearest neighbors to use for each point.
bool fake_surface_
If no surface is given, we use the input PointCloud as the surface.
Protected Attributes inherited from pcl::PCLBase< PointInT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointInT, typename PointNT, typename PointOutT = ReferenceFrame>
class pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >
BOARDLocalReferenceFrameEstimation implements the BOrder Aware Repeatable Directions algorithm for local reference frame estimation as described here:
A. Petrelli, L. Di Stefano, "On the repeatability of the local reference frame for partial shape matching", 13th International Conference on Computer Vision (ICCV), 2011
Author
Alioscia Petrelli (original), Tommaso Cavallari (PCL port)
Definition at line 58 of file board.h.
Member Typedef Documentation
ConstPtr
template<typename PointInT , typename PointNT , typename PointOutT = ReferenceFrame> using pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::ConstPtr = shared_ptr<const BOARDLocalReferenceFrameEstimation<PointInT, PointNT, PointOutT> >
Definition at line 62 of file board.h.
PointCloudIn
template<typename PointInT , typename PointNT , typename PointOutT = ReferenceFrame> using pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::PointCloudIn = typename Feature<PointInT, PointOutT>::PointCloudIn protected
Definition at line 227 of file board.h.
PointCloudOut
template<typename PointInT , typename PointNT , typename PointOutT = ReferenceFrame> using pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::PointCloudOut = typename Feature<PointInT, PointOutT>::PointCloudOut protected
Definition at line 228 of file board.h.
Ptr
template<typename PointInT , typename PointNT , typename PointOutT = ReferenceFrame> using pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::Ptr = shared_ptr<BOARDLocalReferenceFrameEstimation<PointInT, PointNT, PointOutT> >
Definition at line 61 of file board.h.
Constructor & Destructor Documentation
BOARDLocalReferenceFrameEstimation()
template<typename PointInT , typename PointNT , typename PointOutT = ReferenceFrame> pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::BOARDLocalReferenceFrameEstimation () inline
Constructor.
Definition at line 65 of file board.h.
References pcl::Feature< PointInT, ReferenceFrame >::feature_name_, and pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::setCheckMarginArraySize().
~BOARDLocalReferenceFrameEstimation()
template<typename PointInT , typename PointNT , typename PointOutT = ReferenceFrame> pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::~BOARDLocalReferenceFrameEstimation () override default
Empty destructor.
Member Function Documentation
areEquals()
template<typename PointInT , typename PointNT , typename PointOutT = ReferenceFrame> bool pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::areEquals (float val1, float val2, float zero_float_eps = 1E-8f) const inline protected
Check if val1 and val2 are equals.
Parameters
[in] val1 first number to check.
[in] val2 second number to check.
[in] zero_float_eps epsilon
Returns
true if val1 is equal to val2, false otherwise.
Definition at line 321 of file board.h.
computeFeature()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::computeFeature (PointCloudOut & output) override protected
Abstract feature estimation method.
Parameters
[out] output the resultant features
Definition at line 569 of file board.hpp.
computePointLRF()
template<typename PointInT , typename PointNT , typename PointOutT > float pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::computePointLRF (const int & index, Eigen::Matrix3f & lrf) protected
Estimate the LRF descriptor for a given point based on its spatial neighborhood of 3D points with normals.
Parameters
[in] index the index of the point in input_
[out] lrf the resultant local reference frame
Definition at line 183 of file board.hpp.
References pcl::geometry::distance(), M_PI, and pcl::geometry::randomOrthogonalAxis().
directedOrthogonalAxis()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::directedOrthogonalAxis (Eigen::Vector3f const & axis, Eigen::Vector3f const & axis_origin, Eigen::Vector3f const & point, Eigen::Vector3f & directed_ortho_axis) protected
Given an axis (with origin axis_origin), return the orthogonal axis directed to point.
Note
axis must be normalized.
Parameters
[in] axis the axis
[in] axis_origin the axis_origin
[in] point the point towards which the resulting axis is directed
[out] directed_ortho_axis the directed orthogonal axis calculated
Definition at line 48 of file board.hpp.
getAngleBetweenUnitVectors()
template<typename PointInT , typename PointNT , typename PointOutT > float pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::getAngleBetweenUnitVectors (Eigen::Vector3f const & v1, Eigen::Vector3f const & v2, Eigen::Vector3f const & axis) protected
return the angle (in radians) that rotate v1 to v2 with respect to axis .
Parameters
[in] v1 the first vector
[in] v2 the second vector
[in] axis the rotation axis. Axis must be normalized and orthogonal to plane defined by v1 and v2.
Returns
angle
Definition at line 83 of file board.hpp.
References M_PI.
getCheckMarginArraySize()
template<typename PointInT , typename PointNT , typename PointOutT = ReferenceFrame> int pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::getCheckMarginArraySize () const inline
Gets the number of slices in which is divided the margin for the search of missing regions.
Returns
the number of margin slices.
Definition at line 168 of file board.h.
getFindHoles()
template<typename PointInT , typename PointNT , typename PointOutT = ReferenceFrame> bool pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::getFindHoles () const inline
Gets whether holes in the margin of the support, for each point, are searched and accounted for in the estimation of the Reference Frame or not.
Returns
The search for holes in the support is enabled/disabled.
Definition at line 113 of file board.h.
getHoleSizeProbThresh()
template<typename PointInT , typename PointNT , typename PointOutT = ReferenceFrame> float pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::getHoleSizeProbThresh () const inline
Given the angle width of a hole in the support margin, gets the minimum percentage of a circumference this angle must cover to be considered a missing region in the support and hence used for the estimation of the Reference Frame.
Returns
the minimum percentage of a circumference after which a hole is considered in the calculation
Definition at line 190 of file board.h.
getMarginThresh()
template<typename PointInT , typename PointNT , typename PointOutT = ReferenceFrame> float pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::getMarginThresh () const inline
Gets the percentage of the search radius (or tangent radius if set) after which a point is considered part of the support margin.
Returns
The percentage of the search radius after which a point is considered a margin point.
Definition at line 133 of file board.h.
getSteepThresh()
template<typename PointInT , typename PointNT , typename PointOutT = ReferenceFrame> float pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::getSteepThresh () const inline
Gets the minimum steepness that the normals of the points situated on the borders of the hole, with reference to the normal of the best point found by the algorithm, must have in order to be considered in the calculation of the Reference Frame.
Returns
threshold that defines if a missing region contains a point with the most different normal.
Definition at line 212 of file board.h.
getTangentRadius()
template<typename PointInT , typename PointNT , typename PointOutT = ReferenceFrame> float pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::getTangentRadius () const inline
Get the maximum distance of the points used to estimate the x_axis and y_axis of the BOARD Reference Frame for a given point.
Returns
The search radius for x and y axes. If set to 0 the parameter given with setRadiusSearch is used.
Definition at line 91 of file board.h.
normalDisambiguation()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::normalDisambiguation (pcl::PointCloud< PointNT > const & normals_cloud, pcl::Indices const & normal_indices, Eigen::Vector3f & normal) protected
Disambiguates a normal direction using adjacent normals.
Parameters
[in] normals_cloud a cloud of normals used for the calculation
[in] normal_indices the indices of the normals in the cloud that should to be used for the calculation
[in,out] normal the normal to disambiguate, the calculation is performed in place
Definition at line 158 of file board.hpp.
planeFitting()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::planeFitting (Eigen::Matrix< float, Eigen::Dynamic, 3 > const & points, Eigen::Vector3f & center, Eigen::Vector3f & norm) protected
Compute Least Square Plane Fitting in a set of 3D points.
Parameters
[in] points Matrix(nPoints,3) of 3D points coordinates
[out] center centroid of the distribution of points that belongs to the fitted plane
[out] norm normal to the fitted plane
Definition at line 130 of file board.hpp.
projectPointOnPlane()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::projectPointOnPlane (Eigen::Vector3f const & point, Eigen::Vector3f const & origin_point, Eigen::Vector3f const & plane_normal, Eigen::Vector3f & projected_point) protected
Given a plane (origin and normal) and a point, return the projection of x on plane.
Equivalent to vtkPlane::ProjectPoint()
Parameters
[in] point the point to project
[in] origin_point a point belonging to the plane
[in] plane_normal normal of the plane
[out] projected_point the projection of the point on the plane
Definition at line 66 of file board.hpp.
randomOrthogonalAxis()
template<typename PointInT , typename PointNT , typename PointOutT > void pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::randomOrthogonalAxis (Eigen::Vector3f const & axis, Eigen::Vector3f & rand_ortho_axis) protected
Given an axis, return a random orthogonal axis.
Parameters
[in] axis input axis
[out] rand_ortho_axis an axis orthogonal to the input axis and whose direction is random
Definition at line 99 of file board.hpp.
resetData()
template<typename PointInT , typename PointNT , typename PointOutT = ReferenceFrame> void pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::resetData () inline protected
Definition at line 231 of file board.h.
References pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::setCheckMarginArraySize().
setCheckMarginArraySize()
template<typename PointInT , typename PointNT , typename PointOutT = ReferenceFrame> void pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::setCheckMarginArraySize (int size) inline
Sets the number of slices in which is divided the margin for the search of missing regions.
Parameters
[in] size the number of margin slices.
Definition at line 143 of file board.h.
Referenced by pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::BOARDLocalReferenceFrameEstimation(), and pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::resetData().
setFindHoles()
template<typename PointInT , typename PointNT , typename PointOutT = ReferenceFrame> void pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::setFindHoles (bool find_holes) inline
Sets whether holes in the margin of the support, for each point, are searched and accounted for in the estimation of the Reference Frame or not.
Parameters
[in] find_holes Enable/Disable the search for holes in the support.
Definition at line 102 of file board.h.
Referenced by pcl::Hough3DGrouping< PointModelT, PointSceneT, PointModelRfT, PointSceneRfT >::computeRf().
setHoleSizeProbThresh()
template<typename PointInT , typename PointNT , typename PointOutT = ReferenceFrame> void pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::setHoleSizeProbThresh (float prob_thresh) inline
Given the angle width of a hole in the support margin, sets the minimum percentage of a circumference this angle must cover to be considered a missing region in the support and hence used for the estimation of the Reference Frame.
Parameters
[in] prob_thresh the minimum percentage of a circumference after which a hole is considered in the calculation
Definition at line 179 of file board.h.
setMarginThresh()
template<typename PointInT , typename PointNT , typename PointOutT = ReferenceFrame> void pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::setMarginThresh (float margin_thresh) inline
Sets the percentage of the search radius (or tangent radius if set) after which a point is considered part of the support margin.
Parameters
[in] margin_thresh the percentage of the search radius after which a point is considered a margin point.
Definition at line 123 of file board.h.
setSteepThresh()
template<typename PointInT , typename PointNT , typename PointOutT = ReferenceFrame> void pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::setSteepThresh (float steep_thresh) inline
Sets the minimum steepness that the normals of the points situated on the borders of the hole, with reference to the normal of the best point found by the algorithm, must have in order to be considered in the calculation of the Reference Frame.
Parameters
[in] steep_thresh threshold that defines if a missing region contains a point with the most different normal.
Definition at line 201 of file board.h.
setTangentRadius()
template<typename PointInT , typename PointNT , typename PointOutT = ReferenceFrame> void pcl::BOARDLocalReferenceFrameEstimation< PointInT, PointNT, PointOutT >::setTangentRadius (float radius) inline
Set the maximum distance of the points used to estimate the x_axis and y_axis of the BOARD Reference Frame for a given point.
Parameters
[in] radius The search radius for x and y axes. If not set or set to 0 the parameter given with setRadiusSearch is used.
Definition at line 81 of file board.h.
The documentation for this class was generated from the following files:
pcl/features/board.h
pcl/features/impl/board.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:10