Point Cloud Library (PCL): pcl::StopWatch Class Reference
pcl::StopWatch Class Reference
Module common
Simple stopwatch.
#include <pcl/common/time.h>
Public Member Functions
StopWatch ()
Constructor.
double getTime () const
Retrieve the time in milliseconds spent since the last call to reset().
double getTimeSeconds () const
Retrieve the time in seconds spent since the last call to reset().
void reset ()
Reset the stopwatch to 0.
Protected Attributes
std::chrono::time_point< std::chrono::steady_clock > start_time_
Detailed Description
Simple stopwatch.
Definition at line 58 of file time.h.
Constructor & Destructor Documentation
StopWatch()
pcl::StopWatch::StopWatch () inline
Constructor.
Definition at line 62 of file time.h.
Member Function Documentation
getTime()
double pcl::StopWatch::getTime () const inline
Retrieve the time in milliseconds spent since the last call to reset().
Definition at line 68 of file time.h.
References start_time_.
Referenced by getTimeSeconds(), and pcl::ScopeTime::~ScopeTime().
getTimeSeconds()
double pcl::StopWatch::getTimeSeconds () const inline
Retrieve the time in seconds spent since the last call to reset().
Definition at line 76 of file time.h.
References getTime().
Referenced by pcl::registration::FPCSInitialAlignment< PointSource, PointTarget, pcl::Normal, float >::computeTransformation(), and pcl::EventFrequency::event().
reset()
void pcl::StopWatch::reset () inline
Reset the stopwatch to 0.
Definition at line 83 of file time.h.
References start_time_.
Referenced by pcl::EventFrequency::EventFrequency(), and pcl::EventFrequency::reset().
Member Data Documentation
start_time_
std::chrono::time_point<std::chrono::steady_clock> pcl::StopWatch::start_time_ protected
Definition at line 89 of file time.h.
Referenced by getTime(), and reset().
The documentation for this class was generated from the following file:
pcl/common/time.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Jun 2 2020 14:13:03