Point Cloud Library (PCL): pcl::poisson::PPolynomial< Degree > Class Template Reference
pcl::poisson::PPolynomial< Degree > Class Template Reference
#include <pcl/surface/3rdparty/poisson4/ppolynomial.h>
Public Member Functions
PPolynomial (void)
PPolynomial (const PPolynomial< Degree > &p)
~PPolynomial (void)
PPolynomial & operator= (const PPolynomial &p)
int size (void) const
void set (std::size_t size)
void set (StartingPolynomial< Degree > *sps, int count)
void reset (std::size_t newSize)
double operator() (double t) const
double integral (double tMin, double tMax) const
double Integral (void) const
template<int Degree2>
PPolynomial< Degree > & operator= (const PPolynomial< Degree2 > &p)
PPolynomial operator+ (const PPolynomial &p) const
PPolynomial operator- (const PPolynomial &p) const
template<int Degree2>
PPolynomial< Degree+Degree2 > operator* (const Polynomial< Degree2 > &p) const
template<int Degree2>
PPolynomial< Degree+Degree2 > operator* (const PPolynomial< Degree2 > &p) const
PPolynomial & operator+= (double s)
PPolynomial & operator-= (double s)
PPolynomial & operator*= (double s)
PPolynomial & operator/= (double s)
PPolynomial operator+ (double s) const
PPolynomial operator- (double s) const
PPolynomial operator* (double s) const
PPolynomial operator/ (double s) const
PPolynomial & addScaled (const PPolynomial &poly, double scale)
PPolynomial scale (double s) const
PPolynomial shift (double t) const
PPolynomial< Degree-1 > derivative (void) const
PPolynomial< Degree+1 > integral (void) const
void getSolutions (double c, std::vector< double > &roots, double EPS, double min=-DBL_MAX, double max=DBL_MAX) const
void printnl (void) const
PPolynomial< Degree+1 > MovingAverage (double radius)
void write (FILE *fp, int samples, double min, double max) const
PPolynomial< 0 > BSpline (double radius)
Static Public Member Functions
static PPolynomial BSpline (double radius=0.5)
Public Attributes
std::size_t polyCount
StartingPolynomial< Degree > * polys
Detailed Description
template<int Degree>
class pcl::poisson::PPolynomial< Degree >
Definition at line 58 of file ppolynomial.h.
Constructor & Destructor Documentation
PPolynomial() [1/2]
template<int Degree> pcl::poisson::PPolynomial< Degree >::PPolynomial (void)
Definition at line 87 of file ppolynomial.hpp.
PPolynomial() [2/2]
template<int Degree> pcl::poisson::PPolynomial< Degree >::PPolynomial (const PPolynomial< Degree > & p)
Definition at line 92 of file ppolynomial.hpp.
~PPolynomial()
template<int Degree> pcl::poisson::PPolynomial< Degree >::~PPolynomial (void)
Definition at line 100 of file ppolynomial.hpp.
Member Function Documentation
addScaled()
template<int Degree> PPolynomial< Degree > & pcl::poisson::PPolynomial< Degree >::addScaled (const PPolynomial< Degree > & poly, double scale)
Definition at line 221 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polyCount, pcl::poisson::PPolynomial< Degree >::polys, and pcl::poisson::StartingPolynomial< Degree >::start.
BSpline() [1/2]
PPolynomial< 0 > pcl::poisson::PPolynomial< 0 >::BSpline (double radius) inline
Definition at line 378 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polys, and pcl::poisson::PPolynomial< Degree >::set().
BSpline() [2/2]
template<int Degree> PPolynomial< Degree > pcl::poisson::PPolynomial< Degree >::BSpline (double radius = 0.5) static
Definition at line 391 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::MovingAverage().
Referenced by pcl::poisson::BSplineData< Degree, Real >::set().
derivative()
template<int Degree> PPolynomial< Degree-1 > pcl::poisson::PPolynomial< Degree >::derivative (void) const
Definition at line 287 of file ppolynomial.hpp.
References pcl::poisson::StartingPolynomial< Degree >::start.
Referenced by pcl::poisson::FunctionData< Degree, Real >::setValueTables(), and pcl::poisson::BSplineData< Degree, Real >::setValueTables().
getSolutions()
template<int Degree> void pcl::poisson::PPolynomial< Degree >::getSolutions (double c, std::vector< double > & roots, double EPS, double min = -DBL_MAX, double max = DBL_MAX) const
Definition at line 416 of file ppolynomial.hpp.
References pcl::poisson::Polynomial< Degree >::getSolutions(), and pcl::poisson::Polynomial< Degree >::setZero().
integral() [1/2]
template<int Degree> double pcl::poisson::PPolynomial< Degree >::integral (double tMin, double tMax) const
Definition at line 166 of file ppolynomial.hpp.
Integral()
template<int Degree> double pcl::poisson::PPolynomial< Degree >::Integral (void) const
Definition at line 185 of file ppolynomial.hpp.
integral() [2/2]
template<int Degree> PPolynomial< Degree+1 > pcl::poisson::PPolynomial< Degree >::integral (void) const
Definition at line 297 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polys, and pcl::poisson::PPolynomial< Degree >::set().
MovingAverage()
template<int Degree> PPolynomial< Degree+1 > pcl::poisson::PPolynomial< Degree >::MovingAverage (double radius)
Definition at line 396 of file ppolynomial.hpp.
References pcl::poisson::Polynomial< Degree >::integral(), pcl::poisson::StartingPolynomial< Degree >::p, pcl::poisson::PPolynomial< Degree >::set(), pcl::poisson::Polynomial< Degree >::shift(), and pcl::poisson::StartingPolynomial< Degree >::start.
Referenced by pcl::poisson::PPolynomial< Degree >::BSpline(), pcl::poisson::FunctionData< Degree, Real >::setValueTables(), and pcl::poisson::BSplineData< Degree, Real >::setValueTables().
operator()()
template<int Degree> double pcl::poisson::PPolynomial< Degree >::operator() (double t) const
Definition at line 158 of file ppolynomial.hpp.
operator*() [1/3]
template<int Degree> template<int Degree2> PPolynomial< Degree+Degree2 > pcl::poisson::PPolynomial< Degree >::operator* (const Polynomial< Degree2 > & p) const
Definition at line 261 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polys, and pcl::poisson::PPolynomial< Degree >::set().
operator*() [2/3]
template<int Degree> template<int Degree2> PPolynomial< Degree+Degree2 > pcl::poisson::PPolynomial< Degree >::operator* (const PPolynomial< Degree2 > & p) const
Definition at line 244 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polyCount, pcl::poisson::PPolynomial< Degree >::polys, and pcl::poisson::PPolynomial< Degree >::set().
operator*() [3/3]
template<int Degree> PPolynomial< Degree > pcl::poisson::PPolynomial< Degree >::operator* (double s) const
Definition at line 339 of file ppolynomial.hpp.
operator*=()
template<int Degree> PPolynomial< Degree > & pcl::poisson::PPolynomial< Degree >::operator*= (double s)
Definition at line 313 of file ppolynomial.hpp.
operator+() [1/2]
template<int Degree> PPolynomial< Degree > pcl::poisson::PPolynomial< Degree >::operator+ (const PPolynomial< Degree > & p) const
Definition at line 187 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polyCount, pcl::poisson::PPolynomial< Degree >::polys, and pcl::poisson::PPolynomial< Degree >::set().
operator+() [2/2]
template<int Degree> PPolynomial< Degree > pcl::poisson::PPolynomial< Degree >::operator+ (double s) const
Definition at line 325 of file ppolynomial.hpp.
operator+=()
template<int Degree> PPolynomial< Degree > & pcl::poisson::PPolynomial< Degree >::operator+= (double s)
Definition at line 309 of file ppolynomial.hpp.
operator-() [1/2]
template<int Degree> PPolynomial< Degree > pcl::poisson::PPolynomial< Degree >::operator- (const PPolynomial< Degree > & p) const
Definition at line 204 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polyCount, pcl::poisson::PPolynomial< Degree >::polys, and pcl::poisson::PPolynomial< Degree >::set().
operator-() [2/2]
template<int Degree> PPolynomial< Degree > pcl::poisson::PPolynomial< Degree >::operator- (double s) const
Definition at line 332 of file ppolynomial.hpp.
operator-=()
template<int Degree> PPolynomial< Degree > & pcl::poisson::PPolynomial< Degree >::operator-= (double s)
Definition at line 311 of file ppolynomial.hpp.
operator/()
template<int Degree> PPolynomial< Degree > pcl::poisson::PPolynomial< Degree >::operator/ (double s) const
Definition at line 346 of file ppolynomial.hpp.
operator/=()
template<int Degree> PPolynomial< Degree > & pcl::poisson::PPolynomial< Degree >::operator/= (double s)
Definition at line 319 of file ppolynomial.hpp.
operator=() [1/2]
template<int Degree> PPolynomial< Degree > & pcl::poisson::PPolynomial< Degree >::operator= (const PPolynomial< Degree > & p)
Definition at line 140 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polyCount, and pcl::poisson::PPolynomial< Degree >::polys.
operator=() [2/2]
template<int Degree> template<int Degree2> PPolynomial< Degree > & pcl::poisson::PPolynomial< Degree >::operator= (const PPolynomial< Degree2 > & p)
Definition at line 148 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polyCount, and pcl::poisson::PPolynomial< Degree >::polys.
printnl()
template<int Degree> void pcl::poisson::PPolynomial< Degree >::printnl (void) const
Definition at line 354 of file ppolynomial.hpp.
References pcl::poisson::Polynomial< Degree >::printnl().
reset()
template<int Degree> void pcl::poisson::PPolynomial< Degree >::reset (std::size_t newSize)
Definition at line 133 of file ppolynomial.hpp.
scale()
template<int Degree> PPolynomial< Degree > pcl::poisson::PPolynomial< Degree >::scale (double s) const
Definition at line 271 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polys, and pcl::poisson::PPolynomial< Degree >::set().
set() [1/2]
template<int Degree> void pcl::poisson::PPolynomial< Degree >::set (StartingPolynomial< Degree > * sps, int count)
Definition at line 106 of file ppolynomial.hpp.
set() [2/2]
template<int Degree> void pcl::poisson::PPolynomial< Degree >::set (std::size_t size)
Definition at line 121 of file ppolynomial.hpp.
Referenced by pcl::poisson::PPolynomial< Degree >::BSpline(), pcl::poisson::PPolynomial< Degree >::integral(), pcl::poisson::PPolynomial< Degree >::MovingAverage(), pcl::poisson::PPolynomial< Degree >::operator*(), pcl::poisson::PPolynomial< Degree >::operator+(), pcl::poisson::PPolynomial< Degree >::operator-(), pcl::poisson::PPolynomial< Degree >::scale(), and pcl::poisson::PPolynomial< Degree >::shift().
shift()
template<int Degree> PPolynomial< Degree > pcl::poisson::PPolynomial< Degree >::shift (double t) const
Definition at line 279 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polys, and pcl::poisson::PPolynomial< Degree >::set().
size()
template<int Degree> int pcl::poisson::PPolynomial< Degree >::size (void) const
Definition at line 118 of file ppolynomial.hpp.
write()
template<int Degree> void pcl::poisson::PPolynomial< Degree >::write (FILE * fp, int samples, double min, double max) const
Definition at line 435 of file ppolynomial.hpp.
Member Data Documentation
polyCount
template<int Degree> std::size_t pcl::poisson::PPolynomial< Degree >::polyCount
Definition at line 61 of file ppolynomial.h.
Referenced by pcl::poisson::PPolynomial< Degree >::addScaled(), pcl::poisson::PPolynomial< Degree >::operator*(), pcl::poisson::PPolynomial< Degree >::operator+(), pcl::poisson::PPolynomial< Degree >::operator-(), and pcl::poisson::PPolynomial< Degree >::operator=().
polys
template<int Degree> StartingPolynomial<Degree>* pcl::poisson::PPolynomial< Degree >::polys
Definition at line 62 of file ppolynomial.h.
Referenced by pcl::poisson::PPolynomial< Degree >::addScaled(), pcl::poisson::PPolynomial< Degree >::BSpline(), pcl::poisson::PPolynomial< Degree >::integral(), pcl::poisson::PPolynomial< Degree >::operator*(), pcl::poisson::PPolynomial< Degree >::operator+(), pcl::poisson::PPolynomial< Degree >::operator-(), pcl::poisson::PPolynomial< Degree >::operator=(), pcl::poisson::PPolynomial< Degree >::scale(), and pcl::poisson::PPolynomial< Degree >::shift().
The documentation for this class was generated from the following files:
pcl/surface/3rdparty/poisson4/ppolynomial.h
pcl/surface/3rdparty/poisson4/ppolynomial.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:42