Point Cloud Library (PCL): pcl::octree::OctreePointCloudDensityContainer Class Reference
pcl::octree::OctreePointCloudDensityContainer Class Reference
Octree pointcloud density leaf node class
#include <pcl/octree/octree_pointcloud_density.h>
Public Member Functions
OctreePointCloudDensityContainer ()=default
Class initialization.
~OctreePointCloudDensityContainer () override=default
Empty class deconstructor.
virtual OctreePointCloudDensityContainer * deepCopy () const
deep copy function
bool operator== (const OctreeContainerBase &other) const override
Equal comparison operator.
void addPointIndex (index_t) override
Read input data.
uindex_t getPointCounter ()
Return point counter.
void reset () override
Reset leaf node.
Public Member Functions inherited from pcl::octree::OctreeContainerBase
virtual ~OctreeContainerBase ()=default
bool operator!= (const OctreeContainerBase &other) const
Inequal comparison operator.
virtual uindex_t getSize () const
Pure abstract method to get size of container (number of indices)
void getPointIndex (index_t &) const
Empty getPointIndex implementation as this leaf node does not store any point indices.
virtual index_t getPointIndex () const
Empty getPointIndex implementation as this leaf node does not store any point indices.
virtual void getPointIndices (Indices &) const
Empty getPointIndices implementation as this leaf node does not store any data.
Detailed Description
Octree pointcloud density leaf node class
Note
This class implements a leaf node that counts the amount of points which fall into its voxel space.
Author
Julius Kammerl (juliu.nosp@m.s@ka.nosp@m.mmerl.nosp@m..de)
Definition at line 50 of file octree_pointcloud_density.h.
Constructor & Destructor Documentation
OctreePointCloudDensityContainer()
pcl::octree::OctreePointCloudDensityContainer::OctreePointCloudDensityContainer () default
Class initialization.
Referenced by deepCopy().
~OctreePointCloudDensityContainer()
pcl::octree::OctreePointCloudDensityContainer::~OctreePointCloudDensityContainer () override default
Empty class deconstructor.
Member Function Documentation
addPointIndex()
void pcl::octree::OctreePointCloudDensityContainer::addPointIndex (index_t) inline override virtual
Read input data.
Only an internal counter is increased.
Reimplemented from pcl::octree::OctreeContainerBase.
Definition at line 80 of file octree_pointcloud_density.h.
deepCopy()
virtual OctreePointCloudDensityContainer* pcl::octree::OctreePointCloudDensityContainer::deepCopy () const inline virtual
deep copy function
Definition at line 60 of file octree_pointcloud_density.h.
References OctreePointCloudDensityContainer().
getPointCounter()
uindex_t pcl::octree::OctreePointCloudDensityContainer::getPointCounter () inline
Return point counter.
Returns
Amount of points
Definition at line 89 of file octree_pointcloud_density.h.
Referenced by pcl::octree::OctreePointCloudDensity< PointT, LeafContainerT, BranchContainerT >::getVoxelDensityAtPoint().
operator==()
bool pcl::octree::OctreePointCloudDensityContainer::operator== (const OctreeContainerBase & other) const inline override virtual
Equal comparison operator.
Parameters
[in] other OctreePointCloudDensityContainer to compare with
Reimplemented from pcl::octree::OctreeContainerBase.
Definition at line 69 of file octree_pointcloud_density.h.
reset()
void pcl::octree::OctreePointCloudDensityContainer::reset () inline override virtual
Reset leaf node.
Implements pcl::octree::OctreeContainerBase.
Definition at line 96 of file octree_pointcloud_density.h.
The documentation for this class was generated from the following file:
pcl/octree/octree_pointcloud_density.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:34