Point Cloud Library (PCL): pcl::MaskMap Class Reference
pcl::MaskMap Class Reference
#include <pcl/recognition/mask_map.h>
Public Member Functions
MaskMap ()=default
MaskMap (std::size_t width, std::size_t height)
virtual ~MaskMap ()=default
void resize (std::size_t width, std::size_t height)
std::size_t getWidth () const
std::size_t getHeight () const
unsigned char * getData ()
const unsigned char * getData () const
void set (const std::size_t x, const std::size_t y)
void unset (const std::size_t x, const std::size_t y)
bool isSet (const std::size_t x, const std::size_t y) const
void reset ()
unsigned char & operator() (const std::size_t x, const std::size_t y)
const unsigned char & operator() (const std::size_t x, const std::size_t y) const
void erode (MaskMap &eroded_mask) const
Static Public Member Functions
static void getDifferenceMask (const MaskMap &mask0, const MaskMap &mask1, MaskMap &diff_mask)
static PCL_NODISCARD MaskMap getDifferenceMask (const MaskMap &mask0, const MaskMap &mask1)
Detailed Description
Definition at line 46 of file mask_map.h.
Constructor & Destructor Documentation
MaskMap() [1/2]
pcl::MaskMap::MaskMap () default
MaskMap() [2/2]
pcl::MaskMap::MaskMap (std::size_t width, std::size_t height)
~MaskMap()
virtual pcl::MaskMap::~MaskMap () virtual default
Member Function Documentation
erode()
void pcl::MaskMap::erode (MaskMap & eroded_mask) const
getData() [1/2]
unsigned char* pcl::MaskMap::getData () inline
Definition at line 70 of file mask_map.h.
Referenced by pcl::ColorModality< PointInT >::computeDistanceMap(), and pcl::SurfaceNormalModality< PointXYZT >::computeDistanceMap().
getData() [2/2]
const unsigned char* pcl::MaskMap::getData () const inline
Definition at line 76 of file mask_map.h.
getDifferenceMask() [1/2]
static PCL_NODISCARD MaskMap pcl::MaskMap::getDifferenceMask (const MaskMap & mask0, const MaskMap & mask1) static
getDifferenceMask() [2/2]
static void pcl::MaskMap::getDifferenceMask (const MaskMap & mask0, const MaskMap & mask1, MaskMap & diff_mask) static
Deprecated:
Scheduled for removal in version 1 . 12 : "Use new version diff getDifferenceMask(mask0, mask1)"
getHeight()
std::size_t pcl::MaskMap::getHeight () const inline
Definition at line 64 of file mask_map.h.
Referenced by pcl::ColorModality< PointInT >::computeDistanceMap(), pcl::SurfaceNormalModality< PointXYZT >::computeDistanceMap(), pcl::ColorGradientModality< PointXYZT >::erode(), pcl::ColorGradientModality< PointXYZT >::extractAllFeatures(), pcl::SurfaceNormalModality< PointXYZT >::extractAllFeatures(), pcl::ColorModality< PointInT >::extractFeatures(), pcl::ColorGradientModality< PointXYZT >::extractFeatures(), and pcl::SurfaceNormalModality< PointXYZT >::extractFeatures().
getWidth()
std::size_t pcl::MaskMap::getWidth () const inline
Definition at line 58 of file mask_map.h.
Referenced by pcl::ColorModality< PointInT >::computeDistanceMap(), pcl::SurfaceNormalModality< PointXYZT >::computeDistanceMap(), pcl::ColorGradientModality< PointXYZT >::erode(), pcl::ColorGradientModality< PointXYZT >::extractAllFeatures(), pcl::SurfaceNormalModality< PointXYZT >::extractAllFeatures(), pcl::ColorModality< PointInT >::extractFeatures(), pcl::ColorGradientModality< PointXYZT >::extractFeatures(), and pcl::SurfaceNormalModality< PointXYZT >::extractFeatures().
isSet()
bool pcl::MaskMap::isSet (const std::size_t x, const std::size_t y) const inline
Definition at line 102 of file mask_map.h.
operator()() [1/2]
unsigned char& pcl::MaskMap::operator() (const std::size_t x, const std::size_t y) inline
Definition at line 114 of file mask_map.h.
operator()() [2/2]
const unsigned char& pcl::MaskMap::operator() (const std::size_t x, const std::size_t y) const inline
Definition at line 120 of file mask_map.h.
reset()
void pcl::MaskMap::reset () inline
Definition at line 108 of file mask_map.h.
resize()
void pcl::MaskMap::resize (std::size_t width, std::size_t height)
Referenced by pcl::ColorGradientModality< PointXYZT >::erode(), pcl::SurfaceNormalModality< PointXYZT >::extractAllFeatures(), and pcl::SurfaceNormalModality< PointXYZT >::extractFeatures().
set()
void pcl::MaskMap::set (const std::size_t x, const std::size_t y) inline
Definition at line 90 of file mask_map.h.
unset()
void pcl::MaskMap::unset (const std::size_t x, const std::size_t y) inline
Definition at line 96 of file mask_map.h.
The documentation for this class was generated from the following file:
pcl/recognition/mask_map.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Jun 2 2020 14:12:13