Point Cloud Library (PCL): pcl::common::CloudGenerator< pcl::PointXY, GeneratorT > Class Template Reference
pcl::common::CloudGenerator< pcl::PointXY, GeneratorT > Class Template Reference
#include <pcl/common/generate.h>
Public Types
using GeneratorParameters = typename GeneratorT::Parameters
Public Member Functions
CloudGenerator ()
CloudGenerator (const GeneratorParameters &params)
CloudGenerator (const GeneratorParameters &x_params, const GeneratorParameters &y_params)
void setParameters (const GeneratorParameters &params)
void setParametersForX (const GeneratorParameters &x_params)
void setParametersForY (const GeneratorParameters &y_params)
const GeneratorParameters & getParametersForX () const
const GeneratorParameters & getParametersForY () const
pcl::PointXY get ()
int fill (pcl::PointCloud< pcl::PointXY > &cloud)
int fill (int width, int height, pcl::PointCloud< pcl::PointXY > &cloud)
Detailed Description
template<typename GeneratorT>
class pcl::common::CloudGenerator< pcl::PointXY, GeneratorT >
Definition at line 143 of file generate.h.
Member Typedef Documentation
GeneratorParameters
template<typename GeneratorT > using pcl::common::CloudGenerator< pcl::PointXY, GeneratorT >::GeneratorParameters = typename GeneratorT::Parameters
Definition at line 146 of file generate.h.
Constructor & Destructor Documentation
CloudGenerator() [1/3]
template<typename GeneratorT > pcl::common::CloudGenerator< pcl::PointXY, GeneratorT >::CloudGenerator
Definition at line 185 of file generate.hpp.
CloudGenerator() [2/3]
template<typename GeneratorT > pcl::common::CloudGenerator< pcl::PointXY, GeneratorT >::CloudGenerator (const GeneratorParameters & params)
Definition at line 200 of file generate.hpp.
References pcl::common::CloudGenerator< PointT, GeneratorT >::setParameters().
CloudGenerator() [3/3]
template<typename GeneratorT > pcl::common::CloudGenerator< pcl::PointXY, GeneratorT >::CloudGenerator (const GeneratorParameters & x_params, const GeneratorParameters & y_params)
Definition at line 192 of file generate.hpp.
Member Function Documentation
fill() [1/2]
template<typename GeneratorT > int pcl::common::CloudGenerator< pcl::PointXY, GeneratorT >::fill (int width, int height, pcl::PointCloud< pcl::PointXY > & cloud)
Definition at line 262 of file generate.hpp.
References pcl::PointCloud< PointT >::empty(), pcl::PointCloud< PointT >::is_dense, and pcl::PointCloud< PointT >::resize().
fill() [2/2]
template<typename GeneratorT > int pcl::common::CloudGenerator< pcl::PointXY, GeneratorT >::fill (pcl::PointCloud< pcl::PointXY > & cloud)
Definition at line 255 of file generate.hpp.
References pcl::common::CloudGenerator< PointT, GeneratorT >::fill(), pcl::PointCloud< PointT >::height, and pcl::PointCloud< PointT >::width.
get()
template<typename GeneratorT > pcl::PointXY pcl::common::CloudGenerator< pcl::PointXY, GeneratorT >::get
Definition at line 245 of file generate.hpp.
References pcl::PointXY::x, and pcl::PointXY::y.
getParametersForX()
template<typename GeneratorT > const CloudGenerator< pcl::PointXY, GeneratorT >::GeneratorParameters & pcl::common::CloudGenerator< pcl::PointXY, GeneratorT >::getParametersForX
Definition at line 231 of file generate.hpp.
getParametersForY()
template<typename GeneratorT > const CloudGenerator< pcl::PointXY, GeneratorT >::GeneratorParameters & pcl::common::CloudGenerator< pcl::PointXY, GeneratorT >::getParametersForY
Definition at line 238 of file generate.hpp.
setParameters()
template<typename GeneratorT > void pcl::common::CloudGenerator< pcl::PointXY, GeneratorT >::setParameters (const GeneratorParameters & params)
Definition at line 207 of file generate.hpp.
setParametersForX()
template<typename GeneratorT > void pcl::common::CloudGenerator< pcl::PointXY, GeneratorT >::setParametersForX (const GeneratorParameters & x_params)
Definition at line 217 of file generate.hpp.
setParametersForY()
template<typename GeneratorT > void pcl::common::CloudGenerator< pcl::PointXY, GeneratorT >::setParametersForY (const GeneratorParameters & y_params)
Definition at line 224 of file generate.hpp.
The documentation for this class was generated from the following files:
pcl/common/generate.h
pcl/common/impl/generate.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:26