Point Cloud Library (PCL): NCVVectorReuse< T > Class Template Reference
NCVVectorReuse< T > Class Template Reference
NCVVectorReuse.
#include </__w/1/s/gpu/people/src/cuda/nvidia/NCV.hpp>
Public Member Functions
NCVVectorReuse (const NCVMemSegment &memSegment)
NCVVectorReuse (const NCVMemSegment &memSegment, Ncv32u length)
NcvBool isMemReused () const
Public Member Functions inherited from NCVVector< T >
NCVVector ()
void clear ()
NCVStatus copySolid (NCVVector< T > &dst, cudaStream_t cuStream, std::size_t howMuch=0) const
T * ptr () const
std::size_t length () const
NCVMemoryType memType () const
Additional Inherited Members
Protected Attributes inherited from NCVVector< T >
T * _ptr
std::size_t _length
NCVMemoryType _memtype
Detailed Description
template<class T>
class NCVVectorReuse< T >
NCVVectorReuse.
Definition at line 625 of file NCV.hpp.
Constructor & Destructor Documentation
NCVVectorReuse() [1/2]
template<class T > NCVVectorReuse< T >::NCVVectorReuse (const NCVMemSegment & memSegment) inline explicit
Definition at line 632 of file NCV.hpp.
References NCVVector< T >::_length, NCVVector< T >::_ptr, NCVMemSegment::begin, NCVVector< T >::clear(), NCVMemPtr::memtype, NCVMemPtr::ptr, and NCVMemSegment::size.
NCVVectorReuse() [2/2]
template<class T > NCVVectorReuse< T >::NCVVectorReuse (const NCVMemSegment & memSegment, Ncv32u length) inline
Definition at line 644 of file NCV.hpp.
References NCVVector< T >::_length, NCVVector< T >::_ptr, NCVMemSegment::begin, NCVVector< T >::clear(), NCVVector< T >::length(), NCVMemPtr::memtype, NCVMemPtr::ptr, and NCVMemSegment::size.
Member Function Documentation
isMemReused()
template<class T > NcvBool NCVVectorReuse< T >::isMemReused () const inline
Definition at line 659 of file NCV.hpp.
The documentation for this class was generated from the following file:
/__w/1/s/gpu/people/src/cuda/nvidia/NCV.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:06