Point Cloud Library (PCL): pcl::geometry::HalfEdgeIndex Class Reference
pcl::geometry::HalfEdgeIndex Class Reference
Module geometry
Index used to access elements in the half-edge mesh.
#include <pcl/geometry/mesh_indices.h>
Public Types
using Base = boost::totally_ordered< pcl::geometry::HalfEdgeIndex, boost::unit_steppable< pcl::geometry::HalfEdgeIndex, boost::additive< pcl::geometry::HalfEdgeIndex > >>
using Self = pcl::geometry::HalfEdgeIndex
Public Member Functions
HalfEdgeIndex ()
Constructor.
HalfEdgeIndex (const int index)
Constructor.
bool isValid () const
Returns true if the index is valid.
void invalidate ()
Invalidate the index.
int get () const
Get the index.
void set (const int index)
Set the index.
bool operator< (const Self &other) const
Comparison operators (with boost::operators): < > <= >=.
bool operator== (const Self &other) const
Comparison operators (with boost::operators): == !=.
Self & operator++ ()
Increment operators (with boost::operators): ++ (pre and post)
Self & operator-- ()
Decrement operators (with boost::operators): -- (pre and post)
Self & operator+= (const Self &other)
Addition operators (with boost::operators): + +=.
Self & operator-= (const Self &other)
Subtraction operators (with boost::operators): - -=.
Friends
std::istream & operator>> (std::istream &is, pcl::geometry::HalfEdgeIndex &index)
istream operator.
Detailed Description
Index used to access elements in the half-edge mesh.
It is basically just a wrapper around an integer with a few added methods.
Author
Martin Saelzle
Definition at line 194 of file mesh_indices.h.
Member Typedef Documentation
Base
using pcl::geometry::HalfEdgeIndex::Base = boost::totally_ordered< pcl::geometry::HalfEdgeIndex, boost::unit_steppable<pcl::geometry::HalfEdgeIndex, boost::additive<pcl::geometry::HalfEdgeIndex> >>
Definition at line 206 of file mesh_indices.h.
Self
using pcl::geometry::HalfEdgeIndex::Self = pcl::geometry::HalfEdgeIndex
Definition at line 207 of file mesh_indices.h.
Constructor & Destructor Documentation
HalfEdgeIndex() [1/2]
pcl::geometry::HalfEdgeIndex::HalfEdgeIndex () inline
Constructor.
Initializes with an invalid index.
Definition at line 210 of file mesh_indices.h.
HalfEdgeIndex() [2/2]
pcl::geometry::HalfEdgeIndex::HalfEdgeIndex (const int index) inline explicit
Constructor.
Parameters
[in] index The integer index.
Definition at line 215 of file mesh_indices.h.
Member Function Documentation
get()
int pcl::geometry::HalfEdgeIndex::get () const inline
Get the index.
Definition at line 233 of file mesh_indices.h.
Referenced by pcl::geometry::MeshBase< QuadMesh< MeshTraitsT >, MeshTraitsT, QuadMeshTag >::getHalfEdge(), pcl::geometry::MeshBase< QuadMesh< MeshTraitsT >, MeshTraitsT, QuadMeshTag >::getOppositeHalfEdgeIndex(), operator+=(), operator-=(), operator<(), pcl::geometry::operator<<(), operator==(), pcl::geometry::MeshBase< QuadMesh< MeshTraitsT >, MeshTraitsT, QuadMeshTag >::setHalfEdge(), and pcl::geometry::toEdgeIndex().
invalidate()
void pcl::geometry::HalfEdgeIndex::invalidate () inline
Invalidate the index.
Definition at line 226 of file mesh_indices.h.
Referenced by pcl::geometry::MeshBase< QuadMesh< MeshTraitsT >, MeshTraitsT, QuadMeshTag >::markDeleted().
isValid()
bool pcl::geometry::HalfEdgeIndex::isValid () const inline
Returns true if the index is valid.
Definition at line 219 of file mesh_indices.h.
Referenced by pcl::geometry::toEdgeIndex().
operator++()
Self& pcl::geometry::HalfEdgeIndex::operator++ () inline
Increment operators (with boost::operators): ++ (pre and post)
Definition at line 261 of file mesh_indices.h.
operator+=()
Self& pcl::geometry::HalfEdgeIndex::operator+= (const Self & other) inline
Addition operators (with boost::operators): + +=.
Definition at line 277 of file mesh_indices.h.
References get().
operator--()
Self& pcl::geometry::HalfEdgeIndex::operator-- () inline
Decrement operators (with boost::operators): -- (pre and post)
Definition at line 269 of file mesh_indices.h.
operator-=()
Self& pcl::geometry::HalfEdgeIndex::operator-= (const Self & other) inline
Subtraction operators (with boost::operators): - -=.
Definition at line 285 of file mesh_indices.h.
References get().
operator<()
bool pcl::geometry::HalfEdgeIndex::operator< (const Self & other) const inline
Comparison operators (with boost::operators): < > <= >=.
Definition at line 247 of file mesh_indices.h.
References get().
operator==()
bool pcl::geometry::HalfEdgeIndex::operator== (const Self & other) const inline
Comparison operators (with boost::operators): == !=.
Definition at line 254 of file mesh_indices.h.
References get().
set()
void pcl::geometry::HalfEdgeIndex::set (const int index) inline
Set the index.
Definition at line 240 of file mesh_indices.h.
Friends And Related Function Documentation
operator>>
std::istream& operator>> (std::istream & is, pcl::geometry::HalfEdgeIndex & index) friend
istream operator.
Definition at line 308 of file mesh_indices.h.
The documentation for this class was generated from the following file:
pcl/geometry/mesh_indices.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Apr 6 2021 19:04:55