Point Cloud Library (PCL): pcl::octree::OctreeBranchNode< ContainerT > Class Template Reference
pcl::octree::OctreeBranchNode< ContainerT > Class Template Reference
Abstract octree branch class
#include <pcl/octree/octree_nodes.h>
Public Member Functions
OctreeBranchNode ()
Empty constructor.
OctreeBranchNode (const OctreeBranchNode &source)
Empty constructor.
OctreeBranchNode & operator= (const OctreeBranchNode &source)
Copy operator.
OctreeBranchNode * deepCopy () const override
Octree deep copy method.
~OctreeBranchNode ()
Empty deconstructor.
OctreeNode *& operator[] (unsigned char child_idx_arg)
Access operator.
OctreeNode * getChildPtr (unsigned char child_idx_arg) const
Get pointer to child.
void setChildPtr (OctreeNode *child, unsigned char index)
Get pointer to child.
bool hasChild (unsigned char child_idx_arg) const
Check if branch is pointing to a particular child node.
node_type_t getNodeType () const override
Check if branch can be pruned.
void reset ()
const ContainerT * operator-> () const
Get const pointer to container.
ContainerT * operator-> ()
Get pointer to container.
const ContainerT & operator* () const
Get const reference to container.
ContainerT & operator* ()
Get reference to container.
const ContainerT & getContainer () const
Get const reference to container.
ContainerT & getContainer ()
Get reference to container.
const ContainerT * getContainerPtr () const
Get const pointer to container.
ContainerT * getContainerPtr ()
Get pointer to container.
Public Member Functions inherited from pcl::octree::OctreeNode
OctreeNode ()
virtual ~OctreeNode ()
Protected Attributes
OctreeNode * child_node_array_ [8]
ContainerT container_
Detailed Description
template<typename ContainerT>
class pcl::octree::OctreeBranchNode< ContainerT >
Abstract octree branch class
Note
Octree branch classes may collect data of type DataT
Author
Julius Kammerl (juliu.nosp@m.s@ka.nosp@m.mmerl.nosp@m..de)
Definition at line 182 of file octree_nodes.h.
Constructor & Destructor Documentation
OctreeBranchNode() [1/2]
template<typename ContainerT > pcl::octree::OctreeBranchNode< ContainerT >::OctreeBranchNode () inline
Empty constructor.
Definition at line 185 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::child_node_array_.
OctreeBranchNode() [2/2]
template<typename ContainerT > pcl::octree::OctreeBranchNode< ContainerT >::OctreeBranchNode (const OctreeBranchNode< ContainerT > & source) inline
Empty constructor.
Definition at line 192 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::child_node_array_, and pcl::octree::OctreeNode::deepCopy().
~OctreeBranchNode()
template<typename ContainerT > pcl::octree::OctreeBranchNode< ContainerT >::~OctreeBranchNode () inline
Empty deconstructor.
Definition at line 222 of file octree_nodes.h.
Member Function Documentation
deepCopy()
template<typename ContainerT > OctreeBranchNode* pcl::octree::OctreeBranchNode< ContainerT >::deepCopy () const inline override virtual
Octree deep copy method.
Implements pcl::octree::OctreeNode.
Definition at line 215 of file octree_nodes.h.
getChildPtr()
template<typename ContainerT > OctreeNode* pcl::octree::OctreeBranchNode< ContainerT >::getChildPtr (unsigned char child_idx_arg) const inline
Get pointer to child.
Parameters
child_idx_arg index to child node
Returns
OctreeNode pointer
Definition at line 240 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::child_node_array_.
Referenced by pcl::octree::OctreeBase< OctreePointCloudVoxelCentroidContainer< PointT >, OctreeContainerEmpty >::branchHasChild(), pcl::octree::OctreeBase< OctreePointCloudVoxelCentroidContainer< PointT >, OctreeContainerEmpty >::getBranchBitPattern(), pcl::octree::OctreeBase< OctreePointCloudVoxelCentroidContainer< PointT >, OctreeContainerEmpty >::getBranchChildPtr(), and pcl::octree::OctreeBase< OctreePointCloudVoxelCentroidContainer< PointT >, OctreeContainerEmpty >::serializeTreeRecursive().
getContainer() [1/2]
template<typename ContainerT > ContainerT& pcl::octree::OctreeBranchNode< ContainerT >::getContainer () inline
Get reference to container.
Definition at line 342 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::container_.
getContainer() [2/2]
template<typename ContainerT > const ContainerT& pcl::octree::OctreeBranchNode< ContainerT >::getContainer () const inline
Get const reference to container.
Definition at line 335 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::container_.
getContainerPtr() [1/2]
template<typename ContainerT > ContainerT* pcl::octree::OctreeBranchNode< ContainerT >::getContainerPtr () inline
Get pointer to container.
Definition at line 356 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::container_.
getContainerPtr() [2/2]
template<typename ContainerT > const ContainerT* pcl::octree::OctreeBranchNode< ContainerT >::getContainerPtr () const inline
Get const pointer to container.
Definition at line 349 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::container_.
getNodeType()
template<typename ContainerT > node_type_t pcl::octree::OctreeBranchNode< ContainerT >::getNodeType () const inline override virtual
Check if branch can be pruned.
Note
if all children are leaf nodes AND contain identical containers, branch can be pruned
Returns
"true" if branch can be pruned; "false" otherwise
Get the type of octree node. Returns LEAVE_NODE type
Implements pcl::octree::OctreeNode.
Definition at line 292 of file octree_nodes.h.
References pcl::octree::BRANCH_NODE.
hasChild()
template<typename ContainerT > bool pcl::octree::OctreeBranchNode< ContainerT >::hasChild (unsigned char child_idx_arg) const inline
Check if branch is pointing to a particular child node.
Parameters
child_idx_arg index to child node
Returns
"true" if pointer to child node exists; "false" otherwise
Definition at line 261 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::child_node_array_.
Referenced by pcl::octree::OctreeBase< OctreePointCloudVoxelCentroidContainer< PointT >, OctreeContainerEmpty >::deleteBranchChild(), pcl::octree::OctreeBase< OctreePointCloudVoxelCentroidContainer< PointT >, OctreeContainerEmpty >::deleteLeafRecursive(), and pcl::octree::OctreeBase< OctreePointCloudVoxelCentroidContainer< PointT >, OctreeContainerEmpty >::serializeTreeRecursive().
operator*() [1/2]
template<typename ContainerT > ContainerT& pcl::octree::OctreeBranchNode< ContainerT >::operator* () inline
Get reference to container.
Definition at line 328 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::container_.
operator*() [2/2]
template<typename ContainerT > const ContainerT& pcl::octree::OctreeBranchNode< ContainerT >::operator* () const inline
Get const reference to container.
Definition at line 321 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::container_.
operator->() [1/2]
template<typename ContainerT > ContainerT* pcl::octree::OctreeBranchNode< ContainerT >::operator-> () inline
Get pointer to container.
Definition at line 314 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::container_.
operator->() [2/2]
template<typename ContainerT > const ContainerT* pcl::octree::OctreeBranchNode< ContainerT >::operator-> () const inline
Get const pointer to container.
Definition at line 307 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::container_.
operator=()
template<typename ContainerT > OctreeBranchNode& pcl::octree::OctreeBranchNode< ContainerT >::operator= (const OctreeBranchNode< ContainerT > & source) inline
Copy operator.
Definition at line 203 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::child_node_array_, and pcl::octree::OctreeNode::deepCopy().
operator[]()
template<typename ContainerT > OctreeNode*& pcl::octree::OctreeBranchNode< ContainerT >::operator[] (unsigned char child_idx_arg) inline
Access operator.
Parameters
child_idx_arg index to child node
Returns
OctreeNode pointer
Definition at line 229 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::child_node_array_.
reset()
template<typename ContainerT > void pcl::octree::OctreeBranchNode< ContainerT >::reset () inline
Definition at line 299 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::child_node_array_, and pcl::octree::OctreeBranchNode< ContainerT >::container_.
setChildPtr()
template<typename ContainerT > void pcl::octree::OctreeBranchNode< ContainerT >::setChildPtr (OctreeNode * child, unsigned char index) inline
Get pointer to child.
Returns
OctreeNode pointer
Definition at line 250 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::child_node_array_.
Member Data Documentation
child_node_array_
template<typename ContainerT > OctreeNode* pcl::octree::OctreeBranchNode< ContainerT >::child_node_array_[8] protected
Definition at line 362 of file octree_nodes.h.
Referenced by pcl::octree::OctreeBranchNode< ContainerT >::getChildPtr(), pcl::octree::OctreeBranchNode< ContainerT >::hasChild(), pcl::octree::OctreeBranchNode< ContainerT >::OctreeBranchNode(), pcl::octree::OctreeBranchNode< ContainerT >::operator=(), pcl::octree::OctreeBranchNode< ContainerT >::operator[](), pcl::octree::OctreeBranchNode< ContainerT >::reset(), and pcl::octree::OctreeBranchNode< ContainerT >::setChildPtr().
container_
template<typename ContainerT > ContainerT pcl::octree::OctreeBranchNode< ContainerT >::container_ protected
Definition at line 364 of file octree_nodes.h.
Referenced by pcl::octree::OctreeBranchNode< ContainerT >::getContainer(), pcl::octree::OctreeBranchNode< ContainerT >::getContainerPtr(), pcl::octree::OctreeBranchNode< ContainerT >::operator*(), pcl::octree::OctreeBranchNode< ContainerT >::operator->(), and pcl::octree::OctreeBranchNode< ContainerT >::reset().
The documentation for this class was generated from the following file:
pcl/octree/octree_nodes.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Jun 2 2020 14:13:46