Point Cloud Library (PCL): pcl::SampleConsensusModelTorus< PointT, PointNT > Class Template Reference
pcl::SampleConsensusModelTorus< PointT, PointNT > Class Template Reference
Module sample_consensus
SampleConsensusModelTorus defines a model for 3D torus segmentation.
#include <pcl/sample_consensus/sac_model_torus.h>
Public Types
using Ptr = shared_ptr< SampleConsensusModelTorus< PointT, PointNT > >
using ConstPtr = shared_ptr< const SampleConsensusModelTorus< PointT, PointNT > >
Public Types inherited from pcl::SampleConsensusModel< PointT >
using PointCloud = pcl::PointCloud< PointT >
using PointCloudConstPtr = typename PointCloud::ConstPtr
using PointCloudPtr = typename PointCloud::Ptr
using SearchPtr = typename pcl::search::Search< PointT >::Ptr
using Ptr = shared_ptr< SampleConsensusModel< PointT > >
using ConstPtr = shared_ptr< const SampleConsensusModel< PointT > >
Public Types inherited from pcl::SampleConsensusModelFromNormals< PointT, PointNT >
using PointCloudNConstPtr = typename pcl::PointCloud< PointNT >::ConstPtr
using PointCloudNPtr = typename pcl::PointCloud< PointNT >::Ptr
using Ptr = shared_ptr< SampleConsensusModelFromNormals< PointT, PointNT > >
using ConstPtr = shared_ptr< const SampleConsensusModelFromNormals< PointT, PointNT > >
Public Member Functions
SampleConsensusModelTorus (const PointCloudConstPtr &cloud, bool random=false)
Constructor for base SampleConsensusModelTorus.
SampleConsensusModelTorus (const PointCloudConstPtr &cloud, const Indices &indices, bool random=false)
Constructor for base SampleConsensusModelTorus.
SampleConsensusModelTorus (const SampleConsensusModelTorus &source)
Copy constructor.
~SampleConsensusModelTorus () override=default
Empty destructor.
SampleConsensusModelTorus & operator= (const SampleConsensusModelTorus &source)
Copy constructor.
bool computeModelCoefficients (const Indices &samples, Eigen::VectorXf &model_coefficients) const override
Check whether the given index samples can form a valid torus model, compute the model coefficients from these samples and store them in model_coefficients.
void getDistancesToModel (const Eigen::VectorXf &model_coefficients, std::vector< double > &distances) const override
Compute all distances from the cloud data to a given torus model.
void selectWithinDistance (const Eigen::VectorXf &model_coefficients, const double threshold, Indices &inliers) override
Select all the points which respect the given model coefficients as inliers.
std::size_t countWithinDistance (const Eigen::VectorXf &model_coefficients, const double threshold) const override
Count all the points which respect the given model coefficients as inliers.
void optimizeModelCoefficients (const Indices &inliers, const Eigen::VectorXf &model_coefficients, Eigen::VectorXf &optimized_coefficients) const override
Recompute the torus coefficients using the given inlier set and return them to the user.
void projectPoints (const Indices &inliers, const Eigen::VectorXf &model_coefficients, PointCloud &projected_points, bool copy_data_fields=true) const override
Create a new point cloud with inliers projected onto the torus model.
bool doSamplesVerifyModel (const std::set< index_t > &indices, const Eigen::VectorXf &model_coefficients, const double threshold) const override
Verify whether a subset of indices verifies the given torus model coefficients.
pcl::SacModel getModelType () const override
Return a unique id for this model (SACMODEL_TORUS).
Public Member Functions inherited from pcl::SampleConsensusModel< PointT >
SampleConsensusModel (const PointCloudConstPtr &cloud, bool random=false)
Constructor for base SampleConsensusModel.
SampleConsensusModel (const PointCloudConstPtr &cloud, const Indices &indices, bool random=false)
Constructor for base SampleConsensusModel.
virtual ~SampleConsensusModel ()=default
Destructor for base SampleConsensusModel.
virtual void getSamples (int &iterations, Indices &samples)
Get a set of random data samples and return them as point indices.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr getInputCloud () const
Get a pointer to the input point cloud dataset.
void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
void setIndices (const Indices &indices)
Provide the vector of indices that represents the input data.
IndicesPtr getIndices () const
Get a pointer to the vector of indices used.
const std::string & getClassName () const
Get a string representation of the name of this class.
unsigned int getSampleSize () const
Return the size of a sample from which the model is computed.
unsigned int getModelSize () const
Return the number of coefficients in the model.
void setRadiusLimits (const double &min_radius, const double &max_radius)
Set the minimum and maximum allowable radius limits for the model (applicable to models that estimate a radius)
void getRadiusLimits (double &min_radius, double &max_radius) const
Get the minimum and maximum allowable radius limits for the model as set by the user.
void setModelConstraints (std::function< bool(const Eigen::VectorXf &)> function)
This can be used to impose any kind of constraint on the model, e.g.
void setSamplesMaxDist (const double &radius, SearchPtr search)
Set the maximum distance allowed when drawing random samples.
void getSamplesMaxDist (double &radius) const
Get maximum distance allowed when drawing random samples.
double computeVariance (const std::vector< double > &error_sqr_dists) const
Compute the variance of the errors to the model.
double computeVariance () const
Compute the variance of the errors to the model from the internally estimated vector of distances.
Public Member Functions inherited from pcl::SampleConsensusModelFromNormals< PointT, PointNT >
SampleConsensusModelFromNormals ()
Empty constructor for base SampleConsensusModelFromNormals.
virtual ~SampleConsensusModelFromNormals ()=default
Destructor.
void setNormalDistanceWeight (const double w)
Set the normal angular distance weight.
double getNormalDistanceWeight () const
Get the normal angular distance weight.
void setInputNormals (const PointCloudNConstPtr &normals)
Provide a pointer to the input dataset that contains the point normals of the XYZ dataset.
PointCloudNConstPtr getInputNormals () const
Get a pointer to the normals of the input XYZ point cloud dataset.
Protected Member Functions
void projectPointToTorus (const Eigen::Vector3f &pt, const Eigen::Vector3f &pt_n, const Eigen::VectorXf &model_coefficients, Eigen::Vector3f &pt_proj) const
Project a point onto a torus given by its model coefficients (radii, torus_center_point, torus_normal)
bool isModelValid (const Eigen::VectorXf &model_coefficients) const override
Check whether a model is valid given the user constraints.
bool isSampleGood (const Indices &samples) const override
Check if a sample of indices results in a good sample of points indices.
Protected Member Functions inherited from pcl::SampleConsensusModel< PointT >
SampleConsensusModel (bool random=false)
Empty constructor for base SampleConsensusModel.
void drawIndexSample (Indices &sample)
Fills a sample array with random samples from the indices_ vector.
void drawIndexSampleRadius (Indices &sample)
Fills a sample array with one random sample from the indices_ vector and other random samples that are closer than samples_radius_.
int rnd ()
Boost-based random number generator.
Additional Inherited Members
Protected Attributes inherited from pcl::SampleConsensusModel< PointT >
std::string model_name_
The model name.
PointCloudConstPtr input_
A boost shared pointer to the point cloud data array.
IndicesPtr indices_
A pointer to the vector of point indices to use.
double radius_min_
The minimum and maximum radius limits for the model.
double radius_max_
double samples_radius_
The maximum distance of subsequent samples from the first (radius search)
SearchPtr samples_radius_search_
The search object for picking subsequent samples using radius search.
Indices shuffled_indices_
Data containing a shuffled version of the indices.
boost::mt19937 rng_alg_
Boost-based random number generator algorithm.
std::shared_ptr< boost::uniform_int<> > rng_dist_
Boost-based random number generator distribution.
std::shared_ptr< boost::variate_generator< boost::mt19937 &, boost::uniform_int<> > > rng_gen_
Boost-based random number generator.
std::vector< double > error_sqr_dists_
A vector holding the distances to the computed model.
unsigned int sample_size_
The size of a sample from which the model is computed.
unsigned int model_size_
The number of coefficients in the model.
std::function< bool(const Eigen::VectorXf &)> custom_model_constraints_
A user defined function that takes model coefficients and returns whether the model is acceptable or not.
Protected Attributes inherited from pcl::SampleConsensusModelFromNormals< PointT, PointNT >
double normal_distance_weight_ {0.0}
The relative weight (between 0 and 1) to give to the angular distance (0 to pi/2) between point normals and the plane normal.
PointCloudNConstPtr normals_
A pointer to the input dataset that contains the point normals of the XYZ dataset.
Static Protected Attributes inherited from pcl::SampleConsensusModel< PointT >
static const unsigned int max_sample_checks_ = 1000
The maximum number of samples to try until we get a good one.
Detailed Description
template<typename PointT, typename PointNT>
class pcl::SampleConsensusModelTorus< PointT, PointNT >
SampleConsensusModelTorus defines a model for 3D torus segmentation.
The model coefficients are defined as:
radii.inner : the torus's inner radius
radii.outer : the torus's outer radius
torus_center_point.x : the X coordinate of the center of the torus
torus_center_point.y : the Y coordinate of the center of the torus
torus_center_point.z : the Z coordinate of the center of the torus
torus_normal.x : the X coordinate of the normal of the torus
torus_normal.y : the Y coordinate of the normal of the torus
torus_normal.z : the Z coordinate of the normal of the torus
Author
lasdasdas
Definition at line 64 of file sac_model_torus.h.
Member Typedef Documentation
ConstPtr
template<typename PointT , typename PointNT > using pcl::SampleConsensusModelTorus< PointT, PointNT >::ConstPtr = shared_ptr<const SampleConsensusModelTorus<PointT, PointNT> >
Definition at line 82 of file sac_model_torus.h.
Ptr
template<typename PointT , typename PointNT > using pcl::SampleConsensusModelTorus< PointT, PointNT >::Ptr = shared_ptr<SampleConsensusModelTorus<PointT, PointNT> >
Definition at line 81 of file sac_model_torus.h.
Constructor & Destructor Documentation
SampleConsensusModelTorus() [1/3]
template<typename PointT , typename PointNT > pcl::SampleConsensusModelTorus< PointT, PointNT >::SampleConsensusModelTorus (const PointCloudConstPtr & cloud, bool random = false) inline
Constructor for base SampleConsensusModelTorus.
Parameters
[in] cloud the input point cloud dataset
[in] random if true set the random seed to the current time, else set to 12345 (default: false)
Definition at line 89 of file sac_model_torus.h.
References pcl::SampleConsensusModel< PointT >::model_name_, pcl::SampleConsensusModel< PointT >::model_size_, and pcl::SampleConsensusModel< PointT >::sample_size_.
SampleConsensusModelTorus() [2/3]
template<typename PointT , typename PointNT > pcl::SampleConsensusModelTorus< PointT, PointNT >::SampleConsensusModelTorus (const PointCloudConstPtr & cloud, const Indices & indices, bool random = false) inline
Constructor for base SampleConsensusModelTorus.
Parameters
[in] cloud the input point cloud dataset
[in] indices a vector of point indices to be used from cloud
[in] random if true set the random seed to the current time, else set to 12345 (default: false)
Definition at line 104 of file sac_model_torus.h.
References pcl::SampleConsensusModel< PointT >::model_name_, pcl::SampleConsensusModel< PointT >::model_size_, and pcl::SampleConsensusModel< PointT >::sample_size_.
SampleConsensusModelTorus() [3/3]
template<typename PointT , typename PointNT > pcl::SampleConsensusModelTorus< PointT, PointNT >::SampleConsensusModelTorus (const SampleConsensusModelTorus< PointT, PointNT > & source) inline
Copy constructor.
Parameters
[in] source the model to copy into this
Definition at line 118 of file sac_model_torus.h.
References pcl::SampleConsensusModel< PointT >::model_name_.
~SampleConsensusModelTorus()
template<typename PointT , typename PointNT > pcl::SampleConsensusModelTorus< PointT, PointNT >::~SampleConsensusModelTorus () override default
Empty destructor.
Member Function Documentation
computeModelCoefficients()
template<typename PointT , typename PointNT > bool pcl::SampleConsensusModelTorus< PointT, PointNT >::computeModelCoefficients (const Indices & samples, Eigen::VectorXf & model_coefficients) const override virtual
Check whether the given index samples can form a valid torus model, compute the model coefficients from these samples and store them in model_coefficients.
The torus coefficients are: radii, torus_center_point, torus_normal.
Parameters
[in] samples the point indices found as possible good candidates for creating a valid model
[out] model_coefficients the resultant model coefficients
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 97 of file sac_model_torus.hpp.
countWithinDistance()
template<typename PointT , typename PointNT > std::size_t pcl::SampleConsensusModelTorus< PointT, PointNT >::countWithinDistance (const Eigen::VectorXf & model_coefficients, const double threshold) const override virtual
Count all the points which respect the given model coefficients as inliers.
Parameters
[in] model_coefficients the coefficients of a model that we need to compute distances to
[in] threshold maximum admissible distance threshold for determining the inliers from the outliers
Returns
the resultant number of inliers
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 332 of file sac_model_torus.hpp.
References pcl::geometry::distance().
doSamplesVerifyModel()
template<typename PointT , typename PointNT > bool pcl::SampleConsensusModelTorus< PointT, PointNT >::doSamplesVerifyModel (const std::set< index_t > & indices, const Eigen::VectorXf & model_coefficients, const double threshold) const override virtual
Verify whether a subset of indices verifies the given torus model coefficients.
Parameters
[in] indices the data indices that need to be tested against the torus model
[in] model_coefficients the torus model coefficients
[in] threshold a maximum admissible distance threshold for determining the inliers from the outliers
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 529 of file sac_model_torus.hpp.
getDistancesToModel()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelTorus< PointT, PointNT >::getDistancesToModel (const Eigen::VectorXf & model_coefficients, std::vector< double > & distances) const override virtual
Compute all distances from the cloud data to a given torus model.
Parameters
[in] model_coefficients the coefficients of a torus model that we need to compute distances to
[out] distances the resultant estimated distances
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 271 of file sac_model_torus.hpp.
getModelType()
template<typename PointT , typename PointNT > pcl::SacModel pcl::SampleConsensusModelTorus< PointT, PointNT >::getModelType () const inline override virtual
Return a unique id for this model (SACMODEL_TORUS).
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 215 of file sac_model_torus.h.
References pcl::SACMODEL_TORUS.
isModelValid()
template<typename PointT , typename PointNT > bool pcl::SampleConsensusModelTorus< PointT, PointNT >::isModelValid (const Eigen::VectorXf & model_coefficients) const override protected virtual
Check whether a model is valid given the user constraints.
Parameters
[in] model_coefficients the set of model coefficients
Reimplemented from pcl::SampleConsensusModel< PointT >.
Definition at line 549 of file sac_model_torus.hpp.
isSampleGood()
template<typename PointT , typename PointNT > bool pcl::SampleConsensusModelTorus< PointT, PointNT >::isSampleGood (const Indices & samples) const override protected virtual
Check if a sample of indices results in a good sample of points indices.
Pure virtual.
Parameters
[in] samples the resultant index samples
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 53 of file sac_model_torus.hpp.
operator=()
template<typename PointT , typename PointNT > SampleConsensusModelTorus& pcl::SampleConsensusModelTorus< PointT, PointNT >::operator= (const SampleConsensusModelTorus< PointT, PointNT > & source) inline
Copy constructor.
Parameters
[in] source the model to copy into this
Definition at line 132 of file sac_model_torus.h.
optimizeModelCoefficients()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelTorus< PointT, PointNT >::optimizeModelCoefficients (const Indices & inliers, const Eigen::VectorXf & model_coefficients, Eigen::VectorXf & optimized_coefficients) const override virtual
Recompute the torus coefficients using the given inlier set and return them to the user.
Parameters
[in] inliers the data inliers found as supporting the model
[in] model_coefficients the initial guess for the optimization
[out] optimized_coefficients the resultant recomputed coefficients after non-linear optimization
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 359 of file sac_model_torus.hpp.
projectPoints()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelTorus< PointT, PointNT >::projectPoints (const Indices & inliers, const Eigen::VectorXf & model_coefficients, PointCloud & projected_points, bool copy_data_fields = true) const override virtual
Create a new point cloud with inliers projected onto the torus model.
Parameters
[in] inliers the data inliers that we want to project on the torus model
[in] model_coefficients the coefficients of a torus model
[out] projected_points the resultant projected points
[in] copy_data_fields set to true if we need to copy the other data fields
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 466 of file sac_model_torus.hpp.
References pcl::PointCloud< PointT >::height, pcl::PointCloud< PointT >::resize(), and pcl::PointCloud< PointT >::width.
projectPointToTorus()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelTorus< PointT, PointNT >::projectPointToTorus (const Eigen::Vector3f & pt, const Eigen::Vector3f & pt_n, const Eigen::VectorXf & model_coefficients, Eigen::Vector3f & pt_proj) const protected
Project a point onto a torus given by its model coefficients (radii, torus_center_point, torus_normal)
Parameters
[in] pt the input point to project
[in] model_coefficients the coefficients of the torus (radii, torus_center_point, torus_normal)
[out] pt_proj the resultant projected point
Definition at line 407 of file sac_model_torus.hpp.
selectWithinDistance()
template<typename PointT , typename PointNT > void pcl::SampleConsensusModelTorus< PointT, PointNT >::selectWithinDistance (const Eigen::VectorXf & model_coefficients, const double threshold, Indices & inliers) override virtual
Select all the points which respect the given model coefficients as inliers.
Parameters
[in] model_coefficients the coefficients of a torus model that we need to compute distances to
[in] threshold a maximum admissible distance threshold for determining the inliers from the outliers
[out] inliers the resultant model inliers
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 298 of file sac_model_torus.hpp.
References pcl::geometry::distance().
The documentation for this class was generated from the following files:
pcl/sample_consensus/sac_model_torus.h
pcl/sample_consensus/impl/sac_model_torus.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:20