Point Cloud Library (PCL): pcl::keypoint Namespace Reference
pcl::keypoint Namespace Reference
Functions
void harrisCorner (ImageType &output, ImageType &input, const float sigma_d, const float sigma_i, const float alpha, const float thresh)
void hessianBlob (ImageType &output, ImageType &input, const float sigma, bool SCALED)
void hessianBlob (ImageType &output, ImageType &input, const float start_scale, const float scaling_factor, const int num_scales)
void imageElementMultiply (ImageType &output, ImageType &input1, ImageType &input2)
Function Documentation
harrisCorner()
void pcl::keypoint::harrisCorner (ImageType & output, ImageType & input, const float sigma_d, const float sigma_i, const float alpha, const float thresh)
Definition at line 53 of file keypoint.hpp.
References imageElementMultiply().
hessianBlob() [1/2]
void pcl::keypoint::hessianBlob (ImageType & output, ImageType & input, const float sigma, bool SCALED)
Definition at line 121 of file keypoint.hpp.
References pcl::kernel< PointT >::gaussianKernel().
Referenced by hessianBlob().
hessianBlob() [2/2]
void pcl::keypoint::hessianBlob (ImageType & output, ImageType & input, const float start_scale, const float scaling_factor, const int num_scales)
Definition at line 177 of file keypoint.hpp.
References hessianBlob().
imageElementMultiply()
void pcl::keypoint::imageElementMultiply (ImageType & output, ImageType & input1, ImageType & input2)
Definition at line 238 of file keypoint.hpp.
Referenced by harrisCorner().
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Fri Apr 17 2020 07:59:52