Point Cloud Library (PCL): pcl::occlusion_reasoning Namespace Reference
pcl::occlusion_reasoning Namespace Reference
Classes
class ZBuffering
Class to reason about occlusions.
Functions
template<typename ModelT , typename SceneT >
pcl::PointCloud< ModelT >::Ptr filter (typename pcl::PointCloud< SceneT >::ConstPtr &organized_cloud, typename pcl::PointCloud< ModelT >::ConstPtr &to_be_filtered, float f, float threshold)
template<typename ModelT , typename SceneT >
pcl::PointCloud< ModelT >::Ptr filter (typename pcl::PointCloud< SceneT >::Ptr &organized_cloud, typename pcl::PointCloud< ModelT >::Ptr &to_be_filtered, float f, float threshold, bool check_invalid_depth=true)
template<typename ModelT , typename SceneT >
pcl::PointCloud< ModelT >::Ptr getOccludedCloud (typename pcl::PointCloud< SceneT >::Ptr &organized_cloud, typename pcl::PointCloud< ModelT >::Ptr &to_be_filtered, float f, float threshold, bool check_invalid_depth=true)
Function Documentation
filter() [1/2]
template<typename ModelT , typename SceneT > pcl::PointCloud<ModelT>::Ptr pcl::occlusion_reasoning::filter (typename pcl::PointCloud< SceneT >::ConstPtr & organized_cloud, typename pcl::PointCloud< ModelT >::ConstPtr & to_be_filtered, float f, float threshold)
Definition at line 72 of file occlusion_reasoning.h.
References pcl::PointCloud< PointT >::at(), pcl::copyPointCloud(), pcl::PointCloud< PointT >::height, pcl::PointCloud< PointT >::size(), and pcl::PointCloud< PointT >::width.
Referenced by pcl::occlusion_reasoning::ZBuffering< ModelT, SceneT >::filter().
filter() [2/2]
template<typename ModelT , typename SceneT > pcl::PointCloud<ModelT>::Ptr pcl::occlusion_reasoning::filter (typename pcl::PointCloud< SceneT >::Ptr & organized_cloud, typename pcl::PointCloud< ModelT >::Ptr & to_be_filtered, float f, float threshold, bool check_invalid_depth = true)
Definition at line 116 of file occlusion_reasoning.h.
References pcl::PointCloud< PointT >::at(), pcl::copyPointCloud(), pcl::PointCloud< PointT >::height, pcl::PointCloud< PointT >::size(), and pcl::PointCloud< PointT >::width.
getOccludedCloud()
template<typename ModelT , typename SceneT > pcl::PointCloud<ModelT>::Ptr pcl::occlusion_reasoning::getOccludedCloud (typename pcl::PointCloud< SceneT >::Ptr & organized_cloud, typename pcl::PointCloud< ModelT >::Ptr & to_be_filtered, float f, float threshold, bool check_invalid_depth = true)
Definition at line 163 of file occlusion_reasoning.h.
References pcl::PointCloud< PointT >::at(), pcl::copyPointCloud(), pcl::PointCloud< PointT >::height, pcl::PointCloud< PointT >::size(), and pcl::PointCloud< PointT >::width.
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:32