Point Cloud Library (PCL): pcl::tracking Namespace Reference
pcl::tracking Namespace Reference
Classes
class ApproxNearestPairPointCloudCoherence
ApproxNearestPairPointCloudCoherence computes coherence between two pointclouds using the approximate nearest point pairs.
class PointCoherence
PointCoherence is a base class to compute coherence between the two points.
class PointCloudCoherence
PointCloudCoherence is a base class to compute coherence between the two PointClouds.
class DistanceCoherence
DistanceCoherence computes coherence between two points from the distance between them.
class HSVColorCoherence
HSVColorCoherence computes coherence between the two points from the color difference between them.
union RGBValue
struct _ParticleXYZRPY
struct ParticleXYZRPY
struct _ParticleXYZR
struct ParticleXYZR
struct _ParticleXYRPY
struct ParticleXYRPY
struct _ParticleXYRP
struct ParticleXYRP
struct _ParticleXYR
struct ParticleXYR
class KLDAdaptiveParticleFilterTracker
KLDAdaptiveParticleFilterTracker tracks the PointCloud which is given by setReferenceCloud within the measured PointCloud using particle filter method.
class KLDAdaptiveParticleFilterOMPTracker
KLDAdaptiveParticleFilterOMPTracker tracks the PointCloud which is given by setReferenceCloud within the measured PointCloud using particle filter method.
class NearestPairPointCloudCoherence
NearestPairPointCloudCoherence computes coherence between two pointclouds using the nearest point pairs.
class NormalCoherence
NormalCoherence computes coherence between two points from the angle between their normals.
class ParticleFilterTracker
ParticleFilterTracker tracks the PointCloud which is given by setReferenceCloud within the measured PointCloud using particle filter method.
class ParticleFilterOMPTracker
ParticleFilterOMPTracker tracks the PointCloud which is given by setReferenceCloud within the measured PointCloud using particle filter method in parallel, using the OpenMP standard.
class PyramidalKLTTracker
Pyramidal Kanade Lucas Tomasi tracker.
class Tracker
Tracker represents the base tracker class.
Functions
void RGB2HSV (int r, int g, int b, float &fh, float &fs, float &fv)
Convert a RGB tuple to an HSV one.
std::ostream & operator<< (std::ostream &os, const ParticleXYZRPY &p)
ParticleXYZRPY operator* (const ParticleXYZRPY &p, double val)
ParticleXYZRPY operator+ (const ParticleXYZRPY &a, const ParticleXYZRPY &b)
ParticleXYZRPY operator- (const ParticleXYZRPY &a, const ParticleXYZRPY &b)
std::ostream & operator<< (std::ostream &os, const ParticleXYZR &p)
ParticleXYZR operator* (const ParticleXYZR &p, double val)
ParticleXYZR operator+ (const ParticleXYZR &a, const ParticleXYZR &b)
ParticleXYZR operator- (const ParticleXYZR &a, const ParticleXYZR &b)
std::ostream & operator<< (std::ostream &os, const ParticleXYRPY &p)
ParticleXYRPY operator* (const ParticleXYRPY &p, double val)
ParticleXYRPY operator+ (const ParticleXYRPY &a, const ParticleXYRPY &b)
ParticleXYRPY operator- (const ParticleXYRPY &a, const ParticleXYRPY &b)
std::ostream & operator<< (std::ostream &os, const ParticleXYRP &p)
ParticleXYRP operator* (const ParticleXYRP &p, double val)
ParticleXYRP operator+ (const ParticleXYRP &a, const ParticleXYRP &b)
ParticleXYRP operator- (const ParticleXYRP &a, const ParticleXYRP &b)
std::ostream & operator<< (std::ostream &os, const ParticleXYR &p)
ParticleXYR operator* (const ParticleXYR &p, double val)
ParticleXYR operator+ (const ParticleXYR &a, const ParticleXYR &b)
ParticleXYR operator- (const ParticleXYR &a, const ParticleXYR &b)
PCL_EXPORTS double sampleNormal (double mean, double sigma)
Function Documentation
operator*() [1/5]
ParticleXYR pcl::tracking::operator* (const ParticleXYR & p, double val) inline
Definition at line 936 of file tracking.hpp.
References pcl::tracking::_ParticleXYR::pitch, pcl::tracking::_ParticleXYR::roll, and pcl::tracking::_ParticleXYR::yaw.
operator*() [2/5]
ParticleXYRP pcl::tracking::operator* (const ParticleXYRP & p, double val) inline
Definition at line 752 of file tracking.hpp.
References pcl::tracking::_ParticleXYRP::pitch, pcl::tracking::_ParticleXYRP::roll, and pcl::tracking::_ParticleXYRP::yaw.
operator*() [3/5]
ParticleXYRPY pcl::tracking::operator* (const ParticleXYRPY & p, double val) inline
Definition at line 565 of file tracking.hpp.
References pcl::tracking::_ParticleXYRPY::pitch, pcl::tracking::_ParticleXYRPY::roll, and pcl::tracking::_ParticleXYRPY::yaw.
operator*() [4/5]
ParticleXYZR pcl::tracking::operator* (const ParticleXYZR & p, double val) inline
Definition at line 375 of file tracking.hpp.
References pcl::tracking::_ParticleXYZR::pitch, pcl::tracking::_ParticleXYZR::roll, and pcl::tracking::_ParticleXYZR::yaw.
operator*() [5/5]
ParticleXYZRPY pcl::tracking::operator* (const ParticleXYZRPY & p, double val) inline
Definition at line 191 of file tracking.hpp.
References pcl::tracking::_ParticleXYZRPY::pitch, pcl::tracking::_ParticleXYZRPY::roll, and pcl::tracking::_ParticleXYZRPY::yaw.
operator+() [1/5]
ParticleXYR pcl::tracking::operator+ (const ParticleXYR & a, const ParticleXYR & b) inline
Definition at line 950 of file tracking.hpp.
References pcl::tracking::_ParticleXYR::pitch, pcl::tracking::_ParticleXYR::roll, and pcl::tracking::_ParticleXYR::yaw.
operator+() [2/5]
ParticleXYRP pcl::tracking::operator+ (const ParticleXYRP & a, const ParticleXYRP & b) inline
Definition at line 766 of file tracking.hpp.
References pcl::tracking::_ParticleXYRP::pitch, pcl::tracking::_ParticleXYRP::roll, and pcl::tracking::_ParticleXYRP::yaw.
operator+() [3/5]
ParticleXYRPY pcl::tracking::operator+ (const ParticleXYRPY & a, const ParticleXYRPY & b) inline
Definition at line 579 of file tracking.hpp.
References pcl::tracking::_ParticleXYRPY::pitch, pcl::tracking::_ParticleXYRPY::roll, and pcl::tracking::_ParticleXYRPY::yaw.
operator+() [4/5]
ParticleXYZR pcl::tracking::operator+ (const ParticleXYZR & a, const ParticleXYZR & b) inline
Definition at line 389 of file tracking.hpp.
References pcl::tracking::_ParticleXYZR::pitch, pcl::tracking::_ParticleXYZR::roll, and pcl::tracking::_ParticleXYZR::yaw.
operator+() [5/5]
ParticleXYZRPY pcl::tracking::operator+ (const ParticleXYZRPY & a, const ParticleXYZRPY & b) inline
Definition at line 205 of file tracking.hpp.
References pcl::tracking::_ParticleXYZRPY::pitch, pcl::tracking::_ParticleXYZRPY::roll, and pcl::tracking::_ParticleXYZRPY::yaw.
operator-() [1/5]
ParticleXYR pcl::tracking::operator- (const ParticleXYR & a, const ParticleXYR & b) inline
Definition at line 964 of file tracking.hpp.
References pcl::tracking::_ParticleXYR::pitch, pcl::tracking::_ParticleXYR::roll, and pcl::tracking::_ParticleXYR::yaw.
operator-() [2/5]
ParticleXYRP pcl::tracking::operator- (const ParticleXYRP & a, const ParticleXYRP & b) inline
Definition at line 780 of file tracking.hpp.
References pcl::tracking::_ParticleXYRP::pitch, pcl::tracking::_ParticleXYRP::roll, and pcl::tracking::_ParticleXYRP::yaw.
operator-() [3/5]
ParticleXYRPY pcl::tracking::operator- (const ParticleXYRPY & a, const ParticleXYRPY & b) inline
Definition at line 593 of file tracking.hpp.
References pcl::tracking::_ParticleXYRPY::pitch, pcl::tracking::_ParticleXYRPY::roll, and pcl::tracking::_ParticleXYRPY::yaw.
operator-() [4/5]
ParticleXYZR pcl::tracking::operator- (const ParticleXYZR & a, const ParticleXYZR & b) inline
Definition at line 403 of file tracking.hpp.
References pcl::tracking::_ParticleXYZR::pitch, pcl::tracking::_ParticleXYZR::roll, and pcl::tracking::_ParticleXYZR::yaw.
operator-() [5/5]
ParticleXYZRPY pcl::tracking::operator- (const ParticleXYZRPY & a, const ParticleXYZRPY & b) inline
Definition at line 219 of file tracking.hpp.
References pcl::tracking::_ParticleXYZRPY::pitch, pcl::tracking::_ParticleXYZRPY::roll, and pcl::tracking::_ParticleXYZRPY::yaw.
operator<<() [1/5]
std::ostream& pcl::tracking::operator<< (std::ostream & os, const ParticleXYR & p) inline
Definition at line 926 of file tracking.hpp.
References pcl::tracking::_ParticleXYR::pitch, pcl::tracking::_ParticleXYR::roll, and pcl::tracking::_ParticleXYR::yaw.
operator<<() [2/5]
std::ostream& pcl::tracking::operator<< (std::ostream & os, const ParticleXYRP & p) inline
Definition at line 742 of file tracking.hpp.
References pcl::tracking::_ParticleXYRP::pitch, pcl::tracking::_ParticleXYRP::roll, and pcl::tracking::_ParticleXYRP::yaw.
operator<<() [3/5]
std::ostream& pcl::tracking::operator<< (std::ostream & os, const ParticleXYRPY & p) inline
Definition at line 555 of file tracking.hpp.
References pcl::tracking::_ParticleXYRPY::pitch, pcl::tracking::_ParticleXYRPY::roll, and pcl::tracking::_ParticleXYRPY::yaw.
operator<<() [4/5]
std::ostream& pcl::tracking::operator<< (std::ostream & os, const ParticleXYZR & p) inline
Definition at line 365 of file tracking.hpp.
References pcl::tracking::_ParticleXYZR::pitch, pcl::tracking::_ParticleXYZR::roll, and pcl::tracking::_ParticleXYZR::yaw.
operator<<() [5/5]
std::ostream& pcl::tracking::operator<< (std::ostream & os, const ParticleXYZRPY & p) inline
Definition at line 181 of file tracking.hpp.
References pcl::tracking::_ParticleXYZRPY::pitch, pcl::tracking::_ParticleXYZRPY::roll, and pcl::tracking::_ParticleXYZRPY::yaw.
RGB2HSV()
void pcl::tracking::RGB2HSV (int r, int g, int b, float & fh, float & fs, float & fv)
Convert a RGB tuple to an HSV one.
Parameters
[in] r the input Red component
[in] g the input Green component
[in] b the input Blue component
[out] fh the output Hue component
[out] fs the output Saturation component
[out] fv the output Value component
Definition at line 71 of file hsv_color_coherence.hpp.
Referenced by pcl::tracking::HSVColorCoherence< PointInT >::computeCoherence().
sampleNormal()
PCL_EXPORTS double pcl::tracking::sampleNormal (double mean, double sigma)
Referenced by pcl::tracking::ParticleXYZRPY::sample(), pcl::tracking::ParticleXYZR::sample(), pcl::tracking::ParticleXYRPY::sample(), pcl::tracking::ParticleXYRP::sample(), and pcl::tracking::ParticleXYR::sample().
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:47