Point Cloud Library (PCL): pcl::internal Namespace Reference
pcl::internal Namespace Reference
Classes
struct cloud_point_index_idx
Used internally in voxel grid classes.
Functions
PCL_EXPORTS int optimizeModelCoefficientsCone (Eigen::VectorXf &coeff, const Eigen::ArrayXf &pts_x, const Eigen::ArrayXf &pts_y, const Eigen::ArrayXf &pts_z)
PCL_EXPORTS int optimizeModelCoefficientsCylinder (Eigen::VectorXf &coeff, const Eigen::ArrayXf &pts_x, const Eigen::ArrayXf &pts_y, const Eigen::ArrayXf &pts_z)
PCL_EXPORTS int optimizeModelCoefficientsSphere (Eigen::VectorXf &coeff, const Eigen::ArrayXf &pts_x, const Eigen::ArrayXf &pts_y, const Eigen::ArrayXf &pts_z)
Function Documentation
optimizeModelCoefficientsCone()
PCL_EXPORTS int pcl::internal::optimizeModelCoefficientsCone (Eigen::VectorXf & coeff, const Eigen::ArrayXf & pts_x, const Eigen::ArrayXf & pts_y, const Eigen::ArrayXf & pts_z)
Referenced by pcl::SampleConsensusModelCone< PointT, PointNT >::optimizeModelCoefficients().
optimizeModelCoefficientsCylinder()
PCL_EXPORTS int pcl::internal::optimizeModelCoefficientsCylinder (Eigen::VectorXf & coeff, const Eigen::ArrayXf & pts_x, const Eigen::ArrayXf & pts_y, const Eigen::ArrayXf & pts_z)
Referenced by pcl::SampleConsensusModelCylinder< PointT, PointNT >::optimizeModelCoefficients().
optimizeModelCoefficientsSphere()
PCL_EXPORTS int pcl::internal::optimizeModelCoefficientsSphere (Eigen::VectorXf & coeff, const Eigen::ArrayXf & pts_x, const Eigen::ArrayXf & pts_y, const Eigen::ArrayXf & pts_z)
Referenced by pcl::SampleConsensusModelSphere< PointT >::optimizeModelCoefficients().
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:31