Point Cloud Library (PCL): pcl::gpu::PtrStep< T > Struct Template Reference
pcl::gpu::PtrStep< T > Struct Template Reference
#include </__w/1/s/gpu/containers/include/pcl/gpu/containers/kernel_containers.h>
Public Member Functions
__PCL_GPU_HOST_DEVICE__ PtrStep ()
__PCL_GPU_HOST_DEVICE__ PtrStep (T *data_arg, std::size_t step_arg)
__PCL_GPU_HOST_DEVICE__ T * ptr (int y=0)
const __PCL_GPU_HOST_DEVICE__ T * ptr (int y=0) const
__PCL_GPU_HOST_DEVICE__ T & operator() (int y, int x)
const __PCL_GPU_HOST_DEVICE__ T & operator() (int y, int x) const
Public Member Functions inherited from pcl::gpu::DevPtr< T >
__PCL_GPU_HOST_DEVICE__ DevPtr ()
__PCL_GPU_HOST_DEVICE__ DevPtr (T *data_arg)
__PCL_GPU_HOST_DEVICE__ std::size_t elemSize () const
__PCL_GPU_HOST_DEVICE__ operator T* ()
__PCL_GPU_HOST_DEVICE__ operator const T * () const
Public Attributes
std::size_t step
stride between two consecutive rows in bytes.
Public Attributes inherited from pcl::gpu::DevPtr< T >
T * data
Additional Inherited Members
Public Types inherited from pcl::gpu::DevPtr< T >
using elem_type = T
Static Public Attributes inherited from pcl::gpu::DevPtr< T >
const static std::size_t elem_size = sizeof(elem_type)
Detailed Description
template<typename T>
struct pcl::gpu::PtrStep< T >
Definition at line 74 of file kernel_containers.h.
Constructor & Destructor Documentation
PtrStep() [1/2]
template<typename T > __PCL_GPU_HOST_DEVICE__ pcl::gpu::PtrStep< T >::PtrStep () inline
Definition at line 76 of file kernel_containers.h.
PtrStep() [2/2]
template<typename T > __PCL_GPU_HOST_DEVICE__ pcl::gpu::PtrStep< T >::PtrStep (T * data_arg, std::size_t step_arg) inline
Definition at line 77 of file kernel_containers.h.
Member Function Documentation
operator()() [1/2]
template<typename T > __PCL_GPU_HOST_DEVICE__ T& pcl::gpu::PtrStep< T >::operator() (int y, int x) inline
Definition at line 85 of file kernel_containers.h.
References pcl::gpu::PtrStep< T >::ptr().
operator()() [2/2]
template<typename T > const __PCL_GPU_HOST_DEVICE__ T& pcl::gpu::PtrStep< T >::operator() (int y, int x) const inline
Definition at line 86 of file kernel_containers.h.
References pcl::gpu::PtrStep< T >::ptr().
ptr() [1/2]
template<typename T > __PCL_GPU_HOST_DEVICE__ T* pcl::gpu::PtrStep< T >::ptr (int y = 0) inline
Definition at line 82 of file kernel_containers.h.
References pcl::gpu::PtrStep< T >::step.
Referenced by pcl::gpu::DataSource::getNeghborsArray(), pcl::gpu::kinfuLS::CyclicalBuffer::initBuffer(), and pcl::gpu::PtrStep< T >::operator()().
ptr() [2/2]
template<typename T > const __PCL_GPU_HOST_DEVICE__ T* pcl::gpu::PtrStep< T >::ptr (int y = 0) const inline
Definition at line 83 of file kernel_containers.h.
References pcl::gpu::PtrStep< T >::step.
Member Data Documentation
step
template<typename T > std::size_t pcl::gpu::PtrStep< T >::step
stride between two consecutive rows in bytes.
Step is stored always and everywhere in bytes!!!
Definition at line 80 of file kernel_containers.h.
Referenced by pcl::gpu::DeviceMemory2D::operator PtrStep< U >(), pcl::gpu::DeviceMemory2D::operator PtrStepSz< U >(), pcl::gpu::PtrStep< T >::ptr(), and pcl::gpu::TextureBinder::TextureBinder().
The documentation for this struct was generated from the following file:
/__w/1/s/gpu/containers/include/pcl/gpu/containers/kernel_containers.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Jun 2 2020 14:13:33