Point Cloud Library (PCL): pcl::device::numeric_limits< unsigned long > Struct Template Reference
pcl::device::numeric_limits< unsigned long > Struct Template Reference
#include </__w/1/s/gpu/utils/include/pcl/gpu/utils/device/limits.hpp>
Public Types
using type = unsigned long
Static Public Member Functions
__device__ static __forceinline__ type min ()
__device__ static __forceinline__ type max ()
__device__ static __forceinline__ type epsilon ()
__device__ static __forceinline__ type round_error ()
__device__ static __forceinline__ type denorm_min ()
__device__ static __forceinline__ type infinity ()
__device__ static __forceinline__ type quiet_NaN ()
__device__ static __forceinline__ type signaling_NaN ()
Static Public Attributes
static const bool is_signed = false
Detailed Description
template<>
struct pcl::device::numeric_limits< unsigned long >
Definition at line 185 of file limits.hpp.
Member Typedef Documentation
type
using pcl::device::numeric_limits< unsigned long >::type = unsigned long
Definition at line 187 of file limits.hpp.
Member Function Documentation
denorm_min()
__device__ static __forceinline__ type pcl::device::numeric_limits< unsigned long >::denorm_min () static
epsilon()
__device__ static __forceinline__ type pcl::device::numeric_limits< unsigned long >::epsilon () static
infinity()
__device__ static __forceinline__ type pcl::device::numeric_limits< unsigned long >::infinity () static
max()
__device__ static __forceinline__ type pcl::device::numeric_limits< unsigned long >::max () inline static
Definition at line 189 of file limits.hpp.
References pcl::device::numeric_limits< T >::denorm_min(), pcl::device::numeric_limits< T >::epsilon(), pcl::device::numeric_limits< T >::infinity(), pcl::device::numeric_limits< T >::quiet_NaN(), pcl::device::numeric_limits< T >::round_error(), and pcl::device::numeric_limits< T >::signaling_NaN().
min()
__device__ static __forceinline__ type pcl::device::numeric_limits< unsigned long >::min () inline static
Definition at line 188 of file limits.hpp.
quiet_NaN()
__device__ static __forceinline__ type pcl::device::numeric_limits< unsigned long >::quiet_NaN () static
round_error()
__device__ static __forceinline__ type pcl::device::numeric_limits< unsigned long >::round_error () static
signaling_NaN()
__device__ static __forceinline__ type pcl::device::numeric_limits< unsigned long >::signaling_NaN () static
Member Data Documentation
is_signed
const bool pcl::device::numeric_limits< unsigned long >::is_signed = false static
Definition at line 196 of file limits.hpp.
The documentation for this struct was generated from the following file:
/__w/1/s/gpu/utils/include/pcl/gpu/utils/device/limits.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Sep 26 2019 11:52:00