Point Cloud Library (PCL): pcl::common::IntensityFieldAccessor< pcl::PointXYZRGBA > Struct Reference
pcl::common::IntensityFieldAccessor< pcl::PointXYZRGBA > Struct Reference
#include <pcl/common/impl/intensity.hpp>
Public Member Functions
float operator() (const pcl::PointXYZRGBA &p) const
void get (const pcl::PointXYZRGBA &p, float &intensity) const
void set (pcl::PointXYZRGBA &p, float intensity) const
void demean (pcl::PointXYZRGBA &p, float value) const
void add (pcl::PointXYZRGBA &p, float value) const
Detailed Description
Definition at line 160 of file intensity.hpp.
Member Function Documentation
add()
void pcl::common::IntensityFieldAccessor< pcl::PointXYZRGBA >::add (pcl::PointXYZRGBA & p, float value) const inline
Definition at line 191 of file intensity.hpp.
References pcl::common::IntensityFieldAccessor< PointT >::operator()(), and pcl::common::IntensityFieldAccessor< PointT >::set().
demean()
void pcl::common::IntensityFieldAccessor< pcl::PointXYZRGBA >::demean (pcl::PointXYZRGBA & p, float value) const inline
Definition at line 183 of file intensity.hpp.
References pcl::common::IntensityFieldAccessor< PointT >::operator()(), and pcl::common::IntensityFieldAccessor< PointT >::set().
get()
void pcl::common::IntensityFieldAccessor< pcl::PointXYZRGBA >::get (const pcl::PointXYZRGBA & p, float & intensity) const inline
Definition at line 169 of file intensity.hpp.
operator()()
float pcl::common::IntensityFieldAccessor< pcl::PointXYZRGBA >::operator() (const pcl::PointXYZRGBA & p) const inline
Definition at line 163 of file intensity.hpp.
set()
void pcl::common::IntensityFieldAccessor< pcl::PointXYZRGBA >::set (pcl::PointXYZRGBA & p, float intensity) const inline
Definition at line 175 of file intensity.hpp.
The documentation for this struct was generated from the following file:
pcl/common/impl/intensity.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Jun 2 2020 14:13:15