Point Cloud Library (PCL): pcl::tracking::ParticleXYRP Struct Reference
pcl::tracking::ParticleXYRP Struct Reference
#include <pcl/tracking/impl/tracking.hpp>
Public Member Functions
ParticleXYRP ()
ParticleXYRP (float _x, float, float _z)
ParticleXYRP (float _x, float, float _z, float, float _pitch, float _yaw)
void sample (const std::vector< double > &mean, const std::vector< double > &cov)
void zero ()
Eigen::Affine3f toEigenMatrix () const
float operator[] (unsigned int i)
Static Public Member Functions
static int stateDimension ()
static ParticleXYRP toState (const Eigen::Affine3f &trans)
template<class InputIterator >
static ParticleXYRP weightedAverage (InputIterator first, InputIterator last)
Additional Inherited Members
Public Attributes inherited from pcl::tracking::_ParticleXYRP
union {
struct {
float roll
float pitch
float yaw
float weight
}
float data_c [4]
};
Detailed Description
Definition at line 626 of file tracking.hpp.
Constructor & Destructor Documentation
ParticleXYRP() [1/3]
pcl::tracking::ParticleXYRP::ParticleXYRP () inline
Definition at line 627 of file tracking.hpp.
ParticleXYRP() [2/3]
pcl::tracking::ParticleXYRP::ParticleXYRP (float _x, float , float _z) inline
Definition at line 633 of file tracking.hpp.
ParticleXYRP() [3/3]
pcl::tracking::ParticleXYRP::ParticleXYRP (float _x, float , float _z, float , float _pitch, float _yaw) inline
Definition at line 642 of file tracking.hpp.
Member Function Documentation
operator[]()
float pcl::tracking::ParticleXYRP::operator[] (unsigned int i) inline
Definition at line 719 of file tracking.hpp.
sample()
void pcl::tracking::ParticleXYRP::sample (const std::vector< double > & mean, const std::vector< double > & cov) inline
Definition at line 660 of file tracking.hpp.
References pcl::tracking::sampleNormal().
stateDimension()
static int pcl::tracking::ParticleXYRP::stateDimension () inline static
Definition at line 654 of file tracking.hpp.
toEigenMatrix()
Eigen::Affine3f pcl::tracking::ParticleXYRP::toEigenMatrix () const inline
Definition at line 682 of file tracking.hpp.
References pcl::getTransformation().
toState()
static ParticleXYRP pcl::tracking::ParticleXYRP::toState (const Eigen::Affine3f & trans) inline static
Definition at line 688 of file tracking.hpp.
References pcl::getTranslationAndEulerAngles().
weightedAverage()
template<class InputIterator > static ParticleXYRP pcl::tracking::ParticleXYRP::weightedAverage (InputIterator first, InputIterator last) inline static
Definition at line 698 of file tracking.hpp.
References pcl::tracking::_ParticleXYRP::pitch, pcl::tracking::_ParticleXYRP::roll, pcl::tracking::_ParticleXYRP::weight, and pcl::tracking::_ParticleXYRP::yaw.
zero()
void pcl::tracking::ParticleXYRP::zero () inline
Definition at line 671 of file tracking.hpp.
The documentation for this struct was generated from the following file:
pcl/tracking/impl/tracking.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:48