Point Cloud Library (PCL): pcl::tracking::ParticleXYRPY Struct Reference
pcl::tracking::ParticleXYRPY Struct Reference
#include <pcl/tracking/impl/tracking.hpp>
Public Member Functions
ParticleXYRPY ()
ParticleXYRPY (float _x, float, float _z)
ParticleXYRPY (float _x, float, float _z, float _roll, float _pitch, float _yaw)
void sample (const std::vector< double > &mean, const std::vector< double > &cov)
void zero ()
Eigen::Affine3f toEigenMatrix () const
float operator[] (unsigned int i)
Static Public Member Functions
static int stateDimension ()
static ParticleXYRPY toState (const Eigen::Affine3f &trans)
template<class InputIterator >
static ParticleXYRPY weightedAverage (InputIterator first, InputIterator last)
Additional Inherited Members
Public Attributes inherited from pcl::tracking::_ParticleXYRPY
union {
struct {
float roll
float pitch
float yaw
float weight
}
float data_c [4]
};
Detailed Description
Definition at line 436 of file tracking.hpp.
Constructor & Destructor Documentation
ParticleXYRPY() [1/3]
pcl::tracking::ParticleXYRPY::ParticleXYRPY () inline
Definition at line 437 of file tracking.hpp.
ParticleXYRPY() [2/3]
pcl::tracking::ParticleXYRPY::ParticleXYRPY (float _x, float , float _z) inline
Definition at line 443 of file tracking.hpp.
ParticleXYRPY() [3/3]
pcl::tracking::ParticleXYRPY::ParticleXYRPY (float _x, float , float _z, float _roll, float _pitch, float _yaw) inline
Definition at line 452 of file tracking.hpp.
Member Function Documentation
operator[]()
float pcl::tracking::ParticleXYRPY::operator[] (unsigned int i) inline
Definition at line 532 of file tracking.hpp.
sample()
void pcl::tracking::ParticleXYRPY::sample (const std::vector< double > & mean, const std::vector< double > & cov) inline
Definition at line 470 of file tracking.hpp.
References pcl::tracking::sampleNormal().
stateDimension()
static int pcl::tracking::ParticleXYRPY::stateDimension () inline static
Definition at line 464 of file tracking.hpp.
toEigenMatrix()
Eigen::Affine3f pcl::tracking::ParticleXYRPY::toEigenMatrix () const inline
Definition at line 492 of file tracking.hpp.
References pcl::getTransformation().
toState()
static ParticleXYRPY pcl::tracking::ParticleXYRPY::toState (const Eigen::Affine3f & trans) inline static
Definition at line 498 of file tracking.hpp.
References pcl::getTranslationAndEulerAngles().
weightedAverage()
template<class InputIterator > static ParticleXYRPY pcl::tracking::ParticleXYRPY::weightedAverage (InputIterator first, InputIterator last) inline static
Definition at line 508 of file tracking.hpp.
References pcl::tracking::_ParticleXYRPY::pitch, pcl::tracking::_ParticleXYRPY::roll, pcl::tracking::_ParticleXYRPY::weight, and pcl::tracking::_ParticleXYRPY::yaw.
zero()
void pcl::tracking::ParticleXYRPY::zero () inline
Definition at line 481 of file tracking.hpp.
The documentation for this struct was generated from the following file:
pcl/tracking/impl/tracking.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:48