Point Cloud Library (PCL): pcl::Correspondence Struct Reference
pcl::Correspondence Struct Reference
Module common
Correspondence represents a match between two entities (e.g., points, descriptors, etc).
#include <pcl/correspondence.h>
Public Member Functions
Correspondence ()=default
Standard constructor.
Correspondence (index_t _index_query, index_t _index_match, float _distance)
Constructor.
Public Attributes
index_t index_query = 0
Index of the query (source) point.
index_t index_match = UNAVAILABLE
Index of the matching (target) point.
union {
float distance = std::numeric_limits<float>::max()
float weight
};
Distance between the corresponding points, or the weight denoting the confidence in correspondence estimation.
Detailed Description
Correspondence represents a match between two entities (e.g., points, descriptors, etc).
This is represented via the indices of a source point and a target point, and the distance between them.
Author
Dirk Holz, Radu B. Rusu, Bastian Steder
Definition at line 60 of file correspondence.h.
Constructor & Destructor Documentation
Correspondence() [1/2]
pcl::Correspondence::Correspondence () inline default
Standard constructor.
Sets index_query to 0, index_match to -1, and distance to std::numeric_limits<float>::max().
Correspondence() [2/2]
pcl::Correspondence::Correspondence (index_t _index_query, index_t _index_match, float _distance) inline
Constructor.
Definition at line 79 of file correspondence.h.
Member Data Documentation
union { ... }
Distance between the corresponding points, or the weight denoting the confidence in correspondence estimation.
distance
float pcl::Correspondence::distance = std::numeric_limits<float>::max()
Definition at line 69 of file correspondence.h.
Referenced by pcl::recognition::TrimmedICP< PointT, Scalar >::compareCorrespondences(), pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::determineCorrespondences(), pcl::registration::CorrespondenceEstimation< PointSource, PointTarget, Scalar >::determineCorrespondences(), pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::determineCorrespondences(), pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::determineReciprocalCorrespondences(), pcl::registration::CorrespondenceEstimation< PointSource, PointTarget, Scalar >::determineReciprocalCorrespondences(), pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::determineReciprocalCorrespondences(), pcl::isBetterCorrespondence(), pcl::registration::sortCorrespondencesByDistance::operator()(), pcl::registration::sortCorrespondencesByQueryIndexAndDistance::operator()(), and pcl::registration::sortCorrespondencesByMatchIndexAndDistance::operator()().
index_match
index_t pcl::Correspondence::index_match = UNAVAILABLE
Index of the matching (target) point.
Set to -1 if no correspondence found.
Definition at line 65 of file correspondence.h.
Referenced by pcl::JointIterativeClosestPoint< PointSource, PointTarget, Scalar >::computeTransformation(), pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::determineCorrespondences(), pcl::registration::CorrespondenceEstimation< PointSource, PointTarget, Scalar >::determineCorrespondences(), pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::determineCorrespondences(), pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::determineReciprocalCorrespondences(), pcl::registration::CorrespondenceEstimation< PointSource, PointTarget, Scalar >::determineReciprocalCorrespondences(), pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::determineReciprocalCorrespondences(), pcl::registration::DataContainer< PointT, NormalT >::getCorrespondenceScore(), pcl::registration::DataContainer< PointT, NormalT >::getCorrespondenceScoreFromNormals(), pcl::registration::sortCorrespondencesByMatchIndex::operator()(), and pcl::registration::sortCorrespondencesByMatchIndexAndDistance::operator()().
index_query
index_t pcl::Correspondence::index_query = 0
Index of the query (source) point.
Definition at line 63 of file correspondence.h.
Referenced by pcl::JointIterativeClosestPoint< PointSource, PointTarget, Scalar >::computeTransformation(), pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::determineCorrespondences(), pcl::registration::CorrespondenceEstimation< PointSource, PointTarget, Scalar >::determineCorrespondences(), pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::determineCorrespondences(), pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::determineReciprocalCorrespondences(), pcl::registration::CorrespondenceEstimation< PointSource, PointTarget, Scalar >::determineReciprocalCorrespondences(), pcl::registration::CorrespondenceEstimationNormalShooting< PointSource, PointTarget, NormalT, Scalar >::determineReciprocalCorrespondences(), pcl::registration::DataContainer< PointT, NormalT >::getCorrespondenceScore(), pcl::registration::DataContainer< PointT, NormalT >::getCorrespondenceScoreFromNormals(), pcl::registration::sortCorrespondencesByQueryIndex::operator()(), and pcl::registration::sortCorrespondencesByQueryIndexAndDistance::operator()().
weight
float pcl::Correspondence::weight
Definition at line 70 of file correspondence.h.
The documentation for this struct was generated from the following file:
pcl/correspondence.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:09