Point Cloud Library (PCL): pcl::tracking::ParticleXYZR Struct Reference
pcl::tracking::ParticleXYZR Struct Reference
#include <pcl/tracking/impl/tracking.hpp>
Public Member Functions
ParticleXYZR ()
ParticleXYZR (float _x, float _y, float _z)
ParticleXYZR (float _x, float _y, float _z, float, float _pitch, float)
void sample (const std::vector< double > &mean, const std::vector< double > &cov)
void zero ()
Eigen::Affine3f toEigenMatrix () const
float operator[] (unsigned int i)
Static Public Member Functions
static int stateDimension ()
static ParticleXYZR toState (const Eigen::Affine3f &trans)
template<class InputIterator >
static ParticleXYZR weightedAverage (InputIterator first, InputIterator last)
Additional Inherited Members
Public Attributes inherited from pcl::tracking::_ParticleXYZR
union {
struct {
float roll
float pitch
float yaw
float weight
}
float data_c [4]
};
Detailed Description
Definition at line 252 of file tracking.hpp.
Constructor & Destructor Documentation
ParticleXYZR() [1/3]
pcl::tracking::ParticleXYZR::ParticleXYZR () inline
Definition at line 253 of file tracking.hpp.
ParticleXYZR() [2/3]
pcl::tracking::ParticleXYZR::ParticleXYZR (float _x, float _y, float _z) inline
Definition at line 259 of file tracking.hpp.
ParticleXYZR() [3/3]
pcl::tracking::ParticleXYZR::ParticleXYZR (float _x, float _y, float _z, float , float _pitch, float) inline
Definition at line 268 of file tracking.hpp.
Member Function Documentation
operator[]()
float pcl::tracking::ParticleXYZR::operator[] (unsigned int i) inline
Definition at line 342 of file tracking.hpp.
sample()
void pcl::tracking::ParticleXYZR::sample (const std::vector< double > & mean, const std::vector< double > & cov) inline
Definition at line 286 of file tracking.hpp.
References pcl::tracking::sampleNormal().
stateDimension()
static int pcl::tracking::ParticleXYZR::stateDimension () inline static
Definition at line 280 of file tracking.hpp.
toEigenMatrix()
Eigen::Affine3f pcl::tracking::ParticleXYZR::toEigenMatrix () const inline
Definition at line 308 of file tracking.hpp.
References pcl::getTransformation().
toState()
static ParticleXYZR pcl::tracking::ParticleXYZR::toState (const Eigen::Affine3f & trans) inline static
Definition at line 314 of file tracking.hpp.
References pcl::getTranslationAndEulerAngles().
weightedAverage()
template<class InputIterator > static ParticleXYZR pcl::tracking::ParticleXYZR::weightedAverage (InputIterator first, InputIterator last) inline static
Definition at line 324 of file tracking.hpp.
References pcl::tracking::_ParticleXYZR::pitch, pcl::tracking::_ParticleXYZR::roll, pcl::tracking::_ParticleXYZR::weight, and pcl::tracking::_ParticleXYZR::yaw.
zero()
void pcl::tracking::ParticleXYZR::zero () inline
Definition at line 297 of file tracking.hpp.
The documentation for this struct was generated from the following file:
pcl/tracking/impl/tracking.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:48