Point Cloud Library (PCL): pcl::device::numeric_limits< short > Struct Template Reference
pcl::device::numeric_limits< short > Struct Template Reference
#include </__w/1/s/gpu/kinfu/src/cuda/utils.hpp>
Public Types
using type = short
Static Public Member Functions
__device__ static __forceinline__ short max ()
__device__ static __forceinline__ type min ()
__device__ static __forceinline__ type max ()
__device__ static __forceinline__ type epsilon ()
__device__ static __forceinline__ type round_error ()
__device__ static __forceinline__ type denorm_min ()
__device__ static __forceinline__ type infinity ()
__device__ static __forceinline__ type quiet_NaN ()
__device__ static __forceinline__ type signaling_NaN ()
Static Public Attributes
static const bool is_signed = true
Detailed Description
template<>
struct pcl::device::numeric_limits< short >
Definition at line 69 of file utils.hpp.
Member Typedef Documentation
type
using pcl::device::numeric_limits< short >::type = short
Definition at line 116 of file limits.hpp.
Member Function Documentation
denorm_min()
__device__ static __forceinline__ type pcl::device::numeric_limits< short >::denorm_min () static
epsilon()
__device__ static __forceinline__ type pcl::device::numeric_limits< short >::epsilon () static
infinity()
__device__ static __forceinline__ type pcl::device::numeric_limits< short >::infinity () static
max() [1/2]
__device__ static __forceinline__ short pcl::device::numeric_limits< short >::max () inline static
Definition at line 72 of file utils.hpp.
max() [2/2]
__device__ static __forceinline__ type pcl::device::numeric_limits< short >::max () inline static
Definition at line 118 of file limits.hpp.
References pcl::device::numeric_limits< T >::denorm_min(), pcl::device::numeric_limits< T >::epsilon(), pcl::device::numeric_limits< T >::infinity(), pcl::device::numeric_limits< T >::quiet_NaN(), pcl::device::numeric_limits< T >::round_error(), and pcl::device::numeric_limits< T >::signaling_NaN().
min()
__device__ static __forceinline__ type pcl::device::numeric_limits< short >::min () inline static
Definition at line 117 of file limits.hpp.
quiet_NaN()
__device__ static __forceinline__ type pcl::device::numeric_limits< short >::quiet_NaN () static
round_error()
__device__ static __forceinline__ type pcl::device::numeric_limits< short >::round_error () static
signaling_NaN()
__device__ static __forceinline__ type pcl::device::numeric_limits< short >::signaling_NaN () static
Member Data Documentation
is_signed
const bool pcl::device::numeric_limits< short >::is_signed = true static
Definition at line 125 of file limits.hpp.
The documentation for this struct was generated from the following files:
/__w/1/s/gpu/kinfu/src/cuda/utils.hpp
/__w/1/s/gpu/utils/include/pcl/gpu/utils/device/limits.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Sep 26 2019 11:52:00