Point Cloud Library (PCL): pcl::device::Emulation Struct Reference
pcl::device::Emulation Struct Reference
#include </__w/1/s/gpu/kinfu/src/cuda/utils.hpp>
Static Public Member Functions
static __device__ __forceinline__ int warp_reduce (volatile int *ptr, const unsigned int tid)
static __forceinline__ __device__ int Ballot (int predicate, volatile int *cta_buffer)
static __forceinline__ __device__ bool All (int predicate, volatile int *cta_buffer)
static __forceinline__ __device__ int Ballot (int predicate, volatile int *cta_buffer)
static __forceinline__ __device__ int ballot (int predicate, volatile int *cta_buffer)
Detailed Description
Definition at line 562 of file utils.hpp.
Member Function Documentation
All()
static __forceinline__ __device__ bool pcl::device::Emulation::All (int predicate, volatile int * cta_buffer) inline static
Definition at line 594 of file utils.hpp.
References pcl::utils::ignore().
ballot()
static __forceinline__ __device__ int pcl::device::Emulation::ballot (int predicate, volatile int * cta_buffer) inline static
Definition at line 50 of file emulation.hpp.
References pcl::utils::ignore().
Ballot() [1/2]
static __forceinline__ __device__ int pcl::device::Emulation::Ballot (int predicate, volatile int * cta_buffer) inline static
Definition at line 50 of file emulation.hpp.
References pcl::utils::ignore().
Ballot() [2/2]
static __forceinline__ __device__ int pcl::device::Emulation::Ballot (int predicate, volatile int * cta_buffer) inline static
Definition at line 583 of file utils.hpp.
References pcl::utils::ignore().
warp_reduce()
static __device__ __forceinline__ int pcl::device::Emulation::warp_reduce (volatile int * ptr, const unsigned int tid) inline static
Definition at line 565 of file utils.hpp.
The documentation for this struct was generated from the following files:
/__w/1/s/gpu/kinfu/src/cuda/utils.hpp
/__w/1/s/gpu/octree/src/utils/emulation.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Tue Jun 2 2020 14:13:25