Point Cloud Library (PCL): pcl::tracking::ParticleXYZRPY Struct Reference
pcl::tracking::ParticleXYZRPY Struct Reference
#include <pcl/tracking/impl/tracking.hpp>
Public Member Functions
ParticleXYZRPY ()
ParticleXYZRPY (float _x, float _y, float _z)
ParticleXYZRPY (float _x, float _y, float _z, float _roll, float _pitch, float _yaw)
void sample (const std::vector< double > &mean, const std::vector< double > &cov)
void zero ()
Eigen::Affine3f toEigenMatrix () const
float operator[] (unsigned int i)
Static Public Member Functions
static int stateDimension ()
static ParticleXYZRPY toState (const Eigen::Affine3f &trans)
template<class InputIterator >
static ParticleXYZRPY weightedAverage (InputIterator first, InputIterator last)
Additional Inherited Members
Public Attributes inherited from pcl::tracking::_ParticleXYZRPY
union {
struct {
float roll
float pitch
float yaw
float weight
}
float data_c [4]
};
Detailed Description
Definition at line 25 of file tracking.hpp.
Constructor & Destructor Documentation
ParticleXYZRPY() [1/3]
pcl::tracking::ParticleXYZRPY::ParticleXYZRPY () inline
Definition at line 26 of file tracking.hpp.
ParticleXYZRPY() [2/3]
pcl::tracking::ParticleXYZRPY::ParticleXYZRPY (float _x, float _y, float _z) inline
Definition at line 32 of file tracking.hpp.
ParticleXYZRPY() [3/3]
pcl::tracking::ParticleXYZRPY::ParticleXYZRPY (float _x, float _y, float _z, float _roll, float _pitch, float _yaw) inline
Definition at line 41 of file tracking.hpp.
Member Function Documentation
operator[]()
float pcl::tracking::ParticleXYZRPY::operator[] (unsigned int i) inline
Definition at line 158 of file tracking.hpp.
sample()
void pcl::tracking::ParticleXYZRPY::sample (const std::vector< double > & mean, const std::vector< double > & cov) inline
Definition at line 60 of file tracking.hpp.
References pcl::getEulerAngles(), pcl::getTransformation(), and pcl::tracking::sampleNormal().
stateDimension()
static int pcl::tracking::ParticleXYZRPY::stateDimension () inline static
Definition at line 54 of file tracking.hpp.
toEigenMatrix()
Eigen::Affine3f pcl::tracking::ParticleXYZRPY::toEigenMatrix () const inline
Definition at line 118 of file tracking.hpp.
References pcl::getTransformation().
toState()
static ParticleXYZRPY pcl::tracking::ParticleXYZRPY::toState (const Eigen::Affine3f & trans) inline static
Definition at line 124 of file tracking.hpp.
References pcl::getTranslationAndEulerAngles().
weightedAverage()
template<class InputIterator > static ParticleXYZRPY pcl::tracking::ParticleXYZRPY::weightedAverage (InputIterator first, InputIterator last) inline static
Definition at line 134 of file tracking.hpp.
References pcl::tracking::_ParticleXYZRPY::pitch, pcl::tracking::_ParticleXYZRPY::roll, pcl::tracking::_ParticleXYZRPY::weight, and pcl::tracking::_ParticleXYZRPY::yaw.
zero()
void pcl::tracking::ParticleXYZRPY::zero () inline
Definition at line 107 of file tracking.hpp.
The documentation for this struct was generated from the following file:
pcl/tracking/impl/tracking.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Wed Oct 23 2024 10:17:48